### ISSUE TITLE
Consider versioning against API version rather than Kubernetes version

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/client-go#1]
With the API guarantees since 1.0, it makes more sense to version the client against the API version. There should be no need to use a matching client version against Kubernetes version, the only thing that matters is the API version. Software using the go-client should not have to keep versions in lock-step with the Kubernetes version they are running against. This would seriously limit the usability of the client.

So I propose that the client be versioned independently to Kubernetes itself & the API compatibility be documented instead, e.g. client-go v0.1 supports Kubernetes API v1, extensions API v1beta1, etc.

**Comment by caesarxuchao** [comment]
"1.4" just indicates when the library is cut. `client-go/1.4` should work against 1.3 Kubernetes master, as long as the API group/version are supported.
You can see the API versions supported by client-go/1.4 here: https://github.com/kubernetes/client-go/tree/master/1.4/kubernetes/typed

**Comment by timoreimann** [comment]
Seems related to #2, which is closed. Shall we close this one too?

/cc @lavalamp

**Comment by timoreimann** [comment]
Meant to reference #3.

**Comment by lavalamp** [comment]
Different API groups are versioned differently, so there is no single api version to use. Everything is backwards compatible. The differing versions give us places where we can change the *client library's* interface without breaking code that depends on it.
