### ISSUE TITLE
Update pod.status with dynamic get error

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes/client-go#1006]
Basic process is:
```
client :=  dynamic.NewForConfigOrDie(restConfig)
nri := client.Resource(gvr)
......
nri.UpdateStatus(....)
```
The resource is `pod`, we try to sync `pod.status` from another k8s cluster to this one and then get:
```
status.conditions.lastProbeTime: Invalid value: "null": status.conditions.lastProbeTime in body must be of type string: "null"
```
This confuse me, actually the `status.conditions.lastProbeTime` is type `metav1.Time`

So, any suggestion?

**Comment by Jeffwan** [comment]
@vincent-pli use pointer instead. Check this for more details https://github.com/kubernetes/kubernetes/issues/86811
