### ISSUE TITLE
Question about version compatibility of go-client with k8s api server

### ISSUE THREAD

**Issue by jyotimahapatra** [kubernetes/client-go#1013]
Hi ! I've a question about the compatibility matrix between go-client and k8s apiserver. 

Description of issue:
We recently faced an issue where the k8s apiserver version was 1.20 and go-client version was 1.10. K8s 1.20 removed the deprecated unsecure port 8080 from apiserver, as a result all communication from go-client to apiserver was switched to TLS based. Without TLS, communication between go-client and apiserver was based on http1. After switching to TLS(by updating certs in kube-config), the apiserver forced protocol negotiation(ALPN) during connection creation. This forced go-client to use http2 connection with apiserver. The http2 library used in go-client version 1.10 probably had bugs, which caused the go-client watch with k8s apiserver to terminate and not be able to reestablish connection with an error message `http2: no cached connection was available` .  We fixed the issue by upgrading the go-client to 1.16 (probably an earlier version could have worked too).
[ I can describe more details around the error if that helps]

Question::
1. The client-go documentation states `We will backport bugfixes--but not new features--into older versions of client-go.` . How far back are the bug fixes back ported. I wanted to understand the processes so that i can keep the client-go version updated when we change apiserver versions.
2. The compatibility matrix shows a matrix for apiserver and client-go versions 1.15 to 1.20. Does that mean its safe to assume client-go can work with apiserver drift as much as 5 versions? I understand not all features would be available across versions, but want to understand from a perspective of bug fixes.

**Comment by hahewlet** [comment]
I am curious about this issue myself. I wish the compatibility matrix was updated through all the newest releases e.g. up to 1.22, https://github.com/kubernetes/client-go#compatibility-client-go---kubernetes-clusters. The written description certainly implies compatibility with older client-go releases. It would be a reassurance to see that explicitly confirmed as we make a decision about which client-go release to use when we add support for K8s 1.22.
