### ISSUE TITLE
Unable to create a config map

### ISSUE THREAD

**Issue by s0n00im** [kubernetes/client-go#1015]
I am using the client-go package to create a configmap to deploy in my cluster. 

````
configMapData := make(map[string]string, 0)
	uiProperties := `
	color.good=purple
	color.bad=yellow
	`
	namespace := "abc"
	configMapName := "configmap"
	configMapData["ui.properties"] = uiProperties
	configMap := corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			Kind: "ConfigMap",
			APIVersion: "v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: configMapName,
			Namespace: namespace,
		},
		Data:configMapData,
	}
print("config map data", configMap.Data["ui.properties"])
	var cm *corev1.ConfigMap
	cm, _ = clientset.CoreV1().ConfigMaps(namespace).Create(context.TODO(), &configMap, metav1.CreateOptions{})
	print("Post config map creation", cm.Data["ui.properties"])
````

While the first print command works (config map data), the second print command does not work. It does not print anything. I dont get an error either on running my go file with go run.
 
No output from corev1 "k8s.io/api/core/v1" ->Configmap

**Comment by rajendragosavi** [comment]
@s0n00im  - Hi, did you resolve this issue or still facing the same ?

**Comment by adamwoolhether** [comment]
Does the ConfigMap actually get created in the K8s env? 

I recall having some similar issues. I'm creating CMs with data that may be binary or string, so in the initial construction I use 
```
		Data:       map[string]string{},
		BinaryData: map[string][]byte{},
```
and then, based on the input, modify the relevant field:
```
	if utf8.Valid(SOURCE_DATA) {
		configMap.Data["filename"] = string(SOURCE_DATA)
	} else {
		configMap.BinaryData["filename"] = SOURCE_DATA
	}
```

Not sure if applicable to your case tho....
