### ISSUE TITLE
Errors in klog.go

### ISSUE THREAD

**Issue by s0n00im** [kubernetes/client-go#1016]
When I try to download dependencies, i see errors in klog.go file, can someone take a look?

 k8s.io/klog/v2
```
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:705:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:724:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:742:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:763:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:782:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:783:3: undefined: logr.WithCallDepth
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:794:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:795:3: undefined: logr.WithCallDepth
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:915:9: invalid operation: log != nil (mismatched types logr.Logger and nil)
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:919:4: undefined: logr.WithCallDepth
../../../../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:919:4: too many errors



```

**Comment by arosh** [comment]
@s0n00im 
logr introduced a breaking change as of v1.0.0 that changes the type of `logr.Logger` from interface to struct. See the following.

* https://github.com/go-logr/logr/releases/tag/v1.0.0-rc1
* https://github.com/go-logr/logr/pull/42/files#diff-792a9b98675a458cdbd537bf51c36acec5d9f0bf8eea4ad2ba441cf54be5017dL147-R193

I am using v0.4.0 as a workaround now. If you need to use both the library that depends on v1.0 and the library that depends on v0.4.0, then I have no idea... 😢

**Comment by arosh** [comment]
A commit has just been merged to replace the new klog which is compatible with logr v1.0, so it should be fine for later versions.

https://github.com/kubernetes/client-go/commit/92773dec00392b35f67f090025b757387df7d226
