### ISSUE TITLE
No Create method on fake client?

### ISSUE THREAD

**Issue by Miles-Garnsey** [kubernetes/client-go#1017]
I am trying to use the fake client to write some simple unit tests. I'm following instructions from [here](https://medium.com/the-phi/mocking-the-kubernetes-client-in-go-for-unit-testing-ddae65c4302) since I can't find a fully worked through example anywhere else.

I have a mocked client which looks like this:

```
// client.go
package mocks

import "k8s.io/client-go/kubernetes"

// Mocked client for unit tests
type Client struct {
	Clientset kubernetes.Interface
}
```

I'm then instantiating a test which looks like this - 

```
// reconcilers_test.go
import fakeclientset "k8s.io/client-go/kubernetes/fake"

testClientSet := fakeclientset.NewSimpleClientset(testReaper)
k8sClient := mocks.Client{testClientSet}

r := defaultReconciler{
		k8sClient,
		testScheme,
		testSecretsmngr,
	}
```

When instantiating my `defaultReconciler` I'm getting a compile error `cannot use k8sClient (variable of type mocks.Client) as client.Client value in struct literal: missing method Create`. 

`defaultReconciler` looks like this:

```
type defaultReconciler struct {
    client.Client
    scheme *runtime.Scheme
    secretsManager SecretsManager
}
```

Does this mean that I need to mock out all CRUD operations in order to use the `fake` client? Is there an example anywhere that I can refer to when testing operators using these mocks?

**Comment by jonyhy96** [comment]
what is the import statement of package `client`?

**Comment by Miles-Garnsey** [comment]
It was of the form import "github.com/k8ssandra/reaper-operator/mocks" and there is a `client` struct under that package.

FYI, this can possibly be closed as we've discovered that the `operator-sdk` fake client is no longer deprecated. We are moving to continue using that for unit tests right now.

In saying that, I'd be curious to know if there is something that does do a similar job in this module!
