### ISSUE TITLE
How to "kubectl config view" in go-client - to merge $KUBECONFIG

### ISSUE THREAD

**Issue by JCzz** [kubernetes/client-go#1021]
Hi

I am trying to use current config in go-client, from a file referenced in $KUBECONFIG. 

I have a ~/.zshrc:

`export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/custom_config`

And `kubectl config current-context` shows me that I am using the context from `/.kube/custom_config`.

When using `go-client` using `~/.kube/custom_config` file I get [this error](https://github.com/kubernetes/client-go/issues/1020) but it works if I use `~/.kube/config` using `kubectl config use-context` - no problem.

Therefore I am looking for a way to do, like you can do `kubectl config view` to merge file in $KUBECONFIG, in `go-client`?

**Comment by xie233** [comment]
what happen?  if "kubectl config view --kubeconfig=.kube/custom_config"
