### ISSUE TITLE
Does client-go support listing all resources in namespace

### ISSUE THREAD

**Issue by yogesh-reddy** [kubernetes/client-go#1023]
`kubectl get all -n <ns>  `
Lists down all the resources in that namespace, does client-go has this functionality.

**Comment by eddie-knight** [comment]
I believe what you're looking for is here:
https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/kubernetes/typed/core/v1/namespace.go#L81
