### ISSUE TITLE
kubectl get <something> command return - Throttling request log

### ISSUE THREAD

**Issue by anencore94** [kubernetes/client-go#1029]
I've been used 6-node k8s cluster in my company since a year ago.

But this happened since a few days ago.
- When I execute `kubectl get <something>`, similar to following log message printed as StdOut sometime:
  - `Throttling request took 920.039316ms, request: GET:https://172.25.0.2:6443/apis/apiextensions.k8s.io/v1beta1?timeout=32s`
  - (172.25.0.2 is the IP address of master node)
- After this message was printed, such message doesn't printed for a few minutes since cache was saved. But it happens again.

I found the log message was caused by : https://github.com/kubernetes/client-go/blob/56656ba0e04ff501549162385908f5b7d14f5dc8/rest/request.go#L593

But I don't know what is the main reason.

Here's the full log of `kubectl get pod -v=9`:
- https://walnut-court-431.notion.site/kubectl-get-issue-fb5372528b12440bb8f040d7a03e97ea

I found the similar issue here: https://stackoverflow.com/questions/66339069/kubectl-get-all-command-return-throttling-request  . However my cache directory permission and kubectl version was not the reason.

Let me know if there is any idea to resolve this issue. Thanks in advance.

## env (Checked)
kubernetes cluster version : v1.19.3
kubectl version : v1.19.3, v1.21.1, v1.22.1
os : ubuntu 20.04, maxos

**Comment by anencore94** [comment]
I see https://github.com/kubernetes/kubernetes/pull/105520 , the default `discoveryBurst` value was increased from 100 to 300.
Also, If anyone needs more, I think we could just compile our own `kubectl` with increased `discoveryBurst` value.

So I'll close this issue.

**Comment by xmcqueen** [comment]
yes this old ticket fixed me up! Thanks
