### ISSUE TITLE
How to use the go-client to get cluster info

### ISSUE THREAD

**Issue by 2hangchen** [kubernetes/client-go#1032]
How to use the go-client to get cluster info that the same info as the 'kubectl get cluster'?

**Comment by hzliangbin** [comment]
> How to use the go-client to get cluster info that the same info as the 'kubectl get cluster'?

k8s does't hava a resource named Cluster.

**Comment by timo-klarshift** [comment]
I would just look at the content of KUBECONFIG to obtain the data
