### ISSUE TITLE
CRD created with empty Spec on Kubernetes 1.22 using apiextensions/v1

### ISSUE THREAD

**Issue by soniabha-intc** [kubernetes/client-go#1034]
We are creating custom CRD using client-go on kubernetes 1.22( "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1" ) and trying to create instances of this CRD
The CRD is created successfully but when we create the instance of the CRD, it doesn’t throw any error but the Spec is empty. Here is the output of kubectl describe as well as in code, the response of create returns Null for spec.

Name:         edgedeployment-druid-vjjxk
Namespace:    smartedge-system
Labels:       <none>
Annotations:  <none>
API Version:  smartedge.intel.com/v1alpha1
Kind:         EdgeDeployment
Metadata:
  Creation Timestamp:  2021-11-19T15:17:29Z
  Generate Name:       edgedeployment-druid-
  Generation:          1
  Managed Fields:
    API Version:  smartedge.intel.com/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
    Manager:         edgedeploy
    Operation:       Update
    Time:            2021-11-19T15:17:29Z
  Resource Version:  4691659
  UID:               26513bdc-4916-48fa-bc53-bde8b3471730
**Spec:**

This used to run correctly when we were using client-go on kubernetes 1.20 using 
 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1" . This is a blocker for our release. Anyone can help or point to any go examples of CRD creation using apiextensions/v1 on kubernetes 1.22

**Comment by pradeeppanga** [comment]
@soniabha-intc We are facing similar issue. Were you able to fix it?
