### ISSUE TITLE
client-go timezone is different to kubectl describe

### ISSUE THREAD

**Issue by mizhexiaoxiao** [kubernetes/client-go#1047]
when I use client-go to get deployment resource, field `creationTimestamp` is different from the one obtained with `kubectl describe`, 8 hours difference in time zone. How can I fix it？

client-go
```
{
    "metadata": {
      "name": "front-tracing-go",
      "namespace": "dev",
      "selfLink": "/apis/apps/v1/namespaces/dev/deployments/front-tracing-go",
      "uid": "ebee64e9-c623-436a-a9d5-e22a61d9c591",
      "resourceVersion": "31923081038",
      "generation": 2,
      "creationTimestamp": "2021-12-31T03:51:52Z"
```

kubectl describe
```
Name:                   front-tracing-go
Namespace:              dev
CreationTimestamp:      Fri, 31 Dec 2021 11:51:52 +0800
Labels:                 app.kubernetes.io/instance=front-tracing-go
```

**Comment by kamikazechaser** [comment]
`2021-12-31T03:51:52Z` is 03:51 UTC (Notice the 'Z') which is equal to `11:51 +8 GMT`. Works as intended.

**Comment by mizhexiaoxiao** [comment]
>

**Comment by mizhexiaoxiao** [comment]
I mean how do I get the expected value `11:51 +8 GMT` using client-go?

**Comment by mizhexiaoxiao** [comment]
> `2021-12-31T03:51:52Z` is 03:51 UTC (Notice the 'Z') which is equal to `11:51 +8 GMT`. Works as intended.

I mean how do I get the expected value 11:51 +8 GMT using client-go?

**Comment by kamikazechaser** [comment]
https://github.com/kubernetes/apimachinery/blob/v0.23.1/pkg/apis/meta/v1/types.go#L195

You will have to write some helper function to convert it in the format you want.
