### ISSUE TITLE
something wrong here

### ISSUE THREAD

**Issue by atlaswoo** [kubernetes/client-go#1052]
go: downloading k8s.io/api v0.23.1
go: downloading github.com/googleapis/gnostic v0.5.5
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading k8s.io/kube-openapi v0.0.0-20211115234752-e816edb12b65
# sigs.k8s.io/json/internal/golang/encoding/json
/root/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
/root/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)

**Comment by abhishekk049** [comment]
stuck with the same issue, any update on this ?

**Comment by iam-veeramalla** [comment]
Hi @atlaswoo @abhishekk049 is the issue resolved ? Are you trying to update your kubernetes clients to v1.23.0 ?

**Comment by abhishekk049** [comment]
@iam-veeramalla i upgraded the golang version to 1.17.0 and it worked fine. try upgrading your golang version

**Comment by aleksrosz** [comment]
Hi 
Is this error related to JetBrains Goland IDE? Can you attach screenshot?

**Comment by atlaswoo** [comment]
> Hi @atlaswoo @abhishekk049 is the issue resolved ? Are you trying to update your kubernetes clients to v1.23.0 ?

Not yet,my golang version is 'go1.16 linux/amd64' and im trying to upgrade it.

**Comment by atlaswoo** [comment]
> Has nothing to do with JetBrains Golang IDE. Having a look at https://pkg.go.dev/reflect#StructField
> 
> func (StructField) [IsExported](https://cs.opensource.google/go/go/+/go1.17.7:src/reflect/type.go;l=1146)
> 
> was clearly added with go 1.17.
> 
> So it seems as if we need at least go 1.17...
Thanks ， the issue has been compromised after I upgrade my golang version to 1.17,大佬牛逼！

**Comment by atlaswoo** [comment]
> Has nothing to do with JetBrains Golang IDE. Having a look at https://pkg.go.dev/reflect#StructField
> 
> func (StructField) [IsExported](https://cs.opensource.google/go/go/+/go1.17.7:src/reflect/type.go;l=1146)
> 
> was clearly added with go 1.17.
> 
> So it seems as if we need at least go 1.17...

Thanks ， the issue has been compromised after I upgrade my golang version to 1.17,大佬牛逼！

**Comment by liggitt** [comment]
yes, go1.17 is required for 1.23
