### ISSUE TITLE
FieldSelector is ignored when Listing resources for the faker

### ISSUE THREAD

**Issue by BennyDjo** [kubernetes/client-go#1060]
Hello,

The fake client for the listing resource, such as [ListPod](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/fake/fake_pod.go#L58) is ignoring the FieldSelector:

```
label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.PodList{ListMeta: obj.(*corev1.PodList).ListMeta}
	for _, item := range obj.(*corev1.PodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
```

Only label is actually used for filtering. This makes any unittest testing code with fieldSelector failing. 
I did not checked all resources, but this problem happen at least for Pods, Service and Node.

**Comment by UtkarshChaurasia** [comment]
I was also trying to implement tests for fieldselector and facing the same issue.
