### ISSUE TITLE
Provide FORCE when deleting a pod

### ISSUE THREAD

**Issue by coreyperkins** [kubernetes/client-go#1062]
I am seeking guidance on how to forcefully delete a pod via this library. I would like to do so via DeleteOptions(https://github.com/kubernetes/client-go/blob/6964e37acfd3678087cfb1ced00774753c27ea96/applyconfigurations/meta/v1/deleteoptions.go) but force is not a property. 

Thanks,

Corey

**Comment by juliev0** [comment]
I would like to see this too!
