### ISSUE TITLE
example get error

### ISSUE THREAD

**Issue by jianghuitheoutsider** [kubernetes/client-go#1063]
# sigs.k8s.io/json/internal/golang/encoding/json
D:\Gopath\pkg\mod\sigs.k8s.io\json@v0.0.0-20211020170558-c049b76a60c6\internal\golang\encoding\json\encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
D:\Gopath\pkg\mod\sigs.k8s.io\json@v0.0.0-20211020170558-c049b76a60c6\internal\golang\encoding\json\encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)

**Comment by t1ger** [comment]
upgrade go version to 1.17
