### ISSUE TITLE
import  error for  k8s.io/api/batch/v2alpha1 

### ISSUE THREAD

**Issue by jianghuitheoutsider** [kubernetes/client-go#1064]
k8s.io/api/batch/v2alpha1: module k8s.io/api@latest found (v0.23.4), but does not contain package k8s.io/api/batch/v2alpha1

**Comment by AparnaSaripaka** [comment]
Any workaround found?

**Comment by jianghuitheoutsider** [comment]
> module k8s.io/api@latest found (v0.23.4), but does not contain package k8s

can you give me help ?  I don't know hao to resolve it.

**Comment by AparnaSaripaka** [comment]
latest go package doesn't have these modules. 

replace these in go.mod 
replace(	
        k8s.io/api => k8s.io/api v0.19.0
	k8s.io/apimachinery => k8s.io/apimachinery v0.19.0
	k8s.io/client-go => k8s.io/client-go v0.19.0
}

**Comment by jianghuitheoutsider** [comment]
OK,thanks! I'll try it right now

**Comment by jianghuitheoutsider** [comment]
this problem has been solved. Thank you very much！！！

**Comment by yavidor** [comment]
What if I want to use newer version?
