### ISSUE TITLE
How to use incluster config with custom service account and work with WorkLoadIdentity in GKE?

### ISSUE THREAD

**Issue by slaise** [kubernetes/client-go#1065]
Hi, 

I'm trying to make my code run in the cluster, and it worked with the default solution, by add `ClusterRole` to the `default/default` service account. But it failed when I tried to replace the default service account with another one, for example, a service account `test-sa` in `test` namespace. The error I got is:
```
in cluster config failed open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```
I couldn't find any docs about it, can some help out here?

And one more thing, I use GCP cloud API in the code too, so I tried to setup workload identity for the default service account. And failed and got the same error as above.  The only change I made to the service account is adding an annotation, e.g.
```
kubectl annotate serviceaccount default \
    --namespace default \
    iam.gke.io/gcp-service-account=GSA_NAME@GSA_PROJECT.iam.gserviceaccount.com
```

Does anyone have the experience working with both client-go and gke together?

**Comment by telecoda** [comment]
I've run into exactly the same problem. The workaround I'm using for now is to have the pod auto mount the service account token. Then fetch the token for the workload identity and use that as the bearer token. Then the IAM roles are respected.

```
// creates the in-cluster config
config, err := rest.InClusterConfig()
if err != nil {
	return nil, err
}
// replace k8s token with workload identity token
config.BearerToken, err = getWorkloadIdentityToken(serviceAccount)
if err != nil {
	return nil, err
}
config.BearerTokenFile = ""
```

I fetch the workload identity token with a function like this:
```
func getWorkloadIdentityToken(serviceAccount string) (string, error) {
	serviceAccount = strings.ReplaceAll(serviceAccount, "@", "%40") // escape the @
	tokenURL := w.MetadataURL + "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/" + serviceAccount + "/token"
	req, err := http.NewRequest("GET", tokenURL, nil)
	if err != nil {
		return "", err
	}

	req.Header.Add("Metadata-Flavor", "Google")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 299 {
		// extract token from response
		oauthResp := &oauth2.Token{}
		body, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			return "", err
		}

		err = json.Unmarshal(body, oauthResp)
		if err != nil {
			return "", err
		}

		return oauthResp.AccessToken, nil
	}

	return "", fmt.Errorf("unable to receive successful (< 299) responses from GKE metadata server")
}
```

**Comment by castaneai** [comment]
Hi, I am also using client-go with GKE and Workload Identity.
You can use [oauth2/google's DefaultTokenSource](https://pkg.go.dev/golang.org/x/oauth2/google#DefaultTokenSource) to fetch the token and pass it to the REST Config as follows

```go
config := &rest.Config{...}

// Fetch the access token (with Workload Identity)
tokenSource, err := google.DefaultTokenSource(ctx, "https://www.googleapis.com/auth/cloud-platform")
if err != nil {
	// error handling
}
token, err := tokenSource.Token()
if err != nil {
	// error handling
}

config.BearerToken = token.AccessToken
```
