### ISSUE TITLE
The compatibility-matrix needs to up to 1.28 in readme.md 

### ISSUE THREAD

**Issue by yankay** [kubernetes/client-go#1069]
The compatibility-matrix needs to up to 1.28 in readme.md.

Should it update to v1.23.x ？

(https://github.com/kubernetes/client-go#compatibility-matrix)

**Comment by RichardoC** [comment]
/remove-lifecycle rotten

This is still true on master that it needs updating

**Comment by sebrandon1** [comment]
The compatibility matrix still seems to need an update.
