### ISSUE TITLE
Continuously test installation instructions

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/client-go#107]
#106 adds detailed install instructions; I manually tested them, but the shell sections should be extracted to .sh files and travis should run them.

**Comment by lavalamp** [comment]
The difficulty here is testing the thing we're about to push to github, not the thing that currently lives in github. I started to do this the other day and realized that this step is not obvious.

**Comment by caesarxuchao** [comment]
cc @mbohlool

**Comment by sttts** [comment]
We do some smoke testing here: https://github.com/kubernetes/publishing-bot/blob/master/configs/kubernetes-rules-configmap.yaml#L144
