### ISSUE TITLE
Package upgrade blocked

### ISSUE THREAD

**Issue by regnaio** [kubernetes/client-go#1075]
Please refer to the command and its output below:

```
go get -u ./...

# k8s.io/client-go/applyconfigurations/meta/v1
/go/pkg/mod/k8s.io/client-go@v0.23.5/applyconfigurations/meta/v1/unstructured.go:64:37: cannot use doc (type *"github.com/googleapis/gnostic/openapiv2".Document) as type *"github.com/google/gnostic/openapiv2".Document in argument to "k8s.io/kube-openapi/pkg/util/proto".NewOpenAPIData
```

**Comment by websi96** [comment]
Same here, but I think it already got resolved in an upcoming version:

Here the correct pkg gets imported: [https://github.com/kubernetes/client-go/blob/v0.24.0-alpha.4/discovery/discovery_client.go#L32](https://github.com/kubernetes/client-go/blob/v0.24.0-alpha.4/discovery/discovery_client.go#L32)

**Comment by Dudssource** [comment]
Same problem here, updating all deps through `go get -u `doesn't work.

**Comment by Dudssource** [comment]
> > Same problem here, updating all deps through `go get -u `doesn't work.
> 
> update to `v0.24.0-alpha.4`, it helped me

It worked @zrks ! Thank you!

**Comment by sumithreddy** [comment]
did anyone figure out a solution for this one. Looks like issue is on all versions of 0.23

**Comment by nicks** [comment]
i was able to fix this by replacing the `k8s.io/kube-openapi` entry in the go.mod in my project with this:

```
k8s.io/kube-openapi v0.0.0-20211115234752-e816edb12b65 // indirect
```

**Comment by jbyers19** [comment]
Adding this to my `go.mod` fixed some of the openapi type errors I was running into:
```golang
replace (
    github.com/googleapis/gnostic => github.com/googleapis/gnostic v0.5.5
)
```

**Comment by Jefftree** [comment]
The latest version of kube-openapi is only compatible with v0.24 of kubernetes so a `go get -u` on a v0.23 repo will pull in an incompatible module. I was under the impression that for a specific k8s release, we have dependencies pinned for a reason. Is it convention to run a `go get -u` on the client-go repo?

We try to maintain backwards incompatibility as much as possible, but things like module renames will cause version incompatibilities between certain versions.  

cc @liggitt

**Comment by liggitt** [comment]
> Is it convention to run a go get -u on the client-go repo?

no, upgrading to HEAD of all dependencies of client-go is not expected to work as long as some are on v0... revisions

**Comment by wqgs2004214** [comment]
1

> > Is it convention to run a go get -u on the client-go repo?
> 
> no, upgrading to HEAD of all dependencies of client-go is not expected to work as long as some are on v0... revisions

**Comment by nyetwurk** [comment]
> 

This does not work either.

**Comment by nyetwurk** [comment]
https://github.com/kubernetes/kube-openapi/issues/404

**Comment by shubham-cmyk** [comment]
I am still facing this issue I am using  `k8s.io/client-go v0.27.3`

**Comment by liggitt** [comment]
`go get -u ./...` is not likely to work seamlessly with v0 modules, which includes client-go and many of its dependencies (including gnostic, mergo, and others).

client-go is tested with the versions of dependencies referenced from its go.mod file, but newer versions of v0... dependencies may or may not work correctly with client-go

When client-go v0.28.x is released (~August 2023), this specific conflict between gnostic and gnostic-models will be resolved.

/close
