### ISSUE TITLE
Fake SimpleClientSet: Can't use GetScale

### ISSUE THREAD

**Issue by TomFreeman** [kubernetes/client-go#1077]
If I try to use the GetScale method on the Fake SimpleClientset, then it causes a panic related to the underlying Fake re-using the Deployment object, and not selecting a Scale one, even if provided.

It seems this should work, but appreciate it might be beyond the capabilities of the SimpleClientset.

It appears the GroupVersionResource used in both fetching the Deployment, and GetScale are the same, so the underlying mock holds them in the same place.

Some examples:

Trying to provide the scale object alongside the deployment will fail.

```go
func Test_GetScaleFakeClient(t *testing.T) {
	fakeKubeClient := fake.NewSimpleClientset(
		&appsv1.Deployment{ObjectMeta: metav1.ObjectMeta{Namespace: "foo-ns", Name: "foo-name"}},
		&autoscalingv1.Scale{ObjectMeta: metav1.ObjectMeta{Namespace: "foo-ns", Name: "foo-name"}, Spec: autoscalingv1.ScaleSpec{Replicas: 1}},
	)

    // Panics as GetScale gets the deployment object, and fails to cast.
	_, _ := fakeKubeClient.AppsV1().Deployments("foo-ns").GetScale(context.TODO(), "foo-name", metav1.GetOptions{})
}
```

You can use UpdateScale to set the Scale object, which works for GetScale - but causes a panic when you next fetch a deployment, as the scale object is now in the same place on the dictionary, and can't be cast back to a deployment.

```go
func Test_GetScaleFakeClient(t *testing.T) {
	fakeKubeClient := fake.NewSimpleClientset(&appsv1.Deployment{ObjectMeta: metav1.ObjectMeta{Namespace: "foo-ns", Name: "foo-name"}})

	fakeKubeClient.AppsV1().Deployments("foo-ns").UpdateScale(context.TODO(), "foo-name", &autoscalingv1.Scale{ObjectMeta: metav1.ObjectMeta{Namespace: "foo-ns", Name: "foo-name"}, Spec: autoscalingv1.ScaleSpec{Replicas: 1}}, metav1.UpdateOptions{})

	_, err := fakeKubeClient.AppsV1().Deployments("foo-ns").GetScale(context.TODO(), "foo-name", metav1.GetOptions{})
	if err != nil {
		t.Fatal(err, "Get Scale will error if UpdateScale not called")
	}

    // Panics here, as the Deployments call actually gets a scale, and panics when trying to cast.
	deployment, err := fakeKubeClient.AppsV1().Deployments("foo-ns").Get(context.TODO(), "foo-name", metav1.GetOptions{})
	if err != nil {
		t.Fatal(err)
	}

	if deployment != nil {
		t.Fatal(deployment)
	}
}
```

**Comment by benjaminclauss** [comment]
appears related to the following

https://github.com/kubernetes/kubernetes/issues/110424#issuecomment-1154633391

**Comment by acouvreur** [comment]
This issue is still present as far as I know, any fix available ?
