### ISSUE TITLE
client-go 0.23.5 run blocked

### ISSUE THREAD

**Issue by regnaio** [kubernetes/client-go#1084]
Using `go 1.18.1` or `go 1.17.9` and `client-go 0.23.5`

```bash
go run <script using client-go>

# k8s.io/client-go/applyconfigurations/meta/v1
/go/pkg/mod/k8s.io/client-go@v0.23.5/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/googleapis/gnostic/openapiv2".Document) as type *"github.com/google/gnostic/openapiv2".Document in argument to proto.NewOpenAPIData
```

**Comment by simongottschlag** [comment]
It helped reverting client-go to `v0.22.8` for me. Just a work around though.

**Comment by liggitt** [comment]
make sure you have matching client-go and kubectl module versions

**Comment by liggitt** [comment]
(and are using the version of k8s.io/kube-openapi/pkg/util/proto indicated by your version of client-go)

**Comment by liggitt** [comment]
I suspect you are trying to use HEAD of k8s.io/kube-openapi with v0.23.5 of client-go

**Comment by liggitt** [comment]
[client-go 0.23.5](https://github.com/kubernetes/client-go/blob/v0.23.5/go.mod#L36) uses this version of kube-openapi:

```
k8s.io/kube-openapi v0.0.0-20211115234752-e816edb12b65
```

https://github.com/kubernetes/kube-openapi/commits/master/pkg/util/proto shows the history of that file, which changed the signature of that method from googleapis/gnostic → google/gnostic on 3/10/2022

the error you're getting indicates you were using a version of kube-openapi >= 3/10/2022 in your build

**Comment by walteh** [comment]
The problem came up again this week from [this pr](https://github.com/kubernetes/kube-openapi/pull/402) in `kube-openapi`.

I solved it today by updating `client-go` to include [this commit](https://github.com/kubernetes/client-go/commit/2bd3f492360701f79b104bc95dfabf3fb1474c5f).

> **Warning** this is not a long term fix and should only be used if necessary and until `v0.28.0` is stable. 

```go
// go.mod
replace k8s.io/client-go => k8s.io/client-go v0.28.0-alpha.2
```

**Comment by lowang-bh** [comment]
also met this error with client-go v0.27.0~v0.27.2

**Comment by bxy4543** [comment]
```
# k8s.io/client-go/openapi
../../../../../../pkg/mod/k8s.io/client-go@v0.25.6/openapi/groupversion.go:35:18: undefined: handler3.OpenAPIV3DiscoveryGroupVersion
../../../../../../pkg/mod/k8s.io/client-go@v0.25.6/openapi/groupversion.go:38:52: undefined: handler3.OpenAPIV3DiscoveryGroupVersion
../../../../../../pkg/mod/k8s.io/client-go@v0.25.6/openapi/client.go:52:24: undefined: handler3.OpenAPIV3Discovery
```

https://pkg.go.dev/k8s.io/kube-openapi/pkg/handler3?tab=versions

```
replace k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20220803164354-a70c9af30aea
```
