### ISSUE TITLE
Get resources whose owner reference is set to my resource

### ISSUE THREAD

**Issue by luckielordie** [kubernetes/client-go#1085]
I'm writing a controller that creates resources that are owners of multiple other resources. This is akin to a 1 to many relationship. 

I need to be able to get all the resources that are owned by the object I'm reconciling.  For now, I'm adding my own ownership label and doing a label selection. But since the ownership information already contains everything I need I wondered if there was a better way. The only method I can fathom though is to List all the resources and filter them myself.

- Is there a function to retrieve only owned resources of an object?
- Do you have any tips for a solution? 
- Would a function to perform this be problematic if added to this library? (Am I even in the right place for this discussion?)

**Comment by kluevandrew** [comment]
same question for me
