### ISSUE TITLE
How to create a node on the master node？

### ISSUE THREAD

**Issue by BeIFreedom** [kubernetes/client-go#1086]
res, err := clientset.CoreV1().Nodes().Create(context.Background(), node, metav1.CreateOptions{})
How do I configure this node？

**Comment by linqinghuang** [comment]
> res, err := clientset.CoreV1().Nodes().Create(context.Background(), node, metav1.CreateOptions{}) How do I configure this node？

same problem？any solution?

**Comment by zhangyial** [comment]
same question，can give us  an example of  this  api to show how to create  a node
