### ISSUE TITLE
Failed to watch *v1.ConfigMap: unknown

### ISSUE THREAD

**Issue by Pangzhihong** [kubernetes/client-go#1090]
Hello,this error is continuously recorded in logs of the customized operator.What's going on?

I0429 15:21:41.748876       1 reflector.go:255] Listing and watching *v1.ConfigMap from k8s.io/client-go@v0.0.0-20220413082133-9e9f9129be1f/tools/cache/reflector.go:167
E0429 15:21:41.752587       1 reflector.go:138] k8s.io/client-go@v0.0.0-20220413082133-9e9f9129be1f/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: unknown (get configmaps)
I0429 15:22:35.053477       1 reflector.go:255] Listing and watching *v1.ConfigMap from k8s.io/client-go@v0.0.0-20220413082133-9e9f9129be1f/tools/cache/reflector.go:167
E0429 15:22:35.058932       1 reflector.go:138] k8s.io/client-go@v0.0.0-20220413082133-9e9f9129be1f/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: unknown (get configmaps)

**Comment by zhucan** [comment]
- apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "watch"]

add it to rbac is ok for you? @Pangzhihong
