### ISSUE TITLE
Invalid apiVersion

### ISSUE THREAD

**Issue by SebastienMelki** [kubernetes/client-go#1095]
Hello,

I'm trying to run the out of cluster example found here https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration . I made sure that 'kubectl get nodes' is working correctly when I run it from my terminal, and also made sure that my kube config if being picked up correctly from ~/.kube/config.
But the example code is not running as expected and generating the following error 'exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"' when running kubernetes.NewForConfig(config).

Any help would be appreciated, I tried searching past issues but didn't find similar errors. 

Thanks! 
![image](https://user-images.githubusercontent.com/5787993/169400505-c5633f29-12ae-47ad-a454-94ac46036dea.png)
![image](https://user-images.githubusercontent.com/5787993/169400500-092a834d-022a-478f-af02-45f7819ee21a.png)

**Comment by ocallaghane** [comment]
I've the identical issue.  

I tried, as a test, to set 'apiVersion: client.authentication.k8s.io/v1beta1' in my .kube/config file, and while that got me past the error described above (exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1") with kubernetes.NewForConfig(config) it lead me to this further error below in the next part of the code (clientset.CoreV1().Pods) listing pods.  

_Get "https://**********************.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods": getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100"_

**Comment by zhengyansheng** [comment]
I've the identical issue.
use aws eks

**Comment by krriteshgupta** [comment]
I was facing the same problem with kubernetes server version is 1.20.x and client-go version 0.24.0 . I downgraded my client-go version to 0.20.4 and it worked. Please make sure that the client-go version is compatible with the version of your K8s server.

**Comment by ocallaghane** [comment]
> I was facing the same problem with kubernetes server version is 1.20.x and client-go version 0.24.0 . I downgraded my client-go version to 0.20.4 and it worked. Please make sure that the client-go version is compatible with the version of your K8s server.

Thanks alot @krriteshgupta - this fixed the issue downgrading the client-go to 0.20.4 (AWS EKS 1.21.x)

**Comment by russau** [comment]
I can talk to EKS okay from  v0.24.1. The most recent version of the AWS cli will generate a kubeconfig with `client.authentication.k8s.io/v1beta1` .  The newer AWS cli also include the correct version in the response from `aws eks  get-token --cluster-name`:

``` json
{
  "kind": "ExecCredential",
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "spec": {},
  "status": {
    "expirationTimestamp": "2022-06-15T06:22:26Z",
    "token": "k8s-aws-..snip.."
  }
}
```

More details here: https://github.com/aws/aws-cli/issues/6920

**Comment by ngangadhar-pki** [comment]
> I've the identical issue.
> 
> I tried, as a test, to set 'apiVersion: client.authentication.k8s.io/v1beta1' in my .kube/config file, and while that got me past the error described above (exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1") with (kubernetes.NewForConfig(config) it lead me to this further error below in the next part of the code (clientset.CoreV1().Pods) listing pods.
> 
> _Get "https://**********************.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods": getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100"_

I have a similar issue. Any help would be appreciated.

**Comment by clayrisser** [comment]
I'm facing the same problem

**Comment by ngangadhar-pki** [comment]
> I'm facing the same problem

@clayrisser Updating AWS CLI V1 to V2 helped me solve this.

**Comment by karthikeayan** [comment]
In my case, I was running the go command via Linux Cron. And the PATH variable contains only the "/usr/bin" path. AWS CLI v2 was in "/usr/local/bin". AWS CLI v1 was in "/usr/bin". Go program used AWS CLI v1 and hence this error.

After adding PATH=/usr/local/bin:$PATH to the Cron command, issue resolved.

**Comment by kaye-alvarado** [comment]
> PATH=/usr/local/bin:$PATH

This worked for me! Thank you!

**Comment by Vinaum8** [comment]
doc for aws: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html#getting-started-install-instructions
