### ISSUE TITLE
Help: Node patching not working

### ISSUE THREAD

**Issue by Shikaz** [kubernetes/client-go#1096]
I am trying to patch custom node condition types, my below code is not working or patching although error is nil, also I have tested by running curl against the api and it's working fine. 

**Example1:**

```
	payloadT := []byte(`[{"op": "replace", "path": "/status/conditions/0","value": { "type": "QuayStatez", "status": "True"}}]`)
	node2, err := clientset.CoreV1().Nodes().Patch(context.TODO(), "<Node-Name>", types.JSONPatchType, payloadT, metav1.PatchOptions{})
```

**Example2:**

```
	type Value struct {
		Type   string `json:"type"`
		Status string `json:"status"`
	}

	type Cond struct {
		Op    string `json:"op"`
		Path  string `json:"path"`
		Value Value  `json:"value"`
	}

	payloadz := []Cond{{
		Op:   "add",
		Path: "/status/conditions/6",
		Value: Value{
			Type:   "SMelikTest",
			Status: "True",
		},
	}}


	bytesPayloadTT, _ := json.Marshal(payloadz)

	node2, err := clientset.CoreV1().Nodes().Patch(context.TODO(), "<Node-Name>", types.JSONPatchType, bytesPayloadTT, metav1.PatchOptions{})
```

Curl command which is working fine:

`curl -k -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json-patch+json" -X PATCH https://<APISERVER>:6443/api/v1/nodes/<Node-Name>/status --data '[{ "op": "replace", "path": "/status/conditions/0","value": { "type": "Test123", "status": "False" }}]'`

Any ideas would be much appreciated.

**Comment by mirocody** [comment]
@Shikaz try this, it works for me 

`node2, err := clientset.CoreV1().Nodes().Patch(context.TODO(), "<Node-Name>", types.JSONPatchType, bytesPayloadTT, metav1.PatchOptions{}, "status")`
