### ISSUE TITLE
Fill out CHANGELOG.md

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/client-go#111]
Changelog has been neglected and it's hard for people to understand what is in which branches.

**Comment by xiang90** [comment]
Can you also talk about how users should migrate from 1.5 to 2.0? What changed? What users should change to.

**Comment by nikhita** [comment]
https://github.com/kubernetes/client-go/pull/275, https://github.com/kubernetes/client-go/pull/313, https://github.com/kubernetes/client-go/pull/317, https://github.com/kubernetes/client-go/pull/341 update the CHANGELOG and it is now upto date.

**Comment by nikhita** [comment]
> What changed? What users should change to.

The current [`CHANGELOG`](https://github.com/kubernetes/client-go/blob/master/CHANGELOG.md#v600) mentions the breaking changes in detail.

Closing. Please reopen if you think more details are needed.

/close
