### ISSUE TITLE
Can we re-open this?

### ISSUE THREAD

**Issue by vgupta-mickey** [kubernetes/client-go#1110]
Can we re-open this? 

I'm happy to answer questions from a Crossplane perspective. My use-case is I would like to filter events of a  Crossplane ManagedResource which happens to be cluster-scoped.

_Originally posted by @luebken in https://github.com/kubernetes/client-go/issues/781#issuecomment-997923047_

**Comment by vgupta-mickey** [comment]
I have the exact same issue.  my Application is running in non-default namespace and I need to generate event on a cluster-scoped CRD. But I want to generate event in non-default namespace.

**Comment by andreaskaris** [comment]
Well I actually have the same question, 3 is a charm? ;-)
