### ISSUE TITLE
get float cpu size

### ISSUE THREAD

**Issue by dateolive** [kubernetes/client-go#1112]
How do i get the numerical value of the cpu, the cpu size is a float

**Comment by monoxane** [comment]
You can convert the type to an `Int` with 
```go 
cpuCapacityInt := int(capacity.cpu)
```
However you haven't provided a whole lot of information, if you're trying to get the node capacity or allocatable capacity as an `Int` you're probably better off getting it like so:
```go
cpuCapacity, err := node.Status.Capacity.Cpu().AsInt64()
if err != nil {
 log.Printf("unable to get node capacity: %s", err)
}
```
Which will return it as an `Int64` that you can then typecast if you need to.
