### ISSUE TITLE
Improve "timed out waiting for the condition" error by providing more details

### ISSUE THREAD

**Issue by ewirch** [kubernetes/client-go#1118]
Seeing this kubectl error message from an atomic Helm deployment in a CI environment is really frustrating. Diagnosing these cases is really time consuming.

kubectl could provide more details about which condition timed out, and maybe even more details like logs (stdout/stderr output).

**Comment by faizanf47** [comment]
+1

**Comment by os-cas** [comment]
Could you re-open this?
