### ISSUE TITLE
How to get all workloads and match them to pods?

### ISSUE THREAD

**Issue by SomniVertix** [kubernetes/client-go#1124]
Im trying to get a complete view of the deployments, statefulsets, replicasets, etc and match them to their respective pods. 

What I've tried so far:

1. Pod-First: I've tried getting all the pods and assuming to use `pod.ObjectMeta.OwnerReferences[0].Name` but that usually results in matching to the ReplicaSet and not the deployment itself.
2. Workload-First: Generally the same issue - I can't seem to overcome the variable of a replicaSet, statefulSet, or any other workload being in between the main workload and the child workloads.

Not really sure what the options are or what the best practices would be for getting this

**Comment by SomniVertix** [comment]
Any help with this?

**Comment by akankshakumari393** [comment]
Hey @SomniVertix could you please elaborate you issue with some example?

**Comment by aerfio** [comment]
why cant you just follow along and get replicaset's owner via ownerref?

**Comment by SomniVertix** [comment]
@akankshakumari393 Sure - the main goal is to get a clear view of the application as a whole. Meaning that I'd like to map an application's parent workload instance to its pods. Currently I've used both the pods API `clientset.CoreV1().Pods("").List(context.TODO(), options)` and the deployments API `clientset.AppsV1().Deployments("").List(context.TODO(), metav1.ListOptions{})`. But wasn't sure which one is better to use?

@aerfio - do replicaSets have a representation of the whole cluster's resources? Some of the different tools I've seen so far seem to separate out Pods/Deployments/Daemonsets/Statefulsets/replicasets/jobs/cronjobs. I imagine that if I start with replicaSets, I would miss out on things like Daemonsets/Statefulsets. And if I go through the replicaSet, I'd then have to constantly iterate to hopefully get to the top-level workload type which may turn into a lot of nesting depending on the workload. 

I guess that does bring up a few questions as well:
1. Do workloads (ex: Deployments/DaemonSets/etc) match straight to pods, or can they sometimes have different workload types in between? Meaning is it normally Deployments -> pods, or can it be Deployments-> Daemonsets -> ReplicaSets -> Pods? 

2.  Is there a master "workload" type that has all the downstream elements of an application?

**Comment by grzesuav** [comment]
@SomniVertix just use https://github.com/tohjustin/kube-lineage to see the type hierarchy if you are unsure of that

**Comment by grzesuav** [comment]
and answering your question, it depends on the workload - Deployment controller uses Replicaset, Statefulset controller uses pods directly
