### ISSUE TITLE
go-restful has a high-risk vulnerability and needs to be upgraded to v3.8.0

### ISSUE THREAD

**Issue by fengshunli** [kubernetes/client-go#1135]
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/18587688/179710656-cfa9d2bb-9c04-4f96-90ec-53bd841d6b79.png">

**Comment by TrygviLauritsen** [comment]
Was also brought up with https://github.com/kubernetes/client-go/issues/1117#issue-1280626159, which is closed without being fixed.

**Comment by briantopping** [comment]
The problem is https://github.com/kubernetes/client-go/commit/2a9f95519059bcb745428698c59bf4a376c3f383 never made it to client-go 1.24 tag due to a missing cherry pick of this commit.

**Comment by briantopping** [comment]
See https://github.com/kubernetes-csi/external-attacher/issues/369 for some analysis.
