### ISSUE TITLE
0.25 version release date

### ISSUE THREAD

**Issue by vinpai** [kubernetes/client-go#1141]
Currently, there is an 0.25.3-alpha version that has been released. When can one expect to have an official 0.25 version to be released ?

**Comment by niteshagrawalgmail** [comment]
Hi. We have also observed some vulnerability with 0.24 versions as reported by whitesource scans. These are fixed in master.
When can we expect 0.25 version to be released?

**Comment by nikhita** [comment]
`0.25.0` will be released when Kubernetes releases a `v1.25.0` - https://github.com/kubernetes/kubernetes/tags
