### ISSUE TITLE
Fake Dynamic Client does not validate object types in create function

### ISSUE THREAD

**Issue by pablochacin** [kubernetes/client-go#1156]
I'm developing some unit tests for a library that uses the Dynamic Client for creating and accessing resources. When developing a test for creating a Pod I noticed that the object I passed to the `Create` function was not validated at all, neither was the `GroupVersionResource`. I thought it was because the `Pod` type was not registered, but adding it to the scheme did not make any difference. 

I'm aware I can add this validation to every tests checking the returned object, but given the dynamic client receives unstructured objects, it seems to me reasonable to expect that it at least validates that the object is of a know type.

The tests in the code bellow passes even when the resource's kind is `Foo` and this is not a known type.

```
func TestDynamicCreate(t *testing.T) {
	t.Parallel()

	ctx := context.TODO()
	scheme := runtime.NewScheme()
	scheme.AddKnownTypeWithName(
		schema.GroupVersionKind{
			Group:    "",
			Version:  "v1",
			Kind:     "Pod",
		},
		&coreV1.Pod{},
	)
	client := dynFake.NewSimpleDynamicClient(
		scheme,
	)
	podGroup := schema.GroupVersionResource{
		Group:    "",
		Version:  "v1",
		Resource: "pods",
	}

	podSpec := map[string]interface{}{
		"apiVersion": "v1",
		"kind":       "Foo",
		"metadata": map[string]interface{}{
			"name": "dynamic-pod",
		},
		"spec": map[string]interface{}{
			"containers": []interface{}{
				map[string]interface{}{
					"name":    "sleeper",
					"image":   "busybox",
					"command": []interface{}{"sh", "-c", "sleep 3"},
				},
			},
		},
	}
	namespace := "default"
	uObj := &unstructured.Unstructured{
		Object: podSpec,
	}
	result, err := client.Resource(podGroup).Namespace(namespace).Create(ctx, uObj, metaV1.CreateOptions{})
	require.NoError(t, err)
	pod :=  result.UnstructuredContent()
	require.NotNil(t, pod)
}
```

**Comment by mark8s** [comment]
@pablochacin Hello, I also encountered this problem, what is the follow-up?
