### ISSUE TITLE
Sort events by timestamp

### ISSUE THREAD

**Issue by naveenbharadwaj-nc** [kubernetes/client-go#1168]
Hello,

`kubectl` provides a way to sort events by using:
`kubectl get events --sort-by='.metadata.creationTimestamp'`

How can I achieve the same using client-go APIs?
```
events, err := clientset.CoreV1().Events(namespace).List(context.TODO(), metav1.ListOptions{
	FieldSelector: "involvedObject.name="+pod, TypeMeta: metav1.TypeMeta{Kind: "Pod"}, 
})
```
Is there any ListOptions that I can use to sort events?

**Comment by gujingit** [comment]
@naveenbharadwaj-nc  hello,  I had the same problem. Do you have any solutions? Thanks.

**Comment by naveenbharadwaj-nc** [comment]
No. I suppose you have to loop through the `EventList `and sort them yourself by checking `event.EventTime`
