### ISSUE TITLE
kubernetes golang client library in k3s cluster

### ISSUE THREAD

**Issue by sumithsudesan** [kubernetes/client-go#1171]
Hi,
Is there any problem in using applications created with k8s client library (golang) in k3s cluster .

Trying to create a service , which create pods, service on request  from the end user.

im getting error like 

panic: stat /etc/rancher/k3s/k3s.yaml: no such file or directory

goroutine 1 [running]:
main.main()
        /app/main.go:83 +0x990

**Comment by dims** [comment]
could you ask k3s folks please?
