### ISSUE TITLE
question: update pod with specific container 

### ISSUE THREAD

**Issue by twokindswater** [kubernetes/client-go#1175]
hi i want to update my pod which has multiple containers.
my source code and error message is bellow. how to update my specific pod? please help.

```golang 
pods, _ := client.CoreV1().Pods("default").List(context.Background(), meta_v1.ListOptions{
		LabelSelector: "mylabel",
	})
	for _, pod := range pods.Items {
		p, err := client.CoreV1().Pods("default").Update(context.Background(), &pod, meta_v1.UpdateOptions{})
		panic(err) // return error 
	}
```

error message : container name must be specified for pod A-POD, choose one of: [A-container B-container C-container]

**Comment by Tsingshen** [comment]
I have tried your code, not get this error, you should check more your code.
