### ISSUE TITLE
Rest Client defaults to no backoff

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes/client-go#1181]
The rest client defaults to no backoff when a custom one is not defined in any environment variables.  This seems dangerous since GET requests which error out due to connection reset will retry immediately by default.

https://github.com/kubernetes/client-go/blob/cbe28cf468c43969d2c170e079f556becfc7adb7/rest/client.go#L143

**Comment by robscott** [comment]
@lavalamp @apelisse Do you know if there's some historical context for the lack of a default backoff here?

**Comment by lavalamp** [comment]
I don't think it was a deliberate choice.

This issue would get more attention if made in the main repo BTW
