### ISSUE TITLE
fake.clientset doesn't behave properly on Apply

### ISSUE THREAD

**Issue by miguescri** [kubernetes/client-go#1184]
**What I'm trying to do:** use the fake.Clientset mock to unit test a declarative Apply operation.
**Expected behavior:** if the declarative resource doesn't refer to an existing object, create it; else, patch it.
**Actual behavior:** when the declarative resource doesn't refer to an existing object, returns error "Not found".

Minimal reproducible test:

```go
package clientest_bug

import (
	"context"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	applyv1 "k8s.io/client-go/applyconfigurations/core/v1"
	"k8s.io/client-go/kubernetes/fake"
	"testing"
)

func TestClientsetApply(t *testing.T) {
	clientset := fake.NewSimpleClientset()
	namespaceClient := clientset.CoreV1().Namespaces()

	namespace := applyv1.Namespace("test-namespace")
	_, err := namespaceClient.Apply(context.TODO(), namespace, v1.ApplyOptions{FieldManager: "test"})
	if err != nil {
		t.Fatalf("Error: %s", err)
	}
}
```
go test output:

```sh
/usr/lib/go-1.18/bin/go tool test2json -t /tmp/GoLand/___go_test_clientest_bug.test -test.v -test.paniconexit0
=== RUN   TestClientsetApply
    main_test.go:18: Error: namespaces "test-namespace" not found
--- FAIL: TestClientsetApply (0.00s)

FAIL

Process finished with the exit code 1
```

**Comment by vietanhduong** [comment]
Not only apply, I think this happens with all other verbs and CRDs.

**Comment by therealmitchconnors** [comment]
I was able to work around this with a Deployment reactor.  A smarter man than myself might combine this with a restmapper and scheme to work for any type until the client-go library is fixed.

```
f := fake.NewSimpleClientset(objects...)
f.PrependReactor(
"patch",
"deployments",
func(action clienttesting.Action) (handled bool, ret runtime.Object, err error) {
	pa := action.(clienttesting.PatchAction)
	if pa.GetPatchType() == types.ApplyPatchType {
		// Apply patches are supposed to upsert, but fake client fails if the object doesn't exist,
		// if an apply patch occurs for a deployment that doesn't yet exist, create it.
		// However, we already hold the fakeclient lock, so we can't use the front door.
		rfunc := clienttesting.ObjectReaction(f.Tracker())
		_, obj, err := rfunc(
			clienttesting.NewGetAction(pa.GetResource(), pa.GetNamespace(), pa.GetName()),
		)
		if kerrors.IsNotFound(err) || obj == nil {
			_, _, _ = rfunc(
				clienttesting.NewCreateAction(
					pa.GetResource(),
					pa.GetNamespace(),
					&appsv1.Deployment{
						ObjectMeta: metav1.ObjectMeta{
							Name:      pa.GetName(),
							Namespace: pa.GetNamespace(),
						},
					},
				),
			)
		}
		return rfunc(clienttesting.NewPatchAction(
			pa.GetResource(),
			pa.GetNamespace(),
			pa.GetName(),
			types.StrategicMergePatchType,
			pa.GetPatch()))
	}
	return false, nil, nil
},
)
```

**Comment by rkk1995** [comment]
> I was able to work around this with a Deployment reactor. A smarter man than myself might combine this with a restmapper and scheme to work for any type until the client-go library is fixed.
> 
> ```
> f := fake.NewSimpleClientset(objects...)
> f.PrependReactor(
> "patch",
> "deployments",
> func(action clienttesting.Action) (handled bool, ret runtime.Object, err error) {
> 	pa := action.(clienttesting.PatchAction)
> 	if pa.GetPatchType() == types.ApplyPatchType {
> 		// Apply patches are supposed to upsert, but fake client fails if the object doesn't exist,
> 		// if an apply patch occurs for a deployment that doesn't yet exist, create it.
> 		// However, we already hold the fakeclient lock, so we can't use the front door.
> 		rfunc := clienttesting.ObjectReaction(f.Tracker())
> 		_, obj, err := rfunc(
> 			clienttesting.NewGetAction(pa.GetResource(), pa.GetNamespace(), pa.GetName()),
> 		)
> 		if kerrors.IsNotFound(err) || obj == nil {
> 			_, _, _ = rfunc(
> 				clienttesting.NewCreateAction(
> 					pa.GetResource(),
> 					pa.GetNamespace(),
> 					&appsv1.Deployment{
> 						ObjectMeta: metav1.ObjectMeta{
> 							Name:      pa.GetName(),
> 							Namespace: pa.GetNamespace(),
> 						},
> 					},
> 				),
> 			)
> 		}
> 		return rfunc(clienttesting.NewPatchAction(
> 			pa.GetResource(),
> 			pa.GetNamespace(),
> 			pa.GetName(),
> 			types.StrategicMergePatchType,
> 			pa.GetPatch()))
> 	}
> 	return false, nil, nil
> },
> )
> ```

What is rfunc?
