### ISSUE TITLE
help integrating aws token generator with client-go

### ISSUE THREAD

**Issue by jeevanragula** [kubernetes/client-go#1189]
### What happened?

Kubernetes client-go informers getting unauthorized error after 15 mins.

As per Kubernetes Client Go blogs and discussion we see the client go wil refresh the token after 15 mins but it is not happening. Any way to refresh the token without stopping the informer?

`

	gen, err := token.NewGenerator(false, false)
	if err != nil {
		return token.Token{}, err
	}

	opts := &token.GetTokenOptions{
		Region:               cluster.Region,
		ClusterID:            aws.StringValue(&cluster.Name),
		AssumeRoleARN:        cluster.AssumeRoleConfig.RoleArn,
		AssumeRoleExternalID: cluster.AssumeRoleConfig.ExternalId,
		SessionName:          "testsession",
		Session:              awsSession,
	}
	token, err := gen.GetWithOptions(opts)
        clientConfig := &rest.Config{
		Host:        cluster.Endpoint,
		BearerToken: token.Token,
		TLSClientConfig: rest.TLSClientConfig{
			CAData: ca,
		},
	}
        dynamicClient, err := dynamic.NewForConfig(clientConfig)

        factory := dynamicinformer.NewFilteredDynamicSharedInformerFactory(dynamicClient, 60*time.Minute, "", nil)	
        gvr := schema.GroupVersionResource{Group: "apps", Version: "v1 ", Resource: "deployments"}

	informer := factory.ForResource(gvr).Informer()

	informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
			fmt.Println(obj)
		},

		UpdateFunc: func(old, new interface{}) {
			fmt.Println(old)
			fmt.Println(new)
		},
	})

	factory.Start(ctx.Done())
`

### What you expected to happen?

The Kubernetes Auth Token created by aws-iam-authenticator should be refreshed automatically.

### Installation tooling

other (please specify in description)

### AWS IAM Authenticator server Version

AWS EKS Managed service

### Client information

```Markdown
- OS/arch: Darwin/arm64 & Linux/amd64
- kubernetes client & version: k8s.io/client-go v0.25.2
- authenticator client & version: sigs.k8s.io/aws-iam-authenticator v0.5.9
```

### Kubernetes API Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:36:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1

**Comment by jeevanragula** [comment]
@liggitt @dims @caesarxuchao @smarterclayton @nikhita Can any one of you please help here?

**Comment by liggitt** [comment]
You're not giving the client any way to get a refreshed token, but are setting a fixed BearerToken: string at client creation time

**Comment by jragula-zs** [comment]
@liggitt Can you suggest how to supply the refresh mechanism to the client?

**Comment by jeevanragula** [comment]
> You're not giving the client any way to get a refreshed token, but are setting a fixed BearerToken: string at client creation time

Can you suggest how to supply the refresh mechanism to the client?

**Comment by liggitt** [comment]
> @liggitt Can you suggest how to supply the refresh mechanism to the client?

instead of setting a bearer token directly in rest.Config, setting `WrapTransport` in the rest.Config to a function that will wrap the transport and inject a token when needed would work.

[TokenSourceWrapTransport](https://pkg.go.dev/k8s.io/client-go/transport#TokenSourceWrapTransport) is an example of what that could look like for a token source that implements [oauth2.TokenSource](https://pkg.go.dev/golang.org/x/oauth2#TokenSource), but I'm not sure how the aws token issuer is expected to be used with client-go.

cc @micahhausler @nckturner

**Comment by jeevanragula** [comment]
Thanks @liggitt .

We implemented it like this and it worked and we are able to supply the new token on every List/Watch call.

But It would be better if the client-go itself has any mechanism to supply this refresh function.

```

restConfig := &rest.Config{
      Host:        kubeConfigResponse.KubeConfig.GetHost(),
      BearerToken: kubeConfigResponse.KubeConfig.GetBearerToken(),
      TLSClientConfig: rest.TLSClientConfig{
	      CAData: kubeConfigResponse.KubeConfig.GetCaData(),
      },
}
httpClient, err := rest.HTTPClientFor(restConfig)
if err != nil {		
    return nil, err
}
refreshTransport := &BearerTokenRefreshRounderTripper{
    Base: httpClient.Transport,
    TokenProvider: func(isListRequest bool) (string, error) {
                              return newToken, nil
                    },
}
httpClient.Transport = refreshTransport
dynamicClient, err := dynamic.NewForConfigAndClient(restConfig, httpClient)

type BearerTokenRefreshRounderTripper struct {
	Base          http.RoundTripper
	TokenProvider func() (string, error)
}

func (t *BearerTokenRefreshRounderTripper) RoundTrip(req *http.Request) (*http.Response, error) {

	token, err := t.TokenProvider()
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", token))
	return t.Base.RoundTrip(req)
}

```

**Comment by zchenyu** [comment]
Can someone provide an example of how to get this refresh mechanism to work with `aws-iam-authenticator` ?

We're currently creating the config using:

```
credentials, err := credentialsProvider.Retrieve(ctx)
...
config.AuthInfos["eks"] = &clientcmdapi.AuthInfo{
	Exec: &clientcmdapi.ExecConfig{
		Command: "aws-iam-authenticator",
		Args: []string{
			"token",
			"-i",
			clusterName,
		},
		Env: []clientcmdapi.ExecEnvVar{
			{
				Name:  "AWS_ACCESS_KEY_ID",
				Value: c.credentials.AccessKeyID,
			},
			{
				Name:  "AWS_SECRET_ACCESS_KEY",
				Value: c.credentials.SecretAccessKey,
			},
			{
				Name:  "AWS_SESSION_TOKEN",
				Value: c.credentials.SessionToken,
			},
		},
		APIVersion:      "client.authentication.k8s.io/v1beta1",
		InteractiveMode: clientcmdapi.NeverExecInteractiveMode,
	},
}
```

which just uses a fixed credentials
