### ISSUE TITLE
Allow non-global metrics factory for workqueues

### ISSUE THREAD

**Issue by austince** [kubernetes/client-go#1193]
Currently, all workqueues share the same metrics provider (see [`util/workqueue/metrics.go`](https://github.com/kubernetes/client-go/blob/1ac8d459351e21458fd1041f41e43403eadcbdba/util/workqueue/metrics.go)). For similar reasons to 
https://github.com/kubernetes-sigs/controller-runtime/issues/210 + https://github.com/kubernetes/community/pull/2909, having a single global metrics provider for all consumers is inflexible. 

Concretely, I'm trying to instrument my apps with OpenTelemetry — we have some dependencies ([controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/daa6f4d9e7c191732b38f310338bafc8e398ddc5/pkg/metrics/workqueue.go)) that set a provider, but we also use workqueues in our code where I'd like to have a different provider. I don't see a way around this currently. 

A fix for only the workqueue package could be done in a non-breaking way I'd think, by allowing the provider to be plumbed through the constructors, e.g. the ...rest arg option function pattern. 

---

Has there been any discussions around the global metrics in the past? I can't find anything, but think this applies to other packages in this repo as well e.g. [`tools/metrics.go`](https://github.com/kubernetes/client-go/blob/1ac8d459351e21458fd1041f41e43403eadcbdba/tools/metrics/metrics.go)

**Comment by maherbeg** [comment]
+1 to this. We just saw an issue where transitively importing  the `controller-runtime` package causes subsequent workqueue metric registration to fail. This is partially because that package uses `init` functions to register things rather than explicitly doing so, but again does it on the global factory which is shared.

**Comment by austince** [comment]
Discussed on the ML a bit: https://groups.google.com/g/kubernetes-sig-api-machinery/c/rs9aIppwWE0/m/TZ5TSHJ5BAAJ

**Comment by austince** [comment]
@ash2k @maherbeg if this is important to you guys, can you add your support here? https://github.com/kubernetes/kubernetes/pull/114242

Otherwise, I'll let this issue + fix will go stale.
