### ISSUE TITLE
Mod Install Error in v0.26.0

### ISSUE THREAD

**Issue by HaoqingCai** [kubernetes/client-go#1197]
I got an error as following when trying to install this in command.

go: k8s.io/client-go@v0.26.0 (in k8s.io/client-go@v0.26.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

**Comment by luizcarlospedrosogomes** [comment]
news?

**Comment by nikhita** [comment]
Please use `go get` instead of `go install` as listed in https://github.com/kubernetes/client-go/blob/master/INSTALL.md#using-a-specific-version.

Closing as installation is documented already.
/close
