### ISSUE TITLE
When posting duplicate event using client-go's Eventf() api server throws error "series.count: Invalid value: "": should be at least 2' (will not retry!)"

### ISSUE THREAD

**Issue by smuraligit** [kubernetes/client-go#1199]
In our application, we are using high level APIs from client-go/tools/event/event_broadcaster.go.
When we post the same event again, we are getting the following error from api-server,

**E1220 17:40:34.360998 1980937 event_broadcaster.go:253] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"testpod.17329128ddba5fde", GenerateName:"", Namespace:"default", SelfLink:"", UID:"a8f7410c-a383-4094-9abd-18c0b368cc0a", ResourceVersion:"18599666", Generation:0, CreationTimestamp:time.Date(2022, time.December, 20, 17, 40, 16, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"event_agent_app", Operation:"Update", APIVersion:"events.k8s.io/v1", Time:time.Date(2022, time.December, 20, 17, 40, 16, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc000012c18), Subresource:""}}}, EventTime:time.Date(2022, time.December, 20, 17, 40, 16, 412565000, time.Local), Series:(*v1.EventSeries)(0xc00040a3e0), ReportingController:"test", ReportingInstance:"test-F6s-nopci-VM-4013", Action:"&", Reason:"Published", Regarding:v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"testpod", UID:"_;();T_warn;array;array;Warning", APIVersion:"v1", ResourceVersion:"", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"sd", Type:"Warning", DeprecatedSource:v1.EventSource{Component:"", Host:""}, DeprecatedFirstTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedLastTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeprecatedCount:0}': 'Event "testpod.17329128ddba5fde" is invalid: series.count: Invalid value: "": should be at least 2' (will not retry!)**

In the event_broadcaster.go code, we see if the event is isomorphic, the event series is initialized with count as 1. If the event is posted two times only, then the series count would be 1 and we would get this error. 

Instead of initializing the series to 1 when recordToSink() detects duplicate event, shouldn't we initializing to 2 taking into account of both original event and duplicate event? Otherwise, could you please let me know why api-server is throwing this error?

Looking forward to get response on this issue.

Thank you very much!

**Comment by smuraligit** [comment]
Thank you very much for your comment on this issue. 

I have not yet tried this workaround. I would like to find when this would happen meaning when we would get this error. Is there anything wrong that leads to this scenario. I would like to find out.

I will also try this workaround and will make an update here.

In the meantime, could you please let me know how did you hit this error?

Thank you very much!

**Comment by tkrishtop** [comment]
Hi @smuraligit I was using a python client, not a go client. Here is a simplified script to run on the pod.

```python
from kubernetes import client
from kubernetes.client.rest import ApiException

if __name__ == '__main__':
    namespace = "example-ns"

    cr = {
        'apiVersion': 'events.k8s.io/v1',
        'kind': 'Event',
        'metadata': {
            'name': 'name-app1-a069xx',
            'namespace': 'example-ns',
            'ownerReferences': [{
                    'apiVersion': 'events.k8s.io/v1',
                    'kind': 'NameApp',
                    'name': 'name-app1',
                    'uid': 'c78b7fe0-5708-49da-8e51-3621358f4040',
                    'controller': True
            }]
        },
        'type': 'Normal',
        'eventTime': '2023-01-25T12:22:02.024897Z',
        'series': {
            'lastObservedTime': '2023-01-25T12:22:02.024897Z'
        },
        'reason': 'TestStarted',
        'action': 'TestStarted',
        'note': 'My nice event message here',
        'regarding': {
            'namespace': 'example-ns',
            'kind': 'NameApp',
            'name': 'name-app1',
            'uid': 'c78b7fe0-5708-49da-8e51-3621358f4040'
        },
        'reportingController': 'pod/' + os.environ['HOSTNAME'],
        'reportingInstance': 'name-app1'
    }

    events_api = client.EventsV1Api()
    try:
        events_api.create_namespaced_event(namespace, cr)
    except ApiException as e:
        print("Exception on creating Event: %s\n" % e)
```

And here is the error I got

```
Exception on creating Event: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '272c1f33-ce5a-4c88-a442-370219ef3fce', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Kubernetes-Pf-Flowschema-Uid': 'd6363d35-55ce-41c8-91da-83ead4b8c8fc', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'dc600c67-6df9-49a2-8d6a-2902a11351c9', 'Date': 'Wed, 25 Jan 2023 12:22:02 GMT', 'Content-Length': '378'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Event \"name-app1-a069xx\" is invalid: series.count: Invalid value: \"\": should be at least 2","reason":"Invalid","details":{"name":"name-app1-a069xx","kind":"Event","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"\": should be at least 2","field":"series.count"}]},"code":422} 
```

**Comment by tkrishtop** [comment]
hi @smuraligit I confirm that explicitly setting `series.count` to 2 in the CR used for the event creation worked for my application and fixed the error

```Exception on creating Event: (422)
Reason: Unprocessable Entity
Event \"name-app1-a069xx\" is invalid: series.count: Invalid value: \"\": should be at least 2
```

Here is the fix 

```
'series': {
    'lastObservedTime': evtTime,
    'count': 2
}
```

Here is the complete example
```
from kubernetes import client
from kubernetes.client.rest import ApiException

if __name__ == '__main__':
    namespace = "example-ns"

    cr = {
        'apiVersion': 'events.k8s.io/v1',
        'kind': 'Event',
        'metadata': {
            'name': 'name-app1-a069xx',
            'namespace': 'example-ns',
            'ownerReferences': [{
                    'apiVersion': 'events.k8s.io/v1',
                    'kind': 'NameApp',
                    'name': 'name-app1',
                    'uid': 'c78b7fe0-5708-49da-8e51-3621358f4040',
                    'controller': True
            }]
        },
        'type': 'Normal',
        'eventTime': '2023-01-25T12:22:02.024897Z',
        'series': {
            'lastObservedTime': '2023-01-25T12:22:02.024897Z'
        },
        'reason': 'TestStarted',
        'action': 'TestStarted',
        'note': 'My nice event message here',
        'regarding': {
            'namespace': 'example-ns',
            'kind': 'NameApp',
            'name': 'name-app1',
            'uid': 'c78b7fe0-5708-49da-8e51-3621358f4040'
        },
        'reportingController': 'pod/' + os.environ['HOSTNAME'],
        'reportingInstance': 'name-app1'
    }

    events_api = client.EventsV1Api()
    try:
        events_api.create_namespaced_event(namespace, cr)
    except ApiException as e:
        print("Exception on creating Event: %s\n" % e)
```

**Comment by smuraligit** [comment]
Hello @tkrishtop 

Thank you for your quick response on this issue.

Thank you for verifying the fix. I see that you are using python client and not client-go's high level API. In such case, you can initialize the count attribute of series to 2 and it would work fine. In such cases, you would not publish your fix for merging into the open source as you are making the change into your application. Please correct me if I'm wrong.

However, since I am using client-go high level api recordToSink() in client-go/tool/events/event_broadcaster.go, we need to make the change to the open source code and verify the fix and publish the PR.

Please let me know your thoughts. I am surprised how not too many people have observed this issue.

**Comment by smuraligit** [comment]
Hello @tkrishtop 

One more question - 
Why do you need to initialize series structure when you are generating only one event? We need series when we see duplicate events.

Thanks,
Srini

**Comment by tkrishtop** [comment]
> Why do you need to initialize series structure when you are generating only one event?

Hi @smuraligit, I apologize for oversimplifying. Actually, my application generates thousands of events, some of which are duplicates. I added the loop `for _ in range(2):` in the example. 

> I see that you are using python client and not client-go's high level API. In such case, you can initialize the count attribute of series to 2 and it would work fine.

You can also use this workaround with the Go client. I'm not familiar with the structure of your application. If you're unable to modify the CR directly like I did, you could add a decorator for the event object to manually overwrite the event initialization and force  `series.count = 2`. 

> In such cases, you would not publish your fix for merging into the open source as you are making the change into your application. Please correct me if I'm wrong.

Do you need help with the fix PR? To be honest, since we're encountering the same issue in both the Go and Python clients, I'm not certain if the series initialization is the correct fix. I'd rather test more and then discuss the issue with some community maintainers.

**Comment by smuraligit** [comment]
Hello @tkrishtop,

Thank you for your response.

Actually, we are using the high level API which initializes the event series for us. You can see the code here at https://github.com/kubernetes/client-go/blob/master/tools/events/event_broadcaster.go, line 186.

I agree with you that I also need to test and see under what circumstances this error is being hit before publishing the changes for review.

Thank you so much!
