### ISSUE TITLE
LeaderElection ConfigMapsLeasesResourceLock backwards compatibility

### ISSUE THREAD

**Issue by sky333999** [kubernetes/client-go#1202]
When upgrading to v0.24.x of the client and higher, we realize the changes to move away from the use of ConfigMap locks in the leader election logic in favor of Leases is a backwards incompatible change and hence wanted to confirm the same.

As the transition from ConfigMap locks to Leases locks happens, it looks like ConfigMapsLeasesResourceLock multilock was intended to be a backwards compatible option that still treats the ConfigMap resource as the primary and the Lease resource as the secondary?
* From what I've tested, this works only if the service account's cluster role is updated to now grant new permissions to at the very least “get” leases - hence requiring a change from the owners of the manifest file.
* This is because in the multilock logic, even if the call to primary (i.e. ConfigMaps lock) returns successfully [here](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/multilock.go#L39), the call to secondary (i.e. Leases lock) is still made [here](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/multilock.go#L44) which now returns a 403 Forbidden error.
* And since [this](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/multilock.go#L47) line only checks for 404 Not Found errors specifically from secondary, it cascades the error further up failing the leader election.

A couple of questions:
1) Assuming we have no control over our customers' manifest files, is it fair to say this would be a breaking change unless they update their ClusterRole to grant new permissions for Leases?
2) Are there plans in the short/long term to completely get rid of support for ConfigMap locks altogether thus making Leases locks to be the only supported option for leader election?
3) Is there a reason to specifically check only for NotFound err [here](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/multilock.go#L47) as opposed to _any_ err? If it got to this point in the code path, it means primary was successful and secondary was not successful, but I'd imagine we can still return primary irrespective of the type of err from secondary.
If not allow all errs on this line, would it be better to atleast check for both 404 Not Found and 403 Forbidden on this line?

**Comment by liggitt** [comment]
> As the transition from ConfigMap locks to Leases locks happens, it looks like ConfigMapsLeasesResourceLock multilock was intended to be a backwards compatible option that still treats the ConfigMap resource as the primary and the Lease resource as the secondary?

That was not the intent, the intent was to allow migration to leases in a leader-safe way, so the component would have to hold both the primary and secondary lock objects, if both APIs existed (e.g. Lease didn't return a 404).

> * Are there plans in the short/long term to completely get rid of support for ConfigMap locks altogether thus making Leases locks to be the only supported option for leader election?

Yes, see https://github.com/kubernetes/kubernetes/issues/80289

> 3\. Is there a reason to specifically check only for NotFound err [here](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/resourcelock/multilock.go#L47) as opposed to _any_ err?

Yes, the point of the primary / secondary is to migrate to Leases. The client must hold both the primary and secondary to be the leader.

**Comment by sky333999** [comment]
Thanks @liggitt - thats helpful. So it looks like the intended way to use the multi lock is either {just leases OR (both configmaps & leases)} and was never designed to work with {just configmaps}.

I need to think through the details but assuming there is a leader safe way to support {either configmaps or leases}, would that PR be considered?

We vend a library to our customers and hence we dont have direct control over our customers' manifest files. Hence this would be a breaking change that I'm trying to avoid. And this would be a breaking change for customers consumed our updated lib not only on K8s >=1.24 but even on those on older versions < 1.24.

Are there any other suggestions/options to avoid a breaking change? Or any other options other consumers of k8s client-go adopted that you are aware of to workaround this?

**Comment by straussb** [comment]
Is there a recommendation then for customers to be able to decouple their client/server deployment?  I.e. right now a customer cannot upgrade to v0.24.x of the client if the cluster doesn't support Leases or has not yet given RBAC permissions to the client.  It forces customers to synchronize their deployments.  (And for us, as vendors of a library, we can't upgrade to v0.24.x since we don't know that that won't break some of our customers.)

**Comment by liggitt** [comment]
> if the cluster doesn't support Leases

Leases have been GA since Kubernetes 1.14 / 2018, so it's reasonable to rely on the API being available at this point.

> or has not yet given RBAC permissions to the client

I would recommend using whatever mechanism was used to communicate the need for configmap or endpoint access to indicate lease access is required.

If you want to keep using just configmaps as leader locks against client-go recommendations, you can also fork the leader election package at a point in time that supported that option.
