### ISSUE TITLE
How to filter pods using metadata.ownerReferences?

### ISSUE THREAD

**Issue by vkhatal** [kubernetes/client-go#1203]
I understand that field selectors are supports only limited fields. As we have huge number of pods in the cluster and we want to fetch metadata of only those pods whose **metadata.ownerReferences** is nil or empty.
 We don't want to fetch all pods information in our application first and then apply filter on it. 

We are looking for solution which will help us to get filtered data from api server directly using client-go. Please help

**Comment by nikhita** [comment]
@vkhatal if you have a large number of pods, the best way to use client-go here is to use the `APIListChunking` feature for list calls and then apply a filter on it - https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks.

While using client-go, you can use the `Limit` and `Continue` fields in `ListOptions` - https://github.com/kubernetes/kubernetes/blob/1edbb8cf1a864c2dd71a1e5b7282de4bc3d8f5fa/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L387

With client-go, you can also use `EachListItem` to incrementally process the chunked list results. It buffers up to `PageBufferSize` (default: 10) pages in the background to minimize foreground wait time.
 
https://github.com/kubernetes/client-go/blob/3e0d99053357a2c37e68b65adbf16437803b1f64/tools/pager/pager.go#L159

**Comment by nikhita** [comment]
Closing based on https://github.com/kubernetes/client-go/issues/1203#issuecomment-1369636966. Please reopen if needed.

**Comment by vkhatal** [comment]
@nikhita  is there any specific reason we have restricted filtering capability on metadata? Can we add this as a feature request?
