### ISSUE TITLE
Update glide install instructions

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/client-go#122]
@ericchiang gave me better ones in a comment on the client strategy doc https://docs.google.com/document/d/1h_IBGYPMa8FS0oih4NbVkAMAzM7YTHr76VBcKy1qFbg/edit# (shared with the sig api machinery email list).

**Comment by jaxxstorm** [comment]
Would be great to get this. I tried to run the examples using glide and still seeing the same issues as in #81

**Comment by lvangool** [comment]
Me too: Followed updated glide installation instructions. Dep didn't work either.
```
./main.go:40: cannot use "**/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions literal (type "**/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "**/vendor/k8s.io/client-go/pkg/api/v1".ListOptions in argument to clientset.CoreV1().Pods("").List
```

**Comment by ericchiang** [comment]
@jaxxstorm @lvangool what version of glide are you running? What where the commands you ran? Did you start with a glide file? What client-go target version did you try to install?

**Comment by lvangool** [comment]
```glide --version
glide version v0.12.3
```

Process I followed:
```
> Cleared whole $GOPATH
> Installed glide (latest via install script)
> glide cache-clear (not sure if this is necessary)
> go get k8s.io/client-go
> cd $GOPATH/src/k8s.io/client-go
> git checkout v2.0.0
> glide init (selecting N for wizard)
> Created new app (copied exactly: https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go)
> copied glide.yml to new app
> modified root to be my new app path
> in new app: 
> glide install --strip-vendor k8s.io/client-go#^2.0.0
> go build
```

**Comment by lvangool** [comment]
FYI - I just re-ran the steps above *again* and my project is now building.

**Comment by ericchiang** [comment]
> FYI - I just re-ran the steps above again and my project is now building.

\*magic\*

glide doesn't actually look at your GOPATH. You don't need to clone it, only install it using glide.

I also don't think that `glide install` actually takes any arguments. Also `glide init`, `glide get`, `glide install`, etc. have a bad tendency of interacting with the `glide.yaml` file in slightly different ways. I'd strongly recommend writing the `glide.yaml` file yourself, then just running `glide update --strip-vendor`.

```yaml
package: ( your package's import path )
import:
- package: k8s.io/client-go
  version: v2.0.0
```

**Comment by lvangool** [comment]
Gotcha - thanks again for the pointers!

**Comment by ericchiang** [comment]
Updated https://github.com/kubernetes/client-go/pull/127

Can this be closed now?

**Comment by kirs** [comment]
I wrote `glide.yml` myself (as suggested in the guide)

```
package: github.com/kirs/myproject
import:
- package: k8s.io/client-go
  version: v2.0.0
```

And running code from examples of this repo still fails with

```
./main.go:30: cannot use 
"github.com/kirs/myproject/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions literal 
(type "github.com/kirs/myproject/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as 
type "github.com/kirs/myproject/vendor/k8s.io/client-go/pkg/api/v1".ListOptions in argument to 
clientset.CoreV1().Pods("").List
```

**Comment by ericchiang** [comment]
@kirs what does your `glide.lock` look like?

**Comment by kirs** [comment]
@ericchiang thanks for a quick reply! I pushed my `glide.lock` here: https://gist.github.com/kirs/7a228787bc36dab97a20f1cc0994ffa5

**Comment by ericchiang** [comment]
Odd it looks like client-go doesn't pin k8s.io/apimachinery in its Godep/Godep.json[0] on the v2.0.0. Though @caesarxuchao fixes this recently in https://github.com/kubernetes/kubernetes/pull/42084 and master has the correct entry. Maybe try a newer SHA until client-go cuts another release? 

[0] https://github.com/kubernetes/client-go/blob/v2.0.0/Godeps/Godeps.json

**Comment by kirs** [comment]
I see. How do I try a newer SHA with glide?

**Comment by ericchiang** [comment]
Something like this:

```
package: github.com/kirs/myproject
import:
- package: k8s.io/client-go
  version: ca90456a21c1db4b5b1dadff1dbcc6f75692d0ee
```

**Comment by lavalamp** [comment]
@caesarxuchao can you look into this? Did this break because we pushed
something new to apimachinery?

**Comment by kirs** [comment]
I confirm that `k8s.io/client-go` with a SHA instead of `v2.0.0` solves the issue. Thanks everyone for help!

**Comment by lavalamp** [comment]
We need to cut a 2.0.1 asap if the 2.0.0 tag is currently broken.

**Comment by tonglil** [comment]
I am unable to get @ericchiang's solution to work.

Following https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go:

```
go build
# github.com/xxx/dv-kube-ns-cleanup
./main.go:40: cannot use "github.com/xxx/dv-kube-ns-cleanup/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions literal (type "github.com/xxx/dv-kube-ns-cleanup/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "github.com/xxx/dv-kube-ns-cleanup/vendor/k8s.io/client-go/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions in argument to clientset.CoreV1().Pods("").List
```

glide.yaml:
```
package: github.com/nytm/dv-kube-ns-cleanup
import:
- package: k8s.io/apimachinery
  subpackages:
  - pkg/apis/meta/v1
- package: k8s.io/client-go
  version: ca90456a21c1db4b5b1dadff1dbcc6f75692d0ee
  subpackages:
  - kubernetes
  - rest
```

Removed glide.lock and ran `glide install`, no `vendor/` dir.

**Comment by kirs** [comment]
Can you try it with `glide update --strip-vendor` as it is suggested in the docs? (Instead of glide install)

**Comment by ericchiang** [comment]
what he said ^

**Comment by tonglil** [comment]
Success!

**Comment by caesarxuchao** [comment]
Thanks @ericchiang for spreading the knowledge.

Just to recap what folks were discussing in the thread:

* client-go v2.0.0 doesn't depend on apimachinery, so there is no entry for it in Godeps.json :)

* If you install the master branch of client-go, as the INSTALL.md suggests, `glide update --strip-vendor` is the way to go,

**Comment by caesarxuchao** [comment]
This INSTALL.md is updated. Closing

**Comment by tonglil** [comment]
But it still says `v2.0.0`, which fails:
```
$ ls
glide.yaml  main.go
$ cat glide.yaml 
package: github.com/xxx/dv-kube-ns-cleanup
import:
- package: k8s.io/client-go
  version: v2.0.0
  subpackages:
  - kubernetes
  - rest

$ glide update --strip-vendor 
...
$ go install .
# github.com/xxx/dv-kube-ns-cleanup
./main.go:41: cannot use "github.com/xxx/dv-kube-ns-cleanup/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions literal (type "github.com/xxx/dv-kube-ns-cleanup/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "github.com/xxx/dv-kube-ns-cleanup/vendor/k8s.io/client-go/pkg/api/v1".ListOptions in argument to clientSet.CoreV1().Namespaces().List
```

**Comment by caesarxuchao** [comment]
Can you paste the code of your main.go? Use the [ListOptions](https://github.com/kubernetes/client-go/blob/v2.0.0/pkg/api/v1/types.go#L3222) defined in client-go if you are uing v2.0.0.

**Comment by caesarxuchao** [comment]
Are you using the examples in the master branch? That won't work with the v2.0.0 client.

**Comment by tonglil** [comment]
Ah gotcha, that's it. Thank you.

**Comment by kirs** [comment]
@lavalamp @caesarxuchao @ericchiang thanks a lot for helping with this issue and issuing 2.0.1 ASAP!

**Comment by caesarxuchao** [comment]
@kirs we are not cutting 2.0.1 as there is no problem with 2.0.0. Please use the [ListOptions]([ListOptions](https://github.com/kubernetes/client-go/blob/v2.0.0/pkg/api/v1/types.go#L3222)) defined in client-go if you are using v2.0.0.
