### ISSUE TITLE
Last sync is from Feb 3.

### ISSUE THREAD

**Issue by deads2k** [kubernetes/client-go#123]
It looks like the last synchronization from k8s.io/kubernetes was on February 3.  Is that correct?  When are we expecting the next one?

@sttts @caesarxuchao @lavalamp

**Comment by DirectXMan12** [comment]
This is causing me issues trying to update kubernetes/heapster#1483 -- master client-go lacks both legacy and autogenerated listers, but release-2.0 doesn't work with master k8s.io/apimachinery and k8s.io/apiserver.

**Comment by lavalamp** [comment]
I asked Chao to turn the syncing bot off until we could be confident it wouldn't break anything. Hopefully we can get it back on soon, I think there's a PR I'm supposed to review.

**Comment by sttts** [comment]
This is the test-infra PR: https://github.com/kubernetes/test-infra/pull/1784. What can be done to get that merged soon? Our apimachinery+client-go situation is sad and becoming more and more embarrassing.

**Comment by deads2k** [comment]
This is now blocking a reasonable sync of kube-aggregator based on external deps.
