### ISSUE TITLE
Can't seem to find `AuthorizationV1().TokenRequest()`

### ISSUE THREAD

**Issue by BBBmau** [kubernetes/client-go#1234]
I'm looking to add a `TokenRequestAPI` resource to our Terraform Kubernetes Provider but can't seem to find any reference of TokenRequests in client. I can find `TokenReview` but nothing along the lines of `TokenRequest`.

I assumed that they would both fall under `AuthorizationV1()`

Let me know if there are plans to add it soon or if I am just looking in the wrong spot for it.

**Comment by liggitt** [comment]
it's located within the serviceaccount client as a subresource

https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/serviceaccount.go#L54
