### ISSUE TITLE
 Is there a way to get table response or metadata only to list k8s resource from k8sclientset?

### ISSUE THREAD

**Issue by Sprakhar97** [kubernetes/client-go#1236]
I'm trying to fetch all the cm/secrets name/metadata in a k8s cluster, 
For this I'm using clientset.CoreV1().ConfigMaps("").List(context.TODO(), metav1.ListOptions{}) but the response for this call is list of configmap with data field.
**Issue:**
As configmap and secrets data size is close to half MB, the memory footprint is too high for this api-call, 
**Expectation:**
I wanted to know if there is a way or plan to support light calls like fetching the metadata or get tabular response same as kubectl get command?

**Comment by liggitt** [comment]
The metadata client (https://github.com/kubernetes/client-go/tree/master/metadata) can be used to select just the metadata stanza of objects.
