### ISSUE TITLE
github.com/golang/protobuf deprecated

### ISSUE THREAD

**Issue by matteo-pergolesi** [kubernetes/client-go#1240]
https://github.com/golang/protobuf/pull/1306 deprecates github.com/golang/protobuf in favor of google.golang.org/protobuf. Any plans to remove the deprecated dependency?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/96564 tracks all the issues around removing this deprecated dependency. It is *very* involved, unfortunately, and not at the top of the priority list.
