### ISSUE TITLE
Failed to add a proxy into clientset.

### ISSUE THREAD

**Issue by ziyanjiang98** [kubernetes/client-go#1246]
Package name: k8s.io/client-go v0.15.11

Issue:
Due to the network structure, I need to add a proxy-url so that the HTTP requests from the client-go can be sent out to my clusters's IP address.

However, I met errors when using the following code
```
// Collect local kubeconfig file.
kubeConfigPath := filepath.Join(homedir.HomeDir(), ".kube", "config")
config, configErr = clientcmd.BuildConfigFromFlags("", kubeConfigPath)
...

// Add a transport to the config.
parsedURL, _ := url.Parse("<my_socks_proxy_url>")
ProxyURL := http.ProxyURL(parsedURL)
Transport := &http.Transport{
    Proxy: ProxyURL,
}
config.Transport = Transport

// Initialize the client.
kubeClient, clientErr := kubernetes.NewForConfig(config)
....
```

Then I got the following error:
`Create kube client fails: using a custom transport with TLS certificate options or the insecure flag is not allowed`

Wondering if there is a way that I can fix it?

**Comment by liggitt** [comment]
you probably want to set `config.Proxy = http.ProxyURL(parsedURL)` instead of constructing your own transport instance

**Comment by ziyanjiang98** [comment]
Hi @liggitt , thanks for responding!

I do find the `Proxy` field in the [latest package](https://pkg.go.dev/k8s.io/client-go/rest#Config), but unfortunately there is no such field in [k8s.io/client-go v0.15.11](https://pkg.go.dev/k8s.io/client-go@v0.15.11/rest#Config). Wondering if there is a workaround for the old version? Or if the proxy setting is only available for the latest version.

**Comment by liggitt** [comment]
it was added in v0.19.x

**Comment by ziyanjiang98** [comment]
Sounds good! Will try to upgrade the package version in our repo. Thanks for the help!
