### ISSUE TITLE
Bump dep: docker/distribution

### ISSUE THREAD

**Issue by HakShak** [kubernetes/client-go#126]
I'm a filthy Windows dev and I needed this: https://github.com/docker/distribution/pull/1716

So I bumped docker/distribution in order to `godep restore ./...`
```
                {
			"ImportPath": "github.com/docker/distribution/digest",
			"Comment": "v2.5.0",
			"Rev": "a9b1322edf48b1fb9aee4e5ded7a4f4ac37c6830"
		},
		{
			"ImportPath": "github.com/docker/distribution/reference",
			"Comment": "v2.5.0",
			"Rev": "a9b1322edf48b1fb9aee4e5ded7a4f4ac37c6830"
		},
```

Unsure if this should have been a PR.

**Comment by ericchiang** [comment]
@HakShak is this a bug fix for client-go or because your own project requires that behavior? If it's the latter, depending on your dependency management tool you can override the value client-go requests. For example: https://github.com/kubernetes/client-go/issues/79#issuecomment-281539491

**Comment by HakShak** [comment]
I have definitely done a local commit to godeps to fix this.

As for a bug fix or my own project needs: Any one who tries to build kubernetes/client-go on Windows will fail if they are using godeps to lock to v2.0.0

I'm good with bumping the upstream godeps in my local vendor, but I just assumed someone else would run into this eventually. :)

**Comment by ericchiang** [comment]
Okay, this seems like this is an actual bug in client-go. Yes, if can submit a PR to the github.comkubernetes/kubernetes repo, that'd be great!

**Comment by HakShak** [comment]
Should that be just the Godeps.json file, or the entirety of the vendor changes as well?

**Comment by ericchiang** [comment]
@HakShak I think you have to use the specialized scripts in the kubernetes repo (haven't updated a dependency in a while). For details, see: https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md

**Comment by nikhita** [comment]
@HakShak Is this still relevant?

If it's a problem affecting anyone who uses client-go on Windows, we should probably fix this ASAP...
