### ISSUE TITLE
gnostic to gnostic-models switch is breaking code 

### ISSUE THREAD

**Issue by joshelb** [kubernetes/client-go#1265]
https://github.com/kubernetes/client-go/blob/master/discovery/cached/disk/cached_discovery.go#L238

The import for openapiv2 has to be updated to gnostic-models 

openapi_v2 "github.com/google/gnostic/openapiv2
to
openapi_v2 "github.com/google/gnostic-models/openapiv2

Maybe this also needs to be updated in other parts im nmot sure yet.

**Comment by Jefftree** [comment]
This has been updated in the latest release v0.28-alpha.2

/close
