### ISSUE TITLE
go-restful  https://github.com/emicklei/go-restful/issues/497

### ISSUE THREAD

**Issue by 467892746** [kubernetes/client-go#1267]
module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system.

**Comment by liggitt** [comment]
see previous responses to this at https://github.com/kubernetes/client-go/issues/1254#issuecomment-1549999313

client-go does not use the impacted functionality, and there are compatibility issues that need resolving before the module can be updated in master (currently targeting 1.28 release)
