### ISSUE TITLE
when creating a watcher,how to solve error :"unknown (get deployments.apps)"?

### ISSUE THREAD

**Issue by steaksunflower0107** [kubernetes/client-go#1271]
when I deploy my program which aims to watch all k8s's deployment's cpu and memory on k8s,it shows the error : "unknown (get deployments.apps)"
here are where my error happend
`	watcher, err := clientSet.AppsV1().Deployments(*nameSpace).Watch(context.Background(), metav1.ListOptions{})
	if err != nil {
		log.Fatalf("Creating Watcher failed: %v", err)
	}
	defer watcher.Stop()`

and I have try to add serviceAccount, clusterRole,clusterRoleBinding,it still does work
here are my yaml file
`apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: watcher
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher
  namespace: watcher
rules:
  - apiGroups:
      - ""
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher-binding
  namespace: watcher
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: watcher
#    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: watcher
  apiGroup: rbac.authorization.k8s.io
`
please help solve this,and explian why it happen

**Comment by rpstw** [comment]
facing the same issue with version 0.24.6

**Comment by rpstw** [comment]
The err returned is misleading. Making klog more verbose shows the actual error.
```
// just a workaround, normally v should be passed via command line
l := klog.Level(6)
_ = l.Set("6")
```


I0705 10:47:43.414058       1 round_trippers.go:553] GET https://10.39.0.1:443/api/v1/namespaces/xxx/pods?fieldSelector=metadata.namespace%3Dxxx%2Cmetadata.name%3Dxxxx-qhj-rpzqh&watch=true 403 Forbidden in 0 milliseconds
