### ISSUE TITLE
List function consuming high chunk of memory

### ISSUE THREAD

**Issue by kusolank** [kubernetes/client-go#1272]
k8sClientSet.CoreV1().Pods("").List(context.Background(), metav1.ListOptions{})

and NewFilteredEventInformer.ListFunc is consuming high chunk of memory when there are large number of pods and pod churn in cluster.

Using them to get resources in every minute
same issue was reported on #871

**Comment by Nefftam** [comment]
On initialising pod informer and in a set up with 1k pods. 
When we run create/delete 100 pods per minute, the streamwatcher memory goes up incrementally and keeps increasing

<img width="820" alt="Streamwatcher" src="https://github.com/kubernetes/client-go/assets/30044825/662db46a-ab71-4903-828a-9fcd3234ff25">

**Comment by alexandnpu** [comment]
same issue here, below is my heap profile and my client-go version is v0.25.3

<img width="1222" alt="image" src="https://github.com/kubernetes/client-go/assets/1999503/33c4ff5e-4196-41ea-ae5f-58d5d71c4897">

<img width="1222" alt="image" src="https://github.com/kubernetes/client-go/assets/1999503/87ec4ca2-dee1-429c-97f3-4012103ae124">

**Comment by typ431127** [comment]
+1  I have the same problem

**Comment by gnuletik** [comment]
I was able to mitigate this issue by using grpc as content type.

**Comment by kuldeepsolanki04** [comment]
@gnuletik Can you please help with the example?

**Comment by gnuletik** [comment]
You can set the `ContentType` value of the config you provide when creating the clientset.

```go
kubeConfig.ContentType = "application/vnd.kubernetes.protobuf"

// creates the clientset
kubeClient, err := kubernetes.NewForConfig(kubeConfig)
if err != nil {
        return nil, err
}
```

**Comment by kuldeepsolanki04** [comment]
@gnuletik Thanks, let me try this as well
