### ISSUE TITLE
Improve the coverage of examples

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/client-go#128]
Apart from helping users, increasing the coverage of examples can also help our CI to detect problems.

We can start with providing examples for all top-level packages, and packages in tools/:
- [ ] dynamic
- [ ] discovery
- [ ] rest
- [ ] testing
- [ ] transport
- [ ] tools/auth
- [ ] tools/cache (https://github.com/kubernetes/client-go/pull/30)
- [ ] tools/portforward
- [ ] tools/record
- [ ] util/workqueue (https://github.com/kubernetes/kubernetes/pull/44320) (and we should move workqueue to tools/)

User requested example
- [ ] simple list and watch https://github.com/kubernetes/client-go/issues/161

@lavalamp 

related: https://github.com/kubernetes/client-go/issues/63

**Comment by rmohr** [comment]
@caesarxuchao I can add one for `tools/record`.

**Comment by caesarxuchao** [comment]
cc @mbohlool

**Comment by rmohr** [comment]
@caesarxuchao posted the inital PR, will clean and properly document it after the weekend (I had some issues compiling the latest client-go code). Let me know if you think that this example is too simplistic.

**Comment by ahmetb** [comment]
I have a different take on how the Client Library samples should be done. I would argue that the examples would be more scenario-oriented and not package-oriented as @caesarxuchao suggested above.

I see the value of documenting what's in each package, but I would argue that it’s not necessarily something a beginner user to the library (or Kubernetes API) needs. Maybe this seems like I'm trying to target rookies more, but as authors of client libraries, we often make assumptions how much users know about the API or how it can be used.

My goal is to simplify getting started experience of this library and provide pointers from www.kubernetes.io to the examples here and create (more beginner-level) samples that make it less intimidating for others to get their hands dirty with the Kubernetes API.

Here’s a quick rundown of what I have in mind for `examples/` directory. I am looking for feedback to refine the list further.

- **Beginner Tasks**
    > Scenario: ”I am new to this, I just did `go get`, how can I write a simple program”
  - Auth: in-cluster
  - Auth: out-of-cluster
  - CRUD: e.g. {create, get, list, delete, update}-deployment
  - Using Namespaces
- **Advanced Tasks**
    > Scenario: “I can do basic things with the API, tell me what’s next.”
  - Using the Watch API
  - Using Informers
- **Sample Applications**
    > Scenario: “I want to write my own Kubernetes extension, get me there quickly.”
    >
    > These are programs that can be directly compiled. people should be able to just take these projects and modify for their needs to write extensions.
  - Sample Scheduler
  - Sample Operator
  - Sample Third Party Resource
  - Sample Controller

Please provide feedback on which route is more agreeable. It’s just my opinion that we should provide real-world scenarios in `examples/` directory and keep package-reference docs somewhere else.

cc'ing some interested parties: @rothgar @jbeda

**Comment by fejta** [comment]
Can we start with figuring out how to eliminate permanent failures from the example suites and tests?

I have an issue opened to delete some of these example suites because they have not passed once during the past 60 days. 

https://github.com/kubernetes/test-infra/issues/2528

**Comment by ahmetb** [comment]
@fejta it looks like ci-kubernetes-e2e-gci-gce-examples and ci-kubernetes-e2e-gce-examples are regarding the examples in the `examples/` directory in the main repo; not the ones in client-go. So I think this is a bit off-topic. Regarding those permanent failures, it looks like some of the samples in the main repo are unmaintained. We are [having discussions](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-apps/a6VcS3uzeHE/TxArQtCJAgAJ) to move those to a separate repo (https://github.com/kubernetes/examples) and deprecate the ones that are no longer maintained.

**Comment by caesarxuchao** [comment]
@ahmetb the progressive layout of examples sounds great. They don't cover all the components though, like /tools/portforward or the /dynamic. I think we can put examples for these packages under "advanced tasks".

**Comment by ahmetb** [comment]
@caesarxuchao agreed. If we can maintain a set of common and simple tasks (such as CRUD Pod) and scaffolding (e.g. sample operator) across official client libraries, there's plenty of room to document advanced aspects and patterns of each client library.

**Comment by fejta** [comment]
Thanks for the clarification. Agree my comment is off topic. Please ignore.

**Comment by rothgar** [comment]
@ahmetb I love the idea of having code examples. It helps new people get started and lets you jump in at your own level rather than code training sites that take you from the beginning. A couple questions I have though.

1. Is this the place for sample applications? It's probably recommended to use the go client to write a scheduler but it by no means is the only way to do it. I don't have an answer but would hate to scare people away from extending kubernetes or writing their own controllers just because they don't know go or want to use this client.
2. How about tips for extending `kubectl`? That is (currently) most people's interface to kubernetes and I'm sure I'm not the only one who has aliases, functions, and wrappers to do various things that I would rather be plugins or custom cli applications.

**Comment by ymruan** [comment]
A sample implementation of operator(controller) with TPR may help the developer to understand the client-go.

**Comment by ahmetb** [comment]
@rothgar great questions:

1. I am hoping to have sample apps (scaffolding scheduler etc) for all officially supported languages. In this case I believe it’s Python and Go. It's also my goal to not to scare people in any way and lower the barrier to extend Kubernetes as much as possible. So we’re on the same page. 👍 That said, if the scaffolding apps turn out to be way more complex then we imagined, we can host them on separate repos to keep the client-{go,python} repos clean.

2. I'd love to learn more about how people can extend `kubectl` other than tricks like aliases and jsonpath queries. We already got some of this stuff documented. However, this seems to be a separate discussion than API client examples and maybe suited better for the docs repository.

**Comment by rmohr** [comment]
@ahmetb We are using client-go in [KubeVirt](https://github.com/kubevirt/kubevirt). I think the layout looks great. It pretty much covers everything which we currently use and it would have helped us to get started.

I would also add an example for completely customized http clients, which integrate with the kubernetes security layers. It took me some time to figure out, how to write your own websocket client. The example I came up with is located at https://github.com/rmohr/kubernetes-custom-exec.

**Comment by jekohk** [comment]
I think it would also be very helpful to have an example of initiating rollbacks on deployments from client-go. I have been trying to research ways to do this for a few days now, and it's a pretty typical use case of this client so I think it'd help a lot of beginners and more advanced users alike. I'm still trying to figure it out myself but if I do I'd be happy to contribute an example.

**Comment by ahmetb** [comment]
@jekohk please feel free to contribute the rollback operation to the crud-deployment example we have if you have time.

**Comment by jekohk** [comment]
@ahmetb I've updated the CRUD example to include a rollback operation, however I'm having issues getting integration tests to pass locally. 
Running `make test` is throws the following:
```
can't load package: package k8s.io/kubernetes/_tmp/federation/pkg/dnsprovider: code in directory /home/john/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/_tmp/federation/pkg/dnsprovider expects import "k8s.io/kubernetes/federation/pkg/dnsprovider"
_tmp/federation/pkg/dnsprovider/providers/google/clouddns/clouddns.go:32:2: use of internal package not allowed
_tmp/federation/pkg/dnsprovider/providers/google/clouddns/interface.go:21:2: use of internal package not allowed
_tmp/federation/pkg/dnsprovider/providers/google/clouddns/clouddns.go:33:2: use of internal package not allowed
can't load package: package k8s.io/kubernetes/_tmp/federation/pkg/federation-controller/cluster: code in directory /home/john/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/_tmp/federation/pkg/federation-controller/cluster expects import "k8s.io/kubernetes/federation/pkg/federation-controller/cluster"
```

Any ideas? I've just been following the Community development guide- not sure if there some extra steps required when working under /staging directory.

**Comment by ahmetb** [comment]
@jekohk can you open a separate issue for this? It looks like one of the dependencies broke the example.

**Comment by caesarxuchao** [comment]
@jekohk it looks wrong if a client-go example requires compiling k8s.io/kubernetes. As @ahmetb suggested, let's discuss the problem in a separate issue.

**Comment by jekohk** [comment]
@ahmetb @caesarxuchao i've elaborated more in [#303](https://github.com/kubernetes/client-go/issues/303)

**Comment by jekohk** [comment]
@ahmetb opened PR [#53474](https://github.com/kubernetes/kubernetes/pull/53474) with some updates to client-go CRUD example. 

I'm interested in the TODO mentioning a sleep with exponential backoff- is this something you thought should be included in the example, or just a suggestion to those running an example like this in prod?

**Comment by ahmetb** [comment]
@jekohk we have a retry package. we should use it where appropriate, for sure.

**Comment by mhausenblas** [comment]
@ahmetb are you working on this? I'm iterating on http://using-client-go.cloudnative.sh and plan to PR when there's something substantial to share …

**Comment by ahmetb** [comment]
@mhausenblas not actively. Happy to review more examples in line with the current ones or the bespoke list above.

**Comment by liggitt** [comment]
> Would be nice to have example for watch

https://github.com/kubernetes/client-go/blob/master/examples/workqueue/main.go#L164-L195 is pretty exemplary
