### ISSUE TITLE
Is it possible to make the error retrieving resource lock for leader election Fatal?

### ISSUE THREAD

**Issue by smg247** [kubernetes/client-go#1280]
We have recently uncovered an error in our [boskos](https://github.com/kubernetes-sigs/boskos) instance like the following:
```
E0710 21:02:45.211259 1 leaderelection.go:330] error retrieving resource lock ci/boskos-cleaner-leaderlock: leases.coordination.k8s.io "boskos-cleaner-leaderlock" is forbidden: User "system:serviceaccount:ci:boskos" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "ci"
```

This went unnoticed for quite some time as it is not a fatal error so the pod wasn't killed (and our alerting was never triggered). Is it possible to make the following errors Fatal?
- https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L332
- https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L336

**Comment by bliotti** [comment]
Have the same issue

**Comment by Gatete-Bruno** [comment]
E0611 21:13:40.731888       1 leaderelection.go:332] error retrieving resource lock email-operator-system/650681eb.batman.example.com: leases.coordination.k8s.io "650681eb.batman.example.com" is forbidden: User "system:serviceaccount:email-operator-system:email-operator-email-operator-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "email-operator-system"
