### ISSUE TITLE
getting credentials: decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100 error

### ISSUE THREAD

**Issue by pandu-bhojaraj-mf** [kubernetes/client-go#1283]
getting credentials: decoding stdout: no kind "**ExecCredential**" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100 error

**kubectl version** command is giving below result

`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/v1alpha1
`

I ran `go get k8s.io/client-go@v0.20.4` also

I ran `sudo rm -rf /root/.kube/config` also

**aws --version** command is giving below result

`aws-cli/2.13.1 Python/3.11.4 Linux/5.4.0-150-generic exe/x86_64.ubuntu.20 prompt/off`

Still i am **facing below error**

![image](https://github.com/kubernetes/client-go/assets/73541850/ed52234f-bd1c-4995-b8ed-8d047d5e99fa)

I

**Comment by liggitt** [comment]
v1alpha1 was dropped in 1.24 in https://github.com/kubernetes/kubernetes/pull/108616

I suspect the credential plugin is built with 1.24+ libraries and only honors v1beta1 or v1

**Comment by pandu-bhojaraj-mf** [comment]
> v1alpha1 was dropped in 1.24 in [kubernetes/kubernetes#108616](https://github.com/kubernetes/kubernetes/pull/108616)
> 
> I suspect the credential plugin is built with 1.24+ libraries and only honors v1beta1 or v1

@liggitt 

The exec-plugin apiVersion in my kubeconfig is pointing to `client.authentication.k8s.io/v1beta1`

![image](https://github.com/kubernetes/client-go/assets/73541850/8cab4aae-1d36-4530-9d21-965fdb18307a)

**Comment by FabianoLothor** [comment]
Make sure to:
1. Change your apiVersion to `client.authentication.k8s.io/v1beta1` (or newer).
2. Update your awscli to latest.
