### ISSUE TITLE
Deprecation of "github.com/gogo/protobuf"

### ISSUE THREAD

**Issue by imJayanth** [kubernetes/client-go#1318]
`"k8s.io/client-go"` is using the deprecated `"github.com/gogo/protobuf"`
 Is it possible to remove this deprecated module and replace it with a suitable alternative?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/96564 tracks all the issues around removing this deprecated dependency. It is *very* involved, unfortunately, and not at the top of the priority list.
