### ISSUE TITLE
Make ApplyConfigurations dynamically extractable in tests

### ISSUE THREAD

**Issue by therealmitchconnors** [kubernetes/client-go#1322]
SSA and ApplyConfigurations are great, but writing dynamic (that is, not specific to any one kubernetes type) logic seems to be currently untestable due to how applyconfigurations are organized.  I'm trying to write logic for any kubernetes type that can 1) accept and apply an arbitrary applyconfig to a dynamic resource client, and 2) when the underlying collection changes, extract an applyconfig from the latest object, and compare it to the most recently applied applyconfig, triggering a re-apply if the two differ.  This seems to be the primary use case for apply, except that it is done using a dynamic client rather than typed clients.

The following code appears to work when running against a live api server (pseudo code for brevity):
```
func repro(d discovery.DiscoveryInterface, c dynamic.Interface) {
	cm := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"data": map[string]interface{}{
				"key": "value",
			},
		},
	}
	ex, _ := metaac.NewUnstructuredExtractor(d)
	inf := dynamicinformer.NewDynamicSharedInformerFactory(c, time.Minute).
		ForResource(gvr.ConfigMap)
	inf.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
		UpdateFunc: func(oldObj, newObj interface{}) {
			uObj := newObj.(unstructured.Unstructured)
			cmac, _ := ex.Extract(&uObj, "repro")
		},
	})
	cmr := c.Resource(gvr.ConfigMap)
	cmr.Namespace("default").
		Apply(context.Background(), "name", cm, metav1.ApplyOptions{
			FieldManager: "repro",
		})
}
```

However, when the above code is passed a `*fakediscovery.FakeDiscovery` as d, the code results in a panic.  This is because the FakeDiscovery server returns an empty Open API document at OpenAPISchema(), which the UnstructuredExtractor depends on being non-empty.

Typed clients bypass this problem by accessing embedded open api schema in their respective internal packages such as https://github.com/kubernetes/client-go/blob/master/applyconfigurations/internal/internal.go#L41, but this schema is not directly available to the FakeClient in a unit test.  

In order for dynamic SSA to be testable, the internal packages of typed clients should be moved to an importable location.

**Comment by howardjohn** [comment]
cc @apelisse
