### ISSUE TITLE
"allow adding indexes after informer starts" is missing in release branches

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/client-go#1327]
I have noticed that some commits are missing from k/client-go release branches.

If you visit client-go master branch, you can see https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go

```
client-go: allow adding indexes after informer starts
Kubernetes-commit: d96a9858d396d7f418d24ea47bdc92ef8429f707
```
This change was done 10 months ago.

But when you visit the `release-1.29` branch or `v0.29.0` branch, this commit is missing.
https://github.com/kubernetes/client-go/blob/v0.29.0/tools/cache/shared_informer.go#L543-L544

Is this intentional or the cherry-pick process failed somewhere?

**Comment by howardjohn** [comment]
While the commit was made 10 months ago, that is how long it was in review -- the merge is 1 month old and after 1.29 unfortunately (https://github.com/kubernetes/kubernetes/commit/db82260c65df9cedaf93e924a2401b4e55a8a2a0)

**Comment by tamalsaha** [comment]
Ah, I see. Makes sense. I needed this feature.
