### ISSUE TITLE
Memory leak in watcher 

### ISSUE THREAD

**Issue by amitschendel** [kubernetes/client-go#1330]
Hey, I am using a watcher, and I am experiencing memory leaks issues.
It seems like something is not being released and over time it grows infinitely...
Below is the pprof result after pprof diff of about 10h.  
![image](https://github.com/kubernetes/client-go/assets/58078857/5b0bd220-9b71-49b4-a89a-d5147e207452)
[Link to my watcher implementation.](https://github.com/kubescape/kapprofiler/blob/main/pkg/watcher/watcher.go)

**Comment by william-wang** [comment]
@amitschendel Is the issue fixed?
