### ISSUE TITLE
How to cancel remote command execution?

### ISSUE THREAD

**Issue by DumbMachine** [kubernetes/client-go#1335]
I'm executing some interactive commands on a pod with the following code:

```go
ctx, cancel := context.WithCancel(context.TODO())
exec, err := remotecommand.NewSPDYExecutor(config, method, url)
	if err != nil {
		return err
	}

return exec.StreamWithContext(ctx, remotecommand.StreamOptions{
	Stdin:             stdin,
	Stdout:            stdout,
	Stderr:            stderr,
	Tty:               tty,
	TerminalSizeQueue: terminalSizeQueue,
})
```

Have a background goroutine that cancels the context if I'm idle. Cancellation works fine, the network connection is closed, but the process on the pod is still running. I want to kill the process on the pod when the context is cancelled. I couldn't find a way for it, is it possible out of the box in k8s client?

If not, what would be the best way to achieve this? I'm thinking making signature of the process and killing it with another command when the context is cancelled. But I'm not sure if it's the best way to do it.

**Comment by DanMHammer** [comment]
@DumbMachine I recently encountered the same issue. I hope the maintainers of client-go can put in a more elegant fix, but I did find a workaround. Here's a quick general example:

```go
	ctx, cancel := context.WithCancel(context.TODO())

	stdinPipeReader, stdinPipeWriter := io.Pipe()

	go func() {
		// copy the original stdin to the pipe
		io.Copy(stdinPipeWriter, stdin)
	}()

	go func() {
		// on context cancel, send ctrl-c to the process by writing to the pipe
		<-ctx.Done()
		stdinPipeWriter.Write([]byte("\x03"))
		// if you're using an interactive shell, you may want to send ctrl-c and exit
		// stdinW.Write([]byte("\nx03\nexit\n"))
	}()

	exec, err := remotecommand.NewSPDYExecutor(config, method, url)
	if err != nil {
		return err
	}

	exec.StreamWithContext(ctx, remotecommand.StreamOptions{
		// pass the pipe reader instead of the original stdin
		Stdin:             stdinPipeReader,
		Stdout:            stdout,
		Stderr:            stderr,
		Tty:               tty,
		TerminalSizeQueue: terminalSizeQueue,
	})
```
