### ISSUE TITLE
Why setting minWatchTimeout to only 5min

### ISSUE THREAD

**Issue by liuyuan10** [kubernetes/client-go#1341]
client-go sets [minWatchTimeout](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L157) to only 5min by default. Every watch will be terminated and reinitiated every 7.5min on average. This can translate to large WATCH QPS to API server on a large scale cluster with per node watch. For example, in a 10k cluster, it's constant 22 QPS even there is no event at all. 

It's configurable through list options but I wonder is there downside to set it large?

**Comment by warmchang** [comment]
@liuyuan10 You can customize the MinWatchTimeout parameter now. https://github.com/kubernetes/client-go/commit/b9e952f4d7a716401820b07cf1506974bef8a152
