### ISSUE TITLE
Missing Kubernetes Labels for Nodes in GKE Cluster after Enabling Image Streaming Feature

### ISSUE THREAD

**Issue by Seelam-Ramesh-Reddy** [kubernetes/client-go#1342]
After enabling the Image Streaming feature in our Google Kubernetes Engine (GKE) cluster, we've observed that Kubernetes labels for nodes are going missing. This issue seems to be consistently reproducible and affects the proper functioning of our cluster.

Steps to Reproduce:

Enable the Image Streaming feature in the GKE cluster.
Observe that Kubernetes labels for nodes are missing or not applied as expected.
Expected Behavior:
Kubernetes labels for nodes should be retained and applied correctly even after enabling the Image Streaming feature.

**Label Name: pool:defaultpool**

Actual Behavior:
After enabling the Image Streaming feature, Kubernetes labels for nodes are missing or not applied as expected.

**Comment by ruiwen-zhao** [comment]
Hi @Seelam-Ramesh-Reddy , image streaming is a GKE specific feature, so i would recommend creating a support ticket against GKE.

Or if you can provide some more details and repro steps, we can take a look.
