### ISSUE TITLE
Why does the url contain %00

### ISSUE THREAD

**Issue by caoJiang7** [kubernetes/client-go#1347]
client-go Version: v0.28.2
k8s version: v1.28.3

log: 
W0408 01:50:20.316882       7 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.Pod: Get "https://10.254.0.1:443/%00api/v1/pods?fieldSelector=spec.nodeName%3Dminion-2&resourceVersion=12299792": stream error: stream ID 137; PROTOCOL_ERROR; invalid header field name "\x01\x00\x00\x00\x04\x00\x00\x00"
E0408 01:50:20.316954       7 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://10.254.0.1:443/%00api/v1/pods?fieldSelector=spec.nodeName%3Dminion-2&resourceVersion=12299792": stream error: stream ID 137; PROTOCOL_ERROR; invalid header field name "\x01\x00\x00\x00\x04\x00\x00\x00"

**Comment by liggitt** [comment]
The configuration or file you are setting up the client from likely contains a null character at the end of the server url line which is getting picked up as part of the base URL

/kind support

**Comment by caoJiang7** [comment]
> The configuration or file you are setting up the client from likely contains a null character at the end of the server url line which is getting picked up as part of the base URL
> 
> /kind support

Use clientcmd.BuildConfigFromFlags("", "") to build the client configuration. This should not cause problems with %00 (NULL characters) in URLs. And the problem occurs randomly.

code：
	clientConfig, err := clientcmd.BuildConfigFromFlags("", "")
	if err != nil {
		return nil, err
	}
	clientConfig.ContentType = "application/vnd.kubernetes.protobuf"
	clientset, err := kubernetes.NewForConfig(clientConfig)
	if err != nil {
		return nil, err
	}
