### ISSUE TITLE
v0.24.17 build error

### ISSUE THREAD

**Issue by developless** [kubernetes/client-go#1349]
../../../pkg/mod/k8s.io/client-go@v0.24.16/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData

**Comment by liangyuanpeng** [comment]
0.24 is a not longer support version, maybe can try to ask the question at slack.
