### ISSUE TITLE
The compatibility-matrix needs to be updated to include versions 1.29 and 1.30 in README.md

### ISSUE THREAD

**Issue by joselitofilho** [kubernetes/client-go#1353]
The compatibility-matrix needs to be updated to include versions 1.29 and 1.30 in README.md.

https://github.com/kubernetes/client-go#compatibility-matrix

**Comment by JanneKiiskila** [comment]
And there's actually also 1.31 now; https://github.com/kubernetes/client-go/tree/release-1.31
