### ISSUE TITLE
Why two client: kubeclient and event client?

### ISSUE THREAD

**Issue by k82cn** [kubernetes/client-go#136]
Can we combine kubeclient & event client into one object?

**Comment by caesarxuchao** [comment]
Sorry, i don't get the question. Could you point me to the code of "event client"?

**Comment by caesarxuchao** [comment]
After offline discussion, i think @k82cn was referring to the fact that kubelet is using both the pkg/client/clientset_generated and k8s.io/client-go: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L64 and https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L48.

@deads2k @sttts i think you did the migration to client-go. Is there any issue blocking us converting kubelet to use client-go solely? Thanks.

**Comment by deads2k** [comment]
> @deads2k @sttts i think you did the migration to client-go. Is there any issue blocking us converting kubelet to use client-go solely? Thanks.

Nothing that I know of offhand.  I think once we got the client code copies removed, the generated listers, and the generated informers all working for client-go, the switch for kubelet, scheduler, and controllers could move forward.

**Comment by sttts** [comment]
For code hygiene I would like to see that we continue separating the apiserver and client sides. This includes the kubelet and the proposed switch to client-go in the kubelet. The only reason right now for not using client-go would be the use of the internal clients which we do not ship in client-go. Not sure how dependent the kubelet is on that.

**Comment by caesarxuchao** [comment]
>  The only reason right now for not using client-go would be the use of the internal clients

But the linked code is using the external clients ("k8s.io/kubernetes/pkg/client/clientset_generated/clientset"). I thought i had cleaned up kubelet's dependencies on internal clients in #36673.

**Comment by caesarxuchao** [comment]
Closing. This is a tech debt in the main kubernetes repo.

**Comment by k82cn** [comment]
@caesarxuchao , which issue is tracing the discussion? I'd like to see anything I can contribute, I'm also learning the major logic of kubelet :).

**Comment by caesarxuchao** [comment]
Feel to create one in the main repo. (i should had done this before closing this issue)

**Comment by k82cn** [comment]
sure, my pleasure :).

**Comment by jcbsmpsn** [comment]
If someone has created the new issue, can they link it here?

**Comment by caesarxuchao** [comment]
Moved to https://github.com/kubernetes/kubernetes/issues/43670
