### ISSUE TITLE
Ensure Pods().List() is Strongly Consistent

### ISSUE THREAD

**Issue by ryanaoleary** [kubernetes/client-go#1383]
I'm wondering if the client-go PodLister is strongly consistent, such that all `List` calls will return an up-to-date list of Pods from the api server, and if not is there a way to ensure consistency using client-go. I'm running into an issue with an admission webhook, where subsequent admission requests will rarely return the same list of Pods. The expected behavior would be for the second request executed in series to return a Pod list containing the updated k8s Pod from the previous mutating admission request.

My usage of the `Pods().Lister()` within the webhook is as follows:
```
factory := informers.NewFilteredSharedInformerFactory(client, 1*time.Minute, metav1.NamespaceAll, tweakListOptionsFunc)
podLister := factory.Core().V1().Pods().Lister()
...
podLister.Pods(namespace).List(labels.SelectorFromSet(labels.Set{"ray.io/node-type": "worker"}))
```

Related Issue: https://github.com/GoogleCloudPlatform/ai-on-gke/issues/858

**Comment by liggitt** [comment]
the Lister obtained from an informer is not making API calls, it is listing from an in-memory cache populated by an open watch

making API requests to the server using the clientset interface (not an informer) *can* be strongly consistent, for example:

https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L39-L51
