### ISSUE TITLE
Dependencies broken in v0.32.0

### ISSUE THREAD

**Issue by thallgren** [kubernetes/client-go#1395]
Our github.com/datawire/k8sapi has a dependency on k8s.io/client-go. I'm not able to update this from v0.31.0 to v0.32.0. Please note that our module is not referencing `k8s.io/client-go/kubernetes/typed/coordination/v1alpha1` anywhere.

```
go: finding module for package k8s.io/client-go/kubernetes/typed/coordination/v1alpha1
go: github.com/datawire/k8sapi/pkg/k8sapi imports
        k8s.io/client-go/kubernetes/typed/coordination/v1alpha1: module k8s.io/client-go@latest found (v0.32.0), but does not contain package k8s.io/client-go/kubernetes/typed/coordination/v1alpha1
```

Everything works fine with v0.31.0.

**Comment by dims** [comment]
See release note in https://github.com/kubernetes/kubernetes/pull/127857, please use newer types!

https://github.com/kubernetes/client-go/tree/master/kubernetes/typed/coordination

/close

**Comment by thallgren** [comment]
@dims as mentioned in my initial comment, we don't use this type at all. So It's unclear to me how I should act to follow your advice to new newer types.

**Comment by liggitt** [comment]
it looks like it's referenced here: https://github.com/datawire/k8sapi/blob/main/pkg/k8sapi/interface.go#L30

**Comment by dims** [comment]
@thallgren https://github.com/search?q=repo%3Adatawire%2Fk8sapi%20%2Fcoordination%5C%2Fv1alpha1%2F&type=code

**Comment by liggitt** [comment]
a simpler way to join the Kubernetes clientset with yours without explicitly repeating all the signatures (which requires explicitly importing the hierarchy of Kubernetes API versions and types) would be to embed the Kubernetes clientset in yours and implicitly inherit everything from it

at https://github.com/datawire/k8sapi/blob/main/pkg/k8sapi/interface.go#L69

```diff
type joinedClientSetInterface struct {
- 	ki  kubernetes.Interface
+ 	kubernetes.Interface
	ari argoRollouts.Interface
}

func NewJoinedClientSetInterface(ki kubernetes.Interface, ari argoRollouts.Interface) JoinedClientSetInterface {
	return &joinedClientSetInterface{
- 		ki:  ki,
+ 		Interface:  ki,
		ari: ari,
	}
}
```

you could then drop *all* the boilerplate methods on joinedClientSetInterface delegating to the Kubernetes implementation

**Comment by thallgren** [comment]
@dims Can't believe I missed that. Thank you so much for taking the time to finding it for me, and sorry for the noise.
@liggitt Thank's for this advice. I'll look into changing this.
