### ISSUE TITLE
InitContainers dont work by default when moving from unversioned client to client-go

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/client-go#142]
- I was Migrating an app using Init Containers from unversioned client to client-go
- All i needed to do in the unversioned client, was populate api.Container into InitContainers field of the PodSpec.
- the migrated app stopped working in client-go.
- i had to explictily enable serialization to annotations to make the init containers work in client-go.

I think that is a bad user experience. By default Init Containers or any other alpha feature should work, without requiring any special serialization. 

I had to call the following function to make this work https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/pod/util.go#L91
which is not part of the client-go code. So i had to duplicate that in my app.

**Comment by caesarxuchao** [comment]
@smarterclayton we had dealt with this when we migrated kubernetes to use versioned client. Is initcontainer going to be stable soon? If so, i don't want to import those conversion functions to client-go.

**Comment by ericchiang** [comment]
Looks like initContainers will be available as a field in 1.6 https://github.com/kubernetes/kubernetes/pull/38382

Which "unversioned" version where you using? I don't think those fields were added until 1.6.
