### ISSUE TITLE
how to determine client-go's commit SHA based on Kubernetes's commit?

### ISSUE THREAD

**Issue by resouer** [kubernetes/client-go#143]
`kubernetes/frakti` now vendors  client-go & apimachinery, what we do currently is: after `godep save ./...`, manually copy all files from `kubernetes/staging/client-go` to `frakti/vendor/k8s.io/client-go`.

So I wonder if there's any I can determine the right commit of client-go under my GOPATH, so I can save them to vendor of frakti later?

FYI, I tried `godep restore` under `kubernetes/staging/src/k8s.io/client-go`, it does not work. client-go under GOPATH is not the same as `staging`.

**Comment by caesarxuchao** [comment]
Why do you "manually copy all files from kubernetes/staging/client-go"? Does the instructions in install.md not work? https://github.com/kubernetes/client-go/blob/master/INSTALL.md#godep.

**Comment by caesarxuchao** [comment]
The client-go's master branch is update-to-date now. I believe you can use the master branch. Closing.
