### ISSUE TITLE
FakeEvents Search method uses wrong ListOptions

### ISSUE THREAD

**Issue by floreks** [kubernetes/client-go#145]
While trying to test method in kubernetes dashboard that uses `client.Core().Events().Search()` method chain to get events for node I've encountered panic error due to wrong `ListOptions` import in [fake_event_expansion.go](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/fake/fake_event_expansion.go#L69).

Method execution chain is as follows:
[Search()](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/fake/fake_event_expansion.go#L69)) -> [NewRootListAction()](https://github.com/kubernetes/client-go/blob/master/testing/actions.go#L50) -> [ExtractFromListOptions()](https://github.com/kubernetes/client-go/blob/master/testing/actions.go#L223)

ExtractFromList options expects ListOptions from `k8s.io/apimachinery/pkg/apis/meta/v1` package while Search method from FakeEvents struct  uses ListOptions from `k8s.io/client-go/pkg/api` package. Due to that there is a panic error that we can't avoid.

**Comment by caesarxuchao** [comment]
Thanks. Sent https://github.com/kubernetes/kubernetes/pull/43039 and assigned to you.
