### ISSUE TITLE
1.6 updates?

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/client-go#147]
I think this is out of date with the staging area of the main kubernetes repo. I updated it in https://github.com/kubernetes/kubernetes/pull/41931 and those changes don't seem to be reflected here.

**Comment by caesarxuchao** [comment]
https://github.com/kubernetes/client-go/pull/140 is updating the master branch.

It has to be merged at the same time as other PRs to other repos that client-go depends on or is depended by.

**Comment by jessfraz** [comment]
gotcha thanks!

**Comment by caesarxuchao** [comment]
Looks like the changes are populated to the master branch. Closing.
