### ISSUE TITLE
kubectl compatible initialization helper

### ISSUE THREAD

**Issue by justinsb** [kubernetes/client-go#149]
I believe a common use case for using the client-go will be writing utilities, and that users of these tools would expect them to work if `kubectl` worked (and to be pointing at the same cluster etc).

However, the kubectl initialization looks like this:

```
loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
// use the standard defaults for this client command
// DEPRECATED: remove and replace with something more accurate
loadingRules.DefaultClientConfig = &clientcmd.DefaultClientConfig

flags.StringVar(&loadingRules.ExplicitPath, "kubeconfig", "", "Path to the kubeconfig file to use for CLI requests.")

overrides := &clientcmd.ConfigOverrides{ClusterDefaults: clientcmd.ClusterDefaults}

flagNames := clientcmd.RecommendedConfigOverrideFlags("")
// short flagnames are disabled by default.  These are here for compatibility with existing scripts
flagNames.ClusterOverrideFlags.APIServer.ShortName = "s"

clientcmd.BindOverrideFlags(overrides, flags, flagNames)
clientConfig := clientcmd.NewInteractiveDeferredLoadingClientConfig(loadingRules, overrides, os.Stdin)

return clientConfig
```

Can we move this method (and a non-interactive version) into client-go?  Right now I'm copying-and-pasting the block into various programs, and that's not ideal, particularly with the uncertainty around the deprecated methods.

**Comment by caesarxuchao** [comment]
I'm not sure if this [DefaultClientConfig](https://github.com/kubernetes/kubernetes/blob/v1.6.0-beta.4/pkg/kubectl/cmd/util/factory_client_access.go#L147) belongs to client-go, the coming kubectl repo (cc @pwittrock), or another utility repo. @lavalamp could you help triage?
