### ISSUE TITLE
Is ResourceVersion honored on Update?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/client-go#150]
Does Update honor ResourceVersion?  I want to do a conditional update i.e. I read a version, change it, but I only want to update if there has been no concurrent modification.

Is this the behaviour of Update?

**Comment by deads2k** [comment]
> Is this the behaviour of Update?

Yes.

**Comment by justinsb** [comment]
Wonderful - thank you @deads2k  :-)

**Comment by krmayankk** [comment]
Conditional Update is supported, what about if i update a k8s object but dont provide ResourceVersion, is that supported as well ?
