### ISSUE TITLE
Conversion *extensions.Deployment to *v1beta1.Deployment fails

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/client-go#151]
I am trying to covert *extensions.Deployment to *v1beta1.Deployment in go-client 2.0 but it fails (actually since 1.4):

2017/03/19 10:17:05 failed to convert: converting (extensions.Deployment).CreationTimestamp.Time.sec to (v1beta1.Deployment).CreationTimestamp.Time.sec: Cannot set dest. (Tried to deep copy something with unexported fields?)
exit status 1

```package main

import (
	"log"

	_ "k8s.io/client-go/kubernetes"
	"k8s.io/client-go/pkg/api"
	"k8s.io/client-go/pkg/apis/extensions"
	"k8s.io/client-go/pkg/apis/extensions/v1beta1"
	"k8s.io/client-go/pkg/runtime"
)

const yaml = `
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push
`

func main() {

	d := api.Codecs.UniversalDecoder()
	obj, _, err := d.Decode([]byte(yaml), nil, nil)
	if err != nil {
		log.Fatalf("could not decode yaml: %s\n%s", yaml, err)
	}

	src := obj.(*extensions.Deployment)
	s := runtime.NewScheme()
	dst := &v1beta1.Deployment{}
	err = s.Convert(src, dst, 0)
	if err != nil {
		log.Fatalf("failed to convert: %s", err)
	}
}
```

I have created the same issue in the Kubernetes repository for client-go 1.4 with more info a while ago, but it still looks broken: https://github.com/kubernetes/kubernetes/issues/39864

**Comment by caesarxuchao** [comment]
Instead of instantiating another scheme, using the `api.Scheme.Convert(...` works for me.

**Comment by andrejvanderzee** [comment]
@caesarxuchao Works indeed, thanks.

**Comment by jinankjain** [comment]
@caesarxuchao This broke for go-client 4.0.0

**Comment by caesarxuchao** [comment]
@jinankjain could you paste your code?

**Comment by jinankjain** [comment]
@caesarxuchao Yeah sure https://github.com/kubernetes/client-go/issues/253#issuecomment-318210890
