### ISSUE TITLE
No change can watch when use client.Namespace.Watch after long time

### ISSUE THREAD

**Issue by shenshouer** [kubernetes/client-go#152]
I want to watch the namespace change and use the client.Namespace.Watch. And the beginning I can get all the namespace changed, but after about one or two day this Cannot get any change when the I create new namespace or delete exist namespace. And there have no error report, and any other logs.  The code like: 

```
	var watchIF watch.Interface
	timeout := int64(3600 * 24)
	if watchIF, err = kss.kubeClient.Namespaces().Watch(api.ListOptions{Watch: true, TimeoutSeconds: &timeout}); err != nil {
		log.Errorf("Watch namespaces from kubernetes cluster error:%v", err)
		return
	}

	eventChan := watchIF.ResultChan()
	for {
		select {
		case event := <-eventChan:
			switch event.Type {
			case watch.Added:
				namespace := event.Object.(*v1.Namespace)
				log.Infoln("ADD namespace:", namespace.Name)
				if namespace.Name == "kube-system" { // 过滤掉为kube-system的namespace
					continue
				}

				nw := &namespaceWatcher{
					wCache:     kss.wCache,
					etcdClient: kss.wCache.client,
					clientset:  kss.kubeClient,
					namespace:  namespace.Name,
					stopOrDel:  make(chan bool, 1),
				}

				if err := kss.wCache.addWatch(nw.namespace, nw); err != nil {
					log.Errorln(err)
				}
			case watch.Deleted:
				namespace := event.Object.(*v1.Namespace)
				log.Infoln("DELETE namespace:", namespace.Name)
				if err := kss.wCache.delWatch(namespace.Name); err != nil {
					log.Errorf("Stop watch namespace:%s error:%v", namespace, err)
				}
			}

		case <-kss.quit:
			log.Infoln("Received quit signal, Exit watch namespaces")
			kss.wCache.stopAllWatch()
			return
		}
	}
```

The same with the param of timeout. Before I found the problem I did not set timeout , After set the timeout and still get nothing changed when pass two days .

Any one who can help me ? Or I need to direct watch the etcd which the master used.

**Comment by ncdc** [comment]
@shenshouer does your for loop exit? Do you see any error messages printed/logged anywhere?

**Comment by caesarxuchao** [comment]
Does the apiserver's log contain any clue?

**Comment by shenshouer** [comment]
@ncdc The for loop did not exit, and has no error messages

**Comment by shenshouer** [comment]
@caesarxuchao The log of apiserver have no exception. And I used the time ticker in for loop to check the change replace the watch

**Comment by sgoodliff** [comment]
Hi,
Did you get to the bottom of this? I'm experiencing something similar.

Thanks
