### ISSUE TITLE
emicklei/go-restful/swagger  Has been moved.  Imports Need To Be Updated.

### ISSUE THREAD

**Issue by mikeln** [kubernetes/client-go#156]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): swagger, swagger12

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Description:**

github.com/emicklei/go-restful/swagger   

has been moved to: 

https://github.com/emicklei/go-restful-swagger12

Imports in several files need to be updated.

**Comment by caesarxuchao** [comment]
PR #154  is out. We'll merge them soon.

**Comment by caesarxuchao** [comment]
The specific version has been included in vendor/, so `go get` won't try to fetch it from the old address. Closing.
