### ISSUE TITLE
JSONPath parser will not filter strings containing parentheses

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/client-go#158]
For example, given this query:
` kubectl get nodes -o jsonpath='{.items[?(@.status.nodeInfo.osImage == "Debian GNU/Linux 7 (wheezy)")].status.nodeInfo.osImage}'`

you get this error:
`error: error parsing jsonpath {.items[?(@.status.nodeInfo.osImage == "Debian GNU/Linux 7 (wheezy)")].status.nodeInfo.osImage}, unclosed array expect ]`

which I believe is due to this code: https://github.com/kubernetes/client-go/blob/088dc4a30d8aea05fe147c21f249f519fece0bf6/util/jsonpath/parser.go#L342

which naively breaks on a `)`, even when inside the comparison string.

**Comment by caesarxuchao** [comment]
cc @daizuozhuo who's the original author of this file. @mtaufen @daizuozhuo if you are going to send a PR, please send it to the main kubernetes repo against https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/jsonpath/jsonpath.go.
