### ISSUE TITLE
Watching and getting pods from all namespaces

### ISSUE THREAD

**Issue by F21** [kubernetes/client-go#159]
It seems to be possible to watch for pods and get pods from all namespaces via the API:

- https://kubernetes.io/docs/api-reference/v1.5/#list-all-namespaces-63
- https://kubernetes.io/docs/api-reference/v1.5/#watch-list-all-namespaces-66

Does the client support these operations (I wasn't able to find methods supporting them)?

If not, it would be nice if the client can support these operations.

**Comment by F21** [comment]
Setting the namespace for `Pods()` to `""`, will get all the pods from all namespaces:

```go
client.CoreV1().Pods("").List(v1.ListOptions{})
```

**Comment by gpanagiotidis** [comment]
Is it possible to watch and get pod from specific namespaces? Neither just one nor all of them.

What I do is I create an array of namcespaces and then run a loop for a new watchlist for each one of them.
