### ISSUE TITLE
Packages not available.

### ISSUE THREAD

**Issue by narkarum** [kubernetes/client-go#162]
The referenced all packages were not available.

package: k8s.io/client-go

- version: 7615377
- subpackages:
- kubernetes
- kubernetes/typed/core/v1
- pkg/api
- pkg/api/v1
- pkg/apis/storage/v1
- pkg/apis/storage/v1beta1
- rest
- tools/cache
- tools/clientcmd
- tools/record

For example, following were not found the commit: 7615377

- pkg/api/resource
- pkg/api/testapi
- pkg/api
- pkg/api/v1

**Comment by ericchiang** [comment]
@narkarum what do you mean by "not available"? The SHAs you reference definitely still have those packages in the repo.

```
$ cat glide.yaml 
package: github.com/ericchiang/client-go-example
import:
- package: k8s.io/client-go
  version: 76153773eaa3a268131d3d993290a194a1370585
$ cat main.go 
package main

import "k8s.io/client-go/tools/clientcmd"

func main() {
	_ = clientcmd.ConfigOverrides{}
}
$ glide up -v # lots of output
$ go build -v main.go # builds fine
```

**Comment by narkarum** [comment]
In the master branch of external-storage, glide has:

package: k8s.io/client-go
version: 7615377
subpackages:
kubernetes
kubernetes/typed/core/v1
pkg/api
pkg/api/v1
pkg/apis/storage/v1
pkg/apis/storage/v1beta1
rest
tools/cache
tools/clientcmd
tools/record

But all these packages were not available in 7615377 commit of k8s.io/client-go

**Comment by narkarum** [comment]
fyi I have been getting a lot of errors from glide tonight like

[ERROR]	Failed to install: https://cloud.google.com/go Not Found

..

[ERROR]	https://golang.org/x/net Not Found

**Comment by narkarum** [comment]
The referenced all packages were not available.

package: k8s.io/client-go
version: 7615377
subpackages:
kubernetes
kubernetes/typed/core/v1
pkg/api
pkg/api/v1
pkg/apis/storage/v1
pkg/apis/storage/v1beta1
rest
tools/cache
tools/clientcmd
tools/record

**For example, following were not found the commit: 7615377**

pkg/api/resource
pkg/api/testapi
pkg/api
pkg/api/v1

**Comment by ericchiang** [comment]
A few of those sub-packages, e.g. "pkg/api/resource" have never been in client-go, to the best of my knowledge. However almost all the other packages you're referencing are in that commit.

https://github.com/kubernetes/client-go/tree/76153773eaa3a268131d3d993290a194a1370585/tools/clientcmd
https://github.com/kubernetes/client-go/tree/76153773eaa3a268131d3d993290a194a1370585/pkg/api/v1

Am I mis-understanding the issue? Do you have an example of a program that you're expecting to build that isn't?

**Comment by narkarum** [comment]
fyi I have been getting a lot of errors from glide tonight like

[ERROR]	Failed to install: https://cloud.google.com/go Not Found

..

[ERROR]	https://golang.org/x/net Not Found

Are you able to compile?
