### ISSUE TITLE
how does error handling work?

### ISSUE THREAD

**Issue by xh3b4sd** [kubernetes/client-go#163]
I am playing around with the client and wonder how error handling works. I scanned the code a bit and could not find typed errors or error codes/matchers. So if I try to create an endpoint for a service and this endpoint exists I get an error which is only identifiable by string matching against the error message. I feel like it would be super useful to have proper error types to match against. How is this intended to work with the client library here?

**Comment by lavalamp** [comment]
Keep digging-- you should be getting `StatusError`s

**Comment by xh3b4sd** [comment]
I see. This is what I was looking for: https://godoc.org/k8s.io/apimachinery/pkg/api/errors. The code base is so huge and one is like to get lost quite quickly. <3

**Comment by ericchiang** [comment]
@xh3b4sd want to contribute an example? :)

**Comment by slintes** [comment]
I had the same problem and would be happy to share my finding with a PR for an extended example. Do I see it correct that I can edit the examples directly in kubernetes/staging/src/k8s.io/client-go/examples? I don't see them in kubernetes/pkg/client...

**Comment by rmohr** [comment]
@slintes, yes `staging/src/k8s.io/client-go/examples/` is the right place.
