### ISSUE TITLE
When l delete the rc , the pod not deleted 

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/client-go#164]
l use CoreV1().ReplicationControllers(Namespace).Delete(Name, &v1.DeleteOptions{}) to delete rc, the rc was delete , but the rc's pod util exsit forerver .  so l checkout another version , produce the same result.
but when use CoreV1().Namespaces().Delete(Name, &v1.DeleteOptions{}) to delete namespace, the rc and pod was delete too. 

so l think the rc's delete func has a bug. 

l wish you group to deal with it.

**Comment by lavalamp** [comment]
This is not a client problem.

Check your kubernetes version. In 1.5 and 1.6, you can pass different settings in delete options. RCs orphan by default. Set that to false (1.5) or use the foreground or background policy (1.6).

**Comment by huangjiasingle** [comment]
@lavalamp l was set the deleteoptions's orphan  true or false ,it produced the same result. why?
