### ISSUE TITLE
Compiling with release-3.0 branch not working

### ISSUE THREAD

**Issue by vsimon** [kubernetes/client-go#167]
With the release-3.0 branch, this
```
package main

import "fmt"

import _ "k8s.io/client-go/kubernetes"

func main() {
	fmt.Println("test")
}
```

results in 

```
$ go run main.go
# gitlab.oblong.com/mezzanine/meow/vendor/k8s.io/client-go/discovery
../vendor/k8s.io/client-go/discovery/restmapper.go:288: del.AliasesForResource undefined (type meta.RESTMapper has no field or method AliasesForResource)
```

Perhaps https://github.com/kubernetes/client-go/commit/999c0d5c20bde4f4ed1c5f4e719d26eb2f687501 needs to be cherry-picked into this branch?

**Comment by caesarxuchao** [comment]
Had you run `godep restore` after checking out release-3.0 of client-go? `AliasesForResource` is defined in apimachinery, release-1.6, see https://github.com/kubernetes/apimachinery/blob/release-1.6/pkg/api/meta/interfaces.go#L145

**Comment by vsimon** [comment]
I wasn't using `godep` but `gvt fetch` to fetch release-3.0 like:
```
$GOPATH/bin/gvt fetch k8s.io/client-go -branch release-3.0
go run main.go

# gitlab.oblong.com/mezzanine/meow/vendor/k8s.io/client-go/discovery
vendor/k8s.io/client-go/discovery/restmapper.go:288: del.AliasesForResource undefined (type meta.RESTMapper has no field or method AliasesForResource)
```
this fails.

But this succeeds

```
$GOPATH/bin/gvt fetch -branch release-3.0 k8s.io/client-go
$GOPATH/bin/gvt fetch -branch release-1.6 k8s.io/apimachinery
go run main.go

test
```
Is pinning the apimachinery branch the solution, otherwise it pulls 'master'? I didn't find anything obvious from the README that would say that is the case.

**Comment by caesarxuchao** [comment]
> Is pinning the apimachinery branch the solution, otherwise it pulls 'master'?

I think it's the behavior of `gvt`. It looks like `gvt` requires `vendor/manifest` to track the version of dependencies, which is not provided in this repo.

README.md takes you to the [INSTALL.md](https://github.com/kubernetes/client-go/blob/master/INSTALL.md), where we describe how to use `godep`, `glide`, or `dep` to manage the vendor. I think you need to go through similar steps if using `gvt`.

**Comment by vsimon** [comment]
:+1: I'll take a look, thanks!
