### ISSUE TITLE
client-go does not support SNI even though API server does

### ISSUE THREAD

**Issue by deitch** [kubernetes/client-go#173]
The kube-apiserver support SNI correctly, as given by the docs and code with the `--tls-sni-cert-key` option (and real testing with 1.6.1).

The client-go library does not. 

The `TLSClientClientConfig struct` has a line for it at https://github.com/kubernetes/client-go/blob/master/rest/config.go#L136 but when using `InClusterConfig()` and `NewConfig(config)`, there is no way to indicate it should use the provided server_name.

See https://github.com/kubernetes/client-go/blob/master/rest/config.go#L287

It probably should be something like:

```go
	tlsClientConfig := TLSClientConfig{ServerName: host}
```

By default, it probably should specify the ServerName.

**Comment by ericchiang** [comment]
The crypto/tls library adds this by default if it's not present[0]. What version of Go are you using?

[0] https://github.com/golang/go/blob/release-branch.go1.8/src/crypto/tls/tls.go#L134-L141

**Comment by deitch** [comment]
> The crypto/tls library adds this by default if it's not present[0]. What version of Go are you using?

Oops. :-)
What version does this start with?

I came across it when using weave in a kube cluster. It accesses the cluster from inside the daemonset, so uses `InClusterConfig()` and access the `kubernetes` service available from within the pod.

I definitely can confirm that the requests to the API server did *not* have the `server_name` extension on them (tcpdump+wireshark), and ran a manual `openssl` to confirm that they do show up in the captured packets (scientific control group).

@bboreham can you answer?

**Comment by ericchiang** [comment]
Something ancient like 1.4. I can try to dig into the client-go package and see if it's not hitting this code path.

**Comment by deitch** [comment]
Good thing I didn't close the issue in weave. :-)

Let's confirm that it is just a golang version issue, and I will close this one out.

**Comment by bboreham** [comment]
Weave Net is built with Go 1.7.4

**Comment by deitch** [comment]
Heh, I just ran `strings weave-npc | grep go1` and found `go17` in a lot of places. :-)

That is pretty recent.
