### ISSUE TITLE
incomplete recommendation in INSTALL.md

### ISSUE THREAD

**Issue by ensonic** [kubernetes/client-go#176]
I've tried to follow the the recommendation to use the `dep` tool.
First you will have to call this `~/go/bin/dep` unless you added $GOPATH/bin to PATH.

After some fiddling with the gopath I've got the dep tool to run, but the build still fails:
```
./main.go:36: cannot use deployment (type *"k8s.io/client-go/pkg/apis/apps/v1beta1".Deployment) as type *"app/vendor/k8s.io/client-go/pkg/apis/extensions/v1beta1".Deployment in argument to k8s.ExtensionsV1beta1().Deployments("").Create
```
It would be nice to provide some guidelines of how to handle this and how the imports supposed to look like.
1.) is it okay to mix sources like:
```
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
"k8s.io/client-go/pkg/api/v1"
appsv1beta1 "k8s.io/client-go/pkg/apis/apps/v1beta1"
```
Or is meta/v1 available somewhere under client-go too (did not find it so far).

2.) why are the package path's so repetitive? whats the difference in
```
"k8s.io/client-go/pkg/apis/apps/v1beta1"
"k8s.io/client-go/pkg/apis/extensions/v1beta1"
```
- they both have Deployment().

Swapping the 'apps' with 'extensions', the initial error becomes:
```
./main.go:36: cannot use deployment (type *"k8s.io/client-go/pkg/apis/extensions/v1beta1".Deployment) as type *"app/vendor/k8s.io/client-go/pkg/apis/extensions/v1beta1".Deployment in argument to k8s.ExtensionsV1beta1().Deployments("").Create
```
Seems, I am getting closer...

**Comment by caesarxuchao** [comment]
`app/vendor/k8s.io/client-go/pkg/apis/extensions/v1beta1` looks really strange, i'll look into it.

**Comment by caesarxuchao** [comment]
> 2.) why are the package path's so repetitive? whats the difference in
```
"k8s.io/client-go/pkg/apis/apps/v1beta1"
"k8s.io/client-go/pkg/apis/extensions/v1beta1"
```

They are different API groups, `apps` vs. `extensions`. Usually when a new beta feature is introduced, developers put it in the `extensions` group, and later move it to a more specific group like `apps`. The migration for Deployment is done in 1.6 (https://github.com/kubernetes/kubernetes/pull/39683). For backwards compatibility, the extensions/v1beta1.Deployment was not removed, but i guess it will be removed in kubernetes 1.7. @soltysh might know more about the planning.

**Comment by caesarxuchao** [comment]
> 1.) is it okay to mix sources like:

metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
"k8s.io/client-go/pkg/api/v1"
appsv1beta1 "k8s.io/client-go/pkg/apis/apps/v1beta1"
Or is meta/v1 available somewhere under client-go too (did not find it so far).

Yeah, you can use the HEAD of apimachinery with the HEAD of client-go. Or you can refer to the client-go/Godeps/Godeps.json to see what the compatible version of apimachinery repo is.

**Comment by caesarxuchao** [comment]
@ensonic what is `app/vendor/...`? Is `app` your project?

Are there two copies of client-go in your GOPATH? Perhaps one in $GOPATH/src/k8s.io/client-go and another one in $GOPATH/src/???/app/vendor/k8s.io/client-go?

**Comment by ensonic** [comment]
>  Or you can refer to the client-go/Godeps/Godeps.json to see what the compatible version of apimachinery repo is.
As recomended in go-client I am using `~/go/bin/dep ensure k8s.io/client-go@^2.0.0`. When looking at
https://github.com/kubernetes/apimachinery/blob/master/Godeps/Godeps.json#L2
apimachinery does not seem to have a version. I've tried `/go/bin/dep ensure k8s.io/apimachinery` or `/go/bin/dep ensure k8s.io/apimachinery@^2.0.0` but it never installs `apimachinery` into my vendor dir (see output at https://gist.github.com/ensonic/84e7941cfd078c968785ca8cc7265fe7)

The only way to get apimachinery is to run 'go get  -d', but then it ends up in the first entry of the GOPATH before the one with the vendor dir. My GOPATH is "$HOME/go:$HOME/projects/foo". 
$HOME/projects/foo has:
```
src/
   bar/
      bar.go
   app/
     main.go
     vendor/
       k8s.io/
          client-go/
```

**Comment by ensonic** [comment]
Update: I've dropped my local 'bar' package. Seems I would also need a vendor dir in there to make things work. Also I disovered that there is no apimachinery counterpart for V2.0.0. ObjectMeta is in "k8s.io/client-go/pkg/api/v1" and TypeMeta is in "k8s.io/client-go/pkg/api/unversioned". I hope this is not changing all the time.

**Comment by soltysh** [comment]
> 2.) why are the package path's so repetitive? whats the difference in
> 
> "k8s.io/client-go/pkg/apis/apps/v1beta1"
> "k8s.io/client-go/pkg/apis/extensions/v1beta1"

> For backwards compatibility, the extensions/v1beta1.Deployment was not removed, but i guess it will be removed in kubernetes 1.7. @soltysh might know more about the planning.

The reason is that `extensions` api group was the first introduced, sort of grab bag where we put all the new resources at the time. After we've polished the API groups we've started creating more targeted groups, such as `apps`, `batch`, `autoscaling`, etc. `extensions` is currently being retired but it'll take us some time to clean it up (see https://github.com/kubernetes/kubernetes/issues/43214). You are encouraged to use the `apps` deployments above all :)

**Comment by caesarxuchao** [comment]
You are right, client-go v2.0.0 doesn't depend on k8s.io/apimachinery, so there is no entry for apimachinery in Godeps.json. The apimachinery repo is created later after client-go v2.0.0-alpha. We decided to vendor apimachinery after v2.0.0 so that client-go can be used with other kubernetes repos.

Do you have another checkout of client-go in your first GOPATH? The error message you go seemed to suggest that. Also, personally i avoid using multiple GOPATH as that had caused unexpected issues for me in the past.

> Also please DO NOT suggest the dep tool to people yet (or at least not as a first suggestion). It is definitely not ready yet. Just now the manifest file changed from manifest.json to Gopkg.toml.

I'm sending a PR now.
