### ISSUE TITLE
in-cluster and out-of-cluster examples don't build again

### ISSUE THREAD

**Issue by cristian-pirnog** [kubernetes/client-go#177]
```
cristian@cristian-laptop:~/code/go/src/k8s.io/client-go$ go build ./examples/in-cluster/
# k8s.io/client-go/discovery
discovery/restmapper.go:304: cannot use DeferredDiscoveryRESTMapper literal (type *DeferredDiscoveryRESTMapper) as type meta.RESTMapper in assignment:
	*DeferredDiscoveryRESTMapper does not implement meta.RESTMapper (missing AliasesForResource method)
cristian@cristian-laptop:~/code/go/src/k8s.io/client-go$ go build ./examples/out-of-cluster/
# k8s.io/client-go/discovery
discovery/restmapper.go:304: cannot use DeferredDiscoveryRESTMapper literal (type *DeferredDiscoveryRESTMapper) as type meta.RESTMapper in assignment:
	*DeferredDiscoveryRESTMapper does not implement meta.RESTMapper (missing AliasesForResource method)
```
This seems to be a similar issue with #81. I'm using the commit 4a3ab2f5be5177366f8206fd79ce55ca80e417fa.

**Comment by caesarxuchao** [comment]
Hey @cristian-pirnog, it looks like you didn't check out the correct version of k8s.io/apimachinery. The [Godeps.json](https://github.com/kubernetes/client-go/commit/4a3ab2f5be5177366f8206fd79ce55ca80e417fa#diff-681659ab9abb4b4883e78e8aaa980dbaR319) of 4a3ab2f shows it depends on b317fa7ec8e0e7d1f77ac63bf8c3ec7b29a2a215 of apimachinery, where the [meta.RESTMapper interface](https://github.com/kubernetes/apimachinery/blob/b317fa7ec8e0e7d1f77ac63bf8c3ec7b29a2a215/pkg/api/meta/interfaces.go#L125-L146) doesn't have `AliasesForResource`.

Please follow the [INSTALL.md](https://github.com/kubernetes/client-go/blob/master/INSTALL.md) to check out the correct version of the dependencies.

**Comment by cristian-pirnog** [comment]
Thanks! That did the trick.
Also thank you for the reference to INSTALL.md. I've been meaning to have a closer look at non-casual dependency management.
