### ISSUE TITLE
Can't compile release 3.0.0 beta-0

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/client-go#180]
We're seeing multiple errors, like:

```
# github.com/topfreegames/maestro/vendor/k8s.io/client-go/pkg/api/v1
models/vendor/k8s.io/client-go/pkg/api/v1/meta.go:24: cannot use obj (type *ObjectMeta) as type v1.Object in return argument:
	*ObjectMeta does not implement v1.Object (missing GetDeletionGracePeriodSeconds method)
```

**Comment by JuJu227** [comment]
The generals/commons (meta and types) has been exacted out and moved to https://github.com/kubernetes/apimachinery. So, you will need to vendor that package and do something similar to  `import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"`. Also worth noting that several of the method signatures have changed, they're basically now requiring additional metadata parameters.

**Comment by felipejfc** [comment]
@cscatolini, can you try it and see if using apimachinery works?

**Comment by ericchiang** [comment]
@felipejfc how are you vendoring client-go? client-go generally requires you vendor specific versions of packages it imports, like apimachinery. Are you using any of the instructions here? https://github.com/kubernetes/client-go/blob/master/INSTALL.md

**Comment by cscatolini** [comment]
@JuJu227, @ericchiang thanks for your help. Following both your instructions I was able to make it compile pointing both to the master branch:

```
dep ensure k8s.io/client-go@master
dep ensure k8s.io/apimachinery@master
```

When I try with `v3.0.0-beta.0` client-go is installed correctly but apimachinery produces the following output:

```
 ❯ dep ensure k8s.io/apimachinery@v3.0.0-beta.0
solve error: No versions of k8s.io/apimachinery met constraints:
	master: Could not introduce k8s.io/apimachinery@master, as it is not allowed by constraint v3.0.0-beta.0 from project github.com/topfreegames/maestro.
	release-1.6: Could not introduce k8s.io/apimachinery@release-1.6, as it is not allowed by constraint v3.0.0-beta.0 from project github.com/topfreegames/maestro.
ensure Solve(): No versions of k8s.io/apimachinery met constraints:
	master: Could not introduce k8s.io/apimachinery@master, as it is not allowed by constraint v3.0.0-beta.0 from project github.com/topfreegames/maestro.
	release-1.6: Could not introduce k8s.io/apimachinery@release-1.6, as it is not allowed by constraint v3.0.0-beta.0 from project github.com/topfreegames/maestro.
```

I checked the repo and there is no tag `v3.0.0-beta.0` for apimachinery. In this case how can I know witch versions are compatible? I also tried pointing client-go to `v3.0.0-beta.0` and apimachinery to `master` and the compilation errors persist, so I assume they are not compatible.

**Comment by ericchiang** [comment]
> The installation reference it not very clear about the dependencies. Do you think this is worth clarifying? If so, I could send you a PR.

I was hoping that dep would automatically detect the version of transitive dependencies from Godeps.json like glide does. This seems like an issue. Does dep look for a manifests file in the packages you `ensure`? Could we publish that format too?

**Comment by caesarxuchao** [comment]
dep is not stable, e.g., it recently changed from json to toml for the manifest. I think we shouldn't commit its manifests, as [suggested](https://github.com/golang/dep#usage) by dep.

I'll send a PR to add an entry for using dep with v3.0.0-beta.0.

**Comment by caesarxuchao** [comment]
Looks like dep needs some time to support manifests generated by other tools: https://github.com/golang/dep/issues/222
