### ISSUE TITLE
add example of performing a Patch

### ISSUE THREAD

**Issue by jmccormick2001** [kubernetes/client-go#181]
would be great to have a working example of performing a Patch using the client api, particularly would be useful for a ThirdPartyResource as an example.

**Comment by jmccormick2001** [comment]
after digging thru the kubectl code, I found something that works with Kube 1.6...here is a snippet of the code I managed to get working, showing how you can patch a TPR.......

 type ThingSpec struct {
        Op    string `json:"op"`
        Path  string `json:"path"`
        Value string `json:"value"`
}
things := make([]ThingSpec, 1)
        things[0].Op = "replace"
        things[0].Path = "/spec/ccpimagetag"
        things[0].Value = "newijeff"
        patchBytes, err4 := json.Marshal(things)
        if err4 != nil {
                fmt.Println(err4.Error())
        }
        fmt.Println(string(patchBytes))

        result, err6 := tprclient.Patch(api.JSONPatchType).
                Namespace(api.NamespaceDefault).
                Resource("pgupgrades").
                Name("junk").
                Body(patchBytes).
                Do().
                Get()

**Comment by ngtuna** [comment]
@jmccormick2001 How did it work from your setup? I hit this below issue when following your code sample:

```
       //f is a tpr struct
	data, err := json.Marshal(f)
	if err != nil {
		return err
	}

	//var result spec.Function
	_, err = tprClient.Patch(types.JSONPatchType).
		Resource("functions").
		Namespace(f.Metadata.Namespace).
		Name(f.Metadata.Name).
		Body(data).
		Do().Get()

	if err != nil {
		return err
	}
```
```
FATA[0000] json: cannot unmarshal object into Go value of type jsonpatch.Patch
```

It seems like a problem with json data ???

**Comment by jmccormick2001** [comment]
the 'data' needs to be that patch structure, not your tpr data based on the example you listed.  hope that helps.
