### ISSUE TITLE
Using client-go 2.0 with k8s 1.5

### ISSUE THREAD

**Issue by nvartolomei** [kubernetes/client-go#183]
I'm trying to use 2.0 branch of `client-go` to access resources on a 1.5 k8s cluster. Looking at [compatibility matrix](https://github.com/kubernetes/client-go#compatibility-matrix) I expect this to work.

Looks like it is not the case `Failed to list *v1beta1.StatefulSet: the server could not find the requested resource`.

It there a way to list alpha/beta/stable resources using a single client? The client-go 2.0 is missing `v1alpha1.StatefulSet` definition.

**Comment by caesarxuchao** [comment]
1.4 server only has v1alpha1.statefulset: https://github.com/kubernetes/kubernetes/tree/v1.4.0/pkg/apis/apps

1.5 server only has v1beta1 statefulset: https://github.com/kubernetes/kubernetes/tree/v1.5.0/pkg/apis/apps

client-go 2.0 is tracking kubernetes 1.5 release, so it only has v1beta1 statefulset.

> Failed to list *v1beta1.StatefulSet: the server could not find the requested resource

Regarding the error you observed, could you try `kubectl apiversions` to see what resources are supported by your apiserver?

**Comment by nvartolomei** [comment]
@caesarxuchao this basically means there is no way to support multiple versions of Kubernetes (1.3, 1.4, 1.5) using client-go 2.0?

If the client kept v1alpha1 definitions then user could use either v1alpha1 or v1beta1 depending on the server (kubernetes).

**Comment by caesarxuchao** [comment]
Unfortunately, not by using the /kubernetes package. You can try the dynamic client in /dynamic, depending on what you intend to do.

We should update the meaning of `+` in the compatibility matrix, adding "alpha/beta features might be missing in client-go".

> If the client kept v1alpha1 definitions then user could use either v1alpha1 or v1beta1 depending on the server (kubernetes).

client-go shares same version API types with kubernetes, it's difficult to maintain multiple versions. We plan to distribute the client generator in the future, then it's possible to generate clients for deprecated API.
