### ISSUE TITLE
[question] Idiomatic way to update a Deployment and its Annotations?

### ISSUE THREAD

**Issue by cilindrox** [kubernetes/client-go#185]
So, I'm using the following code (in-cluster, kubernetes v1.6.2, GKE) to update an existing Deployment's image. I'm also trying to add a `deployed-by` annotation.

```go
package main

import (
	"fmt"
	"os"

	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

func UpdateDeployment(app, image string) {
	config, err := rest.InClusterConfig()
	if err != nil {
		panic(err.Error())
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}

	namespace := "default"
	deployments := clientset.Extensions().Deployments(namespace)

	deploySpec, err := deployments.Get(app)
	if err != nil {
		panic(err.Error())
	}

	deploySpec.Spec.Template.Spec.Containers[0].Image = image
	deploySpec.ObjectMeta.Annotations["deployed-by"] = "me<me@domain.com>"
	_, err := deployments.Update(deploySpec)
}
```

Image gets updated and deployment is rolled out without any issues whatsoever. Annotations however do not get added/updated at all.

Any clues as to what I'm doing wrong here?

**Comment by krmayankk** [comment]
@cilindrox annotations are not propagated to pods by default, you have to expplicitly pass them in the pod template as well. You havent clarified above if the annotations are NOT updated in pods or deployments ?

**Comment by cilindrox** [comment]
@krmayankk thanks for the input. Trying to update de annotation on the Deployment currently. Seeing neither the Deployment (unexpected) nor the pods (expected) being affected by it.

**Comment by caesarxuchao** [comment]
What's the annotations of the deployment returned by Update()?

**Comment by cilindrox** [comment]
This seems to have been fixed after an upgrade on the cluster to Kubernetes 1.6.4, thanks everybody.
