### ISSUE TITLE
BUILD files in client-go repository

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/client-go#189]
I am wondering if Bazel BUILD files in this repository serve any particular reason (e.g. does the CI etc build/test the repository and uses Bazel for it)?

If not, having BUILD files might actually be confusing. Especially in `examples/*/` directories, users probably will click to something they don't necessarily understand. I personally don’t know Bazel and seeing that doesn’t help me with anything.

I would recommend removing BUILD files while/after mirroring if possible.

**Comment by ahmetb** [comment]
Anyone has opinions about this? tl;dr I think we should not have `BUILD` files in this repository, especially in `examples/*`

**Comment by caesarxuchao** [comment]
I think these BUILD files actually work if someone is use Bazel to build client-go. Since the kubernetes main repo is using bazel as its build system, so i think it's not a bad idea to enable bazel for client-go. It could use more documentation for sure.

**Comment by ahmetb** [comment]
@caesarxuchao do you anticipate people running `examples/` to use these BUILD files? I think they're just causing confusion. `examples/` is not being vendored by most people and does not compile as people do not take dependency on examples/... packages. So Bazel doesn't apply to examples I think.

**Comment by caesarxuchao** [comment]
Yeah, we can remove BUILD files from `examples/`. Not sure where/how to do it elegantly. It would be most reliable we can remove the BUILD files from kubernetes/staging/client-go/examples.

**Comment by ahmetb** [comment]
We can probably add a flag to https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/publish_scripts/publish_template.sh or https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/publish_scripts/publish_client_go.sh. 

I'm not familiar with these, I need to look into them to see if they directly take commits, or do any sort of `git commit`. If so, we might be able to delete BUILD files in `examples/` and amend the commit.

**Comment by caesarxuchao** [comment]
It's too risky to change the robot. The robot runs `git filter-branch` and `git cherry-pick` to pick up upstream changes, removing contents there might break the cherry-picks. Let's try to remove BUILD files from the source.

**Comment by ahmetb** [comment]
Understood. I am not familiar enough with Bazel to answer if we can remove these BUILD files directly on the kubernetes/kubernetes repo. Let's keep this issue open until we have a better answer.

**Comment by caesarxuchao** [comment]
Ok. I hope we can develop in client-go soon. The publishing process puts many restrictions on client-go.

**Comment by lavalamp** [comment]
Are the BUILD files causing any actual problem?

**Comment by ahmetb** [comment]
No, just confusion point for beginners.

**Comment by ash2k** [comment]
Please keep them. They are needed for those who use Bazel.

**Comment by ahmetb** [comment]
This is not a big dela.
/close
