### ISSUE TITLE
Support for parsing K8s yaml spec into client-go data structures

### ISSUE THREAD

**Issue by newtonkishore** [kubernetes/client-go#193]
Hi,

I am trying to create K8s cluster with spec coming from yaml files. I had to write Yaml equivalent of the same datastructures to convert the spec from yaml to go data structures to start the cluster.

 The Kubernetes/client-go data structures are tuned to Json Parsing, can we just add "`yaml:""` " support to client-go datastructures?

Or is there a better way to do this?

Thanks.

**Comment by ahmetb** [comment]
@newtonkishore consider converting from YAML to JSON and then unmarshaling into structs as the `json:""` field tags are there.

**Comment by ahmetb** [comment]
Or actually I'm not sure, I saw something in the issue description of #194 which looks like there's a universal decoder you can use.

**Comment by rmohr** [comment]
@newtonkishore you can use  `yaml.yaml.NewYAMLOrJSONDecoder(reader, buffSize)` from   `k8s.io/client-go/pkg/util/yaml`. You can pass in JSON or YAML, and it will use the `json:""` annotations for both formats.

**Comment by kenontech** [comment]
Follow up to this question, what is the right decoder to use if the type of the k8sStruct is not known before decoding?

**Comment by christianhuening** [comment]
`yaml.NewYAMLOrJSONDecoder()` etc. has been moved to `k8s.io/apimachinery/pkg/util/yaml`

**Comment by lavalamp** [comment]
Yes, there is already code laying around that does this and possibly a few
other necessary things. I'd be a bit surprised if it's not included in the
client library; if not, we can move it.

**Comment by christianhuening** [comment]
@kenontech @ahmetb @newtonkishore @rmohr Here's my solution (thanks to Stefan Schimanski for valuable hints!):

```golang
import (
	//...
	"k8s.io/client-go/pkg/api/v1"
	"k8s.io/client-go/pkg/apis/rbac/v1beta1"
	// make sure to import all client-go/pkg/api(s) you need to cover with your code
)

func someFunc() {
	// yamlFiles is an []string
	for _, f := range yamlFiles {

		decode := api.Codecs.UniversalDeserializer().Decode
		obj, groupVersionKind, err := decode([]byte(f), nil, nil)

		if err != nil {
			log.Fatal(fmt.Sprintf("Error while decoding YAML object. Err was: %s", err))
		}

		// now use switch over the typoe of the object
		// and match each type-case
		switch o := obj.(type) {
		case *v1.Pod:
			// o is a pod
		case *v1beta1.Role:
			// o is the actual role Object with all fields etc
		case *v1beta1.RoleBinding:
		case *v1beta1.ClusterRole:
		case *v1beta1.ClusterRoleBinding:
		case *v1.ServiceAccount:
		default:
			//o is unknown for us
		}
	}
}
```

**Comment by MofeLee** [comment]
@christianhuening 

![image](https://user-images.githubusercontent.com/5069410/32635653-cd7eaeb2-c576-11e7-9bac-b86cc724c79c.png)

![image](https://user-images.githubusercontent.com/5069410/32635545-5b54cf92-c576-11e7-91b2-9650571b333e.png)

Why my `client-go` doesn't have `api` inside `pkg` folder? 

I use `go get k8s.io/client-go/...` to get `client-go`

**Comment by lavalamp** [comment]
You are at a different version of the client, in which that code has moved
to the `k8s.io/api/...` package.

**Comment by Catorpilor** [comment]
I tried the following example:
```
package main

import (
    "log"

    "k8s.io/client-go/kubernetes/scheme"
)

var deployment = `
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: my-nginx
spec:
replicas: 2
template:
  metadata:
    labels:
      run: my-nginx
  spec:
    containers:
    - name: my-nginx
      image: nginx
      ports:
      - containerPort: 80
`

func main() {
    // decode := api.Codecs.UniversalDecoder().Decode
    decode := scheme.Codecs.UniversalDeserializer().Decode

    obj, _, err := decode([]byte(deployment), nil, nil)
    if err != nil {
        log.Fatal(err)
    }
}
```
On my late-2016 MacBook Pro laptop 
```
 go run main.go  25.58s user 3.65s system 285% cpu 10.221 total
```
Is there any efficient way?

**Comment by mhindery** [comment]
I am trying a similar thing and am completely lost. What packages are moved to where? I've read the `scheme.Codecs.*` are not supposed to be used anymore, and I have no clue what to import.

My goal is to read a yaml file with a list of rolebindings into a client-go structure, and there seem to be no possibility to do so, and no documentation at all. There are some SO questions, but none have an answer to how to work with multiple items in a list in a yaml file. e.g.:

https://stackoverflow.com/questions/44306554/how-to-deserialize-kubernetes-yaml-file.
https://stackoverflow.com/questions/47116811/client-go-parse-kubernetes-json-files-to-k8s-structures?noredirect=1&lq=1

**Comment by christianhuening** [comment]
@mhindery https://github.com/kubernetes/client-go/issues/193#issuecomment-343138889 doesn't work anymore?

**Comment by sttts** [comment]
The packages have changes. The codec to use is https://github.com/kubernetes/client-go/blob/master/kubernetes/scheme/register.go#L55. But otherwise, not much has changed.

**Comment by mhindery** [comment]
While I can read the file using the method above, I never get into the case in the switch with the correct type. Using this file

```go
package main

import (
	"fmt"

	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/client-go/kubernetes/scheme"
)

var filecontent = `
apiVersion: v1
kind: List
items:
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: myName
    labels:
      source: myLabel
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: User
    name: my@user.com
    apiGroup: rbac.authorization.k8s.io
`

func main() {
	decode := scheme.Codecs.UniversalDeserializer().Decode
	obj, _, _ := decode([]byte(filecontent), nil, nil)

	fmt.Printf("%++v\n\n", obj.GetObjectKind())
	fmt.Printf("%++v\n\n", obj)

	cbl := obj.(*rbacv1.ClusterRoleBindingList) // This fails
	fmt.Printf("%++v\n", cbl)

	switch o := obj.(type) {
	case *rbacv1.ClusterRoleBindingList:
		fmt.Println("correct found") // Never happens
	default:
		fmt.Println("default case")
		_ = o
	}
}
```

I get this output:


```
&TypeMeta{Kind:List,APIVersion:v1,}

&List{ListMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta{SelfLink:,ResourceVersion:,Continue:,},Items:[{[123 34 97 112 105 86 101 114 115 105 111 110 34 58 34 114 98 97 99 46 97 117 116 104 111 114 105 122 97 116 105 111 110 46 107 56 115 46 105 111 47 118 49 34 44 34 107 105 110 100 34 58 34 67 108 117 115 116 101 114 82 111 108 101 66 105 110 100 105 110 103 34 44 34 109 101 116 97 100 97 116 97 3458 123 34 108 97 98 101 108 115 34 58 123 34 115 111 117 114 99 101 34 58 34 109 121 76 97 98 101 108 34 125 44 34 110 97 109 101 34 58 34 109 121 78 97 109 101 34 125 44 34 114 111 108 101 82 101 102 3458 123 34 97 112 105 71 114 111 117 112 34 58 34 114 98 97 99 46 97 117 116 104 111 114 105 122 97 116 105 111 110 46 107 56 115 46 105 111 34 44 34 107 105 110 100 34 58 34 67 108 117 115 116 101 114 82111 108 101 34 44 34 110 97 109 101 34 58 34 99 108 117 115 116 101 114 45 97 100 109 105 110 34 125 44 34 115 117 98 106 101 99 116 115 34 58 91 123 34 97 112 105 71 114 111 117 112 34 58 34 114 98 97 99 46 97 117 116 104 111 114 105 122 97 116 105 111 110 46 107 56 115 46 105 111 34 44 34 107 105 110 100 34 58 34 85 115 101 114 34 44 34 110 97 109 101 34 58 34 109 121 64 117 115 101 114 46 99 111 109 34 125 93 125] <nil>}],}

panic: interface conversion: runtime.Object is *v1.List, not *v1.ClusterRoleBindingList
```

The object I end up with is of the type `runtime.Object` and I don't see anywhere how to convert this to my desired type (the ClusterRoleBindingList). From the printed output, I can see the object has the fields `items` / `typemeta` / `listmeta` somewhere in it, which the [ClusterRoleBindingList](https://godoc.org/k8s.io/api/rbac/v1#ClusterRoleBindingList) also defines, so the data seems to be in there. It's 'simply' the conversion between `runtime.Object` and my type that I'm missing.

In https://github.com/kubernetes/client-go/issues/193#issuecomment-343138889, you seem to immediately end up with the right types in the switch-case, while I have a generic one. I've looked at the linked scheme.Scheme.Conver() function, but that hasn't worked for me. What am I missing?

**Comment by christianhuening** [comment]
@mhindery As your error statets your `(...) runtime.Object is *v1.List, not *v1.ClusterRoleBindingList`, so I guess you should first switch case for v1.List and then look into the items of that list. 
I don't use that list type, but have a single file, where each entry is separated via `---`. 
Here's my parseK8sYaml(...):

```golang
func parseK8sYaml(fileR []byte) []runtime.Object {

	acceptedK8sTypes := regexp.MustCompile(`(Role|ClusterRole|RoleBinding|ClusterRoleBinding|ServiceAccount)`)
	fileAsString := string(fileR[:])
	sepYamlfiles := strings.Split(fileAsString, "---")
	retVal := make([]runtime.Object, 0, len(sepYamlfiles))
	for _, f := range sepYamlfiles {
		if f == "\n" || f == "" {
			// ignore empty cases
			continue
		}

		decode := scheme.Codecs.UniversalDeserializer().Decode
		obj, groupVersionKind, err := decode([]byte(f), nil, nil)

		if err != nil {
			log.Println(fmt.Sprintf("Error while decoding YAML object. Err was: %s", err))
			continue
		}

		if !acceptedK8sTypes.MatchString(groupVersionKind.Kind) {
			log.Printf("The custom-roles configMap contained K8s object types which are not supported! Skipping object with type: %s", groupVersionKind.Kind)
		} else {
			retVal = append(retVal, obj)
		}

	}
	return retVal
}
```

**Comment by huydinhle** [comment]
@christianhuening  Thanks for your solution. I am having a hard time to convert the runtime.Object to let's say something like v1.ConfigMap. Any suggestion?

**Comment by harryleesan** [comment]
I have a similar issue to @huydinhle, however, I am trying to convert `runtime.Object` to a `Deployment` using the following:

```yaml
package main

import (
  "fmt"

  "k8s.io/api/apps/v1beta1"
  "k8s.io/client-go/kubernetes/scheme"
)

var json = `
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": null,
  "name": "my-nginx",
  "replicas": 2,
  "spec": null,
  "template": {
    "metadata": {
      "labels": {
        "run": "my-nginx"
      }
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "my-nginx",
          "ports": [
            {
              "containerPort": 80
            }
          ]
        }
      ]
    }
  }
}
`

func main() {
	decode := scheme.Codecs.UniversalDeserializer().Decode

	obj, _, err := decode([]byte(json), nil, nil)
	if err != nil {
		fmt.Printf("%#v", err)
	}

	deployment := obj.(*v1beta1.Deployment)

	fmt.Printf("%#v\n", deployment)
}
```

I get this error:

```bash
panic: interface conversion: runtime.Object is *v1beta1.Deployment, not *v1beta1.Deployment
```

My `glide.yaml`:

```yaml
package: main
import:
- package: k8s.io/client-go
  version: v6.0.0
```

The error does not make sense to me since it seems like the type is the same. The conversion from `runtime.Object` to resources is not intuitive to me. Was anyone able to solve this?

**Comment by harryleesan** [comment]
I have managed to solve it... the deployment resource is of apiVersion `extensions/v1beta1` and I imported `k8s.io/api/apps/v1beta1`, once I changed it to `k8s.io/api/extensions/v1beta1` everything worked!

Here is the working code:

```go
package main

import (
  "fmt"

  "k8s.io/api/extensions/v1beta1"
  "k8s.io/client-go/kubernetes/scheme"
)

var json = `
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": null,
  "name": "my-nginx",
  "replicas": 2,
  "spec": null,
  "template": {
    "metadata": {
      "labels": {
        "run": "my-nginx"
      }
    },
    "spec": {
      "containers": [
        {
          "image": "nginx",
          "name": "my-nginx",
          "ports": [
            {
              "containerPort": 80
            }
          ]
        }
      ]
    }
  }
}
`

func main() {
	decode := scheme.Codecs.UniversalDeserializer().Decode

	obj, _, err := decode([]byte(json), nil, nil)
	if err != nil {
		fmt.Printf("%#v", err)
	}

	deployment := obj.(*v1beta1.Deployment)

	fmt.Printf("%#v\n", deployment)
}
```

**Comment by trobert2** [comment]
why does `scheme.Codecs.UniversalDeserializer().Decode` while fetching a kubernetes object from file return the proper `TypeMeta` and when fetching the object from the cluster (a config map in this case) using 
```
clientset, err := kubernetes.NewForConfig(config)
clientset.CoreV1().ConfigMaps(namespace).Get(name, metav1.GetOptions{})
```
the `TypeMeta` is empty.

```
  TypeMeta: {
-  Kind: "ConfigMap",
-  APIVersion: "v1",
+  Kind: "",
+  APIVersion: "",
  },
```
Tested on HEAD and version 6 of the `client-go`

If I add a print statement in the `func (r *Request) Do() Result ` function in: `k8s.io/client-go/rest/request.go` [here](https://github.com/kubernetes/client-go/blob/master/rest/request.go#L748)

like so: `fmt.Printf("%++v\n\n", string(result.body[:len(result.body)]))`

I can see the response from the server being: 
```
{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"test-map","namespace":"default","selfLink":"/api/v1/namespaces/default/configmaps/test-map","uid":"27ccefdc-463b-11e8-bd71-080027205854","resourceVersion":"1584679","creationTimestamp":"2018-04-22T14:40:51Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"game.properties\":\"enemies=aliens\\nlives=3\\nenemies.cheat=true\\nenemies.cheat.level=noGoodRotten\\nsecret.code.passphrase=UUDDLRLRBABAS\\nsecret.code.allowed=true\\nsecret.code.lives=30\\n\",\"ui.properties\":\"color.good=purple\\ncolor.bad=yellow\\nallow.textmode=true\\nhow.nice.to.look=fairlyNice\\n\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"name\":\"test-map\",\"namespace\":\"default\"}}\n"}},"data":{"game.properties":"enemies=aliens\nlives=3\nenemies.cheat=true\nenemies.cheat.level=noGoodRotten\nsecret.code.passphrase=UUDDLRLRBABAS\nsecret.code.allowed=true\nsecret.code.lives=30\n","ui.properties":"color.good=purple\ncolor.bad=yellow\nallow.textmode=true\nhow.nice.to.look=fairlyNice\n"}}
```

`kind` and `apiVersion` are there in the response. Is there something wrong with the Marshal/Unmarshal process? what's happening here?

**Comment by 27149chen** [comment]
Hi, I'm trying to covert a json to a crd struct in my unittest, using the decoder "scheme.Codecs.UniversalDeserializer().Decode". but got an error `no kind "*" is registered for version "*"`
Do I need to "register" it, and how?

**Comment by dionysius** [comment]
@27149chen 

This happened to me with my own CRD's, you'll need to add the scheme like:

```
//import
    myscheme "github.com/user/project/go/client/clientset/versioned/scheme"

//use AddToScheme before using the Decoder
    myscheme.AddToScheme(scheme.Scheme)
```

**Comment by integrii** [comment]
I used a nifty YAMLtoJSON package to get this working.

Check it out:

```go
// yamlBytes contains a []byte of my yaml job spec
// convert the yaml to json
jsonBytes, err := yaml.YAMLToJSON(yamlBytes)
if err != nil {
	return v1.Job{}, err
}
// unmarshal the json into the kube struct
var job = v1.Job{}
err = json.Unmarshal(jsonBytes, &job)
if err != nil {
	return v1.Job{}, err
}
// job now contains the YAML for the job!
```

**Comment by geekodour** [comment]
@dionysius @27149chen 
I am getting the error:
```
 no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1" in scheme "pkg/runtime/scheme.go:101"
usage: prombench gke resource apply
```

here the `Kind` is `CustomResourceDefinition` itself, should not it have been the name of the CRD?

**Comment by g0194776** [comment]
> For future reference, if you don't have have `k8s.io/client-go/pkg/api`, then:
> 
> ```
> import "k8s.io/client-go/kubernetes/scheme"
> scheme.Codecs.UniversalDeserializer()
> ```

thank you very much.

**Comment by Colstuwjx** [comment]
just like  @geekodour , I also met error:

```
&runtime.notRegisteredErr{schemeName:"k8s.io/client-go/kubernetes/scheme/register.go:61", gvk:schema.GroupVersionKind{Group:"apps", Version:"__internal", Kind:"Deployment"}, target:runtime.GroupVersioner(nil), t:reflect.Type(nil)}--- FAIL: TestCodecsManifests (0.00s)
panic: interface conversion: runtime.Object is nil, not *v1.Deployment [recovered]
	panic: interface conversion: runtime.Object is nil, not *v1.Deployment
```

deployment yaml definition is here:

```
var yml = `
apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-complex-app-my-complex-app
    labels:
    app: my-complex-app
    chart: my-complex-app-0.2.0
    release: my-complex-app
    heritage: Tiller
spec:
    replicas: 1
    template:
    metadata:
        labels:
        app: my-complex-app
        release: my-complex-app
    spec:
        containers:
        - name: my-complex-app
        image: "nginx:stable"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
        httpGet:
            path: /
            port: 80
        readinessProbe:
        httpGet:
            path: /
            port: 80
        resources: {}
`
```
BTW, use json format is okay for me, and yaml didn't work.

**Comment by DiveInto** [comment]
> @dionysius @27149chen
> I am getting the error:
> 
> ```
>  no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1" in scheme "pkg/runtime/scheme.go:101"
> usage: prombench gke resource apply
> ```
> 
> here the `Kind` is `CustomResourceDefinition` itself, should not it have been the name of the CRD?

@geekodour have you solved the problem?

I come to the same situation here, trying to parse CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongconsumers.configuration.konghq.com
spec:
  additionalPrinterColumns:
  ...
```

after addToScheme in init():

```go

import (
	...
	apiextv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
         ...
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	...
	// +kubebuilder:scaffold:imports
)

func init() {
	_ = clientgoscheme.AddToScheme(scheme)

	_ := apiextv1beta1.AddToScheme(scheme)
        ...
}
```

still see error like this:

> no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1" in scheme "pkg/runtime/scheme.go:101"

why is that?

**Comment by ciiiii** [comment]
@DiveInto 
> ```go
> import(
> 	apiextv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
> 	...
> 	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
> )
> 
> ...
> 
> sch := runtime.NewScheme()
> _ = clientgoscheme.AddToScheme(sch)
> _ = apiextv1beta1.AddToScheme(sch)
> 
> decode := serializer.NewCodecFactory(sch).UniversalDeserializer().Decode
> ```

Thank you, this method works!

**Comment by harsh-98** [comment]
It is really help for decoding CRDs or other resource from yaml.

**Comment by Abirdcfly** [comment]
but If my yaml is kubeconfig.(ns:kube-public cm:cluster-info).I have to use ("k8s.io/client-go/tools/clientcmd")clientcmd.Load.

yaml.NewYAMLOrJSONDecoder() etc will get me a error 

"error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field Config.clusters of type map[string]*api.Cluster"

why?  😭

**Comment by pmgexpo17** [comment]
Here is some code I found useful to discover the right GroupVersionKind for confirming the source package and formatting my yaml config correctly
`
import (

	"log"
	"os"
	"k8s.io/apimachinery/pkg/runtime"
	v1apps "k8s.io/api/apps/v1"
	v1core "k8s.io/api/core/v1")

	logg := log.New(os.Stdout, "INFO: ", log.Lshortfile)
	logg.SetOutput(os.Stdout)
	scheme := runtime.NewScheme()
	_ = v1apps.AddToScheme(scheme)
	_ = v1core.AddToScheme(scheme)
	logg.Printf("Printing All known types for schemes app/v1 and core/v1\n")
	tmap := scheme.AllKnownTypes()
	for key, value := range tmap {
		logg.Printf("GroupVersionKind : %v, Type : %v\n",key,value)
	}
`

Output 
INFO: example.go:24: GroupVersionKind : /v1, Kind=ConfigMap, Type : v1.ConfigMap
INFO: example.go:24: GroupVersionKind : apps/v1, Kind=Deployment, Type : v1.Deployment

In configMap.yaml the apiVersion must = v1
In deployment.yaml the apiVersion must = app/v1 
Otherwise decoding will fail

`

	decode := serializer.NewCodecFactory(scheme).UniversalDeserializer().Decode
	stream, ferr := ioutils.ReadFile(filename)
	if ferr != nil {
		log.Fatal(ferr)
	}
	obj, groupKindVersion, err := decode(stream, nil, nil)
	switch groupKindVersion.Kind {
	case "Deployment": ...
`

**Comment by thobianchi** [comment]
if stream contains a custom resource this line:
`obj, groupKindVersion, err := decode(stream, nil, nil)`
will fail with `error: no kind "X" is registered for version "G/V" in scheme "pkg/runtime/scheme.go:100"`
using `scheme.Codecs.UniversalDecoder().Decode`.

Is possible to create a decoder for every resource known to an actual k8s Cluster with a discovery client? 
methods like `k8s.io/client-go/discovery.GroupVersionResources()` seems oriented in the right direction but I can't find the way to go.

**Comment by dionysius** [comment]
@thobianchi 

I think you're missing to load the scheme for your CRD. Something like:

```
scheme := runtime.NewScheme()
_ = v1apps.AddToScheme(scheme)
```
where `v1apps` should be the package of your CRD

**Comment by thobianchi** [comment]
I am decoding some yaml that can be everything, like kubectl does lauching apply.

**Comment by dionysius** [comment]
I think kubectl apply does no magic, basically just sending the json. And the API server knows everything possible since you had to explicitly register the CRDs.

**Comment by TheApeMachine** [comment]
I guess I kept it simple...

```
import (
    "os"
    "k8s.io/kubectl/pkg/cmd"
)

func deploy() {
    os.Args = []string{
        "kubectl",
        "apply",
        "-f",
        "./cmd/manifests/",
    }

    cmd.NewDefaultKubectlCommand().Execute()
```

It is essentially the same way I integrated kind (kubernetes in docker), containerd, and istio into my project. I went down that path once, using `gopkg.in/yaml.v2` which can unmarshal yaml onto a struct, which I did not write manually, but pulled from their respective packages. Still needed a lot of code, and was generally a very frustrating experience. It's probably much better to just use the dynamic example in the client-go repo, but I wasn't sure whether or not that was only for deployments, or all other kinds too.

**Comment by lavalamp** [comment]
1. Make sure you use the k8s library for yaml parsing: https://pkg.go.dev/sigs.k8s.io/yaml
2. Consider using the SSA client instead of shelling out to kubectl apply: https://kubernetes.io/blog/2021/08/06/server-side-apply-ga/#server-side-apply-support-in-client-go

**Comment by TheApeMachine** [comment]
Yeah, this looks cool, thanks for that :)

**Comment by Arsen-Uulu** [comment]
Does anyone know how to decode a series of documents from a single YAML file? 

I have namespace then stateful set with `---` delimter

**Comment by astingengo** [comment]
@DiveInto 
I'm ussing this
```
	sch := runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(sch)
	_ = apiextv1beta1.AddToScheme(sch)

	decode := serializer.NewCodecFactory(sch).UniversalDeserializer().Decode

	obj, _, err := decode(yamlFile, nil, nil)
	if err != nil {
		fmt.Println(err)
	}
	err = createObject(clientset, *config, obj)
	if err != nil {
		fmt.Println(err)
	}
```
but still I'm seeing this error 
```no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1" in scheme "pkg/runtime/scheme.go:100"
```
I'm I doing something wrong?

**Comment by astingengo** [comment]
@Arsen-Uulu 
This is what I did
```
utilyaml "k8s.io/apimachinery/pkg/util/yaml"


yamlFile, err := ioutil.ReadFile("multi.yaml")
if err != nil {
    log.Printf("yamlFile.Get err   #%v ", err)
}

multidocReader := utilyaml.NewYAMLReader(bufio.NewReader(bytes.NewReader(yamlFile)))

for {
    buf, err := multidocReader.Read()
    if err != nil {
        if err == io.EOF {
            break
        }
        panic(err)
    }

    obj, _, err := decode(buf, nil, nil)
    if err != nil {
        panic(err)
    }
    ...
}
```

**Comment by astingengo** [comment]
How to import a custom kind that was created on the fly with a crds?
E.g. How to deploy Elasticsearch with this approach as I ended up having the same issue but now as:
```
panic: no kind "Elasticsearch" is registered for version "elasticsearch.k8s.elastic.co/v1" in scheme "pkg/runtime/scheme.go:100"
``` 
after sucessfully deployed crds and operator

**Comment by Subhajit97** [comment]
Can we get the line number while parsing K8s yaml spec into client-go data structures?

**Comment by lavalamp** [comment]
May I suggest y'all ask in slack or something? This issue is from 2017 and it's not a place where many people are going to be expecting questions

> `no kind "Elasticsearch" is registered for version "elasticsearch.k8s.elastic.co/v1" in scheme "pkg/runtime/scheme.go:100"`

The solution to this is to register the type with the scheme...

> Can we get the line number while parsing K8s yaml spec into client-go data structures?

All the mechanisms I'm aware of have no way of getting a line number like that at the place where they hit an error

**Comment by christianhuening** [comment]
I find it amusing this pops up every so often over the past 6 years. Yet I wonder: would it make sense to document this some place?

**Comment by jmazzitelli** [comment]
> I find it amusing this pops up every so often over the past 6 years. Yet I wonder: would it make sense to document this some place?

You know what would make more sense and will make all of this go away? The types just need to add `yaml` struct tags next to the already-existing `json` tags. I don't understand why that hasn't been done in all the years this keeps coming up. It's so simple.
