### ISSUE TITLE
(&rest.Request{}).Stream() segfaults

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/client-go#196]
The code below segfaults. It would be more convenient to return an error instead. This happens on version 2.0.0 and 3.0.0-beta.0.

```
package main

import (
	"k8s.io/client-go/rest"
)

func main() {
	req := &rest.Request{}
	req.Stream()
}
```

**Comment by ericchiang** [comment]
Request has an initializer.[1] Why aren't you using that?

Lots of go structs exhibit similar behavior. For example the following program panics:

```
package main

import "regexp"

func main() {
	(&regexp.Regexp{}).MatchString("")
}
```

[1] https://godoc.org/k8s.io/client-go/rest#NewRequest

**Comment by andrejvanderzee** [comment]
I want to write a unit test for PodExpansion interface using FakePods. In client-go/kubernetes/typed/core/v1/fake/fake_pod_expansion.go the following code returns `&rest.Request{}`

```
func (c *FakePods) GetLogs(name string, opts *v1.PodLogOptions) *rest.Request {
        action := testing.GenericActionImpl{}
        action.Verb = "get"
        action.Namespace = c.ns
        action.Resource = podsResource
        action.Subresource = "logs"
        action.Value = opts

        _, _ = c.Fake.Invokes(action, &v1.Pod{})
        return &rest.Request{}
}
```
This obviously results in a segfault as soon as my code calls `Stream()`.

**Comment by ericchiang** [comment]
Ah, that's a different issue then.

Hmm, with a fake client, Stream isn't going to give you anything and I don't see a way to set the Request error without making an HTTP call. Does restructuring your test to take an io.ReadCloser work? I wouldn't see client-go adding setters for the error specifically for testing.

**Comment by andrejvanderzee** [comment]
Unless you see another way, it looks like that I have to write my own version of FakePods with its own GetLogs() that returns my own fake.Request{}.

**Comment by novas0x2a** [comment]
@andrejvanderzee did you end up implementing anything for this? I've run into the same issue you did, and (I think) come to the same conclusion you did above; I was hoping to use whatever you came up with :D
