### ISSUE TITLE
segmentation violation code when I run it for minikube (works fine for real kubernetes clusters)

### ISSUE THREAD

**Issue by medyagh** [kubernetes/client-go#197]
When I run this code for a real kubernetes cluster it works fine,  but when I run it for minkube context I get this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x126204b]
```

To make sure it is not related to kuberentes version, I made my minikube to start with same version as my kuberentes (1.5.1)

here are my kubectl version
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```
Here is part of the code that throws error:
```
	pods, err := Clientset.CoreV1().Pods(lib.Cfg.Namespace).List(v1.ListOptions{})
	if err != nil {
		lib.Log.Error("error:", err)
		panic(err.Error())
	}
```

and here is how I can get my kubeconfig and clientset

```
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	configOverrides := &clientcmd.ConfigOverrides{}
	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
	config, err := kubeConfig.ClientConfig()
	if err != nil {
		return kubernetes.Clientset{}, errors.New("Failed loading client config")
	}
	clientset, err := kubernetes.NewForConfig(config)

```

another information that might be useful, I run my code in a docker container and I mount the .kube/config to the container (which works for real clusters but not for minikube)

**Comment by iordaniordanov** [comment]
I'm experiencing the same issue with Pods("").List()
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x819f98]
```

I'm using a config for remote cluster. The problem occurs only for List(at least this what I've found). Getting a certain Pod info works fine.
The interesting thing is that right at the beginning the code was working fine(copy paste from examples/out-of-cluster). Now List just refuses to run.

**Comment by owenhaynes** [comment]
Getting this with secrets as well.

**Comment by ericchiang** [comment]
@owenhaynes your panic looks like https://github.com/golang/go/issues/20501

@iordaniordanov and @medyagh please including the full stack trace of the program when it panics and the version of transitive dependencies (e.g. what version is golang.org/x/net?). Just posting the top level error isn't enough. All nil pointer panic look the same and the stack trace is the actually actionable thing.

**Comment by owenhaynes** [comment]
@ericchiang cheers for that reverting x/net worked. Never thought to look at x/net

**Comment by iordaniordanov** [comment]
@ericchiang, sry for that. Will compare my trace with [golang/go#20501](https://github.com/golang/go/issues/20501) and will provide an update tomorrow

**Comment by iordaniordanov** [comment]
@ericchiang, my trace is like the one mentioned in [golang/go#20501](https://github.com/golang/go/issues/20501)

**Comment by iordaniordanov** [comment]
Sorry, but how should I fix the issue for myself?

**Comment by ericchiang** [comment]
@iordaniordanov you need to update your vendored copy of golang.org/x/net/http2. Please see the instructions in INSTALL.md https://github.com/kubernetes/client-go/blob/master/INSTALL.md

Particularly the glide instructions tell you how to pin to a vendored version that client-go doesn't request, though by the look of it, no tagged versions of client-go actually request the broken golang.org/x/net/http versions.

**Comment by caesarxuchao** [comment]
Thanks for the solution! I'm closing the issue.
