### ISSUE TITLE
Secret Get() function return the secret data after decode?

### ISSUE THREAD

**Issue by yadzhang** [kubernetes/client-go#198]
I created a secret, with data password:123456, username:hello, after base64 encode, they are stored in k8s like below,
```
apiVersion: v1
data:
  password: MTIzNDU2
  username: aGVsbG8=
kind: Secret
metadata:
  creationTimestamp: 2017-05-23T08:00:26Z
  name: test-secret
  namespace: default
  resourceVersion: "1731624"
  selfLink: /api/v1/namespaces/default/secrets/test-secret
  uid: e197a5b0-3f8d-11e7-b5ab-0800278fe974
type: Opaque
```
But when I want to get secret like below:
```
res, err:= k8sClient.Core().Secrets("default").Get("test-secret")
fmt.Println(string(res.Data["username"]))
```
The result is Data["username"] is "hello" not "aGVsbG8", It is very strange. I want to get the data after base64 encoded, not clear text. I make some test, and feel it is because 
```
err = c.client.Get().
           Namespace(c.ns).
	   Resource("secrets").
           Name(name).
           Do().
          Into(result)
```
`Into` func make a translation when writing byte stream into struct Secret. 
Is it a bug or just should be like that? My client-go is version 1.4, and version 3.0 is also.

**Comment by ericchiang** [comment]
> The result is Data["username"] is "hello" not "aGVsbG8", It is very strange.

Data is a `map[string][]byte` so this is expected. If you want the base64'd data, you'll need to encode it yourself.

The reason it shows up in the API as base64'd at all is because that's how Go marshal's `[]byte` fields for JSON. If you use protobuf, for example, there's no base64'ing.

It seems like this can be closed.

**Comment by yadzhang** [comment]
Got it. Thank you for answer, I will encode myself.
