### ISSUE TITLE
how can i make customer controller watch for events forever?

### ISSUE THREAD

**Issue by debianmaster** [kubernetes/client-go#199]
In this example, a custom controller is created but it exits after listing the tpr's
https://github.com/kubernetes/client-go/blob/master/examples/third-party-resources/main.go

how can make this run forever watching for updates on TPR's?

**Comment by caesarxuchao** [comment]
The controller will continue to run if you don't call the canclefunc: https://github.com/kubernetes/client-go/blob/master/examples/third-party-resources/main.go#L80

**Comment by debianmaster** [comment]
@caesarxuchao   thanks for that tip !!!  :)

**Comment by debianmaster** [comment]
controller is exiting even if i dont call `cancelFunc`  any other workarounds?

**Comment by debianmaster** [comment]
found it!    tried removed `go run` from   `go run controller.Run(ctx)`
