### ISSUE TITLE
vendor directory

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/client-go#2]
I'm so stoked to see this client pulled out from the main repo. Thank you so much!

Okay, so it'd be nice for this repository to not vendor its dependencies. I think it may have happened accidentally since the Godeps directory next to it is blank.

There's been a rough consensus so far that vendoring dependencies is great for OSS binaries but that for OSS libraries they tend to hurt more than they help. This is because a number of Go libraries set globals and fiddle bits in other libraries and the collisions that occur when two (or more) versions of the library interact can be difficult to suss out or even identify.

And since the Godeps directory is blank, even if I was a supremely disciplined engineer that inspect all of my dependencies' dependencies' versions, that would be difficult to do.

But maybe this battle was fought some time ago. Would love to get a link that discussion!

**Comment by ghodss** [comment]
I agree with this. We have many projects that would benefit from having a kube client and having the vendor libs potentially conflict is a non-trivial barrier.

It would also be a good forcing function for both minimizing external dependencies for the client and keeping those libs up-to-date in the main kube repo.

**Comment by caesarxuchao** [comment]
Godeps.json is checked in now. There are more discussions [here](https://github.com/kubernetes/kubernetes/pull/31644#issuecomment-243986996).

Temporary solutions for dependency management: https://github.com/kubernetes/client-go/blob/master/README.md#dependency-management.

We are starting to analyze and minimize the vendor directory. Helps are appreciated!

**Comment by peterbourgon** [comment]
@caesarxuchao At the moment, libraries in Go _cannot_ vendor their dependencies. The solution here is to _remove_, not merely _minimize_, the vendor directory. This is not an optimization but rather an issue of correctness. Is there a way I can help accomplish this goal?

**Comment by caesarxuchao** [comment]
@peterbourgon thanks. It would be great if you can submit PRs to the main repository (https://github.com/kubernetes/kubernetes) to decouple the clients from these vendored dependencies. I guess many dependencies can be removed easily.

**Comment by lavalamp** [comment]
We hate the vendored libraries too, however we're not actually confident that it will even work with head from all the dependencies.

**Comment by lavalamp** [comment]
@krousey is working on removing some dependencies.

**Comment by lavalamp** [comment]
Basically, if we delete the vendor directory, then it will be extremely difficult for people to identify the set of dependencies that is tested and known working.

If we leave the vendor directory there, then people can easily delete it if they want to take their chances with HEAD from everything.

**Comment by seh** [comment]
I found yesterday that I can't use _client-go_ together with my own vendored [_github.com/spf13/pflag_ ](https://github.com/spf13/pflag) package, falling prey to the problem exemplified in [this _golang-broken-vendor_ repository](https://github.com/mattfarina/golang-broken-vendor), without using Glide's `--strip-vendor` option.

**Comment by lavalamp** [comment]
Is there a place you would have seen our documentation? (we mention this in
the README)

**Comment by seh** [comment]
First I'd have to notice that the the _README.md_ file exits, and actually _read_ it. I just did that, and I see that you do indeed mention this problem.

It would be helpful to address those using tools other than _godep_, such as Glide, but then in fairness it's not your responsibility to cover every possible tool under the sun.

**Comment by lavalamp** [comment]
The readme is displayed by github if you visit the client repo-- I guess I
was expecting most people to do that. If you don't mind saying, how did you
find the client repo? maybe there's another place we could have documented
this.

And yeah, sorry, we don't have experience with glide--we'd happily accept a
PR that adds a glide section to the README, though :)

On Thu, Sep 29, 2016 at 10:17 AM, Steven E. Harris <notifications@github.com

**Comment by seh** [comment]
I was being cheeky there; me not reading the _README.md_ was my own laziness, not a problem with it being difficult to find.

I came upon this repository by way of watching issue kubernetes/kubernetes#28559 and PR kubernetes/kubernetes#29147 passively. One day I told _gb_ to update my Kubernetes dependencies, with some trepidation, and I found that some things had moved around. When I used GitHub to search for a few identifiers, I noticed that it found them in more than one place, including within the _client-go_ repository. I got excited and started porting my code over by trial and error: search GitHub, replace imports in my code, compile, note errors, and repeat. Never did I stop and consider the new repository as a new _thing_ from the outside in, where I would have encountered the _README.md_ file right away.

As for the documentation PR, once I'm sure that I have Glide working together, I will consider contributing the advice.

**Comment by lavalamp** [comment]
Thanks, that's good to know. Please feel free to file issues if we can make
your life easier. :)

On Thu, Sep 29, 2016 at 10:42 AM, Steven E. Harris <notifications@github.com

**Comment by timoreimann** [comment]
Is https://github.com/kubernetes/kubernetes/pull/32208 possibly helping with removing the dependency on pflag in client-go?

**Comment by lavalamp** [comment]
It doesn't look like that will actually remove the dependency.

**Comment by caesarxuchao** [comment]
It still imports pflag.

**Comment by peterbourgon** [comment]
The state of the world hasn't changed; libraries still _cannot_ vendor dependencies.

/remove-lifecycle stale
