### ISSUE TITLE
README.md points to examples which do not exist

### ISSUE THREAD

**Issue by xh3b4sd** [kubernetes/client-go#20]
[The README.md](https://github.com/kubernetes/client-go/blob/75399f68c88d27167979821ac280936cfb13cfd6/README.md#how-to-use-it) points to examples which do not exist. I did also not find any example in the repository. Can somebody point me to examples? 

<img width="978" alt="screen shot 2016-10-21 at 11 19 47" src="https://cloud.githubusercontent.com/assets/552769/19593324/636d50a2-9780-11e6-897b-9cbe87b105e6.png">

**Comment by tyrannasaurusbanks** [comment]
I was looking at them last night but you're right I can't find them anymore.

Here's a link to what I believe are the same examples cached in a different project:
https://github.com/timoreimann/kubernetes-goclient-example/tree/master/vendor/k8s.io/client-go/examples

**Comment by timoreimann** [comment]
Apparently, they got removed through commit c72e2838b9cfac95603049d57c9abba12e587fff. 

You can also find them in that commit's parent commit: https://github.com/kubernetes/client-go/tree/c72e2838b9cfac95603049d57c9abba12e587fff/examples

**Comment by caesarxuchao** [comment]
Eh, I need to fix the "Kubernetes Publisher" robot. Thanks for reporting this!

**Comment by caesarxuchao** [comment]
Examples are back. Close.
