### ISSUE TITLE
CachedDiscoveryInterface has no implementations

### ISSUE THREAD

**Issue by ash2k** [kubernetes/client-go#200]
I'm trying to use `RESTMapper` interface and to get an instance of it I'm trying to construct a `DeferredDiscoveryRESTMapper` using the constructor `NewDeferredDiscoveryRESTMapper()`. That constructor function wants `CachedDiscoveryInterface` but there are no implementations available in client-go repository.
The only implementation is `CachedDiscoveryClient` in kubectl.
I guess this is a feature request to add an implementation? Or how should I proceed?

p.s. I'll write a dummy impl for now to work this issue around.

**Comment by caesarxuchao** [comment]
Last time i checked the implementation is in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go

I think we should move it client-go. 

@lavalamp has a PR open adding a memcached version to the garbagecollector recently. https://github.com/kubernetes/kubernetes/pull/46000/files#diff-b68696d4dae421f9f156a677c77c4880R18
