### ISSUE TITLE
Is there a client-go version compatible with kubernetes 1.2 api?

### ISSUE THREAD

**Issue by lth2015** [kubernetes/client-go#201]
I want to use client-go to rewrite my k8s client api, but our team is using kubernetes 1.2 version in product environment, how can I do?

Thank you very much!

**Comment by nikhita** [comment]
@lth2015 No, sadly there is not client-go version compatible with Kubernetes 1.2.

Please see https://github.com/kubernetes/client-go#compatibility-matrix for versions that are compatible.

Side note: client-go 3.0 and below are deprecated so please consider using Kubernetes 1.7 and above, if possible. :)

**Comment by nikhita** [comment]
Closing. Please reopen if you still face any issues.

/close
