### ISSUE TITLE
Versioned helpers (pkg/api/v1/helpers) are missing 

### ISSUE THREAD

**Issue by wongma7** [kubernetes/client-go#202]
pkg/api/v1/helpers.go was removed but pkg/api/v1/helpers/helpers.go was not added in its place. I noticed in staging/copy.sh the line `mkcp "pkg/api/helper" "pkg/api"` was explicitly added: https://github.com/kubernetes/kubernetes/pull/44361/files#diff-79c7edfbbe6b22642e05ac8c9cd431e7. Why did it need to be added and do we need to add  `mkcp "pkg/api/v1/helper" "pkg/api/v1"`too?

https://github.com/kubernetes/kubernetes/pull/44361
https://github.com/kubernetes/client-go/commit/bb2e2ad83cfeab769ec660af19256ba6b0f2c6ef

**Comment by caesarxuchao** [comment]
It's intentional. The entire pkg/api and pkg/apis will be gone after https://github.com/kubernetes/kubernetes/pull/44784. After that, we will selectively introduce back the helpers, but in a more appropriate directory.

**Comment by ericchiang** [comment]
Closing, since it looks like this issue is resolved.
