### ISSUE TITLE
client-go hasn't been synced for more than a week

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/client-go#203]
The publishing robot has bugs.

I'm tracking the fix under https://github.com/kubernetes/test-infra/issues/2847, because the robot code is in the test-infra repo. I'll spend more time on the bot after the code freeze.

**Comment by feiskyer** [comment]
Any updates on this? Met a problem of vendoring kubernetes packages, which depends on updates on client-go.

**Comment by caesarxuchao** [comment]
Just merged the fix. Will start the robot today.

**Comment by nikhita** [comment]
I think this can be closed now. :)

**Comment by feiskyer** [comment]
I think so.

/close
