### ISSUE TITLE
API for remote command execution

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/client-go#204]
In shell, you can use:
- `kubectl port-forward` to send requests to a pod's endpoint
- `kubectl exec` to execute commands in a pod

However, these are not obvious, easy to achieve in client API.
It would be great to provide easy to use API for such functionality.

**Comment by TamalSaha** [comment]
I was also looking for this. It seems to me that this support has been added only very recently https://github.com/kubernetes/client-go/tree/master/tools/remotecommand

**Comment by TimBozeman** [comment]
Do you know how to use remotecommand?

I tried to cannibalize this implementation 
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/6a00fe8b7999a2b6bb34698c30db93665def55ff/executors/kubernetes/exec.go
, but can't seem to get it going. I keep getting a "Timeout occured".

**Comment by wefine** [comment]
Hi, @TimBozeman 

Do you know how to use remotecommand now?

**Comment by tamalsaha** [comment]
@wefine , here are some example using client-go 5.x (master)

**port-forward:**
https://github.com/appscode/swift/blob/27d961dc386eef482127338d8000b3439085fb50/pkg/factory/tunnel.go#L41

**exec**:
https://github.com/appscode/searchlight/blob/22632646424bdd34c98bdaec87553fd182a85945/plugins/check_pod_exec/lib.go#L62

**Comment by TimBozeman** [comment]
That's pretty much what I'm doing. 
`//ExecCommand executes arbitrary command inside the pod
// https://github.com/zalando-incubator/postgres-operator/blob/master/pkg/cluster/exec.go
package main

import (
	"bytes"
	"fmt"

	remotecommandconsts "k8s.io/apimachinery/pkg/util/remotecommand"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/pkg/api/v1"
	"k8s.io/client-go/tools/remotecommand"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)
// Executes a command against a specific container (first one in the pod).
func ExecCommand(clientset kubernetes.Clientset, config rest.Config, pod v1.Pod, namespace string, command []string) (string, error) {
	var (
		execOut bytes.Buffer
		execErr bytes.Buffer
	)

	req := clientset.CoreV1Client.RESTClient().Post().
		Resource("pods").
		Name(pod.Name).
		Namespace(namespace).
		SubResource("exec")
	req.VersionedParams(&v1.PodExecOptions{
		Container: pod.Spec.Containers[0].Name,
		Command:   command,
		Stdout:    true,
		Stderr:    true,
	}, scheme.ParameterCodec)

	exec, err := remotecommand.NewExecutor(&config, "POST", req.URL())
	if err != nil {
		return "", fmt.Errorf("failed to init executor: %v", err)
	}

	err = exec.Stream(remotecommand.StreamOptions{
		SupportedProtocols: remotecommandconsts.SupportedStreamingProtocols,
		Stdout:             &execOut,
		Stderr:             &execErr,
	})

	if err != nil {
		return "", fmt.Errorf("could not execute: %v", err)
	}

	if execErr.Len() > 0 {
		return "", fmt.Errorf("stderr: %v", execErr.String())
	}

	return execOut.String(), nil
}`

**Comment by davecramer** [comment]
the command will timeout if there is no response to stdout or stderr

**Comment by slinkydeveloper** [comment]
:+1: I think we need an API to simplify access to this functionality, I wish to contribute. Someone can point me where I can start? :smile:
