### ISSUE TITLE
how to build client-go

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/client-go#205]
I am a newbie to Go. I cloned the client-go repo. Now what should I type into my shell to make this thing compile?

Actually I want to try to compile client-go into a shared C library as explained here:
https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf

But for that of course I first need to understand how to build it the normal way.

**Comment by lavalamp** [comment]
The client is normally statically linked and not built separately (although
you can build the examples).

If you just cloned the repo, you will need to set up your GOPATH before the
import paths will work.

I do not recommend doing the thing you are trying to do, though. Our
library is full of interfaces and objects to make it convenient to build
requests for go users. A consequence of this is that you will be writing
vast amounts of boilerplate function signature code if you want to use it
from C.
