### ISSUE TITLE
release client-go as a shared C library

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/client-go#206]
This article describes that it is possible to compile Go code as a shared C library:
https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf

If it were possible to build and release client-go this way, then it should be possible to easily use it from all kinds of languages.

**Comment by lavalamp** [comment]
Our current plan is to generate native clients in various languages. This solution would be very awkward at best--I would rather spend effort executing our main plan.

**Comment by thkoch2001** [comment]
More info on the plan to generate native clients:
https://github.com/kubernetes/kubernetes/issues/22405
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/csi-new-client-library-procedure.md
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/csi-client-structure-proposal.md
https://github.com/kubernetes-client
