### ISSUE TITLE
Some packages are missining in k8s.io/client-go/

### ISSUE THREAD

**Issue by zhangtbj** [kubernetes/client-go#207]
Hi,

I am using k8s client-go and I imported some of them:
"k8s.io/client-go/pkg/api/errors"
"k8s.io/client-go/pkg/api/resource"
"k8s.io/client-go/pkg/api/unversioned"
"k8s.io/client-go/pkg/runtime"

But I found they are missing now:

https://github.com/kubernetes/client-go/tree/master/pkg/api

Can you tell me where are they and why they are missed?

If possible, is there any solution that I can use them again?

Thanks!

**Comment by lavalamp** [comment]
Those look like the ones moved to k8s.io/apimachinery.
