### ISSUE TITLE
Client should wait before retrying PATCH/PUT/POSTs in case of http 429 from server

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/client-go#222]
We figured recently while running 4000-node cluster tests that the apiserver was saturated with requests and returning 429s, but clients were still sending requests.
In particular, kubelets and NPDs on the nodes were trying to continually retry PATCH/PUT requests on failures (leading to thousands of qps of 429s), even though they're designed to send updates once every one minute. So this is most likely an issue with client-go.

Following from discussion in https://github.com/kubernetes/node-problem-detector/issues/124

cc @Random-Liu @gmarek @kubernetes/sig-scalability-misc

**Comment by shyamjvs** [comment]
cc @yujuhong

**Comment by shyamjvs** [comment]
We don't want to enter the risky state of being stuck with 429s eventually.

**Comment by lavalamp** [comment]
Do the clients not have a configured rate limit?

Yes, we should make clients respect the server's request if they aren't
right now.

**Comment by yujuhong** [comment]
> Do the clients not have a configured rate limit?

The client had a rate limit, and I believe the QPS was still within the limit. Maybe the problem is that the limit needs to be even lower for the cluster of this scale?


BTW, I was wrong in the initial issue. The rest client [does not retry non-GET requests](https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.1/staging/src/k8s.io/client-go/rest/request.go#L831). I am not sure what's causing the high number of retries on 429 (both NPD's and kubelet's retry loop have large interval).

**Comment by caesarxuchao** [comment]
As i understand, this is not a release blocker, but we need to fix it.

**Comment by caesarxuchao** [comment]
@gmarek do you know if this comment is still true? 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/client.go#L138-L139
```
// readExpBackoffConfig handles the internal logic of determining what the
// backoff policy is.  By default if no information is available, NoBackoff.
// TODO Generalize this see #17727 .
func readExpBackoffConfig() BackoffManager {
```

The env vars were empty on my 1.6.4 gke node.

**Comment by caesarxuchao** [comment]
As Yuju mentioned, the client is only going to retry if `net.IsConnectionReset(err) && r.verb == "GET"`. If the serve returns 429, the client will in total sleep for 
1. the amount of time demanded by the server, plus 
2. the exponential backoff as recorded by the backoff manager. Though by default the backoff manager is empty, so it's 0.

Anyway, i think client is following apiserver's demand, so there is no bug on the client side.

**Comment by Random-Liu** [comment]
> Anyway, i think client is following apiserver's demand, so there is no bug on the client side.

Shouldn't we configure the backoff manager?

**Comment by caesarxuchao** [comment]
IMO the backoff manager is a safety net. APIserver should specify longer duration of retry-after if its load is heavy.

Maybe we should configure the backoff manager, @gmarek do you know what number we should use to initialize the backoff manager?

**Comment by yujuhong** [comment]
> IMO the backoff manager is a safety net. APIserver should specify longer duration of retry-after if its load is heavy.

I remember I also checked this yesterday. Of course there is always a TODO in the code: https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.1/staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go#L33

**Comment by gmarek** [comment]
@caesarxuchao - this is very good question, which probably has very complex answer as: it depends. It's fine to backoff quite some time for Status updates (with the exception of NodeStatus which serves as a heartbeat), but we probably don't want to backoff too much for Spec updates. This should be figured out by @kubernetes/sig-api-machinery-bugs (@smarterclayton ?). For now can we put there something that's non-zero? E.g. 5ms?

(Disclaimer: I don't think I did anything around backoff mgr:)

**Comment by lavalamp** [comment]
IMO folks making requests should understand what their requests are doing
and whether it makes sense to use the backoff manager. I am not comfortable
enabling it by default without thinking a lot more about it.

There is another potential problem that should be considered, which is: is
the client opening a new connection each time or does it reuse an existing
one? The latter is much more efficient. We have a really common bug where
people fail to read the entire contents of the response body, which causes
the go library to not reuse the socket. Is it possible that is happening in
this case?

**Comment by caesarxuchao** [comment]
> We have a really common bug where people fail to read the entire contents of the response body,

Looks like it's taken care of: https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.1/staging/src/k8s.io/client-go/rest/request.go#L846-L848

**Comment by yujuhong** [comment]
> IMO folks making requests should understand what their requests are doing
> and whether it makes sense to use the backoff manager. I am not comfortable
> enabling it by default without thinking a lot more about it.

The backoff manager settings are not exposed through the REST client config...it gets these from the environment variables. They are also not configurable based on the type of requests. If we can make this more useful, perhaps we can remove kubelet's own retry loop.

Given that the client retries up to 10 times (not configurable), I think we should lower the number of retries for node status update in kubelet. There is no point trying to send the same status for a prolonged period time when kubelet can instead sending a new update (every 10s).

**Comment by caesarxuchao** [comment]
Exponential backoff manager is introduced in https://github.com/kubernetes/kubernetes/pull/17529. Sorry @gmarek i confused it with the throttler, which i believed was introduced by you ;)

@jayunit100 do you know why we used env var rather than a config to initialize the backoff manager?

I suggest that we do these:

1. add backoffManager to RESTClient and rest#Config
2. deprecate [readExpBackoffConfig](https://github.com/kubernetes/kubernetes/blob/f18a921a0308c4ecd2e7e8b7e30e39a8216a3447/staging/src/k8s.io/client-go/rest/client.go#L138-L141) after 2 releases.
3. move [maxRetries](https://github.com/kubernetes/kubernetes/blob/f18a921a0308c4ecd2e7e8b7e30e39a8216a3447/staging/src/k8s.io/client-go/rest/request.go#L801) to backoffManager

**Comment by shyamjvs** [comment]
Linking issue https://github.com/kubernetes/kubernetes/issues/47344 for tracking.
