### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by drigz** [kubernetes/client-go#224]
The two example links here are broken: https://github.com/kubernetes/client-go#how-to-use-it

I tried to fix it but this project doesn't accept PRs and I couldn't easily find the relevant file in the kubernetes repo.

**Comment by nikhita** [comment]
Fix in https://github.com/kubernetes/client-go/pull/219.

@drigz Thanks for the issue! Btw for README and other doc changes, PRs can be opened in this repo. All other code changes go in `kubernetes/kubernetes/staging/src/k8s.io/client-go`.
