### ISSUE TITLE
Watch method should implement an heartbeat keepalive

### ISSUE THREAD

**Issue by bjhaid** [kubernetes/client-go#227]
The watch methods should implement an heartbeat keep-alive to ensure the tcp connection isn't severed in environments with aggressive tcp idle timeouts, this will also help fast fail a watch to a dead apiserver.

**Comment by lavalamp** [comment]
1. This is not a client request.
2. We'd almost certainly use TCP keepalives and not modify the watch
protocol.

**Comment by bjhaid** [comment]
@lavalamp 

> 1. This is not a client request.

where should I be posting this request, on the main kubernetes repo, should this be sent to sig-api-machinery? 

> 2. We'd almost certainly use TCP keepalives and not modify the watch
protocol.

That's fair, I'll bring this up wherever I should be sending it correctly to

**Comment by lavalamp** [comment]
Yeah, I think the main kubernetes repo is the place to file this, thanks.
I'm slightly surprised that we don't already turn that on?

**Comment by bjhaid** [comment]
thanks
