### ISSUE TITLE
Allow setting the KeyFunc on SharedInformers

### ISSUE THREAD

**Issue by rmohr** [kubernetes/client-go#229]
I would want to replace the `DeletionHandlingMetaNamespaceKeyFunc` with my own UUID based key function in the `SharedIndexInformer`. It seem like right now, I would have to copy the whole shared informer into my code-base, to be able to replace it:

```golang
// NewSharedIndexInformer creates a new instance for the listwatcher.
func NewSharedIndexInformer(lw ListerWatcher, objType runtime.Object, defaultEventHandlerResyncPeriod time.Duration, indexers Indexers) SharedIndexInformer {
	realClock := &clock.RealClock{}
	sharedIndexInformer := &sharedIndexInformer{
		processor:                       &sharedProcessor{clock: realClock},
		indexer:                         NewIndexer(DeletionHandlingMetaNamespaceKeyFunc, indexers),
		listerWatcher:                   lw,
		objectType:                      objType,
		resyncCheckPeriod:               defaultEventHandlerResyncPeriod,
		defaultEventHandlerResyncPeriod: defaultEventHandlerResyncPeriod,
		cacheMutationDetector:           NewCacheMutationDetector(fmt.Sprintf("%T", objType)),
		clock: realClock,
	}
	return sharedIndexInformer
}
```
My use-case is the following: While in the cluster, I care about the namespace/name identity, on the node where my daemon sits, I am more interested in the change of UUIDs. If a resource on the apiserver is force-deleted and immediately recreated, I want to see the delete of the object with the old UUID and the creation of the new object. 

While  it is pretty easy to live with that, and do explicit uuid checks in the sync loop of the controller, it does not fit so well to the node-nature of things, where only the UUID matters and in my case namespaces don't have any meaning.

Having a function which allows me to set the `KeyFunc`  on the `SharedIndexerInformer` would already be sufficent for me.

Does that sound useful in general?

**Comment by deads2k** [comment]
> Having a function which allows me to set the KeyFunc on the SharedIndexerInformer would already be sufficent for me.
> 
> Does that sound useful in general?

Since that would change the contract on the lister's `Get` functions, I don't think we'd want to do it in general.  In order to support the "normal" `Get` semantics you'd have to create a secondary index on name then find the "best" one to return.  I don't think that's a path we want to pursue.

**Comment by rmohr** [comment]
@deads2k thanks for your fast feedback.

Could you point me to the relevant code, where this is a problem? I had a look on the `GenericLister` interface, and it only says that it takes an argument `name` which is equal to the `key`. To look up the object, the genericLister uses the indexer, which I could supply the correct KeyFunction. If i don't misunderstand something, it is in the responsibility of the controller to provide the right key ... Am I looking at the right spots?

**Comment by lavalamp** [comment]
I can't speak to the sharing layer, but the underlying reflector / informer libraries were originally intended to allow the key function to be replaceable.

UID in particular is not a first-class citizen in our API--that problem is bigger that just this client-side support.

**Comment by rmohr** [comment]
You know  what, while switching the KeyFunc would make the detection of force deletes much more straight forward, it adds the same amount of complexity on another place. I would still have to synchronise the delete and the creation based on the name. That would mean, detecting in the controller if a resource with that name already exists. That is not simpler at all.

Closing this, as it does not really help. Thanks :+1:
