### ISSUE TITLE
Clarification on Object/GetObjectKind

### ISSUE THREAD

**Issue by keitwb** [kubernetes/client-go#230]
I'm trying to write some integration tests for an app that uses this client and I'm struggling to figure out how to create objects that implement the `Object` interface.  

https://github.com/kubernetes/client-go/blob/v2.0.0/kubernetes/typed/core/v1/pod.go#L79 passes in a `"pkg/api/v1".Pod` to the REST client request `Body` method, and then the Body method [appears to assert that it is a `runtime.Object`](https://github.com/kubernetes/client-go/blob/v2.0.0/rest/request.go#L549).  But `v1.Pod` doesn't implement `GetObjectKind`, as my compiler is telling me when I try and use it as an Object.  How can you pass it to a client request as such?  I am somewhat new to Go so perhaps I am just ignorant of some feature of Go that allows this, but what am I missing?

I'm using the v2.0.0 release.

**Comment by lavalamp** [comment]
TypeMeta does implement the interface. It is an inlined field, causing the
thing it is inlined in to also implement the interface.

But you must take its address first: &v1.Pod{ ... }

**Comment by keitwb** [comment]
Thank you! The address was what I was missing.
