### ISSUE TITLE
k8s 1.7 corresponding release of client-go

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/client-go#231]
k8s 1.7 is released.
When is client-go doing a release to match that?

**Comment by ericchiang** [comment]
cc @caesarxuchao who had some thoughts on this.

**Comment by caesarxuchao** [comment]
Because the pkg/api pkg/apis are all removed (for good), so we have breaking changes again, so it will be client-go release-4.0. I'll set it up.

It's insane to bump the major version every quarter. I'll open another issue discussing how to enabling API tests and integration tests for client-go, and eventually decouple the release from kubernetes.

**Comment by lavalamp** [comment]
Why is it bad to increment the major version?

**Comment by caesarxuchao** [comment]
We do now back-port new API groups or new features like leader election across major releases. Users who want to use these features need to upgrade, their life will be easier if we don't bump the major version often.

**Comment by tamalsaha** [comment]
> We do now back-port new API groups or new features like leader election across major releases. 

Do you mind elaborating on that? We write operators for Kubernetes. Dealing with breaking changes with every release of Kubernetes is a major headache for us.

**Comment by joshwget** [comment]
> Because the pkg/api pkg/apis are all removed (for good), so we have breaking changes again, so it will be client-go release-4.0. I'll set it up.

Isn't this code imported in various places in 1.7? For those looking for a client-go release to use when importing code from Kubernetes 1.7 this wouldn't work.

**Comment by caesarxuchao** [comment]
@joshwget sorry, i took that back. pkg/api and pkg/apis are still there in kubernetes/release-1.7, so they will be in the client-go branch that tracks kubernetes/release-1.7.

**Comment by joshwget** [comment]
Awesome, thanks for confirming that.

**Comment by lavalamp** [comment]
> Users who want to use these features need to upgrade, their life will be easier if we don't bump the major version often.

I just want to point out that users who want new features and also don't want to upgrade want a logically impossible thing. ;)

**Comment by caesarxuchao** [comment]
I created the [release-4.0 branch](https://github.com/kubernetes/client-go/commits/release-4.0). Now i need to manually fill out the CHANGELOG, then release the v4.0.0.

**Comment by caesarxuchao** [comment]
I made the [v4.0.0-beta.0 tag](https://github.com/kubernetes/client-go/releases/tag/v4.0.0-beta.0). I'll gvie the beta.0 one week time to soak and create v4.0.0 tag next week.

**Comment by svInfra17** [comment]
@caesarxuchao , is v4.0.0-beta.0 ready for v4.0.0 ?

**Comment by nikhita** [comment]
This is fixed now and the README and CHANGELOG are updated.

Closing.
/close
