### ISSUE TITLE
Compile fails due to apimachinery change

### ISSUE THREAD

**Issue by astropuffin** [kubernetes/client-go#232]
Now that client-go is using apimachinery (which I wholeheartedly appreciate), upstream changes can break compile. The current compile failure was caused by this commit:
https://github.com/kubernetes/apimachinery/commit/6c263f33a6b401d0718c5c5774b5f7ab8daa8488#diff-fb24371e396c1f62cf28521fd747ffa1

client-go depends on those deleted functions in a number of places:
pkg/apis/authentication/v1/defaults.go:24
pkg/apis/authorization/v1/defaults.go:24
pkg/apis/authentication/v1beta1/defaults.go
pkg/apis/authorization/v1beta1/defaults.go:24
pkg/apis/certificates/v1beta1/defaults.go:23
pkg/api/defaults.go:26
pkg/apis/rbac/v1beta1/defaults.go:25
pkg/apis/rbac/v1alpha1/defaults.go:25

**Comment by lavalamp** [comment]
Please double check that you have vendored the right version of your
dependencies.

A given client-go branch/commit will likely only be compatible with the
dependency versions that are in its Godeps.json.

Eventually we will have better version compatibility stories for repos like
apimachinery but the paint is still wet.

**Comment by folago** [comment]
I am seeing the same problem. 

[[constraint]]
  name = "k8s.io/client-go"
  version="4.0.0-beta.0"

[[constraint]]
  revision="abe34e4f5b4413c282a83011892cbeea5b32223b"
  name = "k8s.io/apimachinery"

Results in:

$ go build
# github.com/folago/nird-lb/vendor/k8s.io/api/core/v1
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:897: in.ObjectMeta.DeepCopyInto undefined (type v1.ObjectMeta has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1013: in.ObjectMeta.DeepCopyInto undefined (type v1.ObjectMeta has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1079: in.ObjectMeta.DeepCopyInto undefined (type v1.ObjectMeta has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1440: in.StartedAt.DeepCopyInto undefined (type v1.Time has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1457: in.StartedAt.DeepCopyInto undefined (type v1.Time has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1458: in.FinishedAt.DeepCopyInto undefined (type v1.Time has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1788: in.ObjectMeta.DeepCopyInto undefined (type v1.ObjectMeta has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1967: in.ObjectMeta.DeepCopyInto undefined (type v1.ObjectMeta has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1970: in.FirstTimestamp.DeepCopyInto undefined (type v1.Time has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1971: in.LastTimestamp.DeepCopyInto undefined (type v1.Time has no field or method DeepCopyInto)
vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:1971: too many errors


Should some file be regenerated?
Is this documented somewhere and i missed it?

**Comment by fatih** [comment]
@folago were you able to resolve your issue?

**Comment by folago** [comment]
No, but the head revisions of client-go and apimachinery worked so I pinned those with dep.

**Comment by jinankjain** [comment]
@folago Could you tell me which head revision fixed the issue?

**Comment by madgrape** [comment]
- package: k8s.io/client-go
  version: 1850dd66e4213a26bd70d0b85fee4176d324b845
- package: k8s.io/api
  version: e532fdb5587debfd7aade56dabe9eb5df9544baf
- package: k8s.io/apimachinery
  version: a13245d02534abe88286859b547d041816f9a3f4
- package: k8s.io/apiextensions-apiserver
  version: 6d8c23d2e66ce61e2a7e34f92e8eb3eec13279fa

this works.
hope this can be fixed asap in release version.

**Comment by jonstacks** [comment]
I had a similar issue and was able to get my code to compile by locking down the following versions using dep to what was in the [Godeps.json](https://github.com/kubernetes/client-go/blob/v3.0.0/Godeps/Godeps.json) for tag v3.0.0:

```toml
[[constraint]]
  name = "k8s.io/client-go"
  version = "3.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "85ace5365f33b16fc735c866a12e3c765b9700f2"
```

**Comment by pratikmallya** [comment]
I'm unable to get this to work with any of the pins mentioned in this comment :(.

**Comment by jinankjain** [comment]
@pratikmallya May be this helps?

```
- package: k8s.io/apimachinery
  version: 12d70001ef0c75fc5a26057ca73d3caf5e2cf682
- package: k8s.io/api
- package: k8s.io/client-go
  version: 45673e060eb921b510677b1123737ad1158e49fa
```

**Comment by pratikmallya** [comment]
@jinankjain unfortunately, that doesn't seem to work either. I get a lot of errors like:
`[ERROR]	Error scanning k8s.io/client-go/util/retry: open /Users/mallya/.glide/cache/src/https-k8s.io-client-go/util/retry: no such file or directory`

**Comment by jinankjain** [comment]
Just remove your glide cache or update it rm -rf ~/.glide/

**Comment by pratikmallya** [comment]
@jinankjain that's the first thing I tried. Those errors are present even after removing the folder (and running `glide cc`).

**Comment by ianvernon** [comment]
I am hitting similar issues, except I need to be using `k8s.io/kubernetes` `1.8.0-beta.1`. Keep getting issues like the following when using the following:
* k8s.io/client-go
** c6f8cf2c47d21d55fa0df928291b2580544886c8
* k8s.io/apimachinery
** 1168e538ea3ccf444854d1fdd5681d2d876680a7
* k8s.io/api
** 0b011bb8613011ab0909c6a759d9d811dc21a156
* k8s.io/apiextensions-apiserver
** 2bfb07d318ed549813240d1165fcebad6250c666
* k8s.io/kubernetes
** ~1.8.0-beta.1

**Comment by paralin** [comment]
This stuff is so stupidly difficult to get set up at the moment.... I can't even find a set of versions that compile any more, even with my old Gopkg.toml

**Comment by ianvernon** [comment]
I have the following versions working for compilation:
```
k8s.io/apiextensions-apiserver 8b0133f28359c1325bd4799207a34fd935367ba2
k8s.io/apimachinery b63e1e4b3f7d0681e9a6e15bd4729d3014049e4e
k8s.io/client-go 2554b0b4622d739c8af9da548e8fe2223176803c
k8s.io/kubernetes v1.8.0-beta.1
k8s.io/api a9acc2b601dbe3c7d3782209b99f09b2232bd15a
k8s.io/kube-openapi 80f07ef71bb4f781233c65aa8d0369e4ecafab87
```

**Comment by pratikmallya** [comment]
@ianvernon this doesn't seem to work either. Specifically, glide can't seem to fetch all the dependencies

**Comment by paralin** [comment]
I finally just resorted to using Godeps. Here is my FULL godeps.json (most deps are probably unnecessary): https://gist.github.com/paralin/4e88551a6099d83bf46c20f8f45d973a

**Comment by ianvernon** [comment]
@pratikmallya while I admire what glide tries to do, I think it tries to automate too much of the dependency process and can result in a state that is very hard to debug / fix if something goes wrong. I find [vndr](https://github.com/LK4D4/vndr) to be pretty good for this:

**Comment by xh3b4sd** [comment]
For your interest, when using glide, this works for me. 

```
- package: k8s.io/client-go
  version: v4.0.0
- package: k8s.io/apiextensions-apiserver
  version: release-1.7
- package: k8s.io/apimachinery
  version: release-1.7
```

**Comment by ash2k** [comment]
Works fine with `dep` too: https://github.com/atlassian/smith/blob/master/Gopkg.toml
