### ISSUE TITLE
No documentation about the new home for pkg/api(s)

### ISSUE THREAD

**Issue by kensimon** [kubernetes/client-go#238]
Everything from `pkg/apis` and `pkg/api` are completely gone as of Jun 22nd when https://github.com/kubernetes/kubernetes/commit/ffe74d1fe749b5887711f70af24e1375856f2520 was synced in.

It appears that the new home for all the api calls are in https://github.com/kubernetes/api.

All the existing issues that talk about how broken things are (#232 #226) have been replied to with "well you should be installing from tags", but I think there's more at stake here: those packages seem to be altogether deprecated from this repo, with no mention of that fact in any of the documentation.

Could we get something in the readme or otherwise that documents what's going on here?

**Comment by caesarxuchao** [comment]
I'll update the CHANGELOG.
