### ISSUE TITLE
panic in cache: interface {} is *v1.Service, not *api.Service

### ISSUE THREAD

**Issue by grobie** [kubernetes/client-go#24]
Using the `StoreToServiceLister` in master (f11d57f) leads to panics due to an unmet type assertion in the `List` function.

```
func (s *StoreToServiceLister) List(selector labels.Selector) (ret []*api.Service, err error) {
    err = ListAll(s.Indexer, selector, func(m interface{}) {
        ret = append(ret, m.(*api.Service))
    })
    return ret, err
}
```

**Comment by caesarxuchao** [comment]
Thanks for reporting the bug. https://github.com/kubernetes/kubernetes/pull/35639 will solve the problem. The listers you used will be deprecated. Probably the fix will be ported to client-go next week.

**Comment by caesarxuchao** [comment]
This is fixed in master. Closing.
