### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by IanLewis** [kubernetes/client-go#242]
For the following code I get an error when trying to connect to a GKE API server with v3.0.0.

FWIW this worked in v3.0.0.beta.0

I have a version of apimachinery that's about 28 days old. Could it have to do with some library incompatibility?

```
F0712 12:20:52.391235   71066 main.go:73] Could not create Kubernetes ThirdPartyResource API client: No Auth Provider found for name "gcp"
```

```golang
package main

import (
	"flag"

	"github.com/golang/glog"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

type Thing struct {
	metav1.TypeMeta `json:",inline"`
	ObjectMeta      metav1.ObjectMeta `json:"metadata"`
}

// Required to satisfy ObjectMetaAccessor interface
func (m *Thing) GetObjectMeta() metav1.Object {
	return &m.ObjectMeta
}

type ThingList struct {
	metav1.TypeMeta `json:",inline"`
	ListMeta        metav1.ListMeta `json:"metadata"`
	Items           []Thing         `json:"items"`
}

// Required to satisfy ListMetaAccessor interface
func (m *ThingList) GetListMeta() metav1.List {
	return &m.ListMeta
}

func main() {
	kubeconfig := flag.String("kubeconfig", "", "The path to a kubeconfig. Default is in-cluster config.")

	flag.Parse()

	config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		glog.Exitf("Could not read kubeconfig %s: %v", *kubeconfig, err)
	}

	groupVersion := schema.GroupVersion{
		Group:   "ianlewis.org",
		Version: "v1alpha1",
	}

	config.GroupVersion = &groupVersion
	config.APIPath = "/apis"
	config.ContentType = runtime.ContentTypeJSON
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	schemeBuilder := runtime.NewSchemeBuilder(
		func(scheme *runtime.Scheme) error {
			scheme.AddKnownTypes(
				groupVersion,
				&Thing{},
				&ThingList{},
			)
			return nil
		},
	)
	schemeBuilder.AddToScheme(scheme.Scheme)

	_, err = rest.RESTClientFor(config)

	if err != nil {
		glog.Exitf("Could not create Kubernetes ThirdPartyResource API client: %v", err)
	}

	glog.Infof("OK")
}
```

**Comment by IanLewis** [comment]
```
$ go version
go version go1.8 darwin/amd64
```

**Comment by IanLewis** [comment]
It seems you need import the auth plugin package

```
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
// or
_ "k8s.io/client-go/plugin/pkg/client/auth"
```

Is this working as intended? Is there any benefit to not loading auth plugins by default?

**Comment by ericchiang** [comment]
> Is this working as intended? Is there any benefit to not loading auth plugins by default?

Yes and this is documented in a couple places. The benefit is not overloading regular clients with unnecessary imports. E.g you don't have to import OpenID Connect and Azure packages.

Going to close since it looks like this is working as intended.

**Comment by IanLewis** [comment]
@ericchiang Can you point me to where it's documented?
It wasn't here:
https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration
https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration

I just guessed based on reading the source code. It feels like that could be improved. Not that there are not really any "docs" to speak of yet.

While I understand the need to avoid importing packages that aren't needed I question the wisdom of this a bit. I can see folks creating apps and integrations that don't work w/ GKE/Azure/Openid because they don't import the plugins. It feels weird to drop this all of a sudden since it worked in v2.0.0 and v3.0.0.beta.0

**Comment by ericchiang** [comment]
@IanLewis a few of the examples have lines like this https://github.com/kubernetes/client-go/blob/53c7adfd0294caa142d961e1f780f74081d5b15f/examples/out-of-cluster-client-configuration/main.go#L31

The actual change was made here https://github.com/kubernetes/kubernetes/pull/41532 during the 1.6 release. Are you sure this changed between v3.0.0.beta.0 and v3.0.0? I'm not seeing them imported by default in v3.0.0.beta.0

https://github.com/kubernetes/client-go/blob/v3.0.0-beta.0/kubernetes/clientset.go
https://github.com/kubernetes/client-go/blob/v2.0.0/kubernetes/clientset.go#L35-Lundefined

I can add a changelog item for the v3.0.0.beta.0

**Comment by IanLewis** [comment]
@ericchiang I suppose you're right that it was removed between v2.0.0 and v3.0.0 but still the issue stands.

**Comment by IanLewis** [comment]
More folks noticing this on twitter: https://twitter.com/davecheney/status/915770572017037312

**Comment by G-Harmon** [comment]
FYI, I hit this error message, and the 2nd Google search result led me here. Glad this has the solution! 
As for where to document, perhaps somewhere near the docs for "gcloud container clusters get-credentials"?

**Comment by gregwebs** [comment]
I think the error error message could tell people what to do without them googling to firgure it out. e.g. append this:

```
suggestion: add this import: _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

**Comment by cguertin14** [comment]
This issue is happening in my `kubectl` client after upgrading `gcloud` to v299.0.0. Is it relathere a bug somewhere?

**Comment by vitaminmoo** [comment]
If you're here in >= 2025 you probably just need to `gcloud components install gke-gcloud-auth-plugin`.

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
