### ISSUE TITLE
How to watch DELETE events for any objects

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/client-go#244]
I am trying to write a Kubernetes tool that will perform some action when any Kubernetes object is deleted. Is there any way to watch for DELETE event for any objects instead of adding watcher for each one of them individually?

I understand this is all HTTP under the hood. So, this should be technically possible. My question is there any way to do that using client-go? If not, do you have any hints on how this can be done?

**Comment by lavalamp** [comment]
Watch the collection rather than individual objects.

**Comment by tamalsaha** [comment]
I am doing something like :
```
	lw := &cache.ListWatch{
		ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
			return c.KubeClient.ExtensionsV1beta1().Deployments(apiv1.NamespaceAll).List(metav1.ListOptions{})
		},
		WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
			return c.KubeClient.ExtensionsV1beta1().Deployments(apiv1.NamespaceAll).Watch(metav1.ListOptions{})
		},
	}
	_, ctrl := cache.NewInformer(lw,
		&extensions.Deployment{},
		c.SyncPeriod,
		cache.ResourceEventHandlerFuncs{
			DeleteFunc: func(obj interface{}) {
				if resource, ok := obj.(*extensions.Deployment); ok {
					log.Infof("Deployment %s@%s added", resource.Name, resource.Namespace)

				}
			},
		},
	)
```
"Watch the collection rather than individual objects." ? What do you mean by watch the collection?

**Comment by tamalsaha** [comment]
Thank you @lavalamp . It will be great to have some way to watch for "multiple resource types at the same time" , Then one does not have to know about the  the tprs etc registered in a  clustr ahead of time.

**Comment by lavalamp** [comment]
Funnily enough, that very thing is being fixed in the garbage collector as
we speak--you could take a look at that code.

We don't have any plans to add this feature to the API. Bulk watch is
coming, but even with that you will need to specify which resource types to
watch.

**Comment by tamalsaha** [comment]
Thanks, I am going to take  a look.

**Comment by ash2k** [comment]
@tamalsaha 
> Then one does not have to know about the the tprs etc registered in a clustr ahead of time.

But that is not necessary - setup an informer for TPRs/CRDs to be notified about additions/deletions of resource kinds. See https://github.com/atlassian/smith/blob/master/pkg/controller/controller_tpr_event_handler.go for an example. Not perfect, probably does not need to watch each version...

**Comment by gopinatht** [comment]
Guys, any update on bulk watch APIs?
