### ISSUE TITLE
Anyone can explain why delete so many go files under pkg/v1?

### ISSUE THREAD

**Issue by goupeng212** [kubernetes/client-go#249]
Here is the commit id :https://github.com/kubernetes/client-go/commit/d82cfb70ddc9faa25f41e39a8f73d7ccd20d7a55#diff-5c755714d0649f91c00269ed3d88e19c 
The author deleted so many go files, so our project failed to run . I know I don't complaint that too much. But that change is too too big!

**Comment by lavalamp** [comment]
Use vendoring to lock your dependencies. If you track head, things like this are going to happen to you. 

This particular change is even mentioned in the CHANGELOG: https://github.com/kubernetes/client-go/blob/master/CHANGELOG.md#head-changes-that-will-go-into-v5
