### ISSUE TITLE
1.4 subdirectory causes glide to fail

### ISSUE THREAD

**Issue by tnine** [kubernetes/client-go#25]
When using the following glide.yaml, glide is unable to update or install the client-go to the "1.4" subdirectory under the root.  

`
package: github.com/30x/postgres-k8s/cli
import:
- package: github.com/spf13/cobra
  vcs: git
- package: k8s.io/client-go
  version: v1.4.0
`

This causes the following error.

`
[ERROR]	Error scanning k8s.io/client-go/kubernetes: open /Users/apigee/.glide/cache/src/https-k8s.io-client-go/kubernetes: no such file or directory
[ERROR]	This error means the referenced package was not found.
[ERROR]	Missing file or directory errors usually occur when multiple packages
[ERROR]	share a common dependency and the first reference encountered by the scanner
[ERROR]	sets the version to one that does not contain a subpackage needed required
[ERROR]	by another package that uses the shared dependency. Try setting a
[ERROR]	version in your glide.yaml that works for all packages that share this
[ERROR]	dependency.
[ERROR]	Error scanning k8s.io/client-go/pkg/api: open /Users/apigee/.glide/cache/src/https-k8s.io-client-go/pkg/api: no such file or directory
[ERROR]	This error means the referenced package was not found.
[ERROR]	Missing file or directory errors usually occur when multiple packages
[ERROR]	share a common dependency and the first reference encountered by the scanner
[ERROR]	sets the version to one that does not contain a subpackage needed required
[ERROR]	by another package that uses the shared dependency. Try setting a
[ERROR]	version in your glide.yaml that works for all packages that share this
[ERROR]	dependency.
`

Is it possible to remove the 1.4 subdirectory on the tag?

**Comment by caesarxuchao** [comment]
That's a legacy issue. When we first started client-go, we used subdirectories for versioning (because we tried to support `go get`). Future versions won't have the subdirectories.

If I cut a v2.0.0-alpha.0, will that solve your problem? I think you were developing on master? The v1.4 has multiple problems.

**Comment by tnine** [comment]
That will probably help.  What I really need is a stable 1.4 client against a 1.4.x k8s sytem. 

I've been using it so far, and it's been great.  The only blocker I'm hitting is the lack of ability to run the remote commands, since this wrapper doesn't appear to exist in the client lib.

https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/remotecommand/remotecommand.go#L82

Ultimately I need to be able to execute remote commands in addition to creating replica sets, PV and query pod status.  If you can cut a v2.0.0-alpha.0, I'll give that a try.

**Comment by caesarxuchao** [comment]
The v2.0.0-alpha.0 will work with 1.4.x k8s system. The client-go version doesn't imply the compatibility with the k8s system, see https://github.com/kubernetes/client-go#compatibility-client-go---kubernetes-clusters.

**Comment by caesarxuchao** [comment]
Made an alpha release. https://github.com/kubernetes/client-go/tree/v2.0.0-alpha.0

**Comment by caesarxuchao** [comment]
Because it's an alpha release, we might make more breaking change to the release-2.0 branch.

**Comment by timoreimann** [comment]
@tnine if you remove your existing vendored copy of  client-go, tell glide to fetch the 1.4.0 tag, and update the import paths in your application code, things should work again.

FWIW, note that client-go 1.5 is compatible with Kubernetes 1.4 as well.

**Comment by caesarxuchao** [comment]
I assume the issue is resolved. Please reopen if you need more help.
