### ISSUE TITLE
Broken links for examples

### ISSUE THREAD

**Issue by alexellis** [kubernetes/client-go#251]
Hi - there are broken links for the examples - so I wanted to raise a PR, but got redirected. I thought an issue may be easier.

Patch details below:

https://github.com/kubernetes/client-go/compare/master...alexellis:patch-1

Regards,

Alex

**Comment by nikhita** [comment]
The links for examples have been fixed. I believe this can be closed now.

**Comment by alexellis** [comment]
Thanks @nikhita
