### ISSUE TITLE
Proposal: Remove informers from SharedInformerFactory

### ISSUE THREAD

**Issue by li-ang** [kubernetes/client-go#252]
SharedInformerFactory just only adds resource informers into itself, but can not remove. I think we could add `RemoveResource()` method into SharedInformerFactory interface for **removing resource informer**.

Please give me more advice.

THX!

**Comment by deads2k** [comment]
What is the use-case for removing one?

**Comment by li-ang** [comment]
@deads2k In v2.0.0 version without SharedInformerFactory, we can control every separate informer. Since v3.0.0-beta0 version, SharedInformerFactory can simplify the informer operation   for developers, but the developers

**Comment by li-ang** [comment]
@deads2k We just want to control every separate informer using SharedInformeFactory. Every informer can start and stop.

**Comment by deads2k** [comment]
> @deads2k We just want to control every separate informer using SharedInformeFactory. Every informer can start and stop.

We haven't found a use-case for a selective stop in kube, so I'm not very excited about plumbing one through without a clear use-case.
