### ISSUE TITLE
UniversalDecoder Broken with version client-go version 4.0.0

### ISSUE THREAD

**Issue by jinankjain** [kubernetes/client-go#253]
I was using this script to decode some yml files and when I bumped the version from 3.0.0 to 4.0.0. I get this error `no kind "Deployment" is registered for version "extensions/v1beta1"`

Could someone help me out with that one? @lavalamp 

``` go
package main

import (
	"fmt"
	_ "k8s.io/client-go/kubernetes"
	"k8s.io/client-go/pkg/api"
	apiv1 "k8s.io/client-go/pkg/api/v1"
	"log"
	"reflect"
)

const yaml = `
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: THISISBROKEN
  namespace: THISCANTBETRUE
`

func main() {

	d := api.Codecs.UniversalDecoder()
	obj, _, err := d.Decode([]byte(yaml), nil, nil)
	if err != nil {
		log.Fatalf("could not decode yaml: %s\n%s", yaml, err)
	}

	src := obj.(*api.Pod)
	dst := &apiv1.Pod{}
	err = api.Scheme.Convert(src, dst, 0)
	if err != nil {
		panic(err)
	}
	fmt.Println(reflect.TypeOf(*dst))
}
```

**Comment by hongchaodeng** [comment]
Yeah. We saw similar error in https://github.com/kubernetes/client-go/issues/255

**Comment by caesarxuchao** [comment]
A friendly reminder, try to get away from using client-go/pkg/api#Scheme or Codecs, the entire package is removed in master. You really shouldn't need api.Scheme or api.Codecs, they are only useful if you want to convert objects between the external version and the internal version, which is only useful to the apiserver.

Could you use client-go/kubernetes/scheme#Codecs instead? And you won't need to call `api.Scheme.Convert`, the output of `Decode()` should be extension/v1beta1#Deployment.

**Comment by jinankjain** [comment]
@caesarxuchao Thanks for the help I tried updating it with what you suggested and then I am no longer able to pass runtime.Object as nil as it complains that `invalid indirect of obj (type runtime.Object)`

```go
package main

import (
	"fmt"
	"k8s.io/client-go/kubernetes/scheme"
	"log"
	"reflect"
)

const yaml = `
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: THISISBROKEN
  namespace: THISCANTBETRUE
`

func main() {

	d := scheme.Codecs.UniversalDeserializer()
	obj, _, err := d.Decode([]byte(yaml), nil, nil)
	if err != nil {
		log.Fatalf("could not decode yaml: %s\n%s", yaml, err)
	}

	fmt.Println(reflect.TypeOf(*obj))
}
```

**Comment by jinankjain** [comment]
@caesarxuchao I think I got the problem it was with UniversalDecoder instead of that we should UniversalSerializer that works. Thanks for all the help. I didn't know about that `k8s.io/client-go/pkg/api` this being deprecated so all the packages which were imported way like v1 or /apps/v1beta will get deprecated too for external use?

**Comment by caesarxuchao** [comment]
Yes. The types are moved to k8s.io/api. k8s.io/kubernetes also import its types from k8s.io/api.

> it was with UniversalDecoder instead of that we should UniversalSerializer that works

Yes, I guess `scheme.Codecs.UniversalDecoder` still tries to convert objects to the internalversion and thus the error message. Using `UniversalSerializer` sounds the right solution.

I'm closing the issue, feel free to reopen if there is any remaining problem.
