### ISSUE TITLE
client-go v4.0.0-beta error with 'no kind is registered for the type v1.Endpoints'

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/client-go#255]
We use copy leader election from k8s and replace its client with client-go v4.0.0-beta . But after upgrading to v4, it is broken :

```
Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-operator", GenerateName:"", Namespace:"e2e-etcd-operator-flake-145", SelfLink:"/api/v1/namespaces/e2e-etcd-operator-flake-145/endpoints/etcd-operator", UID:"730424fb-71ef-11e7-9c2f-42010a800fc0", ResourceVersion:"467835", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:63636662689, nsec:0, loc:(*time.Location)(0x23a3f00)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"etcd-operator\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-07-26T10:44:49Z\",\"renewTime\":\"2017-07-26T10:44:49Z\",\"leaderTransitions\":0}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}'
due to: 'no kind is registered for the type v1.Endpoints'. Will not report event: 'Normal' 'LeaderElection' 'etcd-operator became leader'
```

**Comment by lavalamp** [comment]
You should not use the endpoint resource for leader election, it is very
resource intensive in large clusters.

I believe the client should include leader election code now, so you
shouldn't need your copy any more.

**Comment by hongchaodeng** [comment]
Yeah.
We would like to use that package. Waiting for the release though.
Meanwhile, it is probably not about leader election, but the resource kind registration error:
```
no kind is registered for the type v1.Endpoints
```
It seems the client-go v4 api.Scheme doesn't register the types there anymore.
I tried with client-go "master" and it worked though.

**Comment by caesarxuchao** [comment]
Try this [Scheme](https://github.com/kubernetes/client-go/blob/v4.0.0-beta.0/kubernetes/scheme/register.go#L46) instead? 

The entire client-go/pkg/api package is removed in HEAD, so try to get away from using it.

**Comment by caesarxuchao** [comment]
@hongchaodeng If we cut a v5.0.0-alpha.0 off the HEAD, will you be able to use that? The v5.0.0 stable release is 2 months away.

**Comment by hongchaodeng** [comment]
> The entire client-go/pkg/api package is removed in HEAD, so try to get away from using it.

OK. Thanks for the suggestion.

> If we cut a v5.0.0-alpha.0 off the HEAD, will you be able to use that? The v5.0.0 stable release is 2 months away.

I can wait for the stable release. If there are any new release that includes leader election packages, we would definitely like to try it and provide feedback.

**Comment by caesarxuchao** [comment]
Please reopen if this is not resolved.
