### ISSUE TITLE
Error using EventBroadcaster.StartRecordingToSink 

### ISSUE THREAD

**Issue by aledbf** [kubernetes/client-go#26]
I am converting a client to client-go and I see this error:

```
../../pkg/ingress/controller/controller.go:157: cannot use config.Client.Core().Events(config.Namespace) (type "k8s.io/client-go/kubernetes/typed/core/v1".EventInterface) as type record.EventSink in argument to eventBroadcaster.StartRecordingToSink:
	"k8s.io/client-go/kubernetes/typed/core/v1".EventInterface does not implement record.EventSink (wrong type for Patch method)
		have Patch(string, "k8s.io/client-go/pkg/api".PatchType, []byte, ...string) (*"k8s.io/client-go/pkg/api/v1".Event, error)
		want Patch(*"k8s.io/client-go/pkg/api/v1".Event, []byte) (*"k8s.io/client-go/pkg/api/v1".Event, error)
```

This is the code:
```
eventBroadcaster := record.NewBroadcaster()
eventBroadcaster.StartLogging(glog.Infof)
eventBroadcaster.StartRecordingToSink(config.Client.Core().Events(config.Namespace))
```

I'm doing something wrong or it's a bug?
Thanks!

**Edit:** same behavior in master or 1.5 branch

**Comment by caesarxuchao** [comment]
You can use the adapter [here](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/event_expansion.go#L148) to satisfy the interface.

**Comment by aledbf** [comment]
@caesarxuchao just one detail, the `EventImpl` struct methods have a pointer receiver (removing that it works).

**Comment by caesarxuchao** [comment]
Ah, it's me that supplied you with the wrong code! Sorry for that.

This should be solved, I'm closing the issue.
