### ISSUE TITLE
extensions.v1beta1 don't export NetworkPolicy

### ISSUE THREAD

**Issue by jgsqware** [kubernetes/client-go#260]
I have a Network Policy as this one:

```bash
kubectl describe networkpolicy allow-tcp-443
Name:		allow-tcp-443
Namespace:	default
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-tcp-443","namespace":"default"},"spec":{"ingress":...
```

With `go-client`, when I tried to retrieve it via: 

```go
c.Networking().NetworkPolicies(ns).List(metav1.ListOptions{})
```
I got error:

`the server could not find the requested resource`

the `apiVersion` is `extensions/v1beta1` but I don't find any method that allow retrieving NetworkPolicy for extensions/v1beta1

**Comment by jgsqware** [comment]
Fixed with 
```go
npl := &v1b1.NetworkPolicyList{}
	err := c.ExtensionsV1beta1().RESTClient().Get().
		Namespace(ns).
		Resource("networkpolicies").
		Do().
		Into(npl)
```

**Comment by caesarxuchao** [comment]
The workaround looks good.

`c.Networking().NetworkPolicies(ns).List` will work with  >=1.7 apiserver. 

It's a bug that older versions of client-go didn't contain extensions/v1beta1 network policies, but we decided not to fix because network policies had graduated to networking/v1 in 1.7.

**Comment by jgsqware** [comment]
Ok thanks!
