### ISSUE TITLE
Informers with fake clientset

### ISSUE THREAD

**Issue by tao-lu** [kubernetes/client-go#267]
My informer isn't calling its watch/list function routinely, nor is it calling its event handlers when the client which I've passed to it is updated. Is this expected?

I create a fake clientset, create a node informer with it, update nodes with that client set (I've confirmed that the changes are saved by `List`ing from the client directly. It seems that the problem is that the ListFunc is not being called despite the resyncPeriod being non-zero.

**Comment by ncdc** [comment]
@tao-lu could you please post your code? We have several examples in kubernetes/kubernetes using informers with a fake clientset. Hopefully if you can share your code, we can assist.

**Comment by tao-lu** [comment]
@ncdc I ultimately changed the way I relied on informers to bypass this issue. Unfortunately, I don't recall what the circumstances surrounding the initial post were and the commit is probably squashed. I'll just close this for now.
