### ISSUE TITLE
OIDC cache does not have chance to expire when issuer, clientID and clientSecret does not change

### ISSUE THREAD

**Issue by irisdingbj** [kubernetes/client-go#268]
In https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/oidc/oidc.go. newOIDCAuthProvider()

It will try to find the cached provider like below:

// Check cache for existing provider.
	if provider, ok := cache.getClient(issuer, clientID); ok {
		return provider, nil
	}

However, in some cases there might be no changes for the issuer, clientID and clientSecret. But we only changed the refresh-token or access-token. Since we use  (key := cacheKey{issuer, clientID, clientSecret}) as cached key in this case it will still use the old token.

I suggest we add some code logic to let user define whether we should expire the OIDC cache for the client:
       const   cfgExpired                  = "expired"
	expired = cfg[cfgExpired]
	if expired != "true" {
		// Check cache for existing provider.
		if provider, ok := cache.getClient(issuer, clientID, clientSecret); ok {
			return provider, nil
		}

	}

If you agree with this change, I will submit a PR for this. 

Looking forward to your feedback on this issue~ 

Thanks.

Iris Ding

**Comment by ericchiang** [comment]
Sorry, I'm confused what the issue you're reporting here. I understand how the code behaves, but what did you do where you hit this case? Why did this break something?

**Comment by irisdingbj** [comment]
Hi Eric,

Let me give an example here:

1. you have an OIDC provider defined as below:
auth-provider:
      config:
        client-id: abc
        client-secret: abc
        id-token: xxxxx.xxxxx.xxxxx.xxxx
        idp-issuer-url: https://xyz.com/oidc/token
        refresh-token: yyyyyyyyyyyyy
      name: oidc
2. Your provide this as part of your kubeconfig file and create a kube client using client-go: 
        config, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
        kubeClient, err1 := kclient.NewForConfig(config)

3. You kick off your program and let them list resources against your kubernetes server.

4. You id-token and refresh-token has been changed to new value but other part for OIDC provider remains unchanged in your kubeconfig:
  auth-provider:
      config:
        client-id: abc
        client-secret: abc
        id-token: newxxxx.newcccc.newdddd.newssssss
        idp-issuer-url: https://xyz.com/oidc/token
        refresh-token: zzzzzzzzzzz
      name: oidc
5. you do not stop your program and let it keep running. You will detect the changes in your kubeconfig and rebuild kubeclient automatically. 

In step5, alghough you have recreated your kubeclient, but the OIDC provider it used is still the old one since it will get from cache using the unchanged part: client-id, client-secret and idp-issue-url. So your new refreshed token will not take effect and you will get token expired error for your program.


SO based on above scenario,I think we should add the cache expire function for this part.


Thanks & Best Regards,

Iris Ding
