### ISSUE TITLE
Copy versioned listers to client-go

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/client-go#27]
**Problem**
client-go currently only has [listers](https://github.com/kubernetes/client-go/blob/master/tools/cache/listers.go#L320) for internal version object, but the clients provided by client-go use versioned objects (like v1.Pod).

**Solution**
We need to copy the [listers](https://github.com/kubernetes/kubernetes/tree/master/pkg/client/listers) from k8s to client-go.

**Temporary workaround**
For now, users can call the conversion functions translate between versioned and internal API, e.g., [this line](https://github.com/kubernetes/kubernetes/blob/v1.5.0-alpha.2/pkg/api/v1/zz_generated.conversion.go#L5917) (use nil for conversion.Scope).

**Comment by aledbf** [comment]
@caesarxuchao how I can help with this?

**Comment by caesarxuchao** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/41340
