### ISSUE TITLE
client-go v4.0.0 doesn't include CustomResourceDefinition types

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/client-go#280]
CustomResourceDefinition is introduced in 1.7 k8s, but it's not included in client-go v4.0.0.
Not sure if we can still say client-go v4.0.0 satisfies the compatible matrix as defined in:
https://github.com/kubernetes/client-go#compatibility-matrix

**Comment by frankgreco** [comment]
Related #247

**Comment by ericchiang** [comment]
Closing as dup of #247
