### ISSUE TITLE
Namespace flag seems to be ignored when the kubeconfig current context sets it

### ISSUE THREAD

**Issue by hausdorff** [kubernetes/client-go#288]
I will work on a simple reproduction if there's interest, but before I did, I wanted to socialize the general problem to make sure it's not actually the _desired semantics_.

We develop a project, [kubecfg](https://github.com/ksonnet/kubecfg), which is a Kubernetes client building on top of client-go v3.0.0. Our client-go [flag parsing logic](https://github.com/ksonnet/kubecfg/blob/7551f5de0ad4ced970b7481e4926cc4297df251c/cmd/root.go#L104) is essentially stolen wholesale directly from `kubectl` codebase.

So it is somewhat confusing to us that, under these circumstances, we find that the `--namespace` and `-n` flags are ignored when the current context in the kubeconfig file provides a namespace. We've verified this on 4 machines across 2 companies.

My question is: **is this desired behavior?**

If it is not, let me know, and we will provide a concise code sample that reproduces the issue.

If it is useful, we dug deep into this in [our issue 103](https://github.com/ksonnet/kubecfg/issues/103). The essential nature of the problem is that `DirectClientConfig#getContext` will call `mergo.Merge` with the overwrite flag set to `false`, which causes the overrides (such as the `-n` or `--namespace` flags) to NOT overwrite the current values if they are present. So, if the value is set in the kubeconfig file, they are NOT overwritten. This causes us to ignore the flag.

For posterity, I will quote the relevant parts of the issue"

> Here's what's going on. As I mentioned before, we create an `overrides := clientcmd.ConfigOverrides` to pass into `clientcmd.NewInteractiveDefferedLoadingClientConfig`. By making a package-level `var` we can use `fmt.Println` to verify that this `overrides.Context.Namespace` is set correctly by the `--namespace` flag just before we call `clientConfig.Namespace()` in `update.go`. So the data is there, the question at hand is: why is it not being reported correctly?
>
> * `overrides` is being passed into `NewInteractiveClientConfig` when our `init` routines call `createClientConfig`. A pointer to `overrides` is stored as a member inside it.
> * `clientConfig.Namespace()` is called in `update.go`. This would produce the namespace from the current client context, if we continued.
> * `clientConfig.Namespace()` calls `mergedKubeConfig := config.createClientConfig()`. This returns a `ClientConfig` (it's initialized once, so subsequent calls just return the already-initialized member).
> * `clientConfig.Namespace()` then calls `mergedKubeConfig.Namespace()`.
> * `mergedKubeConfig.Namespace()` calls `mergedKubeConfig.getContext()`. Here's where it gets interesting.
>   * `getContext` retrieves the current context from the client, and merges it with an empty context. This gives us a context identical to the currently default context in the kubeconfig file.
>   * Smoking gun: `getContext` then merges its context with the overrides using a call to `mergo.Merge` with the overwrite flag set to `false`. Thus, the `-n` flag override is ignored.

Finally, cc @anguslees, who has been my partner in crime on this issue.

**Comment by lavalamp** [comment]
That sounds like a bug, but a kubectl bug, not a client-go bug? @pwittrock

**Comment by ncdc** [comment]
@lavalamp it is a client-go bug since client-go contains all the config loading + override logic. I'm wondering if https://github.com/kubernetes/kubernetes/pull/46299 fixes the issue?

**Comment by lavalamp** [comment]
I see. That does look like it might fix it.

(that override code is really confusing :( )
