### ISSUE TITLE
Cannot find AddOrUpdateTaint function anymore after migrating from v3 to v4

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/client-go#290]
We recently upgraded a project from client-go v3.0.0 to v4.0.0. Previously, we used the [`AddOrUpdateTaint` function](https://github.com/kubernetes/client-go/blob/v3.0.0/pkg/api/v1/helpers.go#L524) to apply taints to nodes conveniently. Unfortunately, I wasn't able to find the function anymore after the upgrade to the newer client-go version.

Between v3 and v4, [this commit](https://github.com/kubernetes/client-go/commit/bb2e2ad83cfeab769ec660af19256ba6b0f2c6ef) was pushed to refactor the function-hosting `helpers.go` function into multiple files and move them into a new sub-package. `AddOrUpdateTaint` was removed there but apparently not re-added again. Interestingly, the [originating main repository commit](https://github.com/kubernetes/kubernetes/commit/d4850b6c2b3b367345ef944a12a778d860fdd0db#diff-4c2060e6a603f68c60831b6c578e5ad9R10) still included the function, though not in a sub-directory of `staging` (where the whole `helpers` sub-package seems to be missing).

Is `AddOrUpdateTaint` gone for good? If so, what's its designated replacement? Or is it still around and I just happen to miss it?

Thanks.

**Comment by ericchiang** [comment]
This was moved out of `api/v1/helpers` in https://github.com/kubernetes/kubernetes/pull/46514

It's a nice convenience but not particularly complicated to implement yourself. Is there some action you'd like to take to fix this or were you just wondering why it was moved?

**Comment by caesarxuchao** [comment]
@timoreimann we unified the API types used by client-go with those used by the main Kubernetes in last release, so that they can share the same utility functions, but we are short-handed at the moment to finish the moving.

**Comment by timoreimann** [comment]
@ericchiang @caesarxuchao as we continue to need the function, we vendored the copy from v3. That's okay for us, though I think it'd be nicer to reference something hosted by client-go. I could imagine upstream changing the implementation in the future which would then happen detached from our copy.

If you think that bringing back `AddOrUpdateTaint` into client-go is a worthwhile endeavor, I'd be happy to help (though I probably won't have bandwidth available immediately). Just let me know.

**Comment by caesarxuchao** [comment]
We want to move all k8s-specific utility functions to k8s.io/pkg. @mengqiy do you know if we have a proposal for that?

**Comment by mengqiy** [comment]
> We want to move all k8s-specific utility functions to k8s.io/pkg

I believe it will be more likely to be called `k8s.io/common`.
Proposal: https://github.com/kubernetes/kubernetes/issues/50475
I think that repo will be ready at the very beginning of Q4.

**Comment by timoreimann** [comment]
That looks like a bigger restructuring than what I expected -- still happy to help, though it might be easier to let you (upstream) finish the migration planning first.

Shall we keep this issue open to make sure we won't forget about `AddOrUpdateTaint`? Or will that happen automatically once `k8s.io/common` shapes itself up?

**Comment by caesarxuchao** [comment]
I expect all the helper functions that were in pkg/api/v1/helpers.go to be move to the new repos, so it will happen "automatically". Closing.
