### ISSUE TITLE
How to add context in the request?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/client-go#291]
I think add context in the request cloud help in tracing system as well as early cancel, is there a support for `golang.org/x/net/context` ?

**Comment by maleck13** [comment]
I believe this issue is related to what you are referring to https://github.com/kubernetes/kubernetes/issues/46503

**Comment by sttts** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/46503
/close
