### ISSUE TITLE
Does not build with bazel

### ISSUE THREAD

**Issue by justinsb** [kubernetes/client-go#292]
Having trouble getting the recommended v4.0.0 tag working with bazel:

* apimachinery requires @io_kubernetes_build, I grabbed this from the kubernetes/kubernetes WORKSAPCE

* Then hit `.../external/io_k8s_apimachinery/pkg/util/sets/BUILD:25:1: no such package '@io_k8s_apimachinery//hack/boilerplate': BUILD file not found on package path and referenced by '@io_k8s_apimachinery//pkg/util/sets:set-gen'`

Do we have any test coverage of bazel builds?  This would both serve as an example and assurance that the code builds...

**Comment by ash2k** [comment]
I have reported it here https://github.com/kubernetes/kubernetes/issues/50975
