### ISSUE TITLE
dep init fails with "No versions of k8s.io/apimachinery met constraints"

### ISSUE THREAD

**Issue by ianlewis** [kubernetes/client-go#299]
Maybe similar to #186 but errors on apimachinery.

```
$ mkdir -p $GOPATH/src/test
$ cd $GOPATH/src/test
$ curl -o main.go https://raw.githubusercontent.com/kubernetes/client-go/release-4.0/examples/out-of-cluster-client-configuration/main.go
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2535  100  2535    0     0  14419      0 --:--:-- --:--:-- --:--:-- 14485

$ dep init
No versions of k8s.io/apimachinery met constraints:
	master: unable to update checked out version: : command failed: [git checkout 3b05bbfa0a45413bfa184edbf9af617e277962fb]: exit status 1
	release-1.6: unable to update checked out version: : command failed: [git checkout 35be0db31bd6e5635ef6366708dc2b137392f6a2]: exit status 1
	release-1.7: unable to update checked out version: : command failed: [git checkout 8ab5f3d8a330c2e9baaf84e39042db8d49034ae2]: exit status 1
	release-1.8: unable to update checked out version: : command failed: [git checkout 9d38e20d609d27e00d4ec18f7b9db67105a2bde0]: exit status 1
```

**Comment by Ropes** [comment]
If this is any help, I've been working on an example project using `dep` for vendoring. This 
[constraints](https://github.com/Ropes/k8s-trailhead/blob/master/Gopkg.toml#L5) Gopkg.toml file is working with client-go v5.0.1 and k8s api* libs tagged to version: `kubernetes-1.8.2`. 

I can't promise it will work with all client-go types. However as I add examples to the project I've been ironing out issues related to vendoring the client-go lib as a user. 

If you can add the Gopkg.toml to your project and run `dep ensure -v` and see if it resolves your issues. If it fails let me know how, I've been debugging vendor issues for a while..

**Comment by ianlewis** [comment]
There has been some work done by @sttts and others to make this better. I think it's safe to close this issue for now until I get a chance to test it again.
