### ISSUE TITLE
add support for release-1.3

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/client-go#3]
This is really a great step forward, thank you very much! Sometimes we may need an old version such as release-1.3, hope to support for it

**Comment by timoreimann** [comment]
@mlmhl I don't think this is necessary: The 1.4 version is backwards-compatible with 1.3.

See also [this tweet](https://twitter.com/originalavalamp/status/774715926902022144) from @lavalamp.

**Comment by lavalamp** [comment]
Yes, 1.4 is backwards compatible. Please file an issue if you find a case where it isn't.

**Comment by mlmhl** [comment]
Thanks @timoreimann and @lavalamp very much. It's really a great design!
