### ISSUE TITLE
How to get pods ip?

### ISSUE THREAD

**Issue by peterwillcn** [kubernetes/client-go#300]
how to get pod ip?
```golang
package main

import (
	"fmt"
	"time"

	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

func main() {
	// creates the in-cluster config
	config, err := rest.InClusterConfig()
	if err != nil {
		panic(err.Error())
	}
	// creates the clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}
	for {
		pods, err := clientset.CoreV1().Pods("mpich-system").List(metav1.ListOptions{})
		if err != nil {
			panic(err.Error())
		}
		fmt.Printf("There are %d pods in the cluster\n", len(pods.Items))
  ########################### what to do?
   for i, v := range pods.Items {
      fmt.Printf("Pod %d - %s: \n", i, v)
    }
#############################
		............

		time.Sleep(10 * time.Second)
	}
}
```

![icon](http://static.longrunweather.com/pod.jpg)

**Comment by ericchiang** [comment]
```
pods, err := clientset.CoreV1().Pods("mpich-system").List(metav1.ListOptions{})
if err != nil {
	// handle error
}
for _, pod := range pods.Items {
	fmt.Println(pod.Name, pod.Status.PodIP)
}
```

**Comment by peterwillcn** [comment]
@ericchiang Thanks

**Comment by Emixam23** [comment]
Pods("") should get the namespace but where do you find it? I am a bit lost it's all the time nil/empty

**Comment by Emixam23** [comment]
Now it says I have no access ..

`load: "panic: pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" in the namespace "default"`

I can't make it work.. I tried to manage multiple stuff in the IAM but still nothing..

**Comment by mstrYoda** [comment]
> Now it says I have no access ..
> 
> `load: "panic: pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" in the namespace "default"`
> 
> I can't make it work.. I tried to manage multiple stuff in the IAM but still nothing..

@Emixam23 you need to give appropriate roles to your service account via clusterrolebinding or role binding. The default serviceaccount has not permission to list resources.

For example:

```
kubectl create role some-role --verb=get --verb=list --verb=watch --verb=update --resource=pods --resource=endpoints --resource=services

kubectl create rolebinding some-role-binding --role=some-role --serviceaccount=default:default
```

Or you can create a custom serviceaccount and give roles to it and use that serviceaccount.

**Comment by lysShub** [comment]
> ```
> pods, err := clientset.CoreV1().Pods("mpich-system").List(metav1.ListOptions{})
> if err != nil {
> 	// handle error
> }
> for _, pod := range pods.Items {
> 	fmt.Println(pod.Name, pod.Status.PodIP)
> }
> ```

Assign IP is delay and async ?

```
r.CreatePod()

time.Sleep(time.Second*5)

r.GetPodIP()
```
if I has't sleep,  the Status.PodIP is null
