### ISSUE TITLE
release-4.0 is out of sync

### ISSUE THREAD

**Issue by nilebox** [kubernetes/client-go#301]
The latest client-go specific commit in kubernetes monorepo `1.7.6` release (`release-1.7` branch) is the following (Sep 14): https://github.com/kubernetes/kubernetes/commit/4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c
but the latest commit in `release-4.0` branch of client-go repo is "v.1.7.5-beta.0" (Aug 16) https://github.com/kubernetes/client-go/commits/release-4.0

**Comment by nikhita** [comment]
Syncing is back in action with https://github.com/kubernetes/publishing-bot. 🎉 

/close
