### ISSUE TITLE
unit tests failing

### ISSUE THREAD

**Issue by jekohk** [kubernetes/client-go#303]
I'm attempting to add to the CRUD example which requires forking the main kubernetes repository, and making changes in the staging area.

Following the [community development guide](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md) I successfully build with `make` and pass all presubmission verification with `make update` but `make test` always fails with the following error:

```can't load package: package k8s.io/kubernetes/_tmp/federation/pkg/dnsprovider: code in directory /home/john/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/_tmp/federation/pkg/dnsprovider expects import "k8s.io/kubernetes/federation/pkg/dnsprovider"
_tmp/federation/pkg/dnsprovider/providers/google/clouddns/clouddns.go:32:2: use of internal package not allowed
_tmp/federation/pkg/dnsprovider/providers/google/clouddns/interface.go:21:2: use of internal package not allowed
_tmp/federation/pkg/dnsprovider/providers/google/clouddns/clouddns.go:33:2: use of internal package not allowed
can't load package: package k8s.io/kubernetes/_tmp/federation/pkg/federation-controller/cluster: code in directory /home/john/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/_tmp/federation/pkg/federation-controller/cluster expects import "k8s.io/kubernetes/federation/pkg/federation-controller/cluster"
```

I haven't changed any of the imports in the example, so not sure what's causing the issue. 
Alternatively, is it even necessary to compile k8s.io/kubernetes when working on client-go examples? It's not very clear if the same PR requirements apply to examples and client libraries in staging

**Comment by caesarxuchao** [comment]
What's client-go's role in the bug? The error messages didn't mention client-go.

Have you tried `make clean` and than `make test`? Or try to manually remoe the `_tmp` package.

**Comment by jekohk** [comment]
@caesarxuchao that seems to have fixed the issue- you're right, it's unrelated to client-go. I mistakenly thought I had to compile k8s.io/kubernetes. Thanks!

**Comment by caesarxuchao** [comment]
Cool. I should had read your original post more carefully :)
