### ISSUE TITLE
Referenced docker revision in 4.0.0 no longer in github

### ISSUE THREAD

**Issue by JackQuincy** [kubernetes/client-go#304]
Seems like docker changed their history. 
version cd27f179f2c10c5d300e6d09025b538c475b0d51 is no longer in their history. this is breaking me trying to use glide to import client-go.

**Comment by vdemeester** [comment]
@JackQuincy Could you provide more input ? On which project is that happening ? What is your dependency tree (`glide.yaml`, `glide.lock`) ?

`kubernetes/client-go` doesn't depend on `docker/docker` and as far as I know, we never rewrite history on `github.com/docker/docker` (and I hope it is true !!).

**Comment by thaJeztah** [comment]
That commit looks to be a commit from the https://github.com/docker/distribution repository, but GitHub can do "magic things", like showing commits on any other repository 😞 - which can be super confusing.

It **looks** as if the commit is in the moby/moby repository; https://github.com/moby/moby/commit/cd27f179f2c10c5d300e6d09025b538c475b0d51
But the actual commit is in the https://github.com/docker/distribution repository https://github.com/docker/distribution/commit/cd27f179f2c10c5d300e6d09025b538c475b0d51, where it's merged as part of this pull-request; https://github.com/docker/distribution/pull/1635

**Comment by JackQuincy** [comment]
hmm seems I misdiagnosed. This is the error I'm seeing in glide: [INFO]  --> Setting version for github.com/docker/distribution to cd27f179f2c10c5d300e6d09025b538c475b0d51.
[ERROR] Failed to set version on github.com/docker/distribution to cd27f179f2c10c5d300e6d09025b538c475b0d51: Unable to update checked out version
[ERROR] Failed to set references: Unable to update checked out version (Skip to cleanup).
I'm running windows. I wonder if this is something that doesn't work correctly in windows. I'll try in a docker container to see if it behaves differently.

**Comment by JackQuincy** [comment]
yep seems to be something with my dev enviroment as running in a dev container enviroment fixed it. I'll close the issue.

**Comment by thaJeztah** [comment]
Great! Thanks for reporting though! And good luck debugging :sweat_smile:

**Comment by JackQuincy** [comment]
Might of figured out the issue. 4.0.0 depends on an old version of github.com/docker/distribution before this PR https://github.com/docker/distribution/pull/1716 was merged. And that has paths in it which are invalid in windows.
