### ISSUE TITLE
Client-go 5.0.0 ?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/client-go#305]
When can we expect client-go 5.0.0 released?

**Comment by murali-reddy** [comment]
Appriciate if plan for  client-go 5.0.0 release can be shared. 

Are there any gaps in [release-5.0](https://github.com/kubernetes/client-go/tree/release-5.0) branch  or is it compatible with 1.8 release?

**Comment by tamalsaha** [comment]
I asked @sttts on slack. I am sharing his response:
![cgo-5](https://user-images.githubusercontent.com/94814/31280734-314fcbcc-aa62-11e7-924f-7171c76a013a.png)

**Comment by murali-reddy** [comment]
thanks @tamalsaha

**Comment by sigxcpu76** [comment]
How about the CustomResourceDefinition in 1.7 that was missed by 4.0.0? Will 5.0.0 have it and be compatible with Kubernetes 1.7 and 1.8?

**Comment by tamalsaha** [comment]
> How about the CustomResourceDefinition in 1.7 that was missed by 4.0.0?

What do you mean?

**Comment by sigxcpu76** [comment]
CustomResourceDefinition that replaced ThirdPartyResource in Kubernetes 1.7 is missing in client-go 4.0.0 and 5.0.0. TPR is still there although obsolete.
See #247 .

**Comment by tamalsaha** [comment]
See https://github.com/kubernetes/client-go/issues/247#issuecomment-335231159 (from the same thread). You can get CRD working with client-go 4.0.0

**Comment by sigxcpu76** [comment]
I was expecting it to be available as a first class citizen, just like TPR was.

**Comment by nikhita** [comment]
release-5.0 is now synced with the 1.8 branch. :tada:
