### ISSUE TITLE
object return by client-go informer don't have  api Kind info

### ISSUE THREAD

**Issue by wangweihong** [kubernetes/client-go#308]
When I use informer to watch cluster resource infos, I find  runtime.Object return by informer  don't include object `Kind` info. 
`fmt.Println(obj.GetObjectKind().GetVersionKind().String()) `print ` /, Kind=`

**Comment by krmayankk** [comment]
@smarterclayton i am also seeing this issue. If you know how to fix it ,i would like to take a stab at it

**Comment by thomastaylor312** [comment]
I don't think the Kind is returned either with `List`

**Comment by bostrt** [comment]
The k8s REST API does not provide the `Kind` value. `kubectl` (or one of its dependencies) inserts the `Kind` information. Perhaps the code that figures the `Kind` info can be moved to `client-go`? Just for example, [see `get` cmd](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/resource/get.go#L555-L647) and how it inserts the `List` value.

**Comment by nikhita** [comment]
This occurs because the gvk is cleared during decoding: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L256.

This is intentional. See https://github.com/kubernetes/kubernetes/pull/59264#issuecomment-362575608 for more details.

**Comment by nikhita** [comment]
Reported in kubernetes/kubernetes#3030

Fix in progress in kubernetes/kubernetes#63972

**Comment by thomastaylor312** [comment]
Thank you for the update @nikhita!

**Comment by hjkatz** [comment]
For those of us still looking for a concise way to add TypeMeta information to runtime objects, here you go!

```
// addTypeInformationToObject adds TypeMeta information to a runtime.Object based upon the loaded scheme.Scheme
// inspired by: https://github.com/kubernetes/cli-runtime/blob/v0.19.2/pkg/printers/typesetter.go#L41
func addTypeInformationToObject(obj runtime.Object) error {
    gvks, _, err := scheme.Scheme.ObjectKinds(obj)
    if err != nil {
        return fmt.Errorf("missing apiVersion or kind and cannot assign it; %w", err)
    }

    for _, gvk := range gvks {
        if len(gvk.Kind) == 0 {
            continue
        }
        if len(gvk.Version) == 0 || gvk.Version == runtime.APIVersionInternal {
            continue
        }
        obj.GetObjectKind().SetGroupVersionKind(gvk)
        break
    }

    return nil
}
```

**Comment by szuecs** [comment]
Example what everyone needs to do in order to use owner reference with informers and client-go
https://github.com/zalando-incubator/stackset-controller/blob/ec093f68f18c7c21ae03e44a14666fc6e8d4a5d3/controller/stackset.go#L1084-L1096
