### ISSUE TITLE
Dependency on k8s.io/kubernetes/pkg/util/ratelimit

### ISSUE THREAD

**Issue by tsandall** [kubernetes/client-go#31]
Hello!

It looks like a dependency on k8s.io/kubernetes crept in earlier today: https://github.com/kubernetes/client-go/commit/49f8f1bf914a4976d303f68b0c2276452f551d34

Is this intentional?

I only noticed this after adding client-go as a dependency in my project (using Glide) without providing a specific version to depend on.

**Comment by justinsb** [comment]
Not intentional.. my fault! Sorry and thank you for the heads up

**Comment by justinsb** [comment]
Fix - I hope - in https://github.com/kubernetes/kubernetes/pull/36405

**Comment by caesarxuchao** [comment]
This is fixed. Closing.
