### ISSUE TITLE
go-client 5.0.1 does not build with `dep`

### ISSUE THREAD

**Issue by danderson** [kubernetes/client-go#318]
I believe due to recent mutations in k8s.io/apimachinery, specifically https://github.com/kubernetes/apimachinery/commit/158150cb5856aaec3a319ff460ca4b93b715adda .

To reproduce:
 - Create $GOPATH/bug-repro, and copy examples/workqueue/main.go to it.
 - Install/update dep: go get -u github.com/golang/dep && go install github.com/golang/dep/cmd/dep
 - Run `dep init`. Note in the output that it correctly locks go-client to ^5.0.1.
 - `go install .`

The compile will fail with:

# bug-repro/vendor/k8s.io/client-go/tools/cache
vendor/k8s.io/client-go/tools/cache/mutation_detector.go:103:33: scheme.Scheme.Copy undefined (type *"bug-repro/vendor/k8s.io/apimachinery/pkg/runtime".Scheme has no field or method Copy)

**Comment by caesarxuchao** [comment]
dep doesn't parse the Godeps.json file that pins the exact dependency version. I recommend using glide at the moment. https://github.com/kubernetes/client-go/blob/master/INSTALL.md#glide

**Comment by caesarxuchao** [comment]
> dep doesn't parse the Godeps.json file that pins the exact dependency version. 

It seems dep does supports parsing Godeps.json now: https://github.com/golang/dep/blob/master/docs/FAQ.md#what-external-tools-are-supported

But we have other issues: https://github.com/golang/dep/issues/1124

**Comment by danderson** [comment]
Thanks! I've switched to glide, and I got a successful build. Thanks for the help, and for updating the documentation on `dep` (I originally used dep because INSTALL.md seemed to say it would work).
