### ISSUE TITLE
release-5.0 is missing from he compatibility matrix

### ISSUE THREAD

**Issue by davecheney** [kubernetes/client-go#320]
Release 5.0 is not listed in the [compatibility matrix][0]. Which versions of Kubernetes is client-go 5.0 compatible with?

[0]: https://github.com/kubernetes/client-go#compatibility-matrix

**Comment by aledbf** [comment]
@davecheney here https://github.com/kubernetes/client-go/pull/316

**Comment by dlespiau** [comment]
Seems like this could be closed as #316 is merged.
