### ISSUE TITLE
Propose: provide helper for KUBECONFIG resolution

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/client-go#323]
Hi maintainers–
I’ve been thinking that lots of people are developing client-side tooling using client-go and almost all of them are accepting [kubeconfig flags](https://github.com/kubernetes/client-go/blob/72e1c2a1ef30b3f8da039e92d4a6a1f079f374e8/examples/out-of-cluster-client-configuration/main.go#L37-L42).

**I propose that we provide functionality in client-go** (or other parts of apimachinery/utils) **that automatically resolves the kubeconfig from the file path or the KUBECONFIG environment variable**.

This helper method can help developers build tools that resolve the kubeconfig the recommended way (the way `kubectl` works).

This would codify the precedence of user-provided `--kubeconfig` flag, `$HOME/.kube/config` and the `$KUBECONFIG` env var. Otherwise, we are leaving open-ended questions like:
- what is the precedence if no user-provided --kubeconfig flag supplied?
- which env var one should use to look up home directory [on windows](https://github.com/kubernetes/client-go/blob/72e1c2a1ef30b3f8da039e92d4a6a1f079f374e8/examples/out-of-cluster-client-configuration/main.go#L80-L85)
- should you be using env vars or `os.Homedir()` to [find the home directory](https://github.com/kubernetes/client-go/blob/72e1c2a1ef30b3f8da039e92d4a6a1f079f374e8/examples/out-of-cluster-client-configuration/main.go#L80-L85)

#### Rough proposal 
A method signature like:

    func clientcmd.BuildFromKubeConfig(userProvidedValue="") (*Client, error)

should be able to encapsulate user-provided value, $HOME lookup and the environment variable.

/cc @caesarxuchao

**Comment by jekohk** [comment]
I agree- this would reduce some boilerplate code and promote tools using client-go to follow a standard.

Seems easy enough to implement, probably using the same precedence as `kubectl` . 

The bigger question would be where should this helper be located? In `client-go/util`?

There's already a `homedir` helper [here](https://github.com/kubernetes/client-go/blob/master/util/homedir/homedir.go) that can be used for resolving the home directory.

**Comment by jekohk** [comment]
@ahmetb is this still something we'd like to do? I can take a stab at it

/reopen

**Comment by ahmetb** [comment]
@jekohk I think it got fixed in the meanwhile already.

**Comment by sanderploegsma** [comment]
Wondering whether this proposal eventually gained some traction, since the out-of-cluster example still uses a kubeconfig flag.

IMO it would be great if client-go is able to resolve a valid config similar to how `kubectl` works, by using the `KUBECONFIG` variable. For instance: I can't figure out how to configure client-go to use my KUBECONFIG pointing to multiple files (`KUBECONFIG="$HOME/.kube/config1:$HOME/.kube/config2` for example) without running into #1020 and #1021.

**Comment by ahmetb** [comment]
@sanderploegsma The issue is already resolved. The example probably still uses that flag for illustration purposes. Please refer to the methods and types in https://pkg.go.dev/k8s.io/client-go@v0.26.3/tools/clientcmd to learn more.
