### ISSUE TITLE
client-go pins a version of gopkg.in/yaml.v2 from 2 years ago

### ISSUE THREAD

**Issue by danderson** [kubernetes/client-go#325]
The Godeps.json for client-go pins gopkg.in/yaml.v2 to version 53feefa2559fb8dfa8d81baad31be332c97d6c77 . That commit is from 2 years ago, and lacks a lot of bug fixes and new functionality (notably UnmarshalStrict, which is extremely useful for parsing configs out of ConfigMaps).

Please update this package pin to a (much) newer version.

More generally, this is a worrying consequence of using package locks without actively updating them over time. How many CVEs am I vulnerable to because client-go is forcing my code to pull in ancient libraries? Are there any plans to try and address this?

**Comment by sttts** [comment]
@danderson is this still a problem? Feel free to submit a PR.

/remove-lifecycle stale

**Comment by anubhakushwaha** [comment]
@sttts @nikhita Wasn't this updated [here](https://github.com/kubernetes/client-go/commit/5e622f37cd6ed5eebbb179245ac94fa895577c4a#diff-681659ab9abb4b4883e78e8aaa980dbaL283), let me know if I misunderstood something.

**Comment by nikhita** [comment]
@anubhakushwaha That's right. 👍 

The current version is at `670d4cfef0544295bc27a114dbac37980d83185a`, which is from [July 2017](https://github.com/go-yaml/yaml/commit/670d4cfef0544295bc27a114dbac37980d83185a).

Closing.

/close
