### ISSUE TITLE
Fake client doesn't filter Pods on FieldSelector

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/client-go#326]
The fake client is ignoring the FieldSelector when listing Pods.

```golang
package fake_test

import (
	"k8s.io/api/core/v1"
	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
	"testing"
)

func TestPodFieldSelectors(t *testing.T) {
	client := fake.NewSimpleClientset(&v1.Pod{
		TypeMeta: metaV1.TypeMeta{
			Kind:       "Pod",
			APIVersion: "v1",
		},
		ObjectMeta: metaV1.ObjectMeta{
			Name:      "tls-app-579f7cd745-t6fdg",
			Namespace: "default",
			Labels: map[string]string{
				"tag": "",
			},
		},
		Status: v1.PodStatus{
			PodIP: "172.1.0.3",
		},
	})

	podList, _ := client.CoreV1().Pods("default").List(metaV1.ListOptions{FieldSelector: "status.podIp=10.1.2.3"})
	if len(podList.Items) != 0 {
		t.Errorf("Expected no items in podList, got %d", len(podList.Items))
	}
}

```

**Comment by AishwaryaRK** [comment]
I've tested the same functionality of filtering pods based on FieldSelector and LabelSelector using fake clientset and it was filtering the pod.

**Comment by johngmyers** [comment]
Later discovered my filter had mismatched case.

**Comment by johngmyers** [comment]
Fixed the mismatched case, my test case still fails:

```go

import (
	"k8s.io/api/core/v1"
	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
	"testing"
)

func TestPodFieldSelectors(t *testing.T) {
	client := fake.NewSimpleClientset(&v1.Pod{
		TypeMeta: metaV1.TypeMeta{
			Kind:       "Pod",
			APIVersion: "v1",
		},
		ObjectMeta: metaV1.ObjectMeta{
			Name:      "tls-app-579f7cd745-t6fdg",
			Namespace: "default",
			Labels: map[string]string{
				"tag": "",
			},
		},
		Status: v1.PodStatus{
			Phase: v1.PodRunning,
			PodIP: "172.1.0.3",
		},
	})

	podList, _ := client.CoreV1().Pods("default").List(metaV1.ListOptions{FieldSelector: "status.podIP=10.1.2.3"})
	if len(podList.Items) != 0 {
		t.Errorf("Expected no items in podList, got %d", len(podList.Items))
	}
}
```

**Comment by dionysius** [comment]
Can confirm, was working on mock with secrets and the List() always returns the full list.

**Comment by dnwe** [comment]
Confirming that this is still an issue with client-go 8.0 / HEAD

<details>
<summary>
Example test with <tt>status.phase=Pending</tt> fieldselector incorrectly returning pods in running state
</summary>

```go
package main

import (
	"reflect"
	"testing"

	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/fields"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/kubernetes/fake"
)

func listPendingPods(client kubernetes.Interface) (*v1.PodList, error) {
	return client.CoreV1().Pods("default").List(
		metav1.ListOptions{
			FieldSelector: fields.ParseSelectorOrDie("status.phase=Pending").String(),
		})
}

func TestPodFieldSelectors(t *testing.T) {
	client := fake.NewSimpleClientset(&v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "a",
			Namespace: "default",
			Labels:    map[string]string{},
		},
		Status: v1.PodStatus{
			Phase: v1.PodRunning,
		},
	})
	got, err := listPendingPods(client)
	if err != nil {
		t.Errorf("listPendingPods() error = %v, wantErr %v", err, false)
	}
	want := &v1.PodList{}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("listPendingPods() = %v, want %v", got, want)
	}
}
```
</details>

**Comment by liggitt** [comment]
field selection is done serverside. the generated client doesn't have logic to map an object to its field selection map

**Comment by johngmyers** [comment]
This is the fake client. It should be performing the serverside logic.

**Comment by liggitt** [comment]
> This is the fake client. It should be performing the serverside logic.

Anything non-generic (like field selection behavior) can be injected in your tests by adding reactors that deal with specific types of actions, use additional info in the action (in this case, ListAction#GetListRestrictions().Fields), and customize the data returned

**Comment by dnwe** [comment]
@liggitt rather than customising the fake behaviour, I did the equivalent filter of the podlist in the product code after querying, but before returning it. When running against a real backend, we'll get the up-front serverside filter from the field selector and the subsequent range loop is essentially a no-op, but in the fake case it will be the range loop that does the work.

**Comment by johngmyers** [comment]
@dnwe that would not catch an error in which the filter provided by the code under test incorrectly failed to match necessary test objects.

**Comment by johngmyers** [comment]
@liggitt Field selection behavior seems generic to me.

The existing behavior is astonishing in that the fake client, when called with constraints it does not support, does not panic or otherwise call attention to the unsupported request but instead silently returns incorrect data.

The suggestion of using reactors means that either one has to in the test implement the generic matching behavior that would be better implemented in the fake client itself or make the test brittle by asserting the particular filter passed by the present implementation under test (and failing to catch any subtle errors in the filter).

Not to mention the reactor facility of the fake client is under-documented. At least I wasn't able to figure it out at the time. Instead, I left that functionality untested.

**Comment by liggitt** [comment]
> @liggitt Field selection behavior seems generic to me.

I understand it appears that way, but it is not. Each resource's field selector is manually implemented server-side. For example:

https://github.com/kubernetes/kubernetes/blob/d0439d417b0563d44c65b6e400e2070964dea7d1/pkg/registry/core/pod/strategy.go#L235-L248
