### ISSUE TITLE
Allow the /var/run/secrets path to be overridden for InClusterConfig

### ISSUE THREAD

**Issue by wallrj** [kubernetes/client-go#328]
My use case is that I want to use Telepresence to test and develop an in cluster component.

Telepresence makes the service account secrets available on my laptop at e.g.
 * `$TELEPRESENCE_ROOT/var/run/secrets/kubernetes.io/serviceaccount`

See:
* https://www.telepresence.io/howto/volumes.html

There's a tool called `proot` which I could use, but it's not available as a Fedora package right now.

Would you consider something like the following patch, which checks for `KUBERNETES_SERVICE_ACCOUNT_PATH` rather than hard coding `/var/run/secrets/...` ?

```diff
@minikube|bash-4.4$ git diff  vendor/k8s.io/client-go/rest/config.go | cat
diff --git a/vendor/k8s.io/client-go/rest/config.go b/vendor/k8s.io/client-go/rest/config.go
index 57848c8a..0fc0f0a0 100644
--- a/vendor/k8s.io/client-go/rest/config.go
+++ b/vendor/k8s.io/client-go/rest/config.go
@@ -40,8 +40,9 @@ import (
 )
 
 const (
-	DefaultQPS   float32 = 5.0
-	DefaultBurst int     = 10
+	DefaultQPS                float32 = 5.0
+	DefaultBurst              int     = 10
+	DefaultServiceAccountPath         = "/var/run/secrets/kubernetes.io/serviceaccount"
 )
 
 // Config holds the common attributes that can be passed to a Kubernetes client on
@@ -320,12 +321,17 @@ func InClusterConfig() (*Config, error) {
 		return nil, fmt.Errorf("unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined")
 	}
 
-	token, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/" + v1.ServiceAccountTokenKey)
+	serviceAccountPath := os.Getenv("KUBERNETES_SERVICE_ACCOUNT_PATH")
+	if len(serviceAccountPath) == 0 {
+		serviceAccountPath = DefaultServiceAccountPath
+	}
+	tokenPath := filepath.Join(serviceAccountPath, v1.ServiceAccountTokenKey)
+	token, err := ioutil.ReadFile(tokenPath)
 	if err != nil {
 		return nil, err
 	}
 	tlsClientConfig := TLSClientConfig{}
-	rootCAFile := "/var/run/secrets/kubernetes.io/serviceaccount/" + v1.ServiceAccountRootCAKey
+	rootCAFile := filepath.Join(serviceAccountPath, v1.ServiceAccountRootCAKey)
 	if _, err := certutil.NewPool(rootCAFile); err != nil {
 		glog.Errorf("Expected to load root CA config from %s, but got err: %v", rootCAFile, err)
 	} else {

```

**Comment by ericchiang** [comment]
> There's a tool called proot which I could use, but it's not available as a Fedora package right now.

```
$ unshare --map-root-user chroot $TELEPRESENCE_ROOT /bin/my-program 
```

**Comment by ericchiang** [comment]
@wallrj can we close this?

**Comment by wallrj** [comment]
Yep, thanks for suggestion @ericchiang

**Comment by 85danf** [comment]
Hi, @ericchiang , Mac user here.
I'm using telepresence as well and have the exact same issue - would it be possible to revive the PR? it solves my case perfectly...

PS the javascript client opted to allow [similar functionality](https://github.com/kubernetes-client/javascript/pull/102)

**Comment by Yamakaky** [comment]
I have the same problem. I launch the app using vscode Run & Debug, I don't think `unshare` can be easily added.

If you don't want to hardcode telepresence support, maybe allow the configuration of either these files or of a new root?

New location of the problem is here: https://github.com/kubernetes/client-go/blob/master/rest/config.go#L483
