### ISSUE TITLE
HTTP port-forward broke on client terminates

### ISSUE THREAD

**Issue by tomykaira** [kubernetes/client-go#329]
## Situation

- Components are connected as Go server -> port-forward -> iOS Client
- Using chunked transfer encoding to download large movie file from Server to iOS

## problem

When iOS client exits with SIGKILL (i.e. restart app from Xcode), the port forward emits an error

```
E1119 14:59:19.967004    9736 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8888->127.0.0.1:35390: write tcp4 127.0.0.1:8888->127.0.0.1:35390: write: broken pipe
```

It is ok, but after this error, all connections to portforward are rejected with timeout.

```
E1119 15:15:07.167402    9736 portforward.go:271] error creating error stream for port 8888 -> 8888: Timeout occured
```

## Expected behavior

portforward accepts the following requests after broken pipe.

**Comment by andrewshilliday** [comment]
/remove-lifecycle stale
I can confirm that this happens running with linux clients using curl.  If the endpoint streams results back to the client, and the client (ie, curl) is terminated via ctrl-c, the port-forward does not respond to future requests until the timeout.

**Comment by yonilerner** [comment]
Im getting a possibly related issue. Im port forwarding a mongo instance in k8:
```
kubectl port-forward <pod> 27017:27017
```
And then attempting a `mongodump`:
```
mongodump -d db
```
The moment that the `mongodump` reaches 100%, the port-forward says
```
E0601 16:52:54.983193   32720 portforward.go:303] error copying from remote stream to local connection: readfrom tcp6 [::1]:27017->[::1]:39638: write tcp6 [::1]:27017->[::1]:39638: write: broken pipe
```
and the connection dies completely. I can kill and restart the connection, but every single time I do this `mongodump` the port-forward is killed.

```
$ uname -a
Linux pop-os 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Pop!_OS 18.04 LTS
Release:        18.04
Codename:       bionic
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pedrocunha** [comment]
@tomykaira are you still experiencing the same issues? I have the same problem

**Comment by yonilerner** [comment]
I definitely still happen. I basically just have to try over and over until it works once

**Comment by s1dequest** [comment]
@yonilerner We had this issue as well on our build servers, though it was not intermittent for this particular port-forward -> curl. Turned out to be an expired cert. Might be worth double-checking.

**Comment by yonilerner** [comment]
@s1dequest Thanks for the suggestion, but our certs are fine. port-forward always works, its just not stable

**Comment by paaland** [comment]
Experience same error using Kubernetes in Azure when opening a tunnel to the cluster with az aks browse. Works for a time, then starts to get this error and the tunnel becomes very unstable.

**Comment by daniel-hirvonen** [comment]
Can confirm the same on my AKS cluster on azure. The deployment / upgrade goes through and deployment is runned. But the Release pipeline is marked as failed.

`4383 portforward.go:363] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:43163->127.0.0.1:56726: write tcp4 127.0.0.1:43163->127.0.0.1:56726: write: broken pipe`
