### ISSUE TITLE
Keep Dependencies Minimal

### ISSUE THREAD

**Issue by BugRoger** [kubernetes/client-go#330]
As an example, with the addition of e12b58626cb4cf5f820b924eba476b51df0571dc we added 118MB of additional dependencies (not counting transitive dependencies).

As we all know big dependency trees are  annoying to handle and maintain. This is a plea for trying to keep dependencies to a minimum for client-go.

**Comment by ericchiang** [comment]
There's active work on this.

The example azure plugin you linked to is optional and not imported by default, you have to opt in to add it as a dependency https://github.com/kubernetes/kubernetes/pull/41532.

We're also working on breaking dependencies from things like the openapi packages, which should further reduce the set of transitive imports https://github.com/kubernetes/kube-openapi/pull/21
