### ISSUE TITLE
Glide cannot install 5.X with batchv1 reference

### ISSUE THREAD

**Issue by rcorre** [kubernetes/client-go#331]
This is a copy of https://github.com/Masterminds/glide/issues/945. I wasn't sure if it is an issue with `glide` or `client-go`, but since my issue with `glide` is still unanswered, I'm reaching out here. The issue is as follows:

- - -

I'm trying to bump [client-go](https://github.com/kubernetes/client-go/) to 5.x, but `glide up -v` prints:

```
[ERROR] Error scanning k8s.io/client-go/pkg/apis/batch/v1: cannot find package "." in:
        /home/rodencor/.glide/cache/src/https-k8s.io-client-go/pkg/apis/batch/v1
```

## Minimal example:

`glide.yaml`:

```yaml
package: github.com/rcorre/k8stest
import:
- package: k8s.io/client-go
  version: 5.x.x
```

`main.go`:

```
package main

import (
	"k8s.io/client-go/kubernetes"
	batch "k8s.io/client-go/pkg/apis/batch/v1"
	"k8s.io/client-go/rest"
)

func main() {
	conf, err := rest.InClusterConfig()
	if err != nil {
		panic(err)
	}

	kube, err := kubernetes.NewForConfig(conf)
	if err != nil {
		panic(err)
	}

	var jobs []batch.Job
	jobs, err := kube.BatchV1().Jobs(namespace).List(nil)
	if err != nil {
		panic(err)
	}
}
```

I've tried `rm -rf vendor` and `glide cc`.

Let me know if this issue belongs on client-go instead.

**Comment by prithviramesh** [comment]
I'm not able to glide install client-go v5.0.0 with the same error

**Comment by sttts** [comment]
`k8s.io/client-go/pkg/apis/batch/v1` moved to `k8s.io/api/batch/v1`. After fixing the import, glide is happy. Closing this. Please reopen if you think there is still an issue.

**Comment by rcorre** [comment]
Thanks, that got me further (I also had to rename `k8s.io/client-go/pkg/api/v1` to `k8s.io/api/core/v1`).

I'm now hitting:

```
vendor/k8s.io/kubernetes/pkg/apis/extensions/v1beta1/zz_generated.conversion.go:1122:31: cannot use in.AllowPrivilegeEscalation (type bool) as type *bool in assignment
```

I'll open a new ticket if I can't figure that one out...

**Comment by rcorre** [comment]
Turns out my subsequent issue is specific to helm: https://github.com/kubernetes/helm/issues/3445
