### ISSUE TITLE
Adding expectations and controller ref manager to client-go

### ISSUE THREAD

**Issue by rmohr** [kubernetes/client-go#332]
It would be great if the [expectations](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils.go) and the [controller reference manager](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_ref_manager.go) could be added to client-go. They make it a lot easier to write proper controllers.

Especially the controller reference manager is useful, since it help integrating CRDs into the garbage colloector (forground, background and orphan deletion strategies, which helps inheriting kubectl --cascade support).

**Comment by kopaygorodsky** [comment]
it would be great to reopen this issue and add ref manager to the client.

**Comment by Jeffwan** [comment]
I will file a PR to bring the codes. Really want this feature
