### ISSUE TITLE
NetworkPolicyPort requires pointer to const for Protocol

### ISSUE THREAD

**Issue by donovansolms** [kubernetes/client-go#333]
I found an inconsistency for specifying the Protocol for ingress and egress network policies that requires a workaround since Go doesn't allow getting a `const` address directly.

Client Version: client-go 5.0
Kubernetes Version: 1.8

In other areas where you need to specify a protocol/port combination, such as `ServicePort` you can do:
```go
v1.ServiceSpec{
	Ports: []v1.ServicePort{
		{
			Protocol: v1.ProtocolUDP, // Use the const directly
		},
	},
}
```

However, in [NetworkPolicyPort](https://godoc.org/k8s.io/api/networking/v1#NetworkPolicyPort) you need to provide a pointer to the Protocol constant. 

```go
Ports: []networkv1.NetworkPolicyPort{
    {
        // This can't be done in Go directly
        // error: cannot take the address of "k8s.io/api/core/v1".ProtocolUDP
        Protocol: &v1.ProtocolUDP,
        Port: &intstr.IntOrString{
            Type:   intstr.Int,
            IntVal: int32(53),
        },
    },
},
``` 

To make this work you need to assign the `const` to a variable that you can get the address of and use that. This feels wrong to me.

```go
const protocolConst = v1.ProtocolUDP
protocolVar := protocolConst

Ports: []networkv1.NetworkPolicyPort{
    {
        Protocol: &protocolVar,
        Port: &intstr.IntOrString{
            Type:   intstr.Int,
            IntVal: int32(53),
        },
    },
},
```

The differences can be found in [core api/types](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3340) and [networking api/types](https://github.com/kubernetes/api/blob/master/networking/v1/types.go#L142).

This isn't really an issue as the code works as expected, it just requires an odd workaround to make it work. Am I missing something here? Is there a specific reason why this would require a pointer?

*Note: I could not see any reason why it would be generated as such since there is no real difference in the protobuf definitions for [NetworkPolicyPort](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/networking/v1/generated.proto#L139) and [ServicePort](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/generated.proto#L4040)*

**Comment by timthelion** [comment]
I *think* you're supposed to use the `Enum` method: https://stackoverflow.com/questions/50464205/how-to-set-a-protobuf2-enum-using-golang
