### ISSUE TITLE
Informer doesn't update for briefly running Pods

### ISSUE THREAD

**Issue by metalmatze** [kubernetes/client-go#335]
Hey!
We create Pods with client-go like:
https://github.com/drone/drone-kubernetes-runtime/blob/e666fd071ca9420ab0e061b1ca5380b5bc88c5f1/engine/kubernetes/kubernetes.go#L123-L140

Once a Pod is running we wait for updates by the informer like:
https://github.com/drone/drone-kubernetes-runtime/blob/e666fd071ca9420ab0e061b1ca5380b5bc88c5f1/engine/kubernetes/kubernetes.go#L176-L194

When you run a container like `docker run --rm alpine:3.6 /bin/sh -c "echo hello world" ` in the Pod it exists really fast (1s). 
It seems like the informer maybe isn't properly initialized, because it fails to trigger our update func. 

For now I've simply added a `sleep 5` to the end of the script and thus everything is fine. We could also `time.Sleep(5 * time.Second)` in our code, but that's not really what one whats, right?

**Comment by lavalamp** [comment]
https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L57
