### ISSUE TITLE
ResourceEventHandlerFuncs should be called concurrently in separate goroutines

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/client-go#336]
Simple pod list/watcher below.

I added a `sleep(5s)` and executed 5 pods and realized the `AddFunc` is called serially one by one (similar in DeleteFunc etc). So it took 25 seconds to all the way to the last pod. If AddFunc was invoked in parallel with goroutines, it would complete in ~5s.

This `AddFunc` signature doesn't even return an error, any reason why all invocations to these XxxFuncs aren't being done in parallel using goroutines?

```go
	ctx := context.Background()
        restClient := k8s.CoreV1().RESTClient()
	lw := cache.NewListWatchFromClient(restClient, "pods", corev1.NamespaceAll, fields.Everything())
	_, controller := cache.NewInformer(lw,
		&corev1.Pod{},
		time.Second*5,
		cache.ResourceEventHandlerFuncs{
			AddFunc: func(obj interface{}) {
				pod, ok := obj.(*corev1.Pod)
				if !ok {
					log.Fatalf("list/watch returned non-pod object: %T", pod)
				}
				time.Sleep(time.Second * 5)	
				log.Printf("handling pod %s", pod.GetName())
			},
		},
	)
	controller.Run(ctx.Done()
```

**Comment by lavalamp** [comment]
The intention is that you will use a work queue to parallelize this. The
informer can't know if what you are doing is safe for parallelism or not.

On Wed, Nov 29, 2017 at 11:16 AM, Ahmet Alp Balkan <notifications@github.com

**Comment by ahmetb** [comment]
Makes sense thanks.
