### ISSUE TITLE
"create-update-delete-deployment" example outdated

### ISSUE THREAD

**Issue by mactr0n** [kubernetes/client-go#346]
The "create-update-delete-deployment" example seems to be outdated because 
`RollbackTo` of `v1beta1.DeploymentSpec` is deprecated.

There example should be updated using `Rollback` of `v1beta1.DeploymentExpansion`.

**Comment by jekohk** [comment]
@mactr0n good catch. I'll get that updated

**Comment by anubhakushwaha** [comment]
@sttts @jekohk I would like to work on this issue

**Comment by jekohk** [comment]
@anubhakushwaha feel free to pick this up. Let me know if you have any questions but it should be pretty straightforward.

**Comment by nikhita** [comment]
`apps/v1` deployments are GA so the example should be updated to it.

**Comment by nikhita** [comment]
@anubhakushwaha You can use https://github.com/kubernetes/kubernetes/pull/58446 as a reference.

**Comment by nikhita** [comment]
oops

/remove-help

since already assigned to @anubhakushwaha

**Comment by nikhita** [comment]
@anubhakushwaha When deployments are updated to use `apps/v1`, we should probably end up documenting this as well (see https://github.com/kubernetes/kubernetes/pull/59104).

**Comment by anubhakushwaha** [comment]
@nikhita @jekohk I researched around the code and need some help, since we have moved from v1beta1 to v1, I was figuring out how to incorporate DeploymentRollBack as it's no longer a supported API object of v1. [K8s Doc](https://kubernetes.io/docs/reference/generated/federation/v1/definitions/) Any help with how to proceed will be really great. Thanks

**Comment by jekohk** [comment]
Hi @anubhakushwaha 
I believe you need to use the `Rollback` function from the [DeploymentExpansion](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/extensions/v1beta1/deployment_expansion.go) interface in `extensions/v1beta1`
