### ISSUE TITLE
Fake Clientset and cache.ListWatch

### ISSUE THREAD

**Issue by AlexShemeshWix** [kubernetes/client-go#352]
Hi
I have project that uses cache.ListWatch to monitor k8s Deployments.
I want to create tests for my projects.
im creating cache.ListWatch with NewListWatchFromClient and im passing  it to cache.NewInformer

```
unc Test_TestListInformer(t *testing.T) {
	dpl := GenerateHelloMyDeployment()
	clientSet := fake.NewSimpleClientset(&dpl)
	//clientSet := GetClientOutOfCluster()

	restClient := clientSet.ExtensionsV1beta1().RESTClient()
	if restClient == nil {
		t.Error("Cant get rest client")
	}
	watchlist := cache.NewListWatchFromClient(clientSet.ExtensionsV1beta1().RESTClient(), "deployments", api_v1.NamespaceAll, fields.Everything())

	var expectedObj interface{}

	resyncPeriod := 30 * time.Minute

	_, eController := cache.NewInformer(
		watchlist,
		&v1beta1.Deployment{},
		resyncPeriod,
		cache.ResourceEventHandlerFuncs{
			AddFunc: func(obj interface{}) {
				expectedObj = obj
			},
			DeleteFunc: func(obj interface{}) {
				expectedObj = obj
			},
			UpdateFunc: func(oldObj interface{}, newObj interface{}) {
				expectedObj = oldObj
			},
		},
	)
	stopChan := make(chan struct{})
	go eController.Run(stopChan)
	time.Sleep(time.Second)
	close(stopChan)
}
```

It fails when i call eController.Run(stopChan) at here
github.com/wix-private/hdc3/conductor/vendor/k8s.io/client-go/rest.(*RESTClient).Verb at client.go:222

```
func (c *RESTClient) Verb(verb string) *Request {
	backoff := c.createBackoffMgr()

	if c.Client == nil {
		return NewRequest(nil, verb, c.base, c.versionedAPIPath, c.contentConfig, c.serializers, backoff, c.Throttle)
	}
	return NewRequest(c.Client, verb, c.base, c.versionedAPIPath, c.contentConfig, c.serializers, backoff, c.Throttle)
}
```

c is nil.
As far as i understand NewSimpleClientset is not implementing REST client functionality properly.

What fake objects should i use?
How should i approach such problem?

**Comment by thetristan** [comment]
@AlexShemeshWix I ran into a similar issue trying to test my controller code. 

I worked around this by requiring a `cache.ListerWatcher` to be passed to the function under test instead of calling `cache.NewListWatchFromClient` within the function under test.

Here's how that looked for me: https://gist.github.com/thetristan/f0143f1f2760f1e42541172c51d7066e

**Comment by simongormley** [comment]
I've hit this too - looks like it could be caused by the faked core client not initializing createBackoffMgr in the struct, or using NewRESTClient which does set it https://github.com/kubernetes/client-go/blob/master/rest/client.go#L124

Faked code that may not be correct:
https://github.com/kubernetes/client-go/blob/d8b352f6b2b31a09b86fa7d14b7e70ccb77590cd/kubernetes/typed/core/v1/fake/fake_core_client.go#L93-L98

I'm not sure how this could be fixed though

**Comment by aermakov-zalando** [comment]
This still happens. Could someone reopen it?

**Comment by aermakov-zalando** [comment]
@sig-testing/bugs

**Comment by vania-pooh** [comment]
Summon @fejta

**Comment by terorie** [comment]
Also stumbled across this problem and I'm sure I won't be the last one to.
It's unlikely that the entire REST interface ever gets mocked by fake packages, so use of `cache.NewListWatchFromClient` and other `RESTClient()`-based funcs need to be avoided when testing with fake clientsets.

Thankfully, this is possible in a way that doesn't involve injection from unit tests. The approach below is actually cleaner than using `NewListWatch` in the first place.

The typed interfaces already provide any functionality needed (such as the Clientset). `cache.ListerWatcher` can easily be implemented with a wrapper struct. The struct can then be passed to `Informers`, etc.

Here's a very minimal example.

```go
type PodListWatch struct {
	kubernetes.Interface
}

func (p PodListWatch) List(options metav1.ListOptions) (runtime.Object, error) {
	return p.Interface.CoreV1().Pods("mynamespace").List(options)
}

func (p PodListWatch) Watch(options metav1.ListOptions) (watch.Interface, error) {
	return p.Interface.CoreV1().Pods("mynamespace").Watch(options)
}

// Assert PodListWatch implements watch.ListerWatcher
var _ cache.ListerWatcher = (*PodListWatch)(nil)

func test() {
	lw := PodListWatch{/* todo set k8s */}
	_, controller := cache.NewInformer(lw, new(corev1.Pod), 0,
		cache.ResourceEventHandlerFuncs{
			AddFunc: func(obj interface{}) {},
			DeleteFunc: func(obj interface{}) {},
			UpdateFunc: func(oldObj, newObj interface{}) {},
		})
}
```
