### ISSUE TITLE
Azure authentication fails on acquiring consequent tokens

### ISSUE THREAD

**Issue by pavel-khritonenko** [kubernetes/client-go#353]
We use `kubectl` with Azure authentication provider, and our devs are facing issue when `access-token` expired.

    $ kubectl get pods
    E1226 11:52:13.723835   16281 azure.go:126] Failed to acquire a token: refreshing the expired token: refreshing token: adal: Refresh request failed. Status Code = '400'
    Unable to connect to the server: acquiring a token for authorization header: refreshing the expired token: refreshing token: adal: Refresh request failed. Status Code = '400'

Deleting all tokens from `~/.kube/config` and authentication solves the issue until next expiring period.

**Comment by nim-nim** [comment]
Probably the same thing as https://github.com/kubernetes/client-go/issues/379

**Comment by konstantinmiller** [comment]
I have the issue as well, and the workaround (to delete access tokens) works for me. Would still be interested if it could be solved in a different, less manual way.

**Comment by ethereal-sandeep** [comment]
Go to your `~/.kube/config `file and delete `accessToken` and `refreshToken`. Then try running your kubectl commands once again

**Comment by kjozsa** [comment]
I keep having this 3-5 times every day with Azure's k8s. Any hints how to get rid of this (or on why this ticket was closed?)

**Comment by kwaazaar** [comment]
I have this too on different clusters on the same tenant, which all worked flawless for months. I have to to az aks get-credentials to solve this for a short while.

**Comment by nicolasappdirect** [comment]
Same situation, we configured sign-in frequency on Azure and it keeps displaying this error. 
Removing manually the token in the kubeconfig works but it's a very dirty workaround.

The expected behaviour should be to try to authenticate again (device code etc...).

**Comment by powereborn** [comment]
Same situation, we configured sign-in frequency on Azure and it keeps displaying this error. Removing manually the token in the kubeconfig works but it's a very dirty workaround.

The expected behaviour should be to try to authenticate again (device code etc...).

**Comment by vladimirglazkov** [comment]
/reopen
This bug is still here.

**Comment by andyliddle** [comment]
/reopen
This is still and issue

**Comment by andyliddle** [comment]
E1012 17:28:55.767794    4872 azure.go:154] Failed to acquire a token: unexpected error when refreshing token: refreshing token: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"interaction_required","error_description":"AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access ''.\r\nTrace ID: \r\nCorrelation ID:\r\nTimestamp: 2020-10-12 16:28:55Z","error_codes":[50078],"timestamp":"2020-10-12 16:28:55Z","trace_id":"","correlation_id":"","suberror":"basic_action"}

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by noderat** [comment]
@ericchiang Perhaps this could be re-opened? It continues to be an issue and was not triaged prior to being closed.

**Comment by kennexc** [comment]
You can get the credentials again by the following command:
az aks get-credentials --name yourNameSpace --resource-group yourResourceGroup

Overwritten
Y

**Comment by btlyken** [comment]
This is still an issue. Although there are workarounds, it's a pain point for people who need to access their AKS clusters daily.

**Comment by matthieu-eck** [comment]
It looks like it has been [fixed](https://github.com/kubernetes/client-go/commit/88929e8a2b30786ceb354213da55b4b10121d770) on the `master` branch and tag `v0.22.0-alpha.3`.
I confirm this doesn't fail anymore if you build `kubectl` from source:
```
git clone https://github.com/kubernetes/kubernetes 
cd kubernetes
make WHAT=cmd/kubectl
cd cmd/kubectl
go build
```
With `kubectl` 1.21:
```
./kubectl1.21 version                                                                                  
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
./kubectl1.21 get nodes
E0611 azure.go:154] Failed to acquire a token: unexpected error when refreshing token: refreshing token: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"interaction_required","error_description":": The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. "suberror":"token_expired"}
```

With `kubectl` built from `master`:
```
./kubectl version                                                                                      
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%H$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
➜ ./kubectl get nodes -n kube-system 

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code 12345ABC to authenticate.
```
