### ISSUE TITLE
Need example to use `informers` package to listen to pod events

### ISSUE THREAD

**Issue by asridharan** [kubernetes/client-go#354]
I followed this example:
https://gist.github.com/ctaggart/deba294becac3c14678c1c04df2cd089

Which seems to be relevant here, but I am unable to import:
"k8s.io/kubernetes/pkg/api"
with golang 1.8?

Is there a documentation of how the Resource Handlers emanate objects and what go structs these objects map to. The documentation is horrendous in this regard !!

**Comment by sttts** [comment]
"k8s.io/kubernetes/pkg/api" is probably k8s.io/api/core/v1 now.

**Comment by grpndrs** [comment]
@sttts I tried to get the example running. But it is stuck on some weird error. I cannot find any useful documentation or anyone running into same the issue. Can you please help me?

source: https://github.com/grpndrs/client-go/commit/4bb014775e7105104bc89a12b49afe9ce95dff88
error: https://gist.github.com/grpndrs/3de3065814f28a442c668b06b4e41f1d

**Comment by sttts** [comment]
Yes, never import "k8s.io/kubernetes/*. For vendoring we have the k8s.io/api, client-go, apimachinery.... repos.

**Comment by sttts** [comment]
Your gist confirms that you mix k8s.io/kubernetes and k8s.io/client-go.
