### ISSUE TITLE
LGPL License in this repository

### ISSUE THREAD

**Issue by kujenga** [kubernetes/client-go#357]
There is an LGPL license for code that is vendored in this repository:

https://github.com/kubernetes/client-go/blob/master/vendor/github.com/juju/ratelimit/LICENSE

It appears that this is inherited from the main Kubernetes repository:

https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/juju/ratelimit/LICENSE

Does this not "infect" use of the code in this repository in some way? What compatibility is there with the Apache 2.0 license that this repository bears?

---

Edit: Apache lists incompatible licenses: http://www.apache.org/legal/resolved.html#category-x

**Comment by sttts** [comment]
Can you move this discussion to https://github.com/kubernetes/steering/issues/21 ?

**Comment by denismakogon** [comment]
Okay, so, do we already know when the client would get rid of juju/ratelimit ?

**Comment by sttts** [comment]
@denismakogon https://github.com/kubernetes/kubernetes/pull/38320

**Comment by sttts** [comment]
@denismakogon some hours after the upper PR is merged, you see it here.

**Comment by denismakogon** [comment]
@sttts thanks!

**Comment by kujenga** [comment]
Issue moved to [kubernetes/steering #23](https://github.com/kubernetes/steering/issues/23) via [**ZenHub**](https://www.zenhub.com/)
