### ISSUE TITLE
glog terminates program when it can't create a logfile

### ISSUE THREAD

**Issue by tyranteon** [kubernetes/client-go#358]
This is quite a big deal when using with containerized read-only environments. We should absolutely get rid of glog as it just calls `os.Exit(2)` if it can't create a file, killing our entire process.

A workaround would be to do all calls to glog inside a seperate process, which shouldn't be worth the hassle.

**Comment by hjacobs** [comment]
@destructive-dragon do you have any pointers for me where you (or someone else) applied a workaround to disable `glog` file writing? I want to fix https://github.com/kubernetes-incubator/external-dns/issues/595 and I cannot use the command line flags for `glog` as External DNS uses `kingpin` for option parsing.

**Comment by destructive-dragon** [comment]
@hjacobs 

You could either just try to fork the original glog and change the lines of code that do the Exit / require the files. This is a good starting point: https://github.com/golang/glog/blob/master/glog.go#L679

Or the way I solved it was to just reimplement all the glog functions and wrapped them straight onto a go-kit logger without all the complex Verbosity logic (see https://github.com/justwatchcom/glog as an example)

**Comment by hjacobs** [comment]
Fix for External DNS to replace glog with a sane version (for anybody interested): https://github.com/kubernetes-incubator/external-dns/pull/714

**Comment by geekofalltrades** [comment]
There's a core Kubernetes issue open for this: https://github.com/kubernetes/kubernetes/issues/61006

**Comment by hjacobs** [comment]
/remove-lifecycle stale

Kubernetes core switched to `k8s.io/klog` apparently (https://github.com/kubernetes/kubernetes/issues/61006#issuecomment-437606019)

**Comment by gjtempleton** [comment]
Looks like 74cd8bbeee080de457e0ef6b4ad2951c205ade4d has addressed this by switching to klog as of v10.0.0, though it's not called out in the Changelog.

**Comment by hjacobs** [comment]
@gjtempleton that would be awesome!

**Comment by gjtempleton** [comment]
/remove-lifecycle rotten

Switching to klog doesn't fully resolve this, at least by default. (See: https://github.com/projectcalico/typha/pull/258 and https://github.com/coredns/coredns/pull/2529 )
