### ISSUE TITLE
Is the client thread safe?

### ISSUE THREAD

**Issue by F21** [kubernetes/client-go#36]
I want to use the client to build an in-cluster service like this example: https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go

Is the client thread safe? In other words, can I create 1 client and use them across multiple goroutines, or would I have to use a mutex to ensure only 1 goroutine accesses the client at a time?

**Comment by caesarxuchao** [comment]
The client is thread safe.

**Comment by F21** [comment]
@caesarxuchao Thanks! 👍

**Comment by krmayankk** [comment]
can we put something about this in the documentation of client-go somewhere @caesarxuchao ?
