### ISSUE TITLE
Move ReconcileRoleOptions to client-go ?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/client-go#362]
Currently we use PATCH to update Roles from my CRD controllers. Instead, we would like to use the `auth reconcile` functionality, since it is safer. But this functionality in the main Kube repo. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/rbac/reconciliation/reconcile_role.go#L97:10

It will be great if we can use this functionality without needing to depend on the main repo. Can this be moved to client-go ?

cc: @liggitt @deads2k

**Comment by liggitt** [comment]
It makes use of internal api versions which are not available to client-go. What roles are you updating?

**Comment by tamalsaha** [comment]
These are CRD controller specific roles .
