### ISSUE TITLE
Cache Informer sets ResourceVersion=0 which causes API list chunking to break

### ISSUE THREAD

**Issue by madari** [kubernetes/client-go#366]
/kind bug

**What happened**:

Something in the way the cache ListWatch/Informer machinery sets ResourceVersion="0" breaks API chunking when listing pods.

It seems that the API server ignores the limit parameter when ResourceVersion = "0". It's not clear what the actual issue here is.

In contrast, `kubectl` does not appear to set ResourceVersion for the first GET request.

Is there a semantic difference between ResourceVersion "0" and ""?

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with more than one pods, run the following code accessing the cluster via `kubectl proxy -v=7` and notice how chunking is not happening:

```go
// client := ...
lw := &cache.ListWatch{
  ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
    options.Limit = 1
    // Uncommenting the following "fixes" the chunking:
    // if options.ResourceVersion == "0" {
    //  options.ResourceVersion = ""
    // }
    return client.Core().Pods(metav1.NamespaceAll).List(options)
  },
  WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
    return client.Core().Pods(metav1.NamespaceAll).Watch(options)
  },
}
_ informer := cache.NewInformer(lw, &apiv1.Pod{}, 0, cache.ResourceEventHandlerFuncs{})
informer.Run(context.Background())
```

**Environment**:

client-go Version: 78700dec6369ba22221b72770783300f143df150

Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
This is working as intended as far as the chunking behavior is concerned. The server will not return a `continue` token that conflicts with a resourceVersion you specify.

> Is there a semantic difference between ResourceVersion "0" and ""?

Yes, "" is unspecified and leaves the server free to return a continue token pinned to the current resourceVersion. "0" means "serve the current version held by the API server cache", which could not be counted on to be consistent when making the next chunk request.

@smarterclayton did you know reflectors were setting resourceVersion=0 and therefore unable to use chunking?

**Comment by madari** [comment]
@liggitt Thanks for the clarification. In the interim while reflectors aren't doing chunking, is doing `if options.ResourceVersion == "0" { options.ResourceVersion = "" }` as a workaround (see the commented lines above) a safe operation in the sense that the store will get synced to a good state?

**Comment by smarterclayton** [comment]
Yes I did know.  When watch cache is on hitting the watch cache is faster than chunking.  When watch cache is off etcd serves chunks (0 means nothing to etcd layer).  Watch cache initial establishment hits etcd with chunking on (or at least it should), which prevents super large reads from etcd from dying.

At some point watch cache chunking probably makes sense but it’s more expensive to implement.

**Comment by liggitt** [comment]
> Could you comment on https://github.com/kubernetes/client-go/issues/366#issuecomment-364673743? I can deal with listing being less efficient

If you make your lists avoid sending resourceVersion=0, that shouldn't cause any correctness issues

**Comment by JohnRusk** [comment]
See also https://github.com/kubernetes/kubernetes/issues/59684
