### ISSUE TITLE
Remove objectType/expectedType as parameter in Informer/Reflector constructor

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/client-go#367]
It is weird and cumbersome to add `&Pod{}` as parameter in constructor of Informer. Digging further, the objectType is used for logging and runtime type checking:

https://github.com/kubernetes/client-go/blob/7cd1d3291b7d9b1e2d54d4b69eb65995eaf8888e/tools/cache/reflector.go#L385

Is that right? If so, this is unnecessary from user's perspective, and adds another parameter to constructing informer. It would be great to remove that.

**Comment by caesarxuchao** [comment]
It prevents the user from accidentally constructing informers with list/watch functions of wrong types.

Unless there is a strong reason we should avoid making backwards incompatible changes. Please reopen if you think there is one.

**Comment by hongchaodeng** [comment]
> Unless there is a strong reason we should avoid making backwards incompatible changes. 

Is it possible to add new API?

**Comment by hongchaodeng** [comment]
> It prevents the user from accidentally constructing informers with list/watch functions of wrong types.

It already watches specific resources ("pods"), right? Isn't it enough to assume the returned types to be 'Pod'?

**Comment by caesarxuchao** [comment]
The signature is:
```golang
NewSharedIndexInformer(lw ListerWatcher, objType runtime.Object, defaultEventHandlerResyncPeriod time.Duration, indexers Indexers)

// ListerWatcher is any object that knows how to perform an initial list and start a watch on a resource.
type ListerWatcher interface {
	// List should return a list type object; the Items field will be extracted, and the
	// ResourceVersion field will be used to start the watch in the right place.
	List(options metav1.ListOptions) (runtime.Object, error)
	// Watch should begin a watch at the specified version.
	Watch(options metav1.ListOptions) (watch.Interface, error)
}
```

`ListerWatcher` doesn't specify the type, it can be passed from other functions. Human error can occur.
