### ISSUE TITLE
[Question] Example to cp file Kubernetes Container (POD)

### ISSUE THREAD

**Issue by amandahla** [kubernetes/client-go#369]
Is it possible to do it using client-go?

Should I use something like this?

```
execRequest := kubeClient.CoreV1().RESTClient().Post().
        Resource("pods").
        Name(req.Pod).
        Namespace(req.Namespace).
        SubResource("exec").
        Param("container", req.Container).
        Param("command", req.Command).
        Param("stdin", "true").
        Param("stdout", "false").
        Param("stderr", "false").
        Param("tty", "false")
```

**Comment by happilymarrieddad** [comment]
I have this same question. @amandahla have you figured this out?

**Comment by amandahla** [comment]
@happilymarrieddad Sorry, I don't remember if I solved this but I have found this link here that might help you:

https://stackoverflow.com/questions/51686986/how-to-copy-file-to-container-with-kubernetes-client-go
