### ISSUE TITLE
Support "DeleteByKey" for "Store interface"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/client-go#372]
The interface has `Get` and `GetByKey`, but it only has `Delete` for deletion. It would be great to support `DeleteByKey`.

https://github.com/kubernetes/client-go/blob/8aceb98010c1c18b6b54a35b52fd5b46905e3d7f/tools/cache/store.go#L34-L48

Guess this might influence some downstream codes if we support this.

/cc @caesarxuchao @deads2k

**Comment by xiangpengzhao** [comment]
After another look, seems like the function `DeleteByKey` is covered by `Delete`, right? i.e., users can use `Delete(key)` to delete by the key.

**Comment by deads2k** [comment]
> After another look, seems like the function DeleteByKey is covered by Delete, right? i.e., users can use Delete(key) to delete by the key.

You can't pass it a key, but it is normally only used by our test code.  You have some specific case you're trying to solve unrelated to test code (which could do a get/delete) that needs handling?

**Comment by xiangpengzhao** [comment]
I have an internal tool whose server side hopes to use this cache mechanism. It can accept API request to delete an item but the request might only have the key, so I hope it can delete by key.

**Comment by lavalamp** [comment]
IIRC Delete should work on anything that it can get the key out of, as a
hack I think you can construct the DeletedFinalStateUnknown tombstone and
pass that...

**Comment by xiangpengzhao** [comment]
Thanks @deads2k @lavalamp ! :+1:
