### ISSUE TITLE
Regenerating APIS

### ISSUE THREAD

**Issue by nim-nim** [kubernetes/client-go#378]
Hi,

It seems the kubernetes 1.7.14 client is using an obsolete ugorji version (they released their first stable supported version a little while ago). I get a lot of

```
/usr/share/gocode/src/k8s.io/client-go/pkg/apis/authentication/v1beta1/types.generated.go:132:6: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
```

Errors. What is the preferred way to regenerate those files with a newer ugorji? IIRC for etcd you just removed the generated files and ugorji regenerated clean ones. Is it the same for kubernetes?

**Comment by liggitt** [comment]
> What is the preferred way to regenerate those files with a newer ugorji?

Ugorji use was dropped in 1.9 (see https://github.com/kubernetes/kubernetes/pull/48287). There are no plans to bump versions of ugorji in maintenance branches.

/close
