### ISSUE TITLE
I can't build the out-of-cluster-client-configuration example.

### ISSUE THREAD

**Issue by zhangcunli** [kubernetes/client-go#381]
# github.com/kubernetes/client-go/examples/out-of-cluster-client-configuration
./main.go:56:67: cannot use "github.com/kubernetes/client-go/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions literal (type "github.com/kubernetes/client-go/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions) as type "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions in argument to clientset.CoreV1().Pods("").List
./main.go:67:73: cannot use "github.com/kubernetes/client-go/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions literal (type "github.com/kubernetes/client-go/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions) as type "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions in argument to clientset.CoreV1().Pods(namespace).Get

**Comment by liggitt** [comment]
you need to flatten your vendor tree, to avoid nested vendor directories which causes incompatible types.

with glide, that is done by adding `-v` to the `glide install` or `glide update` commands

/close
