### ISSUE TITLE
informers: resync is inactive without event handlers

### ISSUE THREAD

**Issue by sttts** [kubernetes/client-go#382]
If there is no event handler registered for`sharedIndexInformers` the shared processor has no listener and the `shouldResync` func (https://github.com/kubernetes/kubernetes/blob/5f7b530d87a426348ac7c8fa27f8079fd9445d70/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L436) returns always false.

As a consequence a typed informer without event handlers returns a listener interface for the underlying store that has no working resync. 

Thanks for the great analysis in https://github.com/kubernetes/kube-state-metrics/issues/402#issue-307052307.

**Comment by ncdc** [comment]
It sounds like each `sharedProcessor` needs to store the `defaultEventHandlerResyncPeriod` and use that if there are no listeners, perhaps.

**Comment by sttts** [comment]
> needs to store the defaultEventHandlerResyncPeriod and use that if there are no listeners

If there is no deeper reason for avoiding a resync in that case... Do we have any informer without event handler in kube?

**Comment by ncdc** [comment]
Right, now that I think about this more, I'm not sure this is an actual issue? Resync just means that it takes all of the items in the cache and broadcasts them to all listeners so the listeners can (re)process them, if necessary.

What is the actual issue here?

**Comment by sttts** [comment]
It also does a LIST request before, doesn't it?

**Comment by ncdc** [comment]
We split relist from resync a while ago. The reflector only relists if it loses its watch. Resync is all about broadcasting the current state of the items in the cache to all listeners. Right?

**Comment by ncdc** [comment]
The kube-state-metrics issue has been closed (the root cause was something else). This is not a bug in the informer - everything is working as intended.
