### ISSUE TITLE
Add Safe** methods to Listers

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/client-go#386]
We are using listers to write own controllers. The issue is that it is very easy to inadvertently mutate objects extracted from Listers. I propose that

- Generated Code automatically return DeepCopied versoined in GET and LIST methods.
- Add Unsafe** version methods that return without DeepCopy.

I understand that this might be late for this type of changes. Thanks for the consideration.

cc: @sttts @deads2k

**Comment by liggitt** [comment]
> Generated Code automatically return DeepCopied versoined in GET and LIST methods.

That is prohibitively expensive, memory and CPU-wise

**Comment by tamalsaha** [comment]
May be SafeGet() methods can be added. It is really difficult to identify the bugs resulting from this.

**Comment by sttts** [comment]
Adding Unsafe** methods and switching the default ones to implicitly doing deepcopy is a breaking change as the performance characteristics change drammatically.
