### ISSUE TITLE
Is there demo shows how to use client-go to connect the k8s?

### ISSUE THREAD

**Issue by yingyan003** [kubernetes/client-go#387]
Are there any official docs show us how to use client-go to connect to the k8s? I mean the details  codes in programing. Because I am new with k8s and client-go, I hava tried to find the docs anywhere I can but failed.

**Comment by liggitt** [comment]
There are working examples in-repo (for example, at https://github.com/kubernetes/client-go/blob/master/examples/create-update-delete-deployment/main.go)
