### ISSUE TITLE
Support auth method for AWS

### ISSUE THREAD

**Issue by gururajs15** [kubernetes/client-go#388]
Hi Team,

Does client-go support AWS auth method?

I could see only Azure, Openstack, GCP, OIDC in import section of https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth 

import (
	        // Initialize all known client auth plugins.
	        _ "k8s.io/client-go/plugin/pkg/client/auth/azure"
	        _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	        _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	        _ "k8s.io/client-go/plugin/pkg/client/auth/openstack"
	)

**Comment by liggitt** [comment]
no, exec-based auth method is in alpha in 1.10, and will likely replace the in-tree azure, gcp, and openstack methods eventually

see https://github.com/kubernetes/features/issues/541 for status of the feature and https://kubernetes.io/docs/admin/authentication/#client-go-credential-plugins for documentation on how to use it in 1.10
