### ISSUE TITLE
support modifying an object in jsonpath package

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/client-go#390]
>var nodes = jp.apply(data, '$..author', function(value) { return value.toUpperCase() });
// [
//   { path: ['$', 'store', 'book', 0, 'author'], value: 'NIGEL REES' },
//   { path: ['$', 'store', 'book', 1, 'author'], value: 'EVELYN WAUGH' },
//   { path: ['$', 'store', 'book', 2, 'author'], value: 'HERMAN MELVILLE' },
//   { path: ['$', 'store', 'book', 3, 'author'], value: 'J. R. R. TOLKIEN' }
// ]

Have something similar to https://github.com/dchester/jsonpath#jpapplyobj-pathexpression-fn in our [jsonpath package](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/util/jsonpath) 

/kind feature

**Comment by huydinhle** [comment]
I saw you guys need help from a contributor. I would like to help. Although I don't really understand what's exactly the problem is

**Comment by nikhita** [comment]
@mengqiy can you elaborate ^^?

**Comment by mengqiy** [comment]
I'd imagine it have something like:

Given a jsonpath `string` and modifier function `func(interface{}) interface{}`.
Our jsonpath lib should provide the ability to apply the modifier function to the node(s) specified by the jsonpath.
For example, given the following json object
```
{
  "store": {
    "book": [ 
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      }, {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}
```
And having the modifier function and jsonpath
```
jsonpath := "$.store.book[1].author"
```
```
fn := func(in interface{}) interface{} {
  s := in.(string)
  return strings.ToUpper(s)
}
```
The new object will become:
```
{
  "store": {
    "book": [ 
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      }, {
        "category": "fiction",
        "author": "EVELYN WAUGH",
        "title": "Sword of Honour",
        "price": 12.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}
```

**Comment by sttts** [comment]
IMO this does not belong into client-go. We are not a json library. If we want more, either we use another library or we split out the jsonpath package from client-go in its own project.

**Comment by sttts** [comment]
Also compare https://github.com/kubernetes/kubernetes/blob/1db0024ec99cb2e4a2154df22008c27b344190e0/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/jsonpath_test.go, yet another internal jsonpath library. All that should go into k8s.io/jsonpath or similar.

**Comment by nikhita** [comment]
> All that should go into k8s.io/jsonpath or similar.

Is this still a "help wanted" issue? Removing help-wanted for now.

/remove-help

**Comment by mengqiy** [comment]
Maybe not.
Creating a new repo in the org is non-trivial. This issue may be not easy for new contributors.
