### ISSUE TITLE
Release v7.0.0

### ISSUE THREAD

**Issue by sttts** [kubernetes/client-go#392]
TODO:

- [x] smoke test with https://gist.github.com/sttts/06f5e440540ac629a313f28ad8002277
- [x] update release notes https://github.com/kubernetes/client-go/pull/389
- [x] update README https://github.com/kubernetes/client-go/pull/391

**Comment by sttts** [comment]
@nikhita @caesarxuchao please check https://github.com/kubernetes/client-go/releases/tag/v7.0.0-rc. Smoke tests were green. From my side it's ready to go.

**Comment by nikhita** [comment]
@sttts :+1:

**Comment by nikhita** [comment]
https://github.com/kubernetes/client-go/releases/tag/v7.0.0 exists! :tada: 

Closing.
/close
