### ISSUE TITLE
Panics within cache.IndexerInformer's OnDelete watch handlers don't propagate up

### ISSUE THREAD

**Issue by madari** [kubernetes/client-go#395]
This can be reproduced by creating a cache.NewIndexerInformer and panicing in its OnDelete resource event handler.

**Comment by sttts** [comment]
Can you create a minimal code snippet showing the error? Or maybe even create a PR fixing this (cc me for review)?

**Comment by sttts** [comment]
@ash2k do we lack Go doc for this behaviour?
