### ISSUE TITLE
ConfigMap.Data not working with multilines

### ISSUE THREAD

**Issue by ReneHerrero** [kubernetes/client-go#396]
Hi,
Not sure if this is a bug, or if the problem is between the chair and the keyboard: the Data map[string]string in the ConfigMap struct does not work with new lines.

Sample code is attached (renamed it from config_map.go to config_map.log) 

[config_map.log](https://github.com/kubernetes/client-go/files/1904614/config_map.log)

Thanks

**Comment by ReneHerrero** [comment]
Found something interesting after some desperate exhaustive trial and error: the tabs (\t) where the causing the newlines (\n) to not be recognized???

Working now, but I have a feeling this is a bug?

**Comment by sttts** [comment]
For client-go the data is just a blob, i.e. it does not look into it at all, but sends it to the server. 

If it is fixed in your code, can we close this issue?

**Comment by ReneHerrero** [comment]
Thanks for the reply @sttts 

Yup, I'm good to go, closing this out

**Comment by franpog859** [comment]
Do you have any idea why it happens? Good that we have a workaround but it does not seem right

**Comment by franpog859** [comment]
Removing every space at the end of the template line worked. It's super not intuitive though. It could be mentioned somewhere in the documentation
