### ISSUE TITLE
Option to rollback using client-go 

### ISSUE THREAD

**Issue by anumantharaja** [kubernetes/client-go#398]
I would like to rollback the deployment to a particular revision( rollout history) using client-go(6.0.0) library of k8s. I created a deployment using workload API object apps/v1beta2 . Seems in apps/v1beta2 there is no ".spec.rollbackTo options". Where can i find the options to rollback to particular revision using client-go(6.0.0) library.

**Comment by maxwell92** [comment]
Does it means the struct `DeploymentRollback` and `RollbackConfig` is no more needed or existing? @janetkuo
