### ISSUE TITLE
How to get the node on which a pod is running?

### ISSUE THREAD

**Issue by zwtj** [kubernetes/client-go#399]
`kubectl get pods -o wide` returns a `NODES` column that shows where each pod is running. Given a pod name, how can I get the corresponding node name? I couldn't find a way to get it from `v1.Pod`.

**Comment by lcwxz1989** [comment]
mark   i also  have this problem

**Comment by ananthoju24** [comment]
kubectl get pod -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName --all-namespaces

**Comment by davidpellcb** [comment]
kubectl get pod PODNAME -o jsonpath='{.spec.nodeName}'

**Comment by CH-AhmetBombaci** [comment]
kubectl get pod PODNAME -o wide
