### ISSUE TITLE
Error while deleting services

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes/client-go#409]
I am trying to delete bunch of services using following line,

```
err = c.kubeClient.CoreV1().Services(c.namespace).DeleteCollection(&metav1.DeleteOptions{},metav1.ListOptions{LabelSelector: selector})
```

I am getting following error,

```
the server does not allow this method on the requested resource
```

**Comment by liggitt** [comment]
services do not support DeleteCollection. You need to list/iterate on deletion

**Comment by surajnarwade** [comment]
@liggitt thanks, it should be documented somewhere

**Comment by liggitt** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#-strong-write-operations-strong--165 lists the write operations supported by services and does not include deletecollection

**Comment by surajnarwade** [comment]
@liggitt thanks a lot, closing this issue

**Comment by harpratap** [comment]
@liggitt Is there a technical reason why deleteCollection is purposely not supported for services? Or is it just a missing feature?

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/pull/85802#issuecomment-561239845
