### ISSUE TITLE
release 1.5 doesn't build

### ISSUE THREAD

**Issue by schmohlio** [kubernetes/client-go#41]
Hi all,

Thank you for making the `client-go` available!

I'm having trouble generally using the library with release 1.5 (needed for google auth). The only process I was able to get working involved checkout release 1.5, `godep restore`, and copying it over to a k8s.io directory in my `src/` folder.  This allowed me to get the examples up and running, but doesn't allow me to use `godep save` once i want to save my host project.

Would it be possible to get `go get k8s.io/kubernetes/client-go/1.5/...` working to eschew the complexity of messing with git? 

Furthermore, simply checking out release-1.5 and running `godep install ./...` yields the following type of errors 
```
can't load package: package github.com/kubernetes/client-go/1.5/tools/cache: code in directory .../src/github.com/kubernetes/client-go/1.5/tools/cache expects import "k8s.io/client-go/1.5/tools/cache"
```

**Comment by lavalamp** [comment]
That last error is telling you that the source code ended up in the wrong place in your GOPATH. How did you "check it out"?

**Comment by lavalamp** [comment]
I think you have an extra "kubernetes" in your `go get` path, but `go get k8s.io/client-go/...` gave me some errors just now, too. Maybe @caesarxuchao can say what the proper thing is.

**Comment by caesarxuchao** [comment]
Try `go get k8s.io/client-go/kubernetes`.

`go get k8s.io/client-go/...` failed because the /examples are written against packages in 1.4 or 1.5 branches, and `go get` cannot find the packages in the master branch.

**Comment by schmohlio** [comment]
`go get k8s.io/client-go/kubernetes .` and checking out the release worked. Thanks so much for the quick response!
