### ISSUE TITLE
How to get all pods running in a given node.

### ISSUE THREAD

**Issue by bbhikkaji** [kubernetes/client-go#410]
I am trying to get all pods in a given node. Can list all nodes by following but node struct having NodeSpec and NodeStatus does not have container information.

 nodes, _ := clientset.CoreV1().Nodes().List(metav1.ListOptions{})

**Comment by ericchiang** [comment]
Use a field selector

```go
nodeName := "my-node"
pods, err := clientset.CoreV1().Pods("").List(metav1.ListOptions{
    FieldSelector: "spec.nodeName=" + nodeName,
})
```

/close

**Comment by bbhikkaji** [comment]
Tks

**Comment by GLYASAI** [comment]
> Use a field selector
> 
> ```go
> nodeName := "my-node"
> pods, err := clientset.CoreV1().Pods("").List(metav1.ListOptions{
>     FieldSelector: "spec.nodeName=" + nodeName,
> })
> ```
> 
> /close

thx
