### ISSUE TITLE
importing goclient takes long time to run.

### ISSUE THREAD

**Issue by bbhikkaji** [kubernetes/client-go#412]
I have a simple program using goclient but takes a long time run. In the following case takes about 46 seconds.

bb#time go run example.go
<output>
real    0m21.933s
user    0m46.468s
sys     0m3.988s

Here is the program.

package main

import (
        "flag"
        "fmt"
        "os"
        "path/filepath"
        //"time"

        //"k8s.io/apimachinery/pkg/api/errors"
//      v1 "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/client-go/kubernetes"
        "k8s.io/client-go/tools/clientcmd"
)

func main() {
        var kubeconfig *string
        if home := homeDir(); home != "" {
                kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
        } else {
                kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
        }
        flag.Parse()

        // use the current context in kubeconfig
        config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
        if err != nil {
                panic(err.Error())
        }

        // create the clientset
        clientset, err := kubernetes.NewForConfig(config)
        if err != nil {
                panic(err.Error())
        }

        namespace := "default"
        nodes, _ := clientset.CoreV1().Nodes().List(metav1.ListOptions{})
        for _, node := range nodes.Items {
                pods, _ := clientset.CoreV1().Pods(namespace).List(metav1.ListOptions{
                        FieldSelector: "spec.nodeName=" + node.Name,
                })
                fmt.Printf("\t%s:\n", node.Name)
                for _, pod := range pods.Items {
                        fmt.Printf("\t\t%s: %s\n",pod.Name, pod.Status.PodIP)
                }
        }
}

func homeDir() string {
        if h := os.Getenv("HOME"); h != "" {
                return h
        }
        return os.Getenv("USERPROFILE") // windows
}

**Comment by ericchiang** [comment]
This is somewhat expected. client-go imports a lot of packages and these can take a while to compile. You can use `go build -v` to display which dependencies are compiling to get a sense of what's taking so long.

[Go 1.10 introduced build caching](https://golang.org/doc/go1.10#build) that will significantly speed this up.
