### ISSUE TITLE
how to attach label to some node by using client-go

### ISSUE THREAD

**Issue by jianzi123** [kubernetes/client-go#414]
when using clientset.CoreV1().Nodes().Update(node), I found this orrors:
`Operation cannot be fulfilled on nodes "node1": the object has been modified; please apply your changes to the latest version and try again`.
Ask if anyone can help, thanks.

**Comment by liggitt** [comment]
Nodes update their heartbeat timestamp every ~10 seconds, which makes it likely a get/update will hit a conflict error. You can either retry on conflict errors or submit the label addition as a patch request instead (which makes the server retry application of the patch server-side)
