### ISSUE TITLE
API server not set from kubecontext

### ISSUE THREAD

**Issue by benkeil** [kubernetes/client-go#415]
If you use the newest version of `github.com/imdario/mergo` you can't init the config via a kubecontext.

from https://github.com/kubernetes/client-go/blob/e1b1ad35184abf07819079215c7374ade5b576c9/tools/clientcmd/client_config.go#L420 works with

```
name = "github.com/imdario/mergo"
revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
``` 

For 

```
name = "github.com/imdario/mergo"
version = "v0.3.4"
```

you need to use 

```go
mergo.Merge(mergedClusterInfo, configClusterInfo, mergo.WithOverride)
```

**Comment by liggitt** [comment]
That's correct. That library reversed its API. You must use the same versions as specified in the client-go dependencies file to get expected results.

**Comment by benkeil** [comment]
Thank you, I think it should be commented in the documentation.
