### ISSUE TITLE
client-go does not respect system trusted CAs

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/client-go#416]
I'm trying to debug a Go program using client-go using mitmproxy.

Therefore I'm starting my program with environment variable `HTTPS_PROXY=:8080`.

The rest of the program is working fine, however, the API calls made to Kubernetes apiserver are failing with error:

    Get https://x.x.x.x/api/v1/services: x509: certificate signed by unknown authority

I'm authenticating to the cluster as follows:

	config := &rest.Config{
		TLSClientConfig: rest.TLSClientConfig{
			CAData: ca,
		},
		Host:        "https://x.x.x.x",
		BearerToken: tok.AccessToken,
	}

**Comment by liggitt** [comment]
To use system CAs, you must not specify CAData or CAFile

**Comment by ahmetb** [comment]
That makes sense. I can probably also use `Insecure:true` to debug this.
