### ISSUE TITLE
App Engine support

### ISSUE THREAD

**Issue by adieu** [kubernetes/client-go#42]
My app running on appengine needs to control k8s cluster running in container engine. So I patched v2.0.0-alpha.0 release to make it work.

The patch is at https://github.com/adieu/client-go/commit/a2092b1c5c83a8b1a761ad9222de80a20f310312

I'm not quite sure if we have plan to support appengine. If we do, I'd be pleased to create a PR with my patch.

I also tried to apply the patch with the latest master, it wouldn't work since latest commits use `unsafe` package for conversion. We might have to make another patch to disable conversion for appengine.

**Comment by lavalamp** [comment]
Hm, that's unfortunate. `unsafe` shouldn't be required by the client, or at
the very least should be an optional package that the downstream consumer
can either link in or not. @smarterclayton @ceasarxuchao

I don't think appengine is the only environment where `unsafe` isn't
allowed.

**Comment by adieu** [comment]
Is it @caesarxuchao ?

**Comment by caesarxuchao** [comment]
@adieu sorry I don't understand why is your patch needed to make client-go work in appengine. Does appengine have restrictions on imported packages?

**Comment by caesarxuchao** [comment]
`unsafe` slip in client-go because types.go are in the same package as the conversion functions. We need to reorganize the api folders. Is that a priority for 1.6?

**Comment by lavalamp** [comment]
Yeah, appengine go support doesn't provide unsafe. I will check on the
priority.

**Comment by adieu** [comment]
@caesarxuchao There are two major limitations in appengine:

- No `unsafe` and `syscall` packages
- The max size of compiled binary is 32M

Therefor, my patch removed dependencies for packages using `unsafe` and also some generated code to make client-go smaller.

- Removed protobuf related code because `github.com/gogo/protobuf` imported `unsafe`
- Move openapi related functions to a seprate file beause `github.com/go-openapi/swag` use `github.com/mailru/easyjson` and it imported `unsafe`
- `http.DefaultTransport` isn't available on appengine. So I patched `defaultTransport` in `pkg/util/net/http.go`.

The patch is based on `v2.0.0-alpha.0` release and it wouldn't work with the latest master because new conversion functions uses `unsafe`.

**Comment by smarterclayton** [comment]
I thought we were taking conversions out of client-go?  At minimum we can
generate both conversion types and flag it.  But not having protobuf is
going to be a blocker for our controller libraries.
