### ISSUE TITLE
[Question] How to watch for deployments for new version?

### ISSUE THREAD

**Issue by SachinMaharana** [kubernetes/client-go#422]
https://github.com/kubernetes/client-go/issues/132

I am following the above example and issue, but i am not getting to make it work. Did check the documentation that the api has changed.
https://kubernetes.io/blog/2018/01/introducing-client-go-version-6/

Can anybody point me out the changes i need to make in the example of the above issue?
Thanks.

**Comment by rusenask** [comment]
Hi, check out example here: https://github.com/keel-hq/keel/blob/master/internal/k8s/watcher.go#L19

**Comment by SachinMaharana** [comment]
@rusenask Thanks. That was very helpful.
