### ISSUE TITLE
Client using Google Service account Config

### ISSUE THREAD

**Issue by njyeti** [kubernetes/client-go#424]
Greetings,
Using this client library for the first time and planning on using the Google Service account for instantiating the client for query our GKE cluster.  While using the below code, I'm running into 

`x509: certificate signed by unknown authority`

Upon debugging, it looks like it is not setting the Authorization header while sending the request to the cluster. WrapperTansport/Transport is grabbing the OAuth token, however, it's not set while sending the final request to the cluster. Can you please give me a pointer on how to fix this or not sure whether it is a bug therefore starting out with this ticket. I won't be surprise, if I'm not using the client correctly as I'm using this first time. Any pointer will be much appreciated

`func main() {

	ctx := context.Background()
	serviceaccount := `{
  		"type": "service_account",
  		"project_id": "<project ID>",
  		"private_key_id": "<private key ID>",
  		"private_key": "<private key>",
  		"client_email": "<email address>",
  		"client_id": "<client ID>",
  		"auth_uri": "https://accounts.google.com/o/oauth2/auth",
  		"token_uri": "https://accounts.google.com/o/oauth2/token",
  		"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  		"client_x509_cert_url": "x509 URL"
	}
	`

	cfg, err := google.JWTConfigFromJSON([]byte(serviceaccount), "https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/userinfo.email")

  	if err != nil {
  		fmt.Println(err)
  		return
	}

	config := &rest.Config{
		Host: "<Cluster IP>",
		TLSClientConfig: rest.TLSClientConfig{
		       Insecure: false,
		       CAFile: "<path to the ca file>",
	         },
		WrapTransport: func(rt http.RoundTripper) http.RoundTripper {
			return &oauth2.Transport{
				Source: cfg.TokenSource(ctx),
			}
		},
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		fmt.Printf("failed to get k8s client set from config: %s\n", err)
		return
	}

	ns, err  := clientset.CoreV1().Namespaces().List(v1.ListOptions{})
	if err != nil {
		fmt.Printf("failed to get the ns: %s\n", err)
	}

	for _, item := range ns.Items {
		fmt.Println(item.Name)
	}
}`

**Comment by njyeti** [comment]
So far, I'm able to pinpoint the issue is because of the CA file therefore getting the above issue. However, the exact same set up for Basic Auth works
`&rest.Config{
	Username: "<username>",
	Password: "<password>",
         Host: "<Cluster IP>",
        TLSClientConfig: rest.TLSClientConfig{
		Insecure: false,
		CAFile: "<path to the ca file>",
	},
	WrapTransport: func(rt http.RoundTripper) http.RoundTripper {
		return &oauth2.Transport{
			Source: cfg.TokenSource(ctx),
		}
	}
... ... ...
`

**Comment by while-loop** [comment]
For anyone also with this issue, the supplied `oauth2.Transport` wrapper must supply the given `rt` as the base round tripper to include `TLSClientConfig`'s certpool.

```
var cluster *containerpb.Cluster //  "google.golang.org/genproto/googleapis/container/v1"

// get service account token via `GOOGLE_APPLICATION_CREDENTIALS` or gcp machine
ts, _ := google.DefaultTokenSource(ctx, defaultScopes...) 

caData, _ := base64.StdEncoding.DecodeString(cluster.MasterAuth.ClusterCaCertificate)
config := &rest.Config{
	Host: cluster.Enpoint,
	TLSClientConfig: rest.TLSClientConfig{
	       Insecure: false,
	       CAData: caData,
         },
	WrapTransport: func(rt http.RoundTripper) http.RoundTripper {
		return &oauth2.Transport{
			Source: ts,
			Base: rt,    // <-------- add this
		}
	},
}
```
