### ISSUE TITLE
Conflict between /apps/v1 and apps/v1beta1

### ISSUE THREAD

**Issue by SachinMaharana** [kubernetes/client-go#426]
When creating custom controller, i get the following error:

https://play.golang.org/p/qYc_VSGtfFl
612 reflector.go:205]........Failed to list *v1.Deployment: the server could not find the requested resource

But when i change line 78 from 
watch(clientSet.**AppsV1()**.RESTClient(), new(apps_v1.Deployment), "deployments")
to 
watch(clientSet.**AppsV1beta1()**.RESTClient(), new(apps_v1.Deployment), "deployments")
 it seems to work fine.

https://play.golang.org/p/0O3DN4Tyea7

Am i missing something, or maybe mismatch of clientset object?

**Comment by liggitt** [comment]
what version server are you running against? deployments in the apps/v1 API group only exist in 1.9 and newer

**Comment by SachinMaharana** [comment]
I am running it in gke cluster. Here is the info:

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2
018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}

it seems it is 1.8. I guess it will be safe to use /apps/v1beta1. 
Thanks for pointing this out.

**Comment by liggitt** [comment]
> it seems it is 1.8. I guess it will be safe to use /apps/v1beta1.
> Thanks for pointing this out.

sure

/close
