### ISSUE TITLE
How to modify the post body size

### ISSUE THREAD

**Issue by shigy123456** [kubernetes/client-go#428]
When I use client-go to create a new crd resource object, the object is larger, the creation fails, and when the object is smaller, I can create it. How should I modify the post size limit so that my object can be created successfully.
my code is:
               resp, err := c.client.Post().
		Namespace("default").
		Resource("externalservices").
		Body(externalservice).
		DoRaw()
the externalservice is my post object.

**Comment by shigy123456** [comment]
If you don't change the maximum limit, you need to slice, what's the maximum limit?

**Comment by hzxuzhonghu** [comment]
Any error info? it seems no size limit for request body both server/client side.

**Comment by shigy123456** [comment]
yes, it has  problems,i want to know  how to  modify the post size limit,if i can not modify ,i must split dataset to small part,if i can modify ,it is userful to me.

**Comment by hzxuzhonghu** [comment]
Can you paste error here?

**Comment by shigy123456** [comment]
the error log can not find，it is 23 days ago，you can use this code simulation this scene:
resp, err := c.client.Post().
Namespace("default").
Resource("externalservices").
Body(externalservice).
DoRaw()
the object externalservice'port number is 65535,

**Comment by sttts** [comment]
There are size limits for objects that the server accepts, compare https://github.com/kubernetes/kubernetes/blob/32bc319f4b41744c8b9176a58a0254a6937aaa29/test/integration/master/synthetic_master_test.go#L297

**Comment by shigy123456** [comment]
yes,what is the limit size ? how to modify the limit size?

**Comment by sttts** [comment]
The limit cannot be changed. etcd is our bottle neck here. If you objects grow bigger, you have to find another way to store the data than putting everything into one object and its annotations.

**Comment by shigy123456** [comment]
ok,i know,i have split my object to multiple

**Comment by shigy123456** [comment]
ths
