### ISSUE TITLE
[qestion] release-2.0 compatibility

### ISSUE THREAD

**Issue by ngortheone** [kubernetes/client-go#43]
There is a branch named `release-2.0`. But the ReadMe file looks either irrelevant or outdated.
Is it a truly another release or just  `release-1.5` renamed?
Anyway, that would be great to know compatibilities of this release 
Thanks

**Comment by caesarxuchao** [comment]
The branch is not stable, meaning the public interface defined in that branch are subject to change. If you check the tags, there is only a v2.0.0-alpha.0 tag.

The 2.0 branch has gathered many upstream changes that are not available in the release-1.5 branch, for example, renaming petset to statefulset, renaming schedulejob to cronjob, etc.

We will put a v2.0.0 stable tag on the release-2.0 branch once the upstream finalize its 1.5 release.

**Comment by caesarxuchao** [comment]
For the compatiblity between client-go and the kubernetes cluster, you can check this matrix: https://github.com/kubernetes/client-go#compatibility-matrix.

release-2.0 is not in the matrix yet, but it should be compatible with 1.3-1.5 cluster.
