### ISSUE TITLE
ExecConfig args duplicated when using BuildConfigFromFlags

### ISSUE THREAD

**Issue by gregf1** [kubernetes/client-go#431]
The out-of-cluster-client-configuration example uses `config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)`

If I use this to load a kubeconfig file containing an exec provider
```
users:
  name: foo
  user:
    exec:
      command: foo-command
      args:
      - arg1
      - arg2
```
The args end up being duplicated.  The resulting command gets executed as
`foo-command arg1 arg2 arg1 arg2`

The problem appears to come from
https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#L227
where the config is merged.  For maps and structs this is fine, but for slices mergo is appending the values.

client-go is using a four year old version of mergo, but from mergo >= 0.3.5 the default append slice behavior is changed so if I upgrade mergo the problem goes away.

Here is a test case that demonstrates the problem
```
package main

import (
        "io/ioutil"
        "os"
        "reflect"
        "testing"

        "k8s.io/client-go/tools/clientcmd"
)

func TestAuthConfig(t *testing.T) {
        content := `
apiVersion: v1
clusters:
- cluster:
    server: https://localhost:8080
  name: foo-cluster
contexts:
- context:
    cluster: foo-cluster
    user: foo-user
    namespace: bar
  name: foo-context
current-context: foo-context
kind: Config
users:
- name: foo-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - arg-1
      - arg-2
      command: foo-command
`
        tmpfile, err := ioutil.TempFile("", "kubeconfig")
        if err != nil {
                t.Fatal(err)
        }
        defer os.Remove(tmpfile.Name())
        if err := ioutil.WriteFile(tmpfile.Name(), []byte(content), 0666); err != nil {
                t.Fatal(err)
        }
        config, err := clientcmd.BuildConfigFromFlags("", tmpfile.Name())
        if err != nil {
                t.Fatal(err)
        }
        if !reflect.DeepEqual(config.ExecProvider.Args, []string{"arg-1", "arg-2"}) {
                t.Fatalf("Got args %v when they should be %v\n", config.ExecProvider.Args, []string{"arg-1", "arg-2"})
        }

}
```
The test fails with the version of mergo specified by client-go and passes with mergo >= 0.3.5

**Comment by liggitt** [comment]
update to 0.3.5 is in progress in https://github.com/kubernetes/kubernetes/pull/65779, we just need to make sure we have good coverage of the merge priority cases to ensure there are no regressions

**Comment by liggitt** [comment]
I actually can't get that test to fail with the version of mergo [used by client-go](https://github.com/kubernetes/client-go/blob/master/Godeps/Godeps.json#L157-L160) (6633656539c1639d9d78127b7d47c622b5d7b6dc) or >= 0.3.5...

**Comment by liggitt** [comment]
no worries, thanks for taking the time to let us know. I think we'll proceed with https://github.com/kubernetes/kubernetes/pull/65779 anyway, in case you're interested
