### ISSUE TITLE
Support labelSelector for list and watch filtering

### ISSUE THREAD

**Issue by Itfly** [kubernetes/client-go#433]
I want to list all the jobs created by my specific platform that all the jobs  are labeled by `"job-from": "aiflow"`. However the method `NewListWatchFromClient` in package cache only support `fieldSelector`, it can not to filter jobs by using labels directly. I can create the `optionsModifer` and call `NewFilteredListWatchFromClient` to list/watch with labelSelector:

```
optionsModifer := func(options *metav1.ListOptions) {
		options.LabelSelector = myLabelSelector
	}
watchList := cache.NewFilteredListWatchFromClient(restClient, "jobs", metav1.NamespaceAll, optionsModifer)

```

It's better to add a method to new ListWatch with labelSlector.

**Comment by sttts** [comment]
Why is it better? We intentionally added `NewFilteredListWatchFromClient` to avoid adding yet another func for every use-case. `NewListWatchFromClient` exists for backwards compatibility.

/close

**Comment by Itfly** [comment]
I do not know `NewListWatchFromClient` is for backwards compatibility. That's reasonable.
