### ISSUE TITLE
Unable to find semantic version for constraint k8s.io/client-go v8.0.0

### ISSUE THREAD

**Issue by dvasilen** [kubernetes/client-go#434]
An attempt to run `glide up -v` on `glide.yaml` 

```
package: <my-package-name>
import:
- package: k8s.io/client-go
  version: v8.0.0
```

Results in 

```
Unable to find semantic version for constraint k8s.io/client-go v8.0.0
```

Has anyone been able to upgrade to v8.0.0 client?

**Comment by sttts** [comment]
This is my test-project (which worked fine): https://github.com/sttts/kube-glide-test/blob/v8.0.0/glide.yaml

**Comment by dvasilen** [comment]
OK, thanks, so it should be something on my end then...

**Comment by dvasilen** [comment]
Had to upgrade to glide v0.13.1 to fix the issue.
