### ISSUE TITLE
Proposal: Don't vendor glog

### ISSUE THREAD

**Issue by robfig** [kubernetes/client-go#435]
The vendored glog dependency is causing me a huge headache trying to use the kubernetes client from a large glock-managed codebase due to the "flag redefinition" error.  Forking the repos and removing the vendor directories doesn't help me either because of all the cross imports. I'll look for a tool that can do the mass import renaming to use my fork, but wanted to raise an issue to see if it's an option to not vendor glog? glog never has backwards incompatible changes introduced, so regardless of your feelings on vendoring it seems inarguable that it introduces more hassle than it's worth in this particular case. Thanks!

**Comment by liggitt** [comment]
in order to guarantee reproducible builds, and no external dependencies, all dependencies are vendored, no exceptions.

 Rather than import renaming, the typical solution is to choose the option in your vendoring tool to flatten dependencies, so you end up with a single  level vendor tree 

/close

**Comment by sttts** [comment]
> Forking the repos and removing the vendor directories

Don't use our master branch. The release branches don't have this problem.

**Comment by robfig** [comment]
Ohhh, that's the missing information I needed. Thank you.

**Comment by sttts** [comment]
:-)
