### ISSUE TITLE
Fake Client should generate name for resources

### ISSUE THREAD

**Issue by copejon** [kubernetes/client-go#439]
The Fake Clientset does not behave as expected when the GenerateName field is defined in a resource.   On creation, the resource does not get a Name with a unique suffix.  

When 2 or more resources are created by the Fake ClientSet in testing, an api error occurs because of a Name collision, e.g. "Pod 'default/' already exists" (where Name is an empty string).

This has become a problem for us in testing a custom controller that creates 2 pods sequentially with the GenerateName field defined.

cc @screeley44 @jeffvance

**Comment by liggitt** [comment]
the fake clientset doesn't attempt to duplicate server-side behavior like validation, name generation, uid assignment, etc. if you want to test things like that, you can add reactors to mock that behavior.

**Comment by mihaitodor** [comment]
If anyone is trying to figure out how to add such reactors, I wrote a detailed explanation here: https://stackoverflow.com/questions/68794562/kubernetes-fake-client-doesnt-handle-generatename-in-objectmeta/68794563#68794563
