### ISSUE TITLE
Please add examples and/or docs on how to create PVS, ResourceList, Storage size, etc.

### ISSUE THREAD

**Issue by fabstao** [kubernetes/client-go#444]
Hi!
Please add examples and/or docs on how to create PVS, ResourceList, Storage size, etc.

Is hard trying to guess a lot of things like this:

`Requests: apiv1.ResourceList{`
  `    Storage: resource.Quantity(20),`
`    },` 

Is wrong and can't guess how it should be done, nor where the docs are,

Thanks a lot!

**Comment by Glennvd** [comment]
+1 for this, some proper documentation would be helpful. Or ideally we could extend the examples.

**Comment by gsf** [comment]
Agreed on the need for documentation. In the meantime, to answer the specific question above, it appears `resource` has a `ParseQuantity` method:

https://github.com/kubernetes/apimachinery/blob/d19e3354dd8cc16b92ff36926371c41f30b1025e/pkg/api/resource/quantity.go#L263
