### ISSUE TITLE
leaderelection: LeaseDurationSeconds field not used

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/client-go#445]
Unless I'm mistaken, there's no good use of `LeaderElectionRecord.LeaseDurationSeconds` field.

https://github.com/kubernetes/client-go/blob/0b97d57a869d33ee2fe3cc567d0f8553c70357b0/tools/leaderelection/leaderelection.go#L243

There are no references to this field in the client-go.

It's very likely that the person who started the leader election has configured this through `LeaderElectionConfig` and they have a more accurate representation of this value (time.Duration) rather than int seconds.

Maybe I'm just having trouble understanding why this value is exposed in the record . It doesn't seem like anyone's using it.

**Comment by sttts** [comment]
Can you trace when this was introduced?

**Comment by ahmetb** [comment]
https://github.com/kubernetes/kubernetes/commit/68cf14695c5acc75dc1fa97d2e1a57e5484fe353 

@mikedanese do you recall the reasoning behind this field?
