### ISSUE TITLE
NewNonInteractiveDeferredLoadingClientConfig doesn't override cluster context

### ISSUE THREAD

**Issue by ynqa** [kubernetes/client-go#447]
I'd like to get a GKE cluster config using `NewNonInteractiveDeferredLoadingClientConfig` like the following codes, but the config remains default values.  On the other hands, it's possible to get the config if you use `clientcmd.BuildConfigFromFlags("", "/path/to/.kube/config")`.

```go
package main

import (
	"fmt"
	
	"k8s.io/client-go/tools/clientcmd"
)

func main() {
    loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
    loadingRules.DefaultClientConfig = &clientcmd.DefaultClientConfig
    loadingRules.ExplicitPath = "/path/to/.kube/config"
    configOverrides := &clientcmd.ConfigOverrides{
        ClusterDefaults: clientcmd.ClusterDefaults,
        CurrentContext:  "",  // or "current-context name"
    }

    config, _ := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides).ClientConfig()
    fmt.Println(config)
}
```

result in below:
```
$ go run main.go
&{http://localhost:8080  {  <nil> <nil>}    { [] map[]} <nil> <nil> <nil> {false     [] [] []}  <nil> <nil> 0 0 <nil> 0s <nil>}
```

version in dep:
```
name = "k8s.io/client-go"
version = "kubernetes-1.11.0"
```

**Comment by sttts** [comment]
Isn't the issue that the `CurrentContext` is empty here? To make that work we have to distinguish between empty and unset, e.g. via turning it into a pointer.

**Comment by ynqa** [comment]
@sttts Thanks for replying. I checked by `kubectl config view/current-context` but it indicates target cluster context.

**Comment by ynqa** [comment]
@sttts I also filled in a value from `kubectl config view/current-context` in `CurrentContext`, but it came up to the same result.

**Comment by ynqa** [comment]
@sttts I added mergo package on `Gopkg.toml` like [istio's](https://github.com/istio/istio/blob/master/Gopkg.toml#L371-L373), and work well.
```
[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
```

**Comment by sttts** [comment]
Which version do we require in client-go (compare Godeps.json)?

**Comment by liggitt** [comment]
currently 6633656539c1639d9d78127b7d47c622b5d7b6dc

https://github.com/kubernetes/client-go/blob/0b97d57a869d33ee2fe3cc567d0f8553c70357b0/Godeps/Godeps.json#L153-L156

**Comment by ynqa** [comment]
@sttts @liggitt Thanks. It's necessary to install this pkg with this version yourself if you use dep.
