### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by talhairfanbentley** [kubernetes/client-go#449]
I'm trying to build my code through docker build, and I've been doing it successfully, and today suddenly I get this error:
`/k8s.io/client-go/transport/round_trippers.go:437:9: undefined: strings.Builder`
What can be the issue.

**Comment by nikhita** [comment]
> What can be the issue.

@talhairfanbentley are you using Go version 1.10 or higher? 

The `strings.Builder` change was introduced recently and also broke our bot: see https://github.com/kubernetes/publishing-bot/pull/74. Updating your go version should solve the problem.

**Comment by talhairfanbentley** [comment]
thanks,, fixed.
