### ISSUE TITLE
Support for Exec & Attach APIs

### ISSUE THREAD

**Issue by ianlewis** [kubernetes/client-go#45]
Currently the client doesn't seem to support the Exec into container, attach to container APIs. The client should support those APIs.

**Comment by JrCs** [comment]
Yes its will be great to support exec and attach to container from the client-go.
I really need it.

**Comment by lavalamp** [comment]
I agree, we should support these.

**Comment by rmohr** [comment]
Until the work on this ticket is done, it is pretty simple to use ther `rest.Config` to create your own exec call. I created a [simple example](https://github.com/rmohr/kubernetes-custom-exec). [A detailed description](http://rmohr.github.io/kubernetes/2017/05/15/writing-a-custom-kubectl-exec-command) is also available.

**Comment by JrCs** [comment]
@rmohr thanks for the simple example.
The only problem with your example is that you can't detect if the command return with a non zero exit code.

**Comment by topherbullock** [comment]
I need this enough to pick it up and work on a PR.

Seems like `kubectl` [would also benefit from this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/exec.go#L309-L323) 

Going to make an effort at adding client support for an `Exec()` method (not sure where it should live) which allows different `Executors`, and has a default one [like this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/exec.go#L94-L114).

Thoughts? Suggestions? Cryptic warnings?

**Comment by geekodour** [comment]
What's the update on this?

**Comment by LeoLiuYan** [comment]
So should we open this issue?

**Comment by geekodour** [comment]
I'll be happy to work on this, If provided some initial pointers. The current way to do this seems to be using websockets only. right?
