### ISSUE TITLE
allow custom transport with TLS certificate options

### ISSUE THREAD

**Issue by szuecs** [kubernetes/client-go#452]
I would like to setup a custom Transport with custom TLS certificate options.
This disallows it for whatever reason: https://github.com/kubernetes/client-go/blob/master/transport/transport.go#L31-L32

## Example

client config
```
        ...
	ctx, cancel := context.WithCancel(context.Background())
	kubeConfig, err := configureKubeConfig(config.APIServer, 5*time.Second, ctx.Done())
	if err != nil {
		log.Fatalf("Failed to setup Kubernetes config: %v", err)
	}
	client, err := kubernetes.NewForConfig(kubeConfig)
	if err != nil {
		log.Fatalf("Failed to setup Kubernetes client: %v", err)
	}
       ....

func configureKubeConfig(apiServerURL *url.URL, timeout time.Duration, stopCh <-chan struct{}) (*rest.Config, error) {
	tr := &http.Transport{
		DialContext: (&net.Dialer{
			Timeout:   timeout,
			KeepAlive: 30 * time.Second,
			DualStack: false, // K8s do not work well with IPv6
		}).DialContext,
		TLSHandshakeTimeout:   timeout,
		ResponseHeaderTimeout: 10 * time.Second,
		MaxIdleConns:          10,
		MaxIdleConnsPerHost:   2,
		IdleConnTimeout:       20 * time.Second,
	}

	// We need this to reliably fade on DNS change, which is right
	// now not fixed with IdleConnTimeout in the http.Transport.
	// https://github.com/golang/go/issues/23427
	go func(d time.Duration) {
		for {
			select {
			case <-time.After(d):
				tr.CloseIdleConnections()
			case <-stopCh:
				return
			}
		}
	}(20 * time.Second)

	if apiServerURL != nil {
		return &rest.Config{
			Host:      apiServerURL.String(),
			Timeout:   timeout,
			Transport: tr,
		}, nil
	}

	config, err := rest.InClusterConfig()
	if err != nil {
		return nil, err
	}

	config.Timeout = timeout
	config.Transport = tr
	return config, nil
}
```

Log output
```
time="2018-08-17T13:59:30Z" level=fatal msg="Failed to setup Kubernetes client: using a custom transport with TLS certificate options or the insecure flag is not allowed"
```

**Comment by szuecs** [comment]
@liggitt any workaround for this?

As far as I understnad I have to then set `config.TLSClientConfig = nil` and add a `TLSClientConfig` to my custom transport. The problem is that the fields from does not match. 
I will try something, but maybe you have an idea?

**Comment by liggitt** [comment]
> @liggitt any workaround for this?

the workaround is to make your custom transport implement the TLS options you want

> As far as I understnad I have to then set config.TLSClientConfig = nil and add a TLSClientConfig to my custom transport. The problem is that the fields from does not match.

If you have a `rest.Config`, you can create a *tls.Config from it like this:

`transport.TLSConfigFor(myRESTConfig.TransportConfig())`

**Comment by szuecs** [comment]
@liggitt Thanks so much, always so helpful! 
Can I add somewhere documentation to have this documented?
Add another example in the example section or something like that?
