### ISSUE TITLE
the k8s client keeps sending updates for /api/v1/namespaces/kube-system/endpoints/kube-controller-manager

### ISSUE THREAD

**Issue by krasi-georgiev** [kubernetes/client-go#454]
as part of troubleshooting https://github.com/prometheus/prometheus/issues/4518 I figured that the k8s client keeps sending updates for the `/api/v1/namespaces/kube-system/endpoints/kube-controller-manager` and the change is only  in the `ResourceVersion`

Is this to be expected and what would be a good way to ignore these updates?

```
&Endpoints{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:kube-controller-manager,GenerateName:,Namespace:kube-system,SelfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager,UID:f76b6132-a268-11e8-b8b3-08002709c498,ResourceVersion:363220,Generation:0,CreationTimestamp:2018-08-18 01:00:34 +0300 EEST,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{control-plane.alpha.kubernetes.io/leader: {"holderIdentity":"minikube_cc9a294c-a268-11e8-9149-08002709c498","leaseDurationSeconds":15,"acquireTime":"2018-08-17T22:00:34Z","renewTime":"2018-08-26T12:45:07Z","leaderTransitions":0},},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Subsets:[],}
```
```
&Endpoints{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:kube-controller-manager,GenerateName:,Namespace:kube-system,SelfLink:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager,UID:f76b6132-a268-11e8-b8b3-08002709c498,ResourceVersion:363222,Generation:0,CreationTimestamp:2018-08-18 01:00:34 +0300 EEST,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{control-plane.alpha.kubernetes.io/leader: {"holderIdentity":"minikube_cc9a294c-a268-11e8-9149-08002709c498","leaseDurationSeconds":15,"acquireTime":"2018-08-17T22:00:34Z","renewTime":"2018-08-26T12:45:09Z","leaderTransitions":0},},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Subsets:[],}
```

**Comment by liggitt** [comment]
the renewTime is actually changing:

"renewTime":"2018-08-26T12:45:07Z"
"renewTime":"2018-08-26T12:45:09Z"

because of the large number of clients that watch endpoints, it's actually recommended to use a different object as the leader lease object (for example, setting `--leader-elect-resource-lock=configmaps` in the kube-controller-manager options)

/close

**Comment by krasi-georgiev** [comment]
@liggitt  thanks for the pointer
I think in many setups where Prometheus is used the operators wouldn't have access to change the k8s settings so  I was hoping for an idea how to filter these on the client's side.

I am trying to improve the performance and I am just exploring if there would be a sane way to do this by minimising the k8s client streams processing and before it even hits our code.


> because of the large number of clients that watch endpoints
do you mean that is because we are initialising too many clients in....

https://github.com/prometheus/prometheus/blob/9f4cb06a379c45bb6ec12c241d0492a2f2699887/discovery/kubernetes/kubernetes.go#L252-L284

**Comment by liggitt** [comment]
> do you mean that is because we are initialising too many clients in....


No, every kube-proxy process on every node watches all changes to all endpoints in order to keep iptables rules updates. Perpetual changes on an endpoint object that are unrelated to actual network-endpoint-related changes is noise that has to be delivered to and processed by every node for no reason.

**Comment by krasi-georgiev** [comment]
thanks @liggitt 
I see some `FieldSelector` in the client options. Can't we use this to filter this noise out? `https://github.com/prometheus/prometheus//blob/master/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L328`
