### ISSUE TITLE
stream updates happen very slowly when the clients hit the MaxConcurrentStreams of the k8s API.

### ISSUE THREAD

**Issue by krasi-georgiev** [kubernetes/client-go#456]
https://github.com/golang/net/commit/1c05540f6879653db88113bc4a2b70aec4bd491f
after this commit when the client reaches the MaxConcurrentStreams any updates using the stream happen very slowly (1-2 per minute) so on systems with constant changes the client can never catch up.

> Currently if the http2.Transport hits SettingsMaxConcurrentStreams for a
> server, it just makes a new TCP connection and creates the stream on the
> new connection. This CL updates that behavior to instead block RoundTrip
> until a new stream is available.

as per the commit message the old behaviour was that the client creates a new connection and after https://github.com/golang/net/commit/1c05540f6879653db88113bc4a2b70aec4bd491f is just waits until there is  available streams.

Not sure if we can have some configurable settings in the k8s client or the http2 package needs to allows some tuning.

more details about the issue as part of troubleshooting https://github.com/prometheus/prometheus/issues/4528

**Comment by liggitt** [comment]
that certainly seems like behavior the http/2 package should allow choosing between

**Comment by liggitt** [comment]
see also a buffer starvation issue we just found and opened a fix for: https://github.com/kubernetes/kubernetes/pull/67902

that's only relevant if the blocked requests have bodies (POST/PUT, etc), so it may not be related to your issue
