### ISSUE TITLE
Watcher doesn't see events after it was recreated

### ISSUE THREAD

**Issue by dshulyak** [kubernetes/client-go#46]
We are writing application using client-go https://github.com/Mirantis/k8s-externalipcontroller.

Logs from scheduler (removes ipclaims and watches events):

```
I1124 11:19:59.327322       1 scheduler.go:373] Deleting ipclaim 10-107-10-2-24
I1124 11:19:59.356793       1 scheduler.go:179] Ipclaim deleted 10-107-10-2-24, resource version 14437
I1124 11:19:59.356837       1 scheduler.go:373] Deleting ipclaim 10-107-10-3-24
I1124 11:19:59.370075       1 scheduler.go:179] Ipclaim deleted 10-107-10-3-24, resource version 14439
I1124 11:19:59.370490       1 scheduler.go:373] Deleting ipclaim 10-107-10-4-24
I1124 11:19:59.385053       1 scheduler.go:179] Ipclaim deleted 10-107-10-4-24, resource version 14441
I1124 11:19:59.385136       1 scheduler.go:373] Deleting ipclaim 10-107-10-5-24
I1124 11:19:59.391902       1 scheduler.go:179] Ipclaim deleted 10-107-10-5-24, resource version 14442
```

Controller (watches events):

```
I1124 11:19:59.353745       7 controller.go:119] Received delete event for 10-107-10-2-24 - dind-node-2. Resource version 14437
I1124 11:19:59.353779       7 controller.go:148] Processing claim 10.107.10.2/24 with node dind-node-2 and uid dind-node-2
I1124 11:19:59.353790       7 netutils.go:78] Removing addr 10.107.10.2/24 from link docker0
I1124 11:19:59.394784       7 streamwatcher.go:107] Unable to decode an event from the watch stream: read tcp 172.17.0.7:43748->10.0.0.1:443: read: connection reset by peer
I1124 11:19:59.394836       7 reflector.go:403] github.com/Mirantis/k8s-externalipcontroller/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Watch close - *extensions.IpClaim total 11 items received
I1124 11:19:59.394852       7 controller.go:48] Calling claim watcher with options {{ } <nil> <nil> false 14437 0xc8203eeff8}
```

I am using cache.ListerWatcher and NewInformer. Maybe i am missing something, but i didn't find any special handling of this failures in existing controllers.

@caesarxuchao can you take a look at this problem?

**Comment by dshulyak** [comment]
The problem was with versionedParams. I changed it this way for now https://github.com/Mirantis/k8s-externalipcontroller/pull/67/commits/95ecd5410ac49c84b4ca9d07c082c856dfad576d

**Comment by rmohr** [comment]
I am using VersionedParams too in watchFunc and it works without issues. As far as I have seen in your code, the RESTCLient seems to  be properly constructed for TPRs.

 Could you post the request URL from the apiserver log with and without VersionedParams set?

**Comment by caesarxuchao** [comment]
Sorry, I just got a chance to go over the issues. Can you run the program with --v=9, that will print out the request sent to the API server. I think the query parameters were missing somehow. The reason could be the client was constructed with a different group version. I guess the way you fixed it now is the easiest.
