### ISSUE TITLE
How to make a web terminal

### ISSUE THREAD

**Issue by youngperson** [kubernetes/client-go#464]
websocket + exec pod?  
How to write input and output to the websocket stream？

exec pod code:

> 

        req := p.Client.CoreV1().RESTClient().Post().
		Resource("pods").
		Name(pod.Name).
		Namespace(pod.Namespace).
		SubResource("exec").
		VersionedParams(
			&v1.PodExecOptions{
				Container: containerName,
				Command:   []string{"/bin/sh"},
				Stdin:     true,
				Stdout:    true,
				Stderr:    true,
				TTY:       true,
			}, scheme.ParameterCodec)

	exec, err := remotecommand.NewSPDYExecutor(p.Config, "POST", req.URL())

	err = exec.Stream(remotecommand.StreamOptions{
		Stdin:  os.Stdin,
		Stdout: os.Stdout,
		Stderr: os.Stderr,
		Tty:    true,
	})

**Comment by hwchiu** [comment]
I think you can refer to how kubernetes dashboard create a web terminal and you can see the code here
https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/terminal.go
