### ISSUE TITLE
Listing bug in dynamic 'fake' client in 'kubernetes-1.11.3'

### ISSUE THREAD

**Issue by the-redback** [kubernetes/client-go#465]
`List`ing Bug in dynamic `fake` client in `kubernetes-1.11.3` tag. https://github.com/kubernetes/client-go/blob/kubernetes-1.11.3/dynamic/fake/simple.go#L275
```
no kind "ListList" is registered for version "v1"
```

Though the problem is fixed months ago on master - [commit link](https://github.com/kubernetes/client-go/commit/4b43750b963d2b6e0f7527fe558e71c47bfc5045).

The fix should be picked to kubernetes-1.11 branch (if there is any) as well.

**Comment by deads2k** [comment]
I'm supportive of a pick.  Can you open the cherry-pick?

**Comment by the-redback** [comment]
created https://github.com/kubernetes/kubernetes/pull/68552. 
Is it okay?
Also, isn't this fix also required for `release-1.10` branch?

**Comment by nikhita** [comment]
>  Also, isn't this fix also required for release-1.10 branch?

Yeah, given that we maintain 3 releases at a time - now it would be 1.12, 1.11 and 1.10 - I think it's reasonable to pick this to 1.10. :+1:

**Comment by nikhita** [comment]
This has been fixed by https://github.com/kubernetes/kubernetes/pull/68552. Closing.

/close
