### ISSUE TITLE
v1.Event.Search does not work

### ISSUE THREAD

**Issue by keyingliu** [kubernetes/client-go#47]
k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go:
```
func (e *events) Search(objOrRef runtime.Object) (*v1.EventList, error) {
	ref, err := api.GetReference(objOrRef)
	if err != nil {
		return nil, err
	}
	if e.ns != "" && ref.Namespace != e.ns {
		return nil, fmt.Errorf("won't be able to find any events of namespace '%v' in namespace '%v'", ref.Namespace, e.ns)
	}
	stringRefKind := string(ref.Kind)
	var refKind *string
	if stringRefKind != "" {
		refKind = &stringRefKind
	}
	stringRefUID := string(ref.UID)
	var refUID *string
	if stringRefUID != "" {
		refUID = &stringRefUID
	}
	fieldSelector := e.GetFieldSelector(&ref.Name, &ref.Namespace, refKind, refUID)
	return e.List(v1.ListOptions{FieldSelector: fieldSelector.String()})
}
```
`ref, err := api.GetReference(objOrRef)` should be `ref, err := v1.GetReference(objOrRef)`, or the search will be failed if the parameter is a v1 object.

**Comment by lavalamp** [comment]
@caesarxuchao You might want to look at this, will it cause problems with the client migration you're currently doing?

**Comment by caesarxuchao** [comment]
@keyingliu could you paste the error you saw? 

I agree for consistency we should use v1.GetReference here, but I don't see why using api.GetReference will cause the search to fail. I'm trying to understand the problem better.

**Comment by keyingliu** [comment]
@caesarxuchao the api.GetReference returns err if the object is a v1 object, say "object does not implement the List interfaces", it is quite ease to reproduce it: create a pod with v1 api, and try to get the event list with v1.EventList
