### ISSUE TITLE
INSTALL.md referenced in README.md is missing

### ISSUE THREAD

**Issue by lucastheisen** [kubernetes/client-go#471]
The [README.md](https://github.com/kubernetes/client-go/blob/master/README.md) states:

>See [INSTALL.md](https://github.com/kubernetes/client-go/blob/master/INSTALL.md) for detailed installation instructions.

But there is no INSTALL.md.

**Comment by nikhita** [comment]
This file was removed recently (https://github.com/kubernetes/client-go/pull/468) and added to the staging directory in kubernetes/kubernetes (https://github.com/kubernetes/kubernetes/pull/68790). A publishing-bot sync staging with this repo but it is currently broken.

I've created a fix for it (https://github.com/kubernetes/publishing-bot/pull/113). I'll update here and close this issue once that is merged and the bot syncs up fine.

**Comment by nikhita** [comment]
This is fixed now.

/close
