### ISSUE TITLE
PortForwarder.GetPorts does not return correct port number when local port omitted or set to zero.

### ISSUE THREAD

**Issue by mtaylor91** [kubernetes/client-go#472]
Hey guys,

I came across the new code on master to return the list of forwarded ports (see here: https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go#L349).

After doing some testing, I discovered that this function does not return the correct port if the local port is specified as '0' or left unspecified.

This seems to be because the port reference passed in to `portforwarder.listenOnPort` is a copy of the ForwardedPort struct, and not the actual ForwardedPort owned by the PortForwarder (see here: https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go#L155).

**Comment by liggitt** [comment]
cc @novas0x2a

**Comment by mtaylor91** [comment]
I filed this bug against kubernetes/kubernetes as well once I realized the code is hosted there: https://github.com/kubernetes/kubernetes/issues/69052.  There's also a PR with the fix: https://github.com/kubernetes/kubernetes/pull/69054.

Thanks!
- Mike

**Comment by nikhita** [comment]
Closing this in favour of the similar issue on k/k: https://github.com/kubernetes/kubernetes/issues/69052.

/close
