### ISSUE TITLE
Incorrect error reporting if clusterrole.rules resources not pluralised (configmap instead of configmaps)

### ISSUE THREAD

**Issue by nitishm** [kubernetes/client-go#473]
With RBAC enabled, setting the ClusterRole to - 

```
...
- apiGroups: [""]
  resources: ["configmap"] // Instead of configmaps
  verbs: ["get", "watch", "list"]
...
```

 causes the go-client client.CoreV1().ConfigMaps("").{...} method(s) to return ERROR 
`"unknown (get configmaps)"` instead of warning the user about an RBAC Permission denied issue, which is otherwise reported if the resource is no specified in the ClusterRole definition.

**Comment by nitishm** [comment]
The actual error reason itself has a description that mentions forbidden, but the message itself does not. 
```
ERROR : &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"unknown (get configmaps)", Reason:"Forbidden", Details:(*v1.StatusDetails)(0xc0002da4e0), Code:403}}
```

Is it a requirement that rules.resources should be specified only in the pluralized format ?

**Comment by liggitt** [comment]
if the client is requesting `configmaps`, the presence or absence of a `configmap` authz rule should have no impact on the result from the API

**Comment by nitishm** [comment]
Alright thanks. Will close the issue in that case.
