### ISSUE TITLE
"fake" clientset doesn't match kubernetes API behavior

### ISSUE THREAD

**Issue by stevvooe** [kubernetes/client-go#479]
I've been trying to make a very simple controller test that creates objects with the API then sees if the objects are there. I have tested this with the kube API and its clear that Update will create an object if it does not exist. However, if you do the same with a fake.NewSimpleClientset, it returns a not found error.

We can see the issue at https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L375. If the object does not exist, it should be added to the tracker.

I understand that I could be using this incorrectly. If you have a more sane way to mock out the client api, please point me in the right direction.

**Comment by liggitt** [comment]
Update only creates missing objects for a few resource types (endpoints, maybe one or two others). Returning a NotFound error is the standard behavior

**Comment by liggitt** [comment]
You can add a reactor to a specific fake client yourself to match one-off server behaviors

**Comment by stevvooe** [comment]
> Update only creates missing objects for a few resource types (endpoints, maybe one or two others). Returning a NotFound error is the standard behavior

Really? I have working code that will create a role binding on Update if it does not exist. This is not a one off server behavior.

**Comment by stevvooe** [comment]
While understand that most objects follow a model, the provided mocks should honor this. As a user of the package, this was extremely frustrating to debug this behavior.

The tests for a controller should be this:

1. Do a thing that triggers a controller.
2. Query if the controller created those objects.

With the current `ObjectTracker`, this seems impossible. Even with `AddReactor`, it was impossible to figure out why my reactors weren't being triggered without adding about a dozen print statements. It seems intercepting with a Prepended reactor might work, but now we lose behavior around watches.

Is there a way these strategies can be registered with the object tracker? The other possibility is that since this is a limited set of objects that allow "upsert", the ObjectTracker could special case them.

**Comment by stevvooe** [comment]
To find a way around this, I just added a create fallback, which really only gets executed in the context of functional testing of the controller.

It looks something like this:

```
func (c *controller) createOrUpdateRoleBinding(client rbacv1typed.RoleBindingInterface, rb *rbacv1.RoleBinding) (returned *rbacv1.RoleBinding, err error) {
	returned, err = client.Update(rb)
	if err != nil {
		if !kubeerrors.IsNotFound(err) {
			return nil, errors.Wrapf(err, "updating object %v/%v failed", rb.Namespace, rb.Name)
		}

		// On a realy API server, this code path typically won't be executed,
		// since an update will result in a create for a rolebinding. We have
		// this code here in case that changes and to work with the unit
		// testing facilities.
		returned, err = client.Create(rb)
		if err != nil {
			return nil, errors.Wrapf(err, "creating object %v/%v failed", rb.Namespace, rb.Name)
		}
	}

	return
}
```

For the rolebinding object, we can't really get a race condition, but for other objects, update before create can race against concurrent create (reversing order to create then update will race concurrent delete). For "production" (read: running against a real API server), we'd never want to do the Create first, since that won't be the common case and it will cost a round trip.

Is this generally safe to do?

**Comment by stevvooe** [comment]
I'd also like to report that it is very hard to reproduce behavior around the ResourceVersion for unit and functional testing. Is there any guidance there? Perhaps, you're willing to take some contributions to make this better.
