### ISSUE TITLE
Fake Clientset requires namespace be set on Create and Update but the real Clientset and API server do not

### ISSUE THREAD

**Issue by sykesm** [kubernetes/client-go#48]
The fake `Clientset` requires creates and updates of namespaced objects to have the namespace specified in the target runtime object metadata while the same does not appear to be true for the real `Clientset` and API server.

In particular, something like this:
```go
func createConfigMap(c kubernetes.Interface) error {
	_, err := c.Core().ConfigMaps("namespace").Create(&v1.ConfigMap{
		ObjectMeta: v1.ObjectMeta{Name: "name"},
		Data:       map[string]string{"key": "value"},
	})
	return err
}
```
works against a real cluster with a real `Clientset` but fails with `no namespace specified for a namespaced kind /v1, Kind=ConfigMap` when using the fake.

---

It looks like Create and Update end up adding the object to the `tracker` in [`fixture.go`][1] where the [namespace is checked][2]. The current implementation passes the namespace from the target object without accounting for the namespace from the request.

In the real API server, namespaces are propagated from the request path to the target object when a namespace isn't set on the object. This happens when [`ValidNamespace`][3] is called out of [`BeforeCreate`][4] and [`BeforeUpdate`][5].

Should the behavior of the tracker be updated to propagate the namespace from the request to the object when it's missing on the object?

[1]: https://github.com/kubernetes/client-go/blob/5d8c36c93cf544e3bde13caa4c6222b65753ec3c/testing/fixture.go#L245-L251
[2]: https://github.com/kubernetes/client-go/blob/5d8c36c93cf544e3bde13caa4c6222b65753ec3c/testing/fixture.go#L289
[3]: https://github.com/kubernetes/kubernetes/blob/35a6bfbceed9d8bc779fbfe00963b7674ea68b77/pkg/api/context.go#L104-L110
[4]: https://github.com/kubernetes/kubernetes/blob/35a6bfbceed9d8bc779fbfe00963b7674ea68b77/pkg/api/rest/create.go#L63-L65
[5]: https://github.com/kubernetes/kubernetes/blob/35a6bfbceed9d8bc779fbfe00963b7674ea68b77/pkg/api/rest/update.go#L83-L85

**Comment by deads2k** [comment]
> The fake Clientset requires creates and updates of namespaced objects to have the namespace specified in the target runtime object metadata while the same does not appear to be true for the real Clientset and API server.

The real API server defaults them if not set in the REST handling flow.  I'd support a pull for similar defaulting the test harness.

**Comment by sykesm** [comment]
@deads2k Thanks. I'm happy to do that. Would a PR be against kubernetes/kubernetes or kubernetes/client-go ?

**Comment by deads2k** [comment]
> @deads2k Thanks. I'm happy to do that. Would a PR be against kubernetes/kubernetes or kubernetes/client-go ?

I'm about 95% sure it's still kube/kube first.  @caesarxuchao can confirm.

**Comment by caesarxuchao** [comment]
To kubernetes/kubernetes please. Thanks.

**Comment by markmandel** [comment]
I just ran into this when creating a Pod:
`cs.CoreV1().Pods("default").Create(&pod)`
But can't seem to work out a workaround for this issue until it gets released. Any suggestions?

(Currently working with release-2.0)

Should I upgrade to master (how unstable is it)?

**Comment by markmandel** [comment]
Nevermind - worked it out - it's stored in `ObjectMeta` - I just couldn't find it.
