### ISSUE TITLE
Create a better introductory documentation to CRUD with client-go

### ISSUE THREAD

**Issue by fedebongio** [kubernetes/client-go#482]
Hi!

After chatting with @misterikkit about his struggles figuring out alone how to use some functionalities, decided to create this issue. 

The [client-go example](https://github.com/kubernetes/client-go/tree/master/examples) maybe cover the basic setup and one single case of CRUD (list) but the rest is basically to be deducted or trialed. Seems that a "CRUD for Dummies" is needed.

Even when using an autocomplete tool the hierarchy of extensible objects can be scary. For example, is _clientset.CoreV1()_ the right one to use? how do I know? Which packages can I safely ignore?

A couple of additional improvements suggested:
- in go-doc link to github examples for constructing client
- Optionally add example tests to constructing client

As a comparison guideline, [Python client](https://github.com/kubernetes-client/python/tree/master/examples) has many more examples, [Java client](https://github.com/kubernetes-client/java/blob/master/kubernetes/README.md) has a complete documentation on the rest API. Either way, both seem to be more complete than client-Go).

**Comment by alexzye** [comment]
i thought i was the only one facing this. i started kubernetes a few weeks ago with this client and figuring it out as a beginner was definitely non-trivial. the "how to use" instructions only give a two examples that are more about how to hook up the client than how to actually use the client. a few more example on commonly used operations would be cool.

**Comment by misterikkit** [comment]
/remove-lifecycle stale

I haven't seen any new client-go docs for beginners.

**Comment by seperman** [comment]
2 years later and the documentation still non existent.

**Comment by shenmou98** [comment]
Still didn't see the documentation.
/reopen
