### ISSUE TITLE
Kubectl exec command issue

### ISSUE THREAD

**Issue by zakiournani** [kubernetes/client-go#484]
Hi,
I am trying to execute command using the go client on pods running int a distant kubernetes server.
my issue is about the command construction, for example when i run with {cmd:= "touch test"} it works, but when i use {cmd:=touch test && echo hello > test} it doesnt.
This this just an example, what i really need to run is a command like rados that takes at least 5 parameters.
Any hint, thanks in advance?

	kubeconfig := filepath.Join(os.Getenv("HOME"), ".kube", "config")
	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		panic(err)
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err)
	}
	command := "touch test && echo cool > test"
	req := clientset.Core().RESTClient().Post().
		Resource("pods").
		Name(jobName).
		Namespace("default").
		SubResource("exec")
	scheme := runtime.NewScheme()
	if err := core_v1.AddToScheme(scheme); err != nil {
		panic(err)
	}

	parameterCodec := runtime.NewParameterCodec(scheme)
	req.VersionedParams(&core_v1.PodExecOptions{
		Command:   strings.Fields(command),
		Container: "",
		Stdin:     false,
		Stdout:    true,
		Stderr:    true,
		TTY:       false,
	}, parameterCodec)

	fmt.Println("Request URL:", req.URL().String())

	exec, err := remotecommand.NewSPDYExecutor(config, "POST", req.URL())
	if err != nil {
		panic(err)
	}

	var stdout, stderr bytes.Buffer
	err = exec.Stream(remotecommand.StreamOptions{
		Stdin:  nil,
		Stdout: &stdout,
		Stderr: &stderr,
		Tty:    false,
	})
	if err != nil {
		panic(err)
	}

**Comment by hwchiu** [comment]
Could you try to use `sh -c touch test && echo cool > test` to execute  again?

**Comment by gorjuspixels** [comment]
For anyone reading this, I spent half the day figuring out how to do this. It works when your command is an array of strings starting with `/bin/sh`:

```
[]string{"/bin/sh", "-c", "ls", "-ll", "."}
```

**Comment by dylandee** [comment]
i got the same problem.it seems there's wrong with echo in sh.
i fixed the issue with cmd []string{"/bin/sh", "-c", "echo \"hello\""}
