### ISSUE TITLE
How to get all the events below a deployment

### ISSUE THREAD

**Issue by youngperson** [kubernetes/client-go#486]
command
~ kubectl -n test  get event | grep   beego
1m          3h           671       beego-67b98c5cc4-6b4v7.155c23f1200bb6e3               Pod                                 Warning   FailedScheduling        default-scheduler

client
fieldSelector := "involvedObject.name=beego"
clientset.CoreV1().Events(namespace).List(metav1.ListOptions{FieldSelector: fieldSelector})
{
    "code": 0,
    "data": {
        "metadata": {
            "selfLink": "/api/v1/namespaces/test/events",
            "resourceVersion": "39397040"
        },
        "items": []
    }
}

ps：use client,How to get all the events below a deployment

**Comment by grosser** [comment]
Only way I found was iterating all the pods+replicasets and then watching their events in parallel ... would be nice if there was a builtin way of doing that
