### ISSUE TITLE
Add tests for strategic merge patch for the fake dynamic client

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes/client-go#488]
There are no tests for Strategic Merge Patch. We should add some.

**Comment by caesarxuchao** [comment]
Specifically, we are talking about adding tests to  staging/src/k8s.io/client-go/dynamic/fake/simple_test.go. See https://github.com/kubernetes/kubernetes/pull/69330#discussion_r224161594.

**Comment by caesarxuchao** [comment]
Also we need to fix the todo at https://github.com/kubernetes/kubernetes/pull/69330#discussion_r224160179. Although that's a separate issue, I mentioned it to in case we lost it.
