### ISSUE TITLE
discovery: don't import client auth provider plugins

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/client-go#49]
Import statement here[0].

I maintain the OIDC auth plugin, and I don't think they're useful for most clients, and it has a pretty big dependency footprint.

Can we document which empty imports you need to use to get `oidc` or `gce` support instead of importing these by default? Happy to open this same issue in the Kubernetes repo if that's where it needs to be addressed.

[0] https://github.com/kubernetes/client-go/blob/5d8c36c93cf544e3bde13caa4c6222b65753ec3c/discovery/helper.go#L27

**Comment by caesarxuchao** [comment]
We should address it in the main repo?

Are you suggesting we should remove the import statement[0], and adds a doc telling people to how to install oidc or gce?

**Comment by ericchiang** [comment]
> Are you suggesting we should remove the import statement[0], and adds a doc telling people to how to install oidc or gce?

Yes. I'll open the issue in the main repo.
