### ISSUE TITLE
panic: pods is forbidden: User "system:serviceaccount:testalex:default" cannot list pods at the cluster scope

### ISSUE THREAD

**Issue by justlooks** [kubernetes/client-go#491]
hi , i am testing client-go in-cluster-client-configuration ,and my k8s version is v1.11.3, when i pack app file into my image ,and write a deployment of the image,and run it on k8s,i get error,default sa seems no permission to list all pods,and i try create my own sa and connect it to my deployment ,still same error,how to handle this?

# docker logs 1d29cf7b4df0
panic: pods is forbidden: User "system:serviceaccount:testalex:default" cannot list pods at the cluster scope
goroutine 1 [running]:
main.main()
	/root/go/src/k8s.io/client-go/examples/in-cluster-client-configuration/main.go:44 +0x414

**Comment by mathieu-benoit** [comment]
Hi @justlooks, I'm having the same issue with k8s version 1.11.3. Apparently you closed this issue, how did you resolve it? Thanks for your feedback.

**Comment by mathieu-benoit** [comment]
I found my answer in this [section](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration#authenticating-inside-the-cluster).
