### ISSUE TITLE
Creating Events fails with fake ClientSet

### ISSUE THREAD

**Issue by antoineco** [kubernetes/client-go#493]
**Problem description**

Creating Events via a record.EventRecorder does not work in combination with a fake ClientSet.
The generated error message is:

`'Server rejected event '&v1.Event{...}': request namespace does not match object namespace, request: "" object: "test"' (will not retry!)`

**How to reproduce**

```go
package main

import (
	"flag"
	"time"

	"github.com/golang/glog"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/kubernetes/scheme"
	clientcorev1 "k8s.io/client-go/kubernetes/typed/core/v1"
	"k8s.io/client-go/tools/record"
)

func main() {
	flag.Parse()

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: "test",
			Name:      "dummy",
			SelfLink:  "/api/v1/namespaces/test/pods/dummy",
		},
	}

	cli := fake.NewSimpleClientset(pod)

	eventSink := &clientcorev1.EventSinkImpl{
		cli.CoreV1().Events(corev1.NamespaceAll),
	}

	eventBroadcaster := record.NewBroadcaster()
	eventBroadcaster.StartLogging(glog.V(3).Infof)
	eventBroadcaster.StartRecordingToSink(eventSink)

	r := eventBroadcaster.NewRecorder(scheme.Scheme, corev1.EventSource{Component: "test"})

	r.Event(pod, corev1.EventTypeNormal, "SomeReason", "Dummy event")

	time.Sleep(time.Second)
}
```

**Investigation**

At [fake/fake_event_expansion.go#L27](https://github.com/kubernetes/client-go/blob/release-9.0/kubernetes/typed/core/v1/fake/fake_event_expansion.go#L27), [`core.NewRootCreateAction()`](https://github.com/kubernetes/client-go/blob/release-9.0/testing/actions.go#L94) returns an `action` without Namespace:

```
x/vendor/k8s.io/client-go/testing.CreateActionImpl {
        ActionImpl: x/vendor/k8s.io/client-go/testing.ActionImpl {
                Namespace: "",
                Verb: "create",
                Resource: (*x/vendor/k8s.io/apimachinery/pkg/runtime/schema.GroupVersionResource)(0xc0000f5a58),
                Subresource: "",},
        Name: "",
        Object: x/vendor/k8s.io/apimachinery/pkg/runtime.Object(*x/vendor/k8s.io/api/core/v1.Event) *{
                ...
                Reason: "SuccessfulCreate",
                Message: "Dummy event",
                ...},}
```

Later, inside [c.Fake.Invokes()](https://github.com/kubernetes/client-go/blob/release-9.0/testing/fake.go#L130), the action is [handled](https://github.com/kubernetes/client-go/blob/release-9.0/testing/fixture.go#L91), but because `ns != obj.Namespace` an [error is returned](https://github.com/kubernetes/client-go/blob/release-9.0/testing/fixture.go#L353-L356).

**Comment by antoineco** [comment]
Note: using `cli.CoreV1().Events("test")` to create the `EventSinkImpl` suppresses the error, but then a call to `List()` shows no item.

**Comment by joshuarubin** [comment]
I've started looking into this issue and now have a PR with a test that reproduces it at kubernetes/kubernetes#70343. It does not yet include the fix because it seems like the proper way to address this may require some significant changes to `k8s.io/client-go/kubernetes/fake`. If the possible solution I've suggested is approved, it will fix this issue.
