### ISSUE TITLE
Get resource usage of pods & nodes (Stackoverflow + Bounty)

### ISSUE THREAD

**Issue by weeco** [kubernetes/client-go#498]
I am struggling to fetch the current resource usage from pods & nodes. I created a Stackoverflow post and proposed a bounty, however I believe I couldn't target enough people who are familiar with Go and the Kubernetes architecture. If someone could enlighten me how to fetch the node & pod metrics I'd highly appreciate it:

https://stackoverflow.com/questions/52763291/get-current-resource-usage-of-a-pod-in-kubernetes-with-go-client

**Comment by naeemkhan12** [comment]
I have posted an answer have a look
