### ISSUE TITLE
v1beta1/deployment: delete dependents

### ISSUE THREAD

**Issue by josselin-c** [kubernetes/client-go#50]
When removing a deployment I'd like the related replicaset/pods to be removed as well (this is the cascading mode in kubectl). 

I tried to call `Deployments("ns").Delete` with the `OrphanDependents` option set to `true` or `false` but it didn't seem to do anything. 
How can I do the cascading delete with client-go?

**Comment by caesarxuchao** [comment]
It's not supported yet. Currently cascading deletion is only supported for replicaset/replication controller (i.e., after you delete the rs or rc, the garbage collector controller will delete the pods). Cascading deletion of deployment will be supported after this PR gets merged: https://github.com/kubernetes/kubernetes/pull/35676

As a workaround, you can take a look how `kubectl` deletes a deployment: https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/kubectl/stop.go#L415. Basically it first scales down ([supported](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/extensions/v1beta1/scale_expansion.go#L49) in client-go) the deployment, waits the deployment.status reports the replicas reaches 0, and then delete the deployment.

**Comment by josselin-c** [comment]
Okay, I'll do this then and keep an eye on the PR. 
Thanks for the help!
