### ISSUE TITLE
MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutabl

### ISSUE THREAD

**Issue by barnettZQG** [kubernetes/client-go#508]
I want patch deployment with:
```
{"metadata":{"creationTimestamp":null,"labels":{"creater_id":"1543299964865665410","version":"20181127142603"}},"spec":{"template":{"metadata":{"labels":{"version":"20181127142603","creater_id":"1543299964865665410"}},"spec":{"volumes":[{"name":"slug","hostPath":{"path":"/grdata/build/tenant/e8539a9c33fd418db11cce26d2bca431/slug/2bc58cb783992dff584ee7454360b0c1/20181127142603.tgz"}}],"containers":[{"name":"2bc58cb783992dff584ee7454360b0c1","image":"goodrain.me/runner","args":["start","web"],"ports":[{"containerPort":5000}],"env":[{"name":"LOGGER_DRIVER_NAME","value":"streamlog"},{"name":"PORT","value":"5000"},{"name":"PROTOCOL","value":"http"},{"name":"DEFAULT_DOMAIN_5000","value":"5000.gr60b0c1.0enb7gyx.37e53f.grapps.cn"},{"name":"MONITOR_PORT","value":"5000"},{"name":"CUR_NET","value":"calico"},{"name":"TENANT_ID","value":"e8539a9c33fd418db11cce26d2bca431"},{"name":"SERVICE_ID","value":"2bc58cb783992dff584ee7454360b0c1"},{"name":"MEMORY_SIZE","value":"micro"},{"name":"SERVICE_NAME","value":"gr60b0c1"},{"name":"SERVICE_POD_NUM","value":"1"},{"name":"HOST_IP","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"resources":{"limits":{"cpu":"80m","memory":"128Mi"},"requests":{"cpu":"30m","memory":"128Mi"}},"volumeMounts":[{"name":"slug","readOnly":true,"mountPath":"/tmp/slug/slug.tgz"}]}]}},"strategy":{},"selector":{"matchLabels":{"version":"20181127142603"}}}}
```
if I use method:
```
_, err := s.manager.client.AppsV1().RESTClient().Patch(types.MergePatchType).Namespace(deployment.Namespace).Resource("deployments").Name(deployment.Name).Body(app.UpgradePatch["deployment"]).Do().Get()
```
It will fail. The error message is as follows：
```
Deployment.apps "2bc58cb783992dff584ee7454360b0c1-deployment" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"version":"20181127141244", "name":"gr60b0c1"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
but if I use method:
```
_, err := s.manager.client.ExtensionsV1beta1().RESTClient().Patch(types.MergePatchType).Namespace(deployment.Namespace).Resource("deployments").Name(deployment.Name).Body(app.UpgradePatch["deployment"]).Do().Get()
```
it can be successful. 

kube-api version is : v1.10.9

**Comment by liggitt** [comment]
the selector in Deployment, ReplicaSet, and DaemonSet objects is immutable as of the apps/v1beta2 API. See https://github.com/kubernetes/kubernetes/issues/50808

/close

**Comment by vishrantgupta** [comment]
This could be because of the `kubernetes` `service` and you are trying to do a rolling upgrade,  once deployed the label selectors of kubernetes service can not be updated until you decide to delete the existing deployment so that the services have new label selectors to point to new pods with the updated label.

**Comment by blaskovicz** [comment]
> This could be because of the `kubernetes` `service` and you are trying to do a rolling upgrade, once deployed the label selectors of kubernetes service can not be updated until you decide to delete the existing deployment so that the services have new label selectors to point to new pods with the updated label.

To clarify for others that find this post later, check that your labelSelector doesn't have labels with change each deployment like version, hash, etc. If so, delete the Deployment and make a more generic labelSelector.

Thanks @vishrantgupta

**Comment by ArtificialTruth** [comment]
Fixed for me by doing

`kubectl delete all --all
`
then reapply:

`kubectl apply -f .`

NOTE: You may want to think twice about doing this in production.

**Comment by farazkhawaja** [comment]
makes it hard when introducing new labels that were left out previously. cant do a `kubectl delete` in prod env
