### ISSUE TITLE
Add port-forwarding example

### ISSUE THREAD

**Issue by gtaylor** [kubernetes/client-go#51]
This would be really helpful, as I'm coming from another language. In particular, how to come about the `dialer` param here: https://github.com/kubernetes/client-go/blob/75399f68c88d27167979821ac280936cfb13cfd6/tools/portforward/portforward.go#L111

**Comment by caesarxuchao** [comment]
You can take a look at how kubectl use the equivalent packages in the main repo: https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/kubectl/cmd/portforward.go#L107

**Comment by ngtuna** [comment]
This is still unclear. Did you mean we shouldn't use client-go to execute a port-forward ? @caesarxuchao

**Comment by esimonov** [comment]
@gtaylor Please try this to obtain the `dialer` :

```go
import(
        "flag"
	"fmt"
	"os"
	"path/filepath"
        "net/http"
	"net/url"
        "strings"

        "k8s.io/client-go/tools/clientcmd"
        "k8s.io/client-go/tools/portforward"
        "k8s.io/client-go/transport/spdy"
        "k8s.io/client-go/util/homedir"
)

...

var kubeconfig *string
if home := homedir.HomeDir(); home != "" {
	kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
} else {
	kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
}
flag.Parse()

config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
if err != nil {
	panic(err)
}
roundTripper, upgrader, err := spdy.RoundTripperFor(config)
if err != nil {
	panic(err)
}

path := fmt.Sprintf("/api/v1/namespaces/%s/pods/%s/portforward", "default", podName)
hostIP := strings.TrimLeft(config.Host, "htps:/")
serverURL := url.URL{Scheme: "https", Path: path, Host: hostIP}

dialer := spdy.NewDialer(upgrader, &http.Client{Transport: roundTripper}, http.MethodPost, &serverURL)
```

What about `stopChan`, `readyChan`, `out` and `errOut`, you can initialize then like this:
```go
import "bytes"

stopChan, readyChan := make(chan struct{}, 1), make(chan struct{}, 1)
out, errOut := new(bytes.Buffer), new(bytes.Buffer)
```
The usage is following (with error handling simplified, you would probably want to add more context to the error messages, and/or use log messages instead of panics):
```go

forwarder, err := portforward.New(dialer, ports, stopChan, readyChan, out, errOut)
if err != nil {
	panic(err)
}

go func() {
	for range readyChan { // Kubernetes will close this channel when it has something to tell us.
	}
	if len(errOut.String()) != 0 {
		panic(errOut.String())
	} else if len(out.String()) != 0 {
		fmt.Println(out.String())
	}
}()

if err = forwarder.ForwardPorts(); err != nil { // Locks until stopChan is closed.
		panic(err)
}
```
Just close the `stopChan` when you don't need this connection anymore.

**Comment by h-abinaya28** [comment]
I am getting an error while trying the above code as `error upgrading connection: resource "test" not found`

**Comment by EronWright** [comment]
An article on the topic:
https://gianarb.it/blog/programmatically-kube-port-forward-in-go

**Comment by MarcosCela** [comment]
recommended read: #796 if you find any dataraces. I used the safe buffer implementation for the following gist:

- https://gist.github.com/arkan/5924e155dbb4254b64614069ba0afd81

**Comment by anthhub** [comment]
how to forward for service?

**Comment by anthhub** [comment]
Hi, I made a library with example forwarding service or pods!  You  can see the repo: 😬 https://github.com/anthhub/forwarder

**Comment by Svintooo** [comment]
Code example given above contains a bug.

```go
// All hosts starting with any of the letters 'h', 'p', 's', or 't', will be erroneously truncated.
hostIP := strings.TrimLeft(config.Host, "htps:/")
// Ex: "http://stamp-high.com"
// ->           "amp-high.com"
```

I am posting here since I suspect others might end up here while searching for a solution.
I am sorry if this is the wrong place to do it.

Searching github for 'TrimLeft "htps:/"' gives me over 100+ results, so the bug seems somewhat widely spread.
