### ISSUE TITLE
Intermittent connectivity to api-server when using with Istio

### ISSUE THREAD

**Issue by adinunzio84** [kubernetes/client-go#527]
Client-go seems to have a problem while running on AKS with Istio. We've spent a lot of time trying to figure out which of the 3 causes the issue, but we suspect it to be client-go at this point.

Environment:
* Azure Kubernetes Service (Kubernetes 1.11.5)
* Istio 1.0.2 (bugs in later versions)
* client-go (tried 7.0.0 and 9.0.0)

Description:
We noticed that if our client makes calls to the API server every 10 seconds, it continues to work - however, after (pretty close to if not exactly) 5 minutes of idle time, requests start failing. After another period of time (about 10-15 minutes), it works again before repeating the issue. This is noticeable in (a slightly modified version of) the [in-cluster example](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration).

Error log:
```
...
2018-12-05 18:37:27: Making request
E1205 18:37:37.333173       8 round_trippers.go:169] CancelRequest not implemented by *rest.tokenSourceTransport
2018-12-05 18:37:37: Panic
Error Get https://${FQDN}:443/api/v1/pods: net/http: request canceled (Client.Timeout exceeded while awaiting headers):
```
(replaced my apiserver with `${FQDN}`)

We're also seeing:
```
...
Error Get https://${FQDN}:443/api/v1/pods: unexpected EOF:
```
(replaced my apiserver with `${FQDN}`)

The main factors involved seem to be a combination of:
* Using environment variables on the Pod to access the API server
* Using a ServiceEntry with Istio to access the API server due to the previous factor
* Using client-go to access the API server

The ServiceEntry that needs to be created looks like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: azmk8s-ext
  namespace: default
spec:
  hosts:
  - ${FQDN}
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
```

**Why is this ServiceEntry necessary?**
* On AKS, there is a workaround to Azure/AKS#676 where the following environment variables are set automatically via some MutatingAdmissionWebhook, where FQDN is the fully qualified name for your AKS cluster's apiserver:
  * KUBERNETES_PORT_443_TCP_ADDR = "${FQDN}"
  * KUBERNETES_PORT = "tcp://${FQDN}:443"
  * KUBERNETES_PORT_443_TCP = "tcp://${FQDN}:443"
  * KUBERNETES_SERVICE_HOST = "${FQDN}"

**Why client-go?**
* The issue occurs using client-go but not [client-node](https://github.com/kubernetes-client/javascript). Even though it only happens on AKS and not on GKE, this is probably due to the ServiceEntry requirement, which is necessary on AKS but not on GKE. In both environments, client-node works, provided the ServiceEntry is there on AKS.

Other things we've noticed:
* Making raw REST calls to the API server with the token and cacerts stored on the pod seems to work fine, both via `curl` and Go's `http.Client`.
* The problems are pod-specific - that is, I can have one pod making requests every 10 seconds while another is every 6 minutes, and the 10-second one works while the 6-minute one does not
* Deleting the ServiceEntry and recreating it seems to "restart" the error cycle, so it works soon after, but fails again after that brief period.
* We can use any 2 of AKS, Istio, and client-go, but not all 3
  * If we do not use Istio, the sample app works okay, even with the AKS environment variables set
  * If we do not use AKS (and therefore no ServiceEntry), it works okay
  * If we do not use client-go, but use client-node, it works okay

**Comment by liggitt** [comment]
cc @mikedanese

**Comment by liggitt** [comment]
looks like the token source transport doesn't implement optional transport methods

**Comment by mikedanese** [comment]
Thanks for debugging this.

**Comment by mikedanese** [comment]
Yup, that was my thought as well. I'll work on a repro but cancellation seems like a nice to have in the token transport (if only to get rid of the error messages).

**Comment by adinunzio84** [comment]
I should mention that the individual request doesn't fail after 5 minutes. When the request works, it returns quickly. It's when the app goes 5 minutes without making any requests to the apiserver - that's when the errors start to occur on any requests made after that point (from client-go).

**Comment by adinunzio84** [comment]
We spoke with folks at Microsoft, and they said it's possibly due to the fact that Azure load balancing will drop a connection after a certain amount of idle time but does not send a TCP reset, and certain clients that don't handle this case will experience problems. I'm not much of a networking person so I'm not really sure what implications this has, but wanted to share.

They're not sure why this would happen only in the case where Istio is installed though. I've sent some instructions to help them reproduce the issue, so they will be investigating from their side as well.

Hope this helps!

**Comment by mikedanese** [comment]
Is envoy in the datapath between your application and azure? is it in the datapath between your application and the kubernetes api server?

**Comment by adinunzio84** [comment]
Yes, the traffic should be routing through the envoy proxy, in both the client-node and client-go examples I've tried

**Comment by adinunzio84** [comment]
@mikedanese I can send you a couple sample apps that reproduces the issue directly if you'd like (though open-sourcing it might not be an option at this point without having to jump through some hurdles). I made it so you just need an AKS cluster and Azure Container Registry, then it runs the `az` CLI commands necessary to connect to them (once you've logged in to the right subscription).

**Comment by adinunzio84** [comment]
We had some help from Microsoft again, and they helped us get it working. Details of the cause:
> The issue appears to be caused by the SNAT that happens to all outbound traffic from your instances. When traffic leaves your instances the load balancer performs a SNAT and has a default timeout of 5 minutes. Unfortunately that timeout value can't be changed. What this means is the load balancer terminates any outbound connections that are idle for 5 minutes.

There are two pieces to the fix (both of which we successfully implemented):
* Disable KeepAlives on calls to the apiserver in the Go client
* Create a DestinationRule (Istio CRD) as shown below so that the Envoy proxies don't try to reuse the same connection for multiple requests

DestinationRule:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: azmk8s-dr
spec:
  host: $FQDN
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
```

Does this fix affect client-go's ability to "watch" resources (or anything else)? If not, then I think the issue is resolved.

**Comment by adinunzio84** [comment]
Update regarding this - we just decided to disable egress traffic in Istio, but from what I heard, setting the "IdleConnTimeout" on the http transport to something less than 5 minutes solves the issue. I haven't confirmed this though.

**Comment by prune998** [comment]
Azure Load-Balancers timeout after 4 minutes (not configurables at this time). I would set the `IdleConnTimeout` to 3 mins to be sure not to hit the threshold.
This will not save you from the case when you are using too many connexions, then the LB may drop some of them sooner.

Note that sending `keepalive` packets is a workaround the issue. It will not solve it. AKS is dropping TCP connexions without RESET, which is dirty and break TCP normal behaviour. This is something yo could consider occasional on external networks, and NOT when trying to reach the K8s API itself.

This is a serious issue with AKS and is, by itself, a NO GO to using AKS.

**Comment by adinunzio84** [comment]
I imagine this can be closed now - in my case the problem was with Azure LBs not sending a TCP Reset and my applications having long timeout periods. I think the fix is to use low IdleConnTimeouts along with low request timeouts and wait for AKS to support TCP Resets in its LBs.

I don't know if there is anything client-go can do (maybe change the default IdleConnTimeout to 3 or 4 mins, but as @prune998 described that will not solve the issue of the LBs closing the connections due to high congestion, and as LBs are not obligated to do anything in response to TCP keepalives, that won't solve the issue either). Any further issues might be best placed in Azure/AKS's issues.
