### ISSUE TITLE
Cache.NewInformer UpdateFunc called repeatedly w/o any updates

### ISSUE THREAD

**Issue by nfons** [kubernetes/client-go#529]
I'm using the `NewListWatchFromClient` and `NewInformer` to listen to deployments as per #132.

However, the `UpdatFunc` seems to be repeatedly called, ever 30 secs, event w/o any update to the deployments.

relevant code:

```
watchList := cache.NewListWatchFromClient(clientset.AppsV1().RESTClient(), "deployments", core.NamespaceDefault, fields.Everything())
	_, controller := cache.NewInformer(
		watchList,
		&v1.Deployment{},
		time.Second*30,
		cache.ResourceEventHandlerFuncs{
			UpdateFunc: taskUpdate,
		})
```

the update Task is fired repeatedly in the interval...and all my deployments are output as "updated" even though there are not any updates to my deployments 

I solved the issue by adding a `reflect.DeepEqual()` check on my taskUpdate ) but even with that, on a single deployment update, the taskUpdate gets fired 3x.

it seems the resyncPeriod is not working as intended? I updated this to 0, and still fires multiple times

**Comment by liggitt** [comment]
calling OnUpdate methods every 30 seconds with your original invocation is working as intended:

> resyncPeriod: if non-zero, will re-list this often (you will get OnUpdate
> calls, even if nothing changed). Otherwise, re-list will be delayed as
> long as possible (until the upstream source closes the watch or times out,
> or you stop the controller).

if you change it to zero, relists and OnUpdate method calls will occur when the watch connection is interrupted and has to be re-established.

multiple actors participate in updating a deployment object, so one update can trigger updates in other parts of the object by other actors. all of those updates generate update notifications

**Comment by nfons** [comment]
@liggitt 

> multiple actors participate in updating a deployment object, so one update can trigger updates in other parts of the object by other actors. all of those updates generate update notifications"
sorry i am not following this.

`kubectl apply -f [deployment.yaml]` is running multiple updates? why would that be the case. you would expect a single apply for a single resource to only update that resource 1 time.

further, why would onupdate be called when object is NOT modified?

If I modify the resync to 1 sec, it should sync my local watchlist with the k8s client state every 1 sec.

this is somewhat confirmed by the code in `controller.go`
```
// This will hold the client state, as we know it.
	clientState := NewIndexer(DeletionHandlingMetaNamespaceKeyFunc, indexers)
```
 and further, in the Process func in `controller.go`, we see the client state used as a store of objects
```
if old, exists, err := clientState.Get(d.Object); err == nil && exists {
						....
						h.OnUpdate(old, d.Object)
```

I would expect then, on initial startup of the WatchList, it would fire the `AddFunc`, since watchlist = empty & k8s has objects

this is confirmed by updating the code to `AddFunc` and observing the addFunc get called on init

But why would a update trigger, when no update was done to the resource?

in fact, if i modify the resync to 1 sec,
```
if reflect.DeepEqual(oldObj, obj) == false {
		log.Println("Deployment Updated: " + deploy.Name)
	} else {
		log.Println("not updated")
	}
```

the above code gets fired every 1 sec per deployment 


Is there any way to know when a TRUE update has occurred to a deployment?

**Comment by liggitt** [comment]
> kubectl apply -f [deployment.yaml] is running multiple updates?

No, if kubectl apply makes a change to the spec, the controller will notice that and immediately start reacting to it, updating status in the process, possibly multiple times

> further, why would onupdate be called when object is NOT modified?

* OnUpdate is called with all existing objects on the specific resync interval
* OnUpdate is called with all existing objects when a watch connection is dropped by the server and a full relist is required

> Is there any way to know when a TRUE update has occurred to a deployment?

If resourceVersion differs between old and new, an actual update event was observed.

**Comment by GopeshKh** [comment]
I am facing the same issue. Just checking whether we got any solution to this issue.
