### ISSUE TITLE
Is there a way to get cluster name programmatically from client-go

### ISSUE THREAD

**Issue by rajdhandus** [kubernetes/client-go#530]
hello,

I am looking to derive the current cluster name i am running the controller from. I am using in-cluster authentication method. Is there a way i can retrieve the name of the cluster using client-go ?

thanks..

**Comment by bobby-brennan** [comment]
/reopen

This doesn't currently appear to be possible. Would be great to see the `name` field from kubeconfig plumbed into https://godoc.org/k8s.io/client-go/rest#Config

**Comment by bobby-brennan** [comment]
@rajdhandus looks like I can't reopen, but you can :)

**Comment by shraddhaopsmx** [comment]
It's been more than 3 years since there has been an activity in this thread, just wondering whether there has been any development in this direction or maybe any way in which the in cluster's name can be obtained.
@rbren Know anything?

**Comment by gopaltirupur** [comment]
@shraddhaopsmx 

Seems to be there is some update here
https://github.com/kubernetes/client-go/issues/638
