### ISSUE TITLE
Can't watch only one configMap

### ISSUE THREAD

**Issue by rametta** [kubernetes/client-go#534]
Hello,

I'm having an issue of not being able to "watch" a single configMap.

I can watch ALL the configMaps in a namespace successfully and receive all the updates in the ResultChan() channel. BUT to get the updates of just one config, i need to do hacky stuff with filtering by Labels using the metav1.ListOptions LabelSelector.

Like this:
```go
configMapWatch, err := client.CoreV1().ConfigMaps(namespace).Watch(metav1.ListOptions{
	LabelSelector: "component = config",
	Watch:         true,
})
```

But I would like something like this:
```go
configMapWatch, err := client.CoreV1().ConfigMaps(namespace).Watch(metav1.ListOptions{
	Name: "name-of-my-config",
	Watch:         true,
})
```

Is this possible already??

Thank you very much

**Comment by liggitt** [comment]
yes, set `ListOptions.FieldSelector = fields.Set{"metadata.name": name}.AsSelector().String()`

/close

**Comment by rametta** [comment]
Thank youuuuu @liggitt ! That works!
