### ISSUE TITLE
Provide a way to check compatibility

### ISSUE THREAD

**Issue by smanpathak** [kubernetes/client-go#535]
I ran into an interesting situation: An application controller used UpdateStatus calls for CRDs which are only supported by K8s 1.11 onwards. So I experienced failures on 1.10 K8s.
Can client-go expose an API/we can create a tool which checks if the platform supports all calls made by client-go?

**Comment by liggitt** [comment]
the discovery APIs indicate what endpoints are supported (fetching `/apis/<group>/<version>` returns a list of resources and the supported verbs, including ones like `myresources/status` for status endpoints)

/close

**Comment by smanpathak** [comment]
IMO, there should be a better way to do this. client-go users cannot be expected to introspect all code to figure out which APIs to check for and which don't. If the underlying platform does not support the feature, client-go should fail initialization. This can be easily done with proper versioning of API.
