### ISSUE TITLE
 certificate signed by unknown authority

### ISSUE THREAD

**Issue by Cloudzp** [kubernetes/client-go#536]
InsecureSkipVerify: true is initialized in rest.Config when using "k8s.io/client-go/tools/remotecommand", but it does not seem to take effect
### this is my config
![image](https://user-images.githubusercontent.com/25190767/50435325-c11a3d00-091b-11e9-8abc-68c5536ac2f4.png)
### this is the error
![Uploading image.png…]()

**Comment by liggitt** [comment]
that controls how the client verifies the API server's certificate

for remote command execution, there is another connection made between the apiserver and the kubelet. if the apiserver was started with `--kubelet-certificate-authority`, it will verify the serving certificate presented by the kubelet, and fail with a TLS error if the kubelet's certificate was not issued by a valid authority in that bundle

/close

**Comment by Cloudzp** [comment]
I did not set this parameter "-kubelet-certificate-authority" in my kube-apiserver, I want to know how to make it not verify, thank you very much！

![image](https://user-images.githubusercontent.com/25190767/50461810-0e4deb80-09bc-11e9-9b80-22899030c387.png)
![image](https://user-images.githubusercontent.com/25190767/50461817-1c9c0780-09bc-11e9-896a-167d629e9f58.png)

**Comment by liggitt** [comment]
what is the full error you receive?

**Comment by Cloudzp** [comment]
![image](https://user-images.githubusercontent.com/25190767/50462774-81f2f700-09c2-11e9-8706-ed212b06f27c.png)

![image](https://user-images.githubusercontent.com/25190767/50462769-769fcb80-09c2-11e9-99f9-b34de8b50d11.png)

**Comment by Cloudzp** [comment]
Yes, I have tried setting this parameter too, but I get the following error:

![image](https://user-images.githubusercontent.com/25190767/50462779-8d462280-09c2-11e9-94ba-84ed49a1f7d0.png)

**Comment by liggitt** [comment]
you must not set CAData or CAFile in the TLSClientConfig

**Comment by Cloudzp** [comment]
Ok, I understand, thank you very much.
