### ISSUE TITLE
Document what errors are returned by the client API methods

### ISSUE THREAD

**Issue by filmil** [kubernetes/client-go#537]
It would be nice to have the API documentation also say what errors are returned.

For example see: https://github.com/kubernetes/client-go/blob/master/listers/apps/v1/deployment.go#L31

Did you know that if you call `List` and it finds no matching deployments, you'd get a `404 Not Found`.  From the signature here this is not obvious.  An empty list and a `nil` error would have been just as reasonable a result.

Docs should either mention the error behavior explicitly, or link to a place that documents the general behavior. Otherwise, it's really hard to program against an interface with undocumented behavior.

**Comment by liggitt** [comment]
> Did you know that if you call `List` and it finds no matching deployments, you'd get a `404 Not Found`.

Actually, it returns an empty list. A 404 indicates the server does not know about the API you called.

**Comment by liggitt** [comment]
the returned errors are determined by the server response, not the client

**Comment by filmil** [comment]
Umm, the logs I'm looking at beg to differ.  The code is looking for a list of `Deployment` objects with a specific name.  There's plenty of room for a PEBKAC here, but the point of this bug is to have the default client behavior documented, or documentation easily findable.  I spent the last 20 minutes or so trying to find when `List` returns an error.  It should not be that hard to find. I understand that folks who already know don't need it...

```
1226 21:02:16.088558       1 round_trippers.go:393]     Accept: application/json, */*
I1226 21:02:16.088633       1 round_trippers.go:393]     Content-Type: application/json
I1226 21:02:16.091737       1 round_trippers.go:408] Response Status: 404 Not Found in 3 milliseconds
I1226 21:02:16.092020       1 round_trippers.go:411] Response Headers:
I1226 21:02:16.092172       1 round_trippers.go:414]     Audit-Id: 5b2480a7-2ff2-4290-a68c-64fbb4cc77a6
I1226 21:02:16.092303       1 round_trippers.go:414]     Content-Type: application/json
I1226 21:02:16.092383       1 round_trippers.go:414]     Content-Length: 240
I1226 21:02:16.092445       1 round_trippers.go:414]     Date: Wed, 26 Dec 2018 21:02:16 GMT
I1226 21:02:16.092531       1 request.go:897] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps \"REDACTED\" not found","reason":"NotFound","details":{"name":"REDACTED","group":"apps","kind":"deployments"},"code":404}
I1226 21:02:16.093048       1 nomos_controller.go:695] Awaiting the removal of "REDACTED" pod.
I1226 21:02:16.093674       1 reflector.go:202] Starting reflector *v1.Pod (10h0m0s) from pkg/cache/internal/informers_map.go:196
I1226 21:02:16.093779       1 reflector.go:240] Listing and watching *v1.Pod from pkg/cache/internal/informers_map.go:196
```

**Comment by liggitt** [comment]
> The code is looking for a list of Deployment objects with a specific name

That sounds like a `Get` request, not a `List` request. Do you have the actual URL being requested? 

This is the difference between get and list, in terms of the actual API calls made:

List:
```
$ curl http://localhost:8080/apis/apps/v1/namespaces/kube-system/deployments?fieldSelector=metadata.name=foo -v

> GET /apis/apps/v1/namespaces/kube-system/deployments?fieldSelector=metadata.name=foo HTTP/1.1
< HTTP/1.1 200 OK
{
  "kind": "DeploymentList",
  "apiVersion": "apps/v1",
  "metadata": {
    "selfLink": "/apis/apps/v1/namespaces/kube-system/deployments",
    "resourceVersion": "1474"
  },
  "items": []
}
```

Get:
```
$ curl http://localhost:8080/apis/apps/v1/namespaces/kube-system/deployments/foo -v
> GET /apis/apps/v1/namespaces/kube-system/deployments/foo HTTP/1.1
< HTTP/1.1 404 Not Found
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "deployments.apps \"foo\" not found",
  "reason": "NotFound",
  "details": {
    "name": "foo",
    "group": "apps",
    "kind": "deployments"
  },
  "code": 404
}
```
