### ISSUE TITLE
pod.Spec.Containers[0].Resources.Limits.Cpu() = resource.NewQuantity(500, "")

### ISSUE THREAD

**Issue by lijiansgit** [kubernetes/client-go#540]
pod.Spec.Containers[0].Resources.Limits.Cpu() = resource.NewQuantity(500, "") 
go build 
./main.go:33:48: cannot assign to pod.Spec.Containers[0].Resources.Limits.Cpu()
why

**Comment by liggitt** [comment]
you cannot assign a value to a function call on the left-hand side

/close

**Comment by lijiansgit** [comment]
how can i assign pod.Spec.Containers[0].Resources.Limits.Cpu ?

**Comment by liggitt** [comment]
`pod.Spec.Containers[0].Resources.Limits[api.ResourceCPU] = …`
