### ISSUE TITLE
forbidden: User "system:anonymous" cannot get resource "pods" in API group "" in the namespace "default"

### ISSUE THREAD

**Issue by liukaii** [kubernetes/client-go#542]
here is my config:
```
var kubeconfig *string
	kubeconfig = flag.String("kubeconfig", "/app/config", "(optional) absolute path to the kubeconfig file")
	flag.Parse()
	// uses the current context in kubeconfig
	config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		fmt.Println("buildconfigfromflag failed! err:", err.Error())
		return PotRepository{}
	}
	config.TLSClientConfig = rest.TLSClientConfig{Insecure: true} 
	// creates the clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		fmt.Println("init kubernetes clientset failed! err:", err.Error())
		return PotRepository{}
	}
```
then I `pod, err := repo.clientset.CoreV1().Pods("default").Get(potname, v1.GetOptions{})`
the error is 
`pods "wordpressv3-wordpressv3-80" is forbidden: User "system:anonymous" cannot get resource "pods" in API group "" in the namespace "default"`
Could you tell me how to solve this?

**Comment by liggitt** [comment]
That means you are not sending recognized credentials to the server. https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts walks through what content can be put in the kubeconfig file to configure credentials for a cluster.

/close
