### ISSUE TITLE
[question] Get all the resources linked to a resource using ownerreference or label

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes/client-go#543]
# Use case

I wonder if there is a utility function that I could use to retrieve for a k8s resource all the associated/linked resources created such as by example : deployment, replicaset, service, route, .... using either the ownerReference or labels ?

**Comment by mlycore** [comment]
What's the definition of 

> all the associated/linked resources created

**Comment by teintuc** [comment]
I think what @cmoulliard  means, is to a way to reproduce the following kubectl command:
``` kubectl get deploy,svc,pods --selector app=test --namespace test```

Using client-go

**Comment by cmoulliard** [comment]
This is exactly what I wanted todo ;-) After looking to the kubectl code and discovering the `cli-runtime` project, I was able to design such query DSL in order to find/select resources using a Selector, Namespace

https://github.com/snowdrop/query-api/blob/master/pkg/helper/query/resources.go#L35-L43

```
func (r *Resources) Query(selector, ns, resources string) ([] *resource.Info, error) {
	resp := r.Config().builder.
		Unstructured().
		NamespaceParam(ns).
		ResourceTypeOrNameArgs(true, resources).
		LabelSelector(selector).
		Latest().
		Flatten().
		Do()

	infos, err := resp.Infos()
	if err != nil {
		return nil, err
	}
```
