### ISSUE TITLE
ConfigMap watching drops connection silently

### ISSUE THREAD

**Issue by rametta** [kubernetes/client-go#547]
Hello,

I'm have an issue watching configMaps. After a while the connection will drop silently without any warning and the server will stop receiving updates through the ResultChan(). I've tried using TimeoutSeconds to keep the timeout to be much longer but it seems hacky to put a very large number there.

**Is there any way to catch a dropped connection so i can schedule a reconnect?**

Here is my code. Any insights will be helpful, thank you.

```go
watcher, err := client.CoreV1().ConfigMaps(namespace).Watch(metav1.ListOptions{
  FieldSelector: fields.Set{"metadata.name": namespace + "-" + stage + "-config"}.AsSelector().String(),
  Watch:         true,
})

if err != nil {
  log.Fatalln(err.Error())
}

for event := range watcher.ResultChan() {
  fmt.Println("EVENT TYPE: ", event.Type)
  c := event.Object.(*v1.ConfigMap)
  configMap = c.Data
  fmt.Println("Updated config map")
}
```

**Comment by liggitt** [comment]
when the connection drops, the result channel closes, and your code is responsible for re-establishing the watch

/close

**Comment by alexec** [comment]
@liggitt do you have an example of the code needed please?

**Comment by liggitt** [comment]
you can use:
* [NewRetryWatcher](https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go#L59-L62) if you want to guarantee you observe every watch event and terminate if it can't re-establish a dropped watch at exactly the dropped version
* [NewIndexerInformerWatcher](https://github.com/kubernetes/client-go/blob/master/tools/watch/informerwatcher.go#L103-L106) if you want your watcher to continue getting updates even if it needs to reestablish/relist and there are missed watch events that occurred while the connection was dropped
