### ISSUE TITLE
Cannot use 'clientSet.CoreV1().RESTClient()' (type rest.Interface) as type Getter Type does not implement 'Getter' as some methods are missing: Get() *restclient.Request

### ISSUE THREAD

**Issue by vvkkhjt** [kubernetes/client-go#549]
I want to watch deployments add or delete
but I use cache.NewListWatchFromClient find something wrong
```go
watchlist := cache.NewListWatchFromClient(
		clientSet.CoreV1().RESTClient(),
		"deployments",
		metav1.NamespaceAll,
		fields.Everything())
```
1,Cannot use 'clientSet.CoreV1().RESTClient()' (type rest.Interface) as type Getter Type does not implement 'Getter' as some methods are missing: Get() *restclient.Request
2,Cannot use 'fields.Everything()' (type "aranya/vendor/k8s.io/apimachinery/pkg/fields".Selector) as type "k8s.io/apimachinery/pkg/fields".Selector Type does not implement 'fields.Selector' as some methods are missing: DeepCopySelector() Selector,

please help me tks!

**Comment by vvkkhjt** [comment]
I resolve it

**Comment by zehuaiWANG** [comment]
could you tell me how to resolve this problem
