### ISSUE TITLE
govendor get k8s.io/client-go failed

### ISSUE THREAD

**Issue by inetkiller** [kubernetes/client-go#55]
when exec
`govendor get k8s.io/client-go`
 
I get following error:
`can't load package: package k8s.io/client-go: no buildable Go source files in ~/go/src/k8s.io/client-go`

**Comment by caesarxuchao** [comment]
Try `govendor get k8s.io/client-go/kubernetes`

**Comment by inetkiller** [comment]
@caesarxuchao this command download client-go to $GOPATH dir.
how to install client-go to my project's vendor dir?
thx

**Comment by timoreimann** [comment]
@inetkiller either follow up `govendor get` by `govendor add` to copy the dependency from your `GOPATH` into the vendor folder; or bypass `GOPATH` and use `govendor fetch` in the first place, which downloads dependencies directly into your vendor folder.

**Comment by timoreimann** [comment]
@inetkiller you might also want to prefer vendoring a stable branch or version tag as opposed to unstable master. Append `@=<branch or tag specifier>` to the `govendor fetch` line to achieve that.

Refer to the govendor README file for details.

**Comment by KaleoCheng** [comment]
@inetkiller  You should use `...` like this:
```shell
$ govendor fetch k8s.io/client-go/...
```

**Comment by caesarxuchao** [comment]
I think this issue is resolved. If not, please reopen it.
