### ISSUE TITLE
How to cancel a SPDYExecutor stream?

### ISSUE THREAD

**Issue by rberrelleza** [kubernetes/client-go#554]
I'm executing a long-running command on a pod with the following code:

```
exec, err := remotecommand.NewSPDYExecutor(config, method, url)
	if err != nil {
		return err
	}

	return exec.Stream(remotecommand.StreamOptions{
		Stdin:             stdin,
		Stdout:            stdout,
		Stderr:            stderr,
		Tty:               tty,
		TerminalSizeQueue: terminalSizeQueue,
	})
```

In this implementation, `exec.Stream` won't return until the command finishes. 

How can I cancel the call to `Executor.Stream`? (e.g. to react to a cancellation context, or to initiate a shutdown sequence). I searched in the docs and the code base but couldn't figure out a way to pass a context, a cancel function or something similar.

**Comment by djgilcrease** [comment]
I have found that as soon as stdin is closed it will return. Though I also found this to be inconsistent and just switched to [GetLogs](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/pod_expansion.go#L43) and updated my containers that used to expect stdin to read from an env var what I passed into the POD when starting it.

https://gitlab.com/f5-pwe/kog/blob/master/executor.k8s.go#L197

**Comment by phanhuy1502** [comment]
@rberrelleza do you find the solution to this?
I've tried closing stdin/stdout/stderr stream, the `Executor.Stream()` will stuck [here](https://github.com/kubernetes/client-go/blob/20e59c60f899e4e2b16161938abe0f33b60ff570/tools/remotecommand/v4.go#L75) because of empty error chan

**Comment by rberrelleza** [comment]
> @rberrelleza do you find the solution to this?
> I've tried closing stdin/stdout/stderr stream, the `Executor.Stream()` will stuck [here](https://github.com/kubernetes/client-go/blob/20e59c60f899e4e2b16161938abe0f33b60ff570/tools/remotecommand/v4.go#L75) because of empty error chan

no, the proposed solution didn't work for me. I ended up launching the connection on a goroutine so it wouldn't block the rest, and just time it out if needed.

**Comment by wangjia184** [comment]
You can set `TTY` to true, and send CTRL-C(0x03) to stop the transmission

**Comment by hainesc** [comment]
> 

I send CTRL-D(0x04) and to close it.

**Comment by zhamdoctor** [comment]
> 0x04

write message with ctrl-d or 0x04?

**Comment by liukelin** [comment]
How to with ctrl-d or 0x04?

**Comment by zhamdoctor** [comment]
> How to with ctrl-d or 0x04?

exit command from frontend,but it cant resolve the situation like vpn disconnected unexpectly.you can restore pid locally and send kill command next time the user log in the same pod

**Comment by liukelin** [comment]
请问下。我用了client-go 的新版本，提供了 StreamWithContext函数，可以通过监听前端websocket关闭，来同时控制关闭这个context。这样  Stream流倒是关闭了， 但是我发现pod里面的sh进程还存在。 不知道怎么发送 ctrl-d or 0x04，有例子吗。

**Comment by CirillaQL** [comment]
> 请问下。我用了client-go 的新版本，提供了 StreamWithContext函数，可以通过监听前端websocket关闭，来同时控制关闭这个context。这样 Stream流倒是关闭了， 但是我发现pod里面的sh进程还存在。 不知道怎么发送 ctrl-d or 0x04，有例子吗。

参考这个pr [https://github.com/kubesphere/kubesphere/pull/5024](url)

**Comment by CirillaQL** [comment]
> 有其他好的实现吗，确实还是会sh进程泄露。不知道是不是0x04没发送成的问题

如果只有一层shell进程，网络正常的话，0x04是好用的，我已经在我们的环境上测试完成了。

**Comment by liukelin** [comment]
是直接在这个函数里面写吗  
`Read(p []byte) (size int, err error) `

**Comment by CirillaQL** [comment]
> kubesphere/kubesphere#5024

是的，看pr的terminal.go文件修改内容呀，在需要的退出位置 copy(p, '\u0004')
https://github.com/kubesphere/kubesphere/pull/5024
