### ISSUE TITLE
Need information related to "the server could not find the requested resource" error.

### ISSUE THREAD

**Issue by gautammoulik** [kubernetes/client-go#555]
Hello all,
Firstly thanks a lot for the wonderful documentation and the sample crud code.  I have mixed experience running this code.
On Windows 10: ( Kubectl version : client : 1.13.0, server : 1.8.7 )
the code is running all good.

On Ubuntu 16.04 VM ( Kubectl version : client : 1.10.8, server 1.8.7)
 the same code fails with error "the server could not find the requested resource". 
_list, err := deploymentsClient.List(metav1.ListOptions{})_ [ code was failing here ]

While searching about this issue, I found this post useful ( https://github.com/kubernetes/client-go/issues/178 ) and as mentioned I have modified my code as 
_deployments, err := clientset.ExtensionsV1beta1().Deployments("").List(metav1.ListOptions{})_ 

After changing the code, now the code runs fine on my ubuntu. 

I am new in Go language & Kubernetes and hence wanted to know a few things ... 
a) how to debug such issues to find out the root cause ? the error message was not good enough to indicate what the real issue was ("the server could not find the requested resource". ), is there a way we can take a log of server and can I enable logging while running my code ?
b) Does that mean [ _list, err := deploymentsClient.List(metav1.ListOptions{})_ ] is depends on the Kubectl client and server version ? 
c) I didn't try this piece of code [ _deployments, err := clientset.ExtensionsV1beta1().Deployments("").List(metav1.ListOptions{})_  ] on windows yet, however it will be good to know if this code works absolutely fine in all the environments. 
d ) how to determine which version of these code to choose for my K8 environment ? is it simply error and trial model ?

Note: I was just running the listing existing deployments part from the sample code.
Thanks,
Gautam

**Comment by mlycore** [comment]
In my opnion, using explicitly specified resource version will be preferred, like `deployments, err := clientset.ExtensionsV1beta1().Deployments("").List(metav1.ListOptions{}) `.  That is we should build our understanding of API version first, then we choose the stable resource version in our cluster, and finally write a Go program to handle it.
