### ISSUE TITLE
Unable to resolve k8s.io/api/admissionregistration/v1alpha1

### ISSUE THREAD

**Issue by narasago** [kubernetes/client-go#556]
Hi,

I am using k8s.io/client-go which internally uses k8s.io/api which has dependency resolution problem.

Go version : go version go1.11.4 linux/amd64
Version details of the apis:
k8s.io/api v0.0.0-20190205051315-663a691defed
k8s.io/client-go v10.0.0+incompatible

The packages of k8s.io/api are latest, but when "env GO111MODULE=on go mod vendor" is executed, the dependencies present in k8s.io/client-go are not getting updated.

Error that is seen while building:
vendor/k8s.io/client-go/kubernetes/scheme/register.go:22:2: cannot find package "." in:
        /root/asn/go/src/gerrit.ext.net.nokia.com/AANM/service/egress/vendor/k8s.io/api/admissionregistration/v1alpha1

Any help in troubleshooting this issue would be welcomed.

**Comment by liggitt** [comment]
see resolution in https://github.com/kubernetes/client-go/issues/551#issuecomment-457977525

/close

**Comment by jsravn** [comment]
I think this is still a problem, the linked comment does not solve it.
