### ISSUE TITLE
Statefulset support

### ISSUE THREAD

**Issue by LiuZhiyan** [kubernetes/client-go#56]
In client-go master branch statefulset support [0] has been added by bot from kubernetes master days ago, however it is not included in 1.4 and 1.5 release. So may I know if there is a plan to support it? Will team release a new client version in near future? Thanks.

[0] https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/apps/v1beta1/statefulset.go

**Comment by caesarxuchao** [comment]
No, we are not going to backport statefulset support to 1.4 or 1.5.

Can you use v2.0.0-alpha.1? It should have the statefulset.

**Comment by LiuZhiyan** [comment]
Cool! Will try release-2.0 [0] in these two days. Thanks again.

[0] https://github.com/kubernetes/client-go/blob/release-2.0/kubernetes/typed/apps/v1beta1/statefulset.go

**Comment by dshulyak** [comment]
It would be very convenient to have Petsets/Statefulsets in the same client library. I need to support both 1.4/1.5 clusters in the application. The only solution i came up with is to vendor both kubernetes and client-go of different versions...

@caesarxuchao maybe you can suggest something?

**Comment by dshulyak** [comment]
I actually can't import kubernetes v1.4.7, while i have client-go of v2.0.0. Is there any other workaround?

**Comment by caesarxuchao** [comment]
> I actually can't import kubernetes v1.4.7, while i have client-go of v2.0.0

Why? client-go doesn't vendor k8s, so I thought it wouldn't prevent you from importing kuberentes v1.4.7.

I can't think of a better solution. Statefulset and Petset never coexist in a same release.

(Sorry I've been OOO and will be OOO for the next two weeks, so there might be delay in my replies. Ask @lavalamp if needed)
