### ISSUE TITLE
How to get current node name / hostname from pod

### ISSUE THREAD

**Issue by protheusfr** [kubernetes/client-go#565]
Hello,

I'm looking from a way from client-go to get current node name or node hostname when the code is running in a pod in the cluster (via a `rest.InClusterConfig()`).
Is it possible ?

**Comment by GeorgeGuo2018** [comment]
It seems that no such function is supplied by client-go. you can try :
$ curl -Gs http://localhost:10255/pods/ | grep -o '"nodeName":"[^"]*"' | head -n 1

**Comment by liggitt** [comment]
you can inject the node name or host IP into environment variables in a pod using the downward API

see https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables for more info

/close

**Comment by qiujiangkun** [comment]
Here's a script to match against IP address
```shell
(ip addr | awk '/inet/{print $2}' | awk -F/ '{print $1}') > /tmp/internal_ip.txt
local_node=$(kubectl get node -o wide | grep -f /tmp/internal_ip.txt | awk '{print $1}')
```
