### ISSUE TITLE
watch logs

### ISSUE THREAD

**Issue by jney** [kubernetes/client-go#567]
Hi there, I'd like to watch Job logs, and stream them through a pubsub mechanism.
I'm not sure I should accomplish it through `client.Batch().Jobs(cfg.KubeNamespace).Watch(options)` or using informers. 
Any advices are welcome,  or even better, examples.

By the way, I'm not sure this is the right place to post such question, feel free to delete it, if it shouldn't be there

**Comment by hzxuzhonghu** [comment]
you can do that by getting pod logs. c.Pods().GetLogs
