### ISSUE TITLE
Provide instructions in INSTALL.md for go modules users

### ISSUE THREAD

**Issue by eriksw** [kubernetes/client-go#569]
INSTALL.md should include working instructions for how to use this library when using go modules.

I have been unable to accomplish this. To reproduce, save the following as `Dockerfile` in an empty directory then `docker build .`:

    FROM golang:1.12

    WORKDIR /src

    RUN go mod init example

    RUN go get \
    k8s.io/client-go@kubernetes-1.13.4 \
    k8s.io/apimachinery@kubernetes-1.13.4

    RUN wget -q https://raw.githubusercontent.com/kubernetes/client-go/master/examples/in-cluster-client-configuration/main.go

    RUN go mod tidy

    RUN go build main.go

Output of the step that fails:

    ...
    Step 7/7 : RUN go build main.go
     ---> Running in 5014f5103213
    go: finding k8s.io/api/admissionregistration/v1alpha1 latest
    go: finding k8s.io/api/admissionregistration latest
    go: finding k8s.io/api latest
    build command-line-arguments: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1
    The command '/bin/sh -c go build main.go' returned a non-zero code: 1

Please update `INSTALL.md` with what the `go get ...` should be for this to work.

**Comment by aprice2704** [comment]
Seconded! Would like to get the 10.0 tag with modules/version 12 of Go -- but how? Andy :)

**Comment by dubee** [comment]
Ran into this problem as well when using `go.mod` with `go mod download`...

**Comment by integrii** [comment]
```
../../../go/pkg/mod/k8s.io/client-go@v10.0.0+incompatible/kubernetes/scheme/register.go:22:2: unknown import path "k8s.io/api/admissionregistration/v1alpha1": cannot find module providing package k8s.io/api/admissionregistration/v1alpha1
```

**Comment by liggitt** [comment]
added instructions in https://github.com/kubernetes/kubernetes/pull/75595/files
