### ISSUE TITLE
jsonpb & json co-existance

### ISSUE THREAD

**Issue by f4tq** [kubernetes/client-go#574]
Hi,

We have a bunch of types (Istio 1.0x) whose implementations return `jsonpb` encoded results as `json`: NOT straight `json` go encoding: enums as strings etc.
 
Obviously, such translations fail harshly with json-iterator when proto3 go structs are unmarshalled when the cross into jsonpb assumptions.

Is there a straightforward way (actually any approach)  to register a type deserializer so as to invoke `jsonpb` `Unmarshal` functions were I to generate them for all istio types with `protoc` and register them with client-go? 

In general, is there a way to register a type's json de-serializer (interpretor) ? 

I don't see a way to insert such a de-serializer into the client (NewRESTClient)  without `createSerializers` (private) stomping on any such notions.

kubernetes, as expected, returns `application/json` for istio types so content-type negotiation seems out of the question.   There must be an approach I'm missing....

> FWIW, here is the [proto3 jsonpb encoding 'standard'](https://developers.google.com/protocol-buffers/docs/proto3#json)

I don't mind managing the type <-> [de]serializer relationship either.

Please shed some light on what I'm missing ( a way to register and/or insert some json interpretation)?
Many thanks,
-Chris

**Comment by liggitt** [comment]
See discussion in https://github.com/istio/api/issues/716#issuecomment-440804709

**Comment by liggitt** [comment]
The `config.NegotiatedSerializer` passed in participates in construction of serializers in createSerializers:

https://github.com/kubernetes/client-go/blob/dfef1155b5f78983b85be7b1654ac567d344d136/rest/client.go#L189-L198

**Comment by liggitt** [comment]
ideally the istio types would implement MarshalJSON/UnmarshalJSON if they didn't work with the stdlib json encoder

**Comment by f4tq** [comment]
MarshalJSON/UnmarshalJSON did the the trick.
Thanks for the help.
