### ISSUE TITLE
I cant get Apiversion and Kind from deployment.create return *v1beta2.Deployment

### ISSUE THREAD

**Issue by vvkkhjt** [kubernetes/client-go#576]
![11](https://user-images.githubusercontent.com/12765476/54660485-9e11ba80-4b11-11e9-9de1-233c8910023a.png)

**Comment by alexbumbacea** [comment]
This issue seems to be generic. Encountered same issue with configmaps

**Comment by liggitt** [comment]
yes, this is the same issue as https://github.com/kubernetes/kubernetes/issues/80609

closing in favor of the kubernetes/kubernetes issue

/close
