### ISSUE TITLE
Question: "kubectl delete pods,services -l name=myLabel" 

### ISSUE THREAD

**Issue by muratsplat** [kubernetes/client-go#577]
Hello Guys

As you know We can delete two and more resource on an kubernetes cluster follow `kubectl` cli command on terminal. I want to do same thing using `client-go`. 

How can I delete two and  more resource( pods,services,config,etc..) by client-go library at same time.? Can you give an example about deleting  different resource using label selector ?

**Comment by liggitt** [comment]
That would be two distinct API calls. If you add `--v=6` to the kubectl invocation, you can see it making multiple API calls to satistfy that command.

/close

**Comment by muratsplat** [comment]
I understand, there are a tricky in `kubectl`. I had thought that k8s can handle request for multi resource.
@liggitt  thank you..
