### ISSUE TITLE
Watching and getting resources from multiple namespaces

### ISSUE THREAD

**Issue by gpanagiotidis** [kubernetes/client-go#580]
How to get resoures from multiple namespaces? I do not want to use "" for all namespaces, I want to define my own namespaces I want to get resources from.

**Comment by yuchaoran2011** [comment]
It doesn't seem possible at the moment. The operator uses an "informer" that watches an individual namespace or all namespaces. But it doesn't support multiple namespaces.

Someone asked about this feature years ago and a Kubernetes maintainer [said](https://github.com/kubernetes/ingress-nginx/issues/732#issuecomment-302418412) that it won't be supported.

**Comment by gpanagiotidis** [comment]
What I do is put namespaces into an array, and create a loop just before the watchlist initiation until the start of the controller. So there are multiple controllers starting at the same time for each namespace. However I am not sure this is a correct way to do such a thing.

**Comment by skonto** [comment]
This should be provided by the k8s api server: https://github.com/kubernetes/kubernetes/issues/74415
