### ISSUE TITLE
Is it recommended to use dynamic client now?

### ISSUE THREAD

**Issue by soolaugust** [kubernetes/client-go#585]
Hello everyone,

I am trying to found a better way for CRD resource handling, I saw some best practice are based on dynamic client. 

but when I search deeply. I found this way are not recommended:

> @hochuenw We suggest to use a typed client (i.e. the generated client) instead of the dynamic client, since that has created some problems in the past. We originally had an example for the dynamic client but we moved it to use the typed client.
> 
> However, if you are interested in an example with using the dynamic client, here is an example for an older branch (before we moved the example to a typed client) - https://github.com/kubernetes/apiextensions-apiserver/tree/release-1.8/examples/client-go.

but at end of discussion, @nikhita said new dynamic client  is better and encourage to use. 

So that means dynamic client is recommended for CRD resources handling, right?

**Comment by sttts** [comment]
There is the spectrum of:
1) dynamic - totally untyped but super flexible
2) sigs.k8s.io/controller-runtime client which uses a scheme for CRD types, but no generation – less code generation, less type safety, but generic, i.e. one client for all types.
3) client-gen generated client – super type safe, but need code generation.

I don't think there is a best practice. All clients serve different purposes. Use the one which fits to your use-case.

**Comment by soolaugust** [comment]
@sttts, thanks, I will check these ways.
