### ISSUE TITLE
Cannot watch k8s cluster nodes using the NewListWatchFromClient method

### ISSUE THREAD

**Issue by moadqassem** [kubernetes/client-go#586]
I have been trying to set a watcher on the nodes in my k8s cluster in order to trigger a change on the node object once a specific label occur. 

Here is the error message: 
`E0408 13:26:49.620355   12719 reflector.go:131] pkg/mod/k8s.io/client-go@v0.0.0-20190405212609-89226ff90625/tools/cache/reflector.go:99: Failed to list *v1.Node: the server could not find the requested resource`

Now I am using the `ListWatch` from the cache package: 
`	nodeListWatcher := cache.NewListWatchFromClient(client.CoreV1().RESTClient(), "nodes", namespace, fields.Everything())` 

I am also initialising the state of the cache with the preexisted nodes using the indexer: `indexer.Add(&node); `

The adding functionality to the indexer works just fine, however the list of the resources doesn't. 

Thought that I have to create `RESTCleint` from a different api (e.g: `NodeV1beta1()`) but still it didn't work. 

Server Version: version.Info{Major:"1", Minor:"13"). 

Any thoughts?

**Comment by moadqassem** [comment]
As an assumption the only way to watch nodes is just by using `Watch(opts metav1.ListOptions) (watch.Interface, error)`

**Comment by alekc** [comment]
For anyone ending up here from google like me, `NewListWatchFromClient` actually works for nodes as well, see the example below 

```
var stopCh <- chan struct{}
	watcher := cache.NewListWatchFromClient(clientset.CoreV1().RESTClient(),"nodes", metaV1.NamespaceAll,fields.Everything())
	_, controller := cache.NewInformer(
		watcher,
		&coreV1.Node{},
		time.Second * 10,
		cache.ResourceEventHandlerFuncs{
			AddFunc: func(obj interface{}) {
				node, ok := obj.(*coreV1.Node)
				if !ok {
					log.Fatal().
						Str("object_type",fmt.Sprintf("%T",node)).
						Msg("list/watch returned non-node object")
				}
				log.Info().Str("node_name",node.Name)

				//annotations := node.GetAnnotations()
				//if val,ok := annotations["flannel.alpha.coreos.com/public-ip-overwrite"]; ok {
				//
				//}
				time.Sleep(time.Second * 5)
				log.Printf("handling node %s", node.GetName())
			},
		},
	)

	controller.Run(stopCh)
```
