### ISSUE TITLE
Third Party Resources example improvements

### ISSUE THREAD

**Issue by ash2k** [kubernetes/client-go#59]
Thanks for all the work that has been done here! I tried to use the client when it was part of main repo and it was so hard I gave up. Now it is much more useable! I have a few questions/suggestions:

- `Example` struct uses `ObjectMeta` from `k8s.io/client-go/pkg/api` package. Is that right? Should it be a versioned API object from `k8s.io/client-go/pkg/api/v1`? I only found this document [api_changes.md] with the phrase "Clients should consume and operate on the versioned APIs exclusively". Is there a mode specific document with guidelines on how to use Third Party Resources with detailed explanations and code samples? Would be nice to improve [TPR] docs with at least a link to this repo.
- Package level `config` variable in `main.go` is not used, it is shadowed by the one defined in `main()`. Should probably be deleted.
- `configureClient()` mutates global `api.Scheme` - it is probably a bad idea. Because of that a program I'm writing had a race condition on that field. Any reasons not to create a new `Scheme` instance and mutate it (that is what I did)?

[api_changes.md]: https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md
[TPR]: http://kubernetes.io/docs/user-guide/thirdpartyresources/

**Comment by ash2k** [comment]
Also maybe add assertions to ensure interfaces are actually implemented:
```go
var _ runtime.Object = &Example{}
var _ meta.ObjectMetaAccessor = &Example{}

var _ runtime.Object = &ExampleList{}
var _ meta.ListMetaAccessor = &ExampleList{} // should be metav1?
```

**Comment by caesarxuchao** [comment]
@ash2k, you are right about all four points. Do you have time to create a PR (client-go accepts PRs to examples and docs)? Could you assign it to @lavalamp though? I'm OOO for the next two weeks. Thanks.

What do you mean by "mode specific document"?

**Comment by caesarxuchao** [comment]
FWIW, I tried locally and confirmed that v1.ObjectMeta worked so we should use v1.ObjectMeta.

I also tried to use a new instance of Schema and build codecs around it, it also worked.

**Comment by caesarxuchao** [comment]
cc @wfarr
