### ISSUE TITLE
PKI creation using now.UTC breaks after system clock drift corrections

### ISSUE THREAD

**Issue by mikeparker** [kubernetes/client-go#592]
We're tracking a rare bug in Docker Desktop where users are getting the error message:
`the certificate is not valid yet` (see: https://github.com/docker/for-win/issues/2913)

This can be reproduced by manually changing your system clock forwards and backwards, but we believe it can also occur naturally when a system clock drifts forwards and a reboot or other sync corrects the system clock backwards again. 

We're using the code here to generate our kubernetes certificates:
https://github.com/kubernetes/client-go/blob/master/util/cert/cert.go#L65
which uses `time.Now` and `NotBefore : now.UTC()`

Some options:
a) Switch away from this utility function and write our own code to provide similar functionality
b) Open a PR here to provide flexibility in the NotBefore time, either setting the NotBefore time to a long time ago (e.g. 1970), providing an optional grace period
c) Open a PR here to change the default NotBefore time to use a hard coded grace period or set start time in the past

WDYT?

**Comment by liggitt** [comment]
thanks for the issue, this should actually be filed against kubernetes/kubernetes... there are a few things here:

it looks like https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L249-L256 does client-side validation, which is problematic for the clock drift reasons mentioned. it should not.

it is also reasonable to allow *some* buffer in the NotBefore time (c.f. https://github.com/kubernetes/client-go/blob/master/util/cert/cert.go#L95)

**Comment by mikeparker** [comment]
Ok thanks, copied across to https://github.com/kubernetes/kubernetes/issues/76714
