### ISSUE TITLE
no such file or directory when call exec 

### ISSUE THREAD

**Issue by ycwdaaaa** [kubernetes/client-go#593]
when I try to implement the kubectl exec by calling client-go.  I use the following code:

req := c.K8SClient.CoreV1().RESTClient().Post().
		Resource("pods").
		Name(podsList[0].Name).
		Namespace(c.Namespace).
		SubResource("exec")
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		return err
	}

	//commands := []string{"for i in `seq 1 10`; do dd if=/dev/zero of=/dev/null & done"}
	//commands := []string{"/bin/bash -c dd if=/dev/zero of=/dev/null &"}
	commands := []string{"/bin/bash -c","ls", " /dev"}
	parameterCodec := runtime.NewParameterCodec(scheme)
	req.VersionedParams(&corev1.PodExecOptions{
		//Command:   strings.Fields("/bin/bash -c 'for i in `seq 1 $(cat /proc/cpuinfo |grep \"physical id\" |wc -l)`; do dd if=/dev/zero of=/dev/null & done'"),
		//Command:   strings.Fields("/bin/bash -c dd if=/dev/zero of=/dev/null &"),
		Command:   commands,
		Container: "app",
		Stdin:     true,
		Stdout:    true,
		Stderr:    true,
		TTY:       false,
	}, parameterCodec)

	fmt.Println("Request URL:", req.URL().String())

	exec, err := remotecommand.NewSPDYExecutor(c.Config, "POST", req.URL())
	if err != nil {
		return fmt.Errorf("error to burn cpu in container %v ", err)
	}

	var stdout, stderr, stdin bytes.Buffer
	err = exec.Stream(remotecommand.StreamOptions{
		Stdin:  &stdin,
		Stdout: &stdout,
		Stderr: &stderr,
		Tty:    false,
	})
	fmt.Println(stdout.String())
	if err != nil {
		return fmt.Errorf("error to burn cpu in container. output: %s, err: %s : %v , pod: %s ", stdout.String(), stderr.String(), err, c.Deployment)
	}

	logger.Info("successfully burn cpu in container")

But I got the error: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused \"exec: \\\"/bin/bash -c\\\": stat /bin/bash -c: no such file or directory\": unknown\r\n, err:  : command terminated with exit code 126 , pod: pas "

I found that I cannot see the /  real root path 

Is there anyone know why?

I use the --v=8 to call kubectl exec to see the request and parameter,  and I found that they sent the same request and parameters. So why different?

**Comment by jorgonzalez** [comment]
Hi,

I'm having a similar issue. Can you share your kubernetes version and docker version?
Can you execute a simple the same pod with the following command instead and see if it works (the code below works for me):

    command: ["/bin/bash"]
    args: ["-c", "/bin/echo Works!"]


My system:
- Docker version 18.06.1-ce, build e68fc7a
- Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- CoreOS 1911.4.0 Rhyolite

**Comment by prksu** [comment]
@ycwdaaaa this seem because the container image that invoked `exec` doesn't have `bash` binary. can you describe what container image that running in your pod?

**Comment by xie233** [comment]
commands := []string{"bash", "-c","ls /dev"} should work
