### ISSUE TITLE
go.mod 

### ISSUE THREAD

**Issue by wei0313** [kubernetes/client-go#599]
Hi

I am fairly new to golang. I have a question, which I can't seem to find an answer. 
I have a go file which dependency is the client-go (and the necessary packages like api, apimachinery, utils). My questions is how do I enforce to a particular version? I tried modifying the go.mod file and give "release-10.0" and "v10.0", but I always got master branch. I would like to know what tag I should use to get the 10.0 version. Also, where I should modify to enforce the version? Do I put the version in the "import" in my go file? 

Thanks

**Comment by liggitt** [comment]
`require k8s.io/client-go v10.0.0` specifies a particular version. Note that other dependencies must also be required at specific versions prior to client-go v12.0.0 which will add dependency info in a form go can understand

See https://github.com/kubernetes/client-go/blob/master/INSTALL.md#go-modules for details

**Comment by wei0313** [comment]
@liggitt  

I have tried that so here is my additional question:
I know I need api 1.13 version for client-go v10. Hence, I included api 1.13. However, it seemed like it was only partially pull from the version I specified. 
1. How can I force all the subdirectory of a project to be on the same version?
2. How should i find the correct version name for each associated project? I don't mean compatibility. I meant where/what name of the branch in the repo I should use to enforce to a certain version? 

In my go.mod:
...
require (
	github.com/golang/protobuf v1.3.1
	k8s.io/api kubernetes-1.13.5
	k8s.io/client-go v10.0.0
...}

user@virt-8876$ go build test/client.go 
go: finding k8s.io/api kubernetes-1.13.5
go: finding k8s.io/api/admissionregistration/v1alpha1 latest
go: finding k8s.io/api/admissionregistration latest
go: finding k8s.io/api latest
build command-line-arguments: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1

**Comment by liggitt** [comment]
You can use the kubernetes-… tags for all dependencies, like this:

require (
k8s.io/client-go kubernetes-1.13.5
k8s.io/api kubernetes-1.13.5
k8s.io/apimachinery kubernetes-1.13.5
)

**Comment by wei0313** [comment]
@liggitt 
I tried per your comment. I saw some errors. It seems like api with the tag it was unable to successfully pull everything from 1.13.5. a part of it is from the latest. Is there anything else I should include to enforce everything under an application would be in the same version ?

In my go.mod:
...
require (
github.com/golang/protobuf v1.3.1
k8s.io/api kubernetes-1.13.5
k8s.io/client-go v10.0.0
...}

However, when I build, I kept getting errors because it's pulling "k8s.io/api/admissionregistration/v1alpha1 latest". I tried adding k8s.io/api/admissionregistration/v1alpha1 kubernetes-1.13.5, but it complained about no go.mod in api/addmissionregistration. Could you tell me how to solve this issue? Is my configuration done incorrectly?

user@virt-8876$ go build test/client.go
go: finding k8s.io/api kubernetes-1.13.5
go: finding k8s.io/api/admissionregistration/v1alpha1 latest
go: finding k8s.io/api/admissionregistration latest
go: finding k8s.io/api latest
build command-line-arguments: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1

**Comment by liggitt** [comment]
Can you include your full go.mod file?

**Comment by wei0313** [comment]
`module github.com/myGoProj

go 1.12

require (
	github.com/golang/protobuf v1.3.1
	k8s.io/utils master
	k8s.io/api kubernetes-1.13.5
	k8s.io/apimachinery kubernetes-1.13.5
        k8s.io/client-go v10.0.0
	github.com/google/btree v1.0.0 // indirect
	github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc // indirect
	github.com/imdario/mergo v0.3.7 // indirect
	github.com/peterbourgon/diskv v2.0.1+incompatible // indirect
	golang.org/x/crypto v0.0.0-20190424203555-c05e17bb3b2d // indirect
	golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a // indirect
	golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 // indirect
)

`

**Comment by wei0313** [comment]
@liggitt I don't know what happened, I just tried it again and the error is gone. I was able to compile successfully now. Thank you all the help
