### ISSUE TITLE
GCP auth Provider

### ISSUE THREAD

**Issue by tobstarr** [kubernetes/client-go#6]
Is there already a documented way to use `gcp` as auth provider? I am looking into accessing a GKE cluster with my local kubeconfig file and also tried to use the gcpAuthProvider from https://github.com/kubernetes/kubernetes/blob/99295356ed152663698e002494a5af00d682dc6b/plugin/pkg/client/auth/gcp/gcp.go but things are not working out. 

I inlined the gcpAuthProvider (to to fix all dependencies) into a little test application, but I am getting this error: `the server has asked for the client to provide credentials (get pods)`. 

This is what I have so far: https://gist.github.com/tobstarr/6765104c764a3a6af8ec894bb5a0028b

**Comment by erictune** [comment]
@cjcullen will know the answer.

**Comment by cjcullen** [comment]
The "`server has asked for the client to provide credentials`" error is kubectl translation of a 401: either the client isn't sending any authorization credentials, or the server doesn't like the credential you sent it.

I ran your code against a cluster of mine, and it worked:
```
$ go run kc-test.go
listing pods
2016/09/27 11:12:05 loading token
{"access_token":"<TOKEN>","token_type":"Bearer","expiry":"2016-09-27T11:31:27.972813601-07:00"}
loaded 11 pods
```

Does `kubectl get pods` work when you run it with the gcp provider against that cluster?

**Comment by caesarxuchao** [comment]
The auth plugin was left out of client-go, so it didn't work for gke. It's fixed now. If you are using client-go/1.5 with your local kubeconfig, it should work.

**Comment by tobstarr** [comment]
@caesarxuchao seems things are working out now with version 1.5 cool. 

But could it be that this implementation does not update expired oauth2 tokens? When I ran the code (without registering my provider) for the first time I got this error: `the server has asked for the client to provide credentials` (I did not run kubectl for quite some time), but after running `kubectl get pods` things worked out in my program. Am I maybe missing something?

**Comment by caesarxuchao** [comment]
I'm not familiar with the code. @cjcullen do you know?

**Comment by cjcullen** [comment]
@tobstarr do you have a code sample I could take a look at?

**Comment by caesarxuchao** [comment]
I'm closing this issue due to the age. Please re-open if it's not solved.
