### ISSUE TITLE
NewFilteredDynamicSharedInformerFactory ignores namespace argument

### ISSUE THREAD

**Issue by michaelfig** [kubernetes/client-go#601]
The code at: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/dynamic/dynamicinformer/informer.go#L45
ignores the `namespace` argument, and instead overrides it with `metav1.NamespaceAll`.

I'm sure this is just an oversight, and easy to fix, but it's causing me some trouble when trying to create a dynamic informer on a cluster where I can only have RBAC access to a few namespaces.

**Comment by michaelfig** [comment]
@liggitt, just picking you out of the air for this one.  It's a really trivial change... do you want a PR from me, or can it land before #581?

**Comment by liggitt** [comment]
a PR to kubernetes/kubernetes would be great. client-go#v11.0.0 is already tagged

**Comment by michaelfig** [comment]
Thanks for the quick reply.  I'll do that.
