### ISSUE TITLE
RFE : Func to return the master VIP/URL to be used inside of the cluster

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes/client-go#602]
**What did you do?**
In a golang operator project, I'd like to get the hostname which is returned by the command  `kubectl cluster-info` for example.

```
$ kubectl cluster-info
Kubernetes master is running at https://192.168.64.19:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

The following works when the project is executed out of the cluster by the tool operator-sdk by the command `operator-sdk up local --namespace={{namespace}}` but not when the operator is running in the cluster.

* If it is running in a cluster the os.Getenv("KUBERNETES_SERVICE_HOST") has a value which is returned here and is not the value expected. ("https://172.30.0.1:443")

* When run locally, "outside of the cluster" the  KUBERNETES_SERVICE_HOST is empty and the value expected is returned. ("https://192.168.64.19:8443")

Following the code.
```go
func getClusterProtocol() string {
	cfg, _:= config.GetConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")

	return host[0]
}


func getHostIP() string {
	cfg, _:= config.GetConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")

	return host[1]
}
```
 
The same behaviour happened if we try to use the func `rest.InClusterConfig()` as follows.

```go
func getClusterProtocol() string {
	cfg, _:= rest.InClusterConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")
	log.Info("Utils - ConfigHost", cfg.Host)
	return host[0]
}


func getHostIP() string {
	cfg, _:= rest.InClusterConfig()
	cfgHost := cfg.Host
	cfgHost = strings.Replace(cfgHost, "//", "", 2)
	host := strings.Split(cfgHost, ":")
	log.Info("Utils - ConfigHost", cfg.Host)

	return host[1]
}
```

**What did you expect to see?**

The cluster hostname/master url. 

**What did you see instead? Under which circumstances?**

* If it is running in a cluster the os.Getenv("KUBERNETES_SERVICE_HOST") has a value which is returned here and is not the value expected. ("https://172.30.0.1:443")

**Comment by liggitt** [comment]
cluster-info returns the address at which the client contacts the apiserver. When running inside the cluster, that is based on KUBERNETES_SERVICE_HOST

**Comment by liggitt** [comment]
The URL returned (e.g. https://172.30.0.1:443) is the expected URL to use inside the cluster

**Comment by camilamacedo86** [comment]
@liggitt It is an RFE for you folks add a variable/func which will be returned the value which I am looking ofr. I am not saying that it is NOT working as expected. I am asking a func to solve this need. Could you please re-open it? 

Why it is important?

Currently is hard to use ingress with OCP. Since that we need to pass the HOST for it work as we expected. If the API allow us to get the HOST this issue could be solved.

**Comment by liggitt** [comment]
what you are describing would be a new API, not a client function, since the information you are wanting is not available currently (nor is it known by the apiserver). I would recommend opening a feature request against https://github.com/kubernetes/kubernetes/issues/new?labels=kind%2Ffeature&template=enhancement.md instead

**Comment by camilamacedo86** [comment]
@liggitt tks. It is done : https://github.com/kubernetes/kubernetes/issues/77444 .
