### ISSUE TITLE
why podLister do not support FieldSelector?

### ISSUE THREAD

**Issue by kitianFresh** [kubernetes/client-go#604]
I am new for k8s, I use podInformer and lister to filter some pods, but i found that lister.List() only accept labels.Selector, it do not support fields.Selector, so this behavior do not conform with api List() which support both FieldSelector and LabelSelector in ListOptions.

**Comment by cizixs** [comment]
This feature is necessary for getting pods on a specific node.

**Comment by liggitt** [comment]
field selectors are not able to be generically evaluated client-side, as labels can be. field selectors evaluation is only supported server-side today

/close
