### ISSUE TITLE
strategic merge patch does not work add node labels 

### ISSUE THREAD

**Issue by yekeqiang** [kubernetes/client-go#605]
i want add a labels to my node, so i use coreV1.Nodes().Patch() with StrategicMergePatchType, but the result is not change, no add the `test:test` labels

this is my code
```
payload := PatchStringValue{
                 Op: "merge",
		Path:  "/metadata/labels",
		Value: map[string]string{"test":"test"},
}
payloadBytes, _ := json.Marshal(payload)
newNode, err := coreV1.Nodes().Patch(nodeName, types.StrategicMergePatchType, payloadBytes)
```	

 add or update node labels can't use StrategicMergePatchType ？

**Comment by liggitt** [comment]
an array of op/path patches is type JSONPatch

strategic merge patch format is `{"metadata":{…}}`

**Comment by yekeqiang** [comment]
> an array of op/path patches is type JSONPatch
> 
> strategic merge patch format is `{"metadata":{…}}`

ths, use your method i have apply success
