### ISSUE TITLE
is DeleteFunc useless in cache.ResourceEventHandlerFuncs 

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes/client-go#606]
I try to use cache.ResourceEventHandlerFuncs  to register event handler callback,
and I find when I delete resource the UpdateFunc triggered either.
So why `delete` trigger the `DeleteFunc` or something I missing?

**Comment by liggitt** [comment]
UpdateFunc is only triggered if a delete request makes an intermediate update (for example, to add a garbage collection finalizer or to set a grace period on pods). 

When the resource is actually deleted, the delete function is called
