### ISSUE TITLE
OIDC cache returns old token even after the expiration of refresh token

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes/client-go#608]
This issue is similar to the one mentioned here.
https://github.com/kubernetes/client-go/issues/268

When a client's oidc token has expired, even on passing the latest token to create a client, newOIDCAuthProvider() returns the old client with the expired tokens.

Is there any way to unblock ourselves? Can we have the cache updated after the expiration of the token stored in the cache and store the one that is passed?

**Comment by liggitt** [comment]
sorry for the lack of attention on that issue. can you open this against https://github.com/kubernetes/kubernetes/issues and tag `/sig auth`? most use of that auth plugin is in kubectl commands where the process lifetime is short-lived, which is why this was not noticed previously

**Comment by DheerajSShetty** [comment]
Opened a bug upstream.
https://github.com/kubernetes/kubernetes/issues/78494

Thank you @liggitt
