### ISSUE TITLE
DeleteCollection on Fake client doesn't work

### ISSUE THREAD

**Issue by ye11ow** [kubernetes/client-go#609]
Hi k8s community,

I'm trying to use `Fake` provided by client-go to do some testing. One thing I noticed is that `Fake.BatchV1beta1.CronJobs.DeleteCollection` doesn't work as expected. The function call returns normally without any error but it doesn't really delete anything.

Here is a quick and dirty code to reproduce it:

```go
package main

import (
	"log"
	"time"

	batchv1 "k8s.io/api/batch/v1"
	batchv1beta1 "k8s.io/api/batch/v1beta1"
	apiv1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func main() {
	namespace := ""
	name := "testcron"
	client := fake.NewSimpleClientset()

	objectMeta := metav1.ObjectMeta{
		Name:      name,
		Namespace: namespace,
	}

	jobSpec := batchv1.JobSpec{
		Template: apiv1.PodTemplateSpec{
			ObjectMeta: objectMeta,
			Spec: apiv1.PodSpec{
				Containers: []apiv1.Container{
					{
						Name:  name,
						Image: "test",
					},
				},
			},
		},
	}

	cronJob := &batchv1beta1.CronJob{
		ObjectMeta: objectMeta,
		Spec: batchv1beta1.CronJobSpec{
			Schedule:          "1 1 1 1 1",
			ConcurrencyPolicy: batchv1beta1.ForbidConcurrent,
			JobTemplate: batchv1beta1.JobTemplateSpec{
				Spec: jobSpec,
			},
		},
	}

	cron, err := client.BatchV1beta1().CronJobs(namespace).Create(cronJob)
	if err != nil {
		log.Printf("%v", err)
	}

	cron, err = client.BatchV1beta1().CronJobs(namespace).Get(name, metav1.GetOptions{})
	if err != nil {
		log.Printf("%v", err)
	}

	log.Printf("Before DeleteCollection %v", cron)

	pro := metav1.DeletePropagationForeground

	deleteOptions := &metav1.DeleteOptions{
		PropagationPolicy: &pro,
	}

	listOptions := metav1.ListOptions{}

	if err := client.BatchV1beta1().CronJobs(namespace).DeleteCollection(deleteOptions, listOptions); err != nil {
		log.Println("err")
	}

	time.Sleep(3 * time.Second)

	newcron, err := client.BatchV1beta1().CronJobs(namespace).Get(name, metav1.GetOptions{})
	if err != nil {
		// I would expect this err to occur
		log.Printf("%v", err)
	} else {
		log.Printf("After DeleteCollection %v", newcron)

	}
}
```

Basically I would expect the last `CronJobs.Get` return a not found error. However, with Fake client, it will actually print out the `newcron`
If you change the Fake client to a real client, it works as expect (not found error will occur).

I'm using `k8s.io/client-go` `8.0.0` on macOS 10.14.4 with `go version go1.11.4 darwin/amd64`

**Comment by liggitt** [comment]
fake client essentially records the fact that API calls were made. it does not reimplement server side behavior like deletecollection, field selection, resource version conflicts, conversion between versions, defaulting, and much more

**Comment by ye11ow** [comment]
Hi @liggitt , thank you for the quick response!

I think it is an issue because `CronJobs().Delete()` actually works fine. Well, if this is by design and no plan to "fix", please feel free to close the issue. 😄 

Thanks!

**Comment by liggitt** [comment]
straightforward single item crud operations can be handled without reimplementing complex serverside logic, so create/update/get/delete sort of work (though not identically… no resourceVersion, finalizers, graceful deletion, etc, etc), but not deletecollection

**Comment by ye11ow** [comment]
@liggitt understood! Thank you for all the clarification.

**Comment by till** [comment]
@liggitt a question: Wouldn't e.g. a `panic("unsupported")` make more sense? As in, to highlight when something is not supported. This just seems like a bug or very obscure behaviour otherwise.

**Comment by grosser** [comment]
@liggitt this is closed as completed but still an issue, can you reopen it ?

**Comment by liggitt** [comment]
github partitioned closed issues into "closed as completed" and "closed as not planned", and  retroactively labeled all closed issues as "completed", which is misleading.

This is closed as "not planned"

**Comment by grosser** [comment]
PR welcome or this is know to be really complicated or unwanted for some reason ?1
