### ISSUE TITLE
Bearer Token Support

### ISSUE THREAD

**Issue by Kshitij29** [kubernetes/client-go#616]
Access to my kubernetes cluster is authorized via bearer tokens. Is there a way to add this token to the config (which is used to create the clientset) or the clientset itself, so that the following requests are honoured?

**Comment by liggitt** [comment]
Yes:

```go
config := &rest.Config{
  BearerToken:"...",
  ... other connection info ...
}

client, err := clientset.NewForConfig(config)
```

/close
