### ISSUE TITLE
Issue with Out of Cluster Client Configuration Example

### ISSUE THREAD

**Issue by shyyawn** [kubernetes/client-go#619]
Hi,

I am new to Go, and I need to script something for my GCP Kubernetes cluster.

I am trying to run the Out of Cluster client configuration example:
https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration

I tried connecting to my cluster but I am getting the following error
` imported and not used: "hcheck/vendor/k8s.io/client-go/plugin/pkg/client/auth"`

My Gopkg.toml is:
```

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "master"
  name = "k8s.io/client-go"

[prune]
  go-tests = true
  unused-packages = true

```

Does it work for the most recent versions?

**Comment by agarwalrounak** [comment]
Comment the line where you are importing `k8s.io/client-go/plugin/pkg/client/auth`. It should work after that.

**Comment by liggitt** [comment]
correct, comment out or removed unused import lines

/close
