### ISSUE TITLE
How to get node resource?

### ISSUE THREAD

**Issue by k82cn** [kubernetes/client-go#62]
In NodeInformer callback (AddFunc), it received `v1.Node` which I can not get `allocatable` of that node:

```
pkg/util/resource.go:17: cannot call pointer method on rl["github.com/k82cn/kube-arbitrator/vendor/k8s.io/client-go/1.5/pkg/api/v1".ResourceCPU]
pkg/util/resource.go:17: cannot take the address of rl["github.com/k82cn/kube-arbitrator/vendor/k8s.io/client-go/1.5/pkg/api/v1".ResourceCPU]
pkg/util/resource.go:18: cannot call pointer method on rl["github.com/k82cn/kube-arbitrator/vendor/k8s.io/client-go/1.5/pkg/api/v1".ResourceMemory]
pkg/util/resource.go:18: cannot take the address of rl["github.com/k82cn/kube-arbitrator/vendor/k8s.io/client-go/1.5/pkg/api/v1".ResourceMemory]
```

Related codes:

```
func NewResource(rl v1.ResourceList) *Resource {
	return &Resource{
		MilliCPU: float64(rl[v1.ResourceCPU].MilliValue()),
		Memory:   float64(rl[v1.ResourceMemory].Value()),
	}
}
```

Any suggestion?

**Comment by lavalamp** [comment]
You'll have to do it in two steps because go doesn't allow taking a pointer
of something in a map.

e.g.

```go

cpu := rl[v1.ResourceCPU]

...

MilliCPU: cpu.MilliValue(),

```

**Comment by lavalamp** [comment]
email doesn't do markdown, apparently, hopefully you can follow that anyway. Let me know if that's not clear enough.

**Comment by k82cn** [comment]
@lavalamp , thanks for your input; I used the following code to achieve that, because `MilliValue()` is a pointer method.

```
cpu_ := rl[v1.ResourceCPU]
cpu := &cpu_
...
MilliCPU: cpu.MilliValue(),
```

BTW, I'm using `client-go/1.5`; we can use `rl.Cpu().MilliValue()` in master.

**Comment by lavalamp** [comment]
You shouldn't need the `cpu := &cpu_` line, go should handle that for you...
