### ISSUE TITLE
Patch method support 

### ISSUE THREAD

**Issue by rohantmp** [kubernetes/client-go#620]
My use case: I want multiple entities managing one custom resource without an UPDATE race. This can be solved by having each entity only update its own set fields. This requires PATCH support.

**Comment by rohantmp** [comment]
Maybe a separate PATCH call is better.

**Comment by sttts** [comment]
What is patch support for update?

**Comment by rohantmp** [comment]
Sorry, I meant to ask about how the client-go supports the patch http method, and the got lost reading the examples. Reading an open issue lead me to believe it wasn't supported, but I'm not sure anymore.

Update doesn't have anything to do with it. I was envisioning an update method that selects only certain fields (which is patch).

Sorry for the confusion.

**Comment by sttts** [comment]
Patch is supported. You might have read about strategic merge patch. That's not supported for CustomResource, and won't be in the future (instead we will get server side apply). But JSON patches just work fine.

**Comment by rohantmp** [comment]
Thanks!
