### ISSUE TITLE
reflector go incompatible

### ISSUE THREAD

**Issue by fang19911030** [kubernetes/client-go#622]
I am using microk8s v1.15. The kube-dns doesn't work. The output of kubectl log is 
`E0626 16:37:44.167470       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "endpoints" in API group "" at the cluster scope`

**Comment by fang19911030** [comment]
correct typo.

**Comment by sttts** [comment]
This is not an issue of client-go, but some permission problem in microk8s. Please report the issue there.
