### ISSUE TITLE
Is there a document to explain method of use.

### ISSUE THREAD

**Issue by strugglingyouth** [kubernetes/client-go#63]
Is there a document to explain method of use, I don't know how to start，urgent need to use，Does anyone know，thanks.

**Comment by lavalamp** [comment]
The top-level readme lists two examples:

https://github.com/kubernetes/client-go/blob/master/examples/in-cluster/main.go

https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster/main.go

Do those help?

**Comment by strugglingyouth** [comment]
others?example,create pods,create namespace,delete pods...@lavalamp

**Comment by lavalamp** [comment]
I don't think we have a great source. You can look at godoc, which isn't terrible, here:

https://godoc.org/k8s.io/client-go/kubernetes

Drill in for specific objects like Pods: https://godoc.org/k8s.io/client-go/kubernetes/typed/core/v1#PodInterface

**Comment by samuell** [comment]
Agreed that a few more examples would be extremely helpful. 

E.g, I'm looking for how to create new jobs. I found the [JobInterface docs](https://godoc.org/k8s.io/client-go/kubernetes/typed/batch/v1#JobInterface), with a `Create` method, but have no clue how to even get started using that, as it in itself takes Job interface, etc.

Everything is so dispersed, without no seemingly clear starting point. Thus, would really much hope to see a bunch of more examples.

**Comment by WilliamDenniss** [comment]
Thanks for the feedback! #128 is tracking this now.
