### ISSUE TITLE
Any plan for supporting transaction operation against k8s objects?

### ISSUE THREAD

**Issue by kidlj** [kubernetes/client-go#630]
I'm developing on a customized [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) project, which is designed to support per-path level configurations like proxy timeouts, client-max-size etc. and better canary deployment features. The official Nginx ingress controller only supports per-ingress level configurations, which means all paths configured under an ingress get the same configurations. 

So I breaking a standard Ingress into three kinds of ingresses logically, which are serverIngress, pathIngress and canaryIngress.

A serverIngress holds configurations like hostname, TLS and annotations representing Nginx server scope settings.

A pathIngress holds a single path and annotations representing Nginx location scope settings.

A canaryIngress holds a path and a k8s service, with annotations representing Nginx upstream scope settings.

A set of pathIngress-es and canaryIngress-es are related with a single serverIngress via labels,    they are treated as a whole like a standard atomic ingress, to support all the features as put above.

Here's the question:

When performing creating of a set of ingresses, I create the canaryIngress and pathIngress one by one in a loop, then is the serverIngress, all via client-go functions.

I am worried  about a rare scenario where part of canaryIngress-es or pathIngress-es were created successfully but the serverIngress failed due to some reason, for example the API Server was down or other internal errors. Then the ingress data is in an inconsistent state.

So I'm wondering if there's any plan for supporting transaction operations against k8s objects via client-go. 

Or am I doing in the wrong way since I'm breaking down an atomic ingress object(logically)?

Thanks.

**Comment by liggitt** [comment]
There are no plans for multi resource transactions
