### ISSUE TITLE
rest.InClusterConfig Error when apiserver use http

### ISSUE THREAD

**Issue by snxq** [kubernetes/client-go#634]
Error log:
`
Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
`

`/var/run/secrets/kubernetes.io/serviceaccount` The dir only have `namespace` and `token` two files. And apiServer use http not https. So Cant I use rest.InClusterConfig?

**Comment by liggitt** [comment]
Correct. InClusterConfig only works for https (as does sending authentication credentials). What version of kubernetes are you using?

**Comment by snxq** [comment]
@liggitt Thanks for your reply.

The version of kubernetes: 

`
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`
