### ISSUE TITLE
Can't pass CreateOptions / UpdateOptions

### ISSUE THREAD

**Issue by teamon** [kubernetes/client-go#635]
I can't find a way to pass options to many API functions.

For example, in [API Reference for "create Service"](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#create-service-v1-core) includes `pretty`, `dryRun` and `fieldManager` options. They are  available as structs like [`k8s.io/apimachinery/pkg/apis/meta/v1#CreateOptions](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#CreateOptions).

client-go however does not allow passing `metav1.CreateOptions` to `Create(...)` in [`ServiceInterface`](https://godoc.org/k8s.io/client-go/kubernetes/typed/core/v1#ServiceInterface)

```go
type ServiceInterface interface {
  Create(*v1.Service) (*v1.Service, error)
  // while it could be
  Create(*v1.Service, *metav1.CreateOptions) (*v1.Service, error)
  // ...
}
```

Java's counterpart does allow passing flags:

```java
public V1Service createNamespacedService(String namespace, V1Service body, String pretty, String dryRun, String fieldManager) throws ApiException
```

This applies to many (all?) API interfaces. Am I missing something obvious here or the go client generator needs to be improved?

**Comment by liggitt** [comment]
the generator needs updating. we should batch this change with the proposed context-threading change (https://github.com/kubernetes/kubernetes/pull/78108)

**Comment by teamon** [comment]
@liggitt Given the mentioned PR is now closed, what is the status of this issue?

**Comment by liggitt** [comment]
this would make sense to fold into https://github.com/kubernetes/community/pull/1166 as part of a coordinated generated client signature change (to add context.Context and option structs to write methods)

**Comment by liggitt** [comment]
https://github.com/kubernetes/community/pull/1166 moved to https://github.com/kubernetes/enhancements/pull/1503, I mentioned this request there at https://github.com/kubernetes/enhancements/pull/1503/#pullrequestreview-347577720
