### ISSUE TITLE
Get the cluster name for the Kubernetes cluster.

### ISSUE THREAD

**Issue by sunnyanand17** [kubernetes/client-go#638]
Hi, is it possible to get the cluster name as we get from the below Kubectl commands:
 kubectl config current-context --> output :: cluster-name-context

or the command  kubectl cluster-info 
Kubernetes master is running at https://cluster-name:8001
catalog-ui is running at https://cluster-name:8001/api/v1/namespaces/kube-system/services/catalog-ui:catalog-ui/proxy
Heapster is running at https://cluster-name:8001/api/v1/namespaces/kube-system/services/heapster/proxy
image-manager is running at https://cluster-name:8001/api/v1/namespaces/kube-system/services/image-manager:image-manager/proxy
CoreDNS is running at https://cluster-name:8001/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
metrics-server is running at https://cluster-name:8001/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
platform-ui is running at https://cluster-name:8001/api/v1/namespaces/kube-system/services/platform-ui:platform-ui/proxy

I need this info as our docker repository shares the same cluster name.

**Comment by liggitt** [comment]
No, the cluster name output by the kubectl commands is only stored in the local kubeconfig file, it is not part of an API

**Comment by omeid** [comment]
How does the Dashboard know the cluster name?

**Comment by mkjmkumar** [comment]
It seems that suggestion to use the HOST(master name) as cluster name. How are we going to handle this when we have multiple master nodes serving to cluster?
