### ISSUE TITLE
why  http code 409 do not wait and sleep retry-after time for concurrency conflict?

### ISSUE THREAD

**Issue by kitianFresh** [kubernetes/client-go#639]
https://github.com/kubernetes/client-go/blob/0c47f9da00011ea9a8717671127ac21625c7a6c0/rest/request.go#L1049

When i update node, k8s return 409 and a error message `Operation cannot be fulfilled on nodes "xxx": the object has been modified; please apply your changes to the latest version and try again`; this means i should retry requests, but i found that client-go do not support 409 retry!
I checked the checkWait, when k8s return 409,  client-go do not wait and sleep and do not retry, why?

**Comment by sttts** [comment]
It's not enough to just retry. Instead get the latest object, update it and then try again with the result. 

Just retrying an update without getting the latest resource version will lead to another 409.

**Comment by kitianFresh** [comment]
@sttts  I use PUT http request to do update， i mean i first get a Node object from Get api，then i update some fields such as labels and Annotations and so on， then i put the object back to update api，i wonder if i remove the resourceversion from the object i got，and then update，can it work？

    func (c *Cluster) UpdateNode(nodename string, body *types.NodeUpdateBody) (*apiv1.Node, error) {
	    origin, err := c.ShowNode(nodename, metav1.GetOptions{})
	    if err != nil {
		    glog.Errorf("Node %s not found from cluster %s, caused by %s\n", nodename, c.Name, err.Error())
		    return nil, httperrors.NewMk8sHttpErr(http.StatusNotFound, err.Error())
	    }
	    node := ConstructNodeToUpdate(body, origin)
	    if body.Unschedulable != nil && node.Spec.Unschedulable != *body.Unschedulable {
		    node.Spec.Unschedulable = *body.Unschedulable
	    }
	    return c.Client.UpdateNode(node)
    }

Another method i found in community is PATCH method，it sames that api server will retry 5 times 
 automatically if updating resource by PATCH method, so the client-sides do not need retry.

**Comment by kitianFresh** [comment]
@sttts what do you mean use patch in the first place，you mean get -> change-> update loop retry is for PUT method，and patch just use patch once?
