### ISSUE TITLE
can the default conf.APIPath in k8s.io/client-go/1.5/dynamic/client.go change to  /apis?

### ISSUE THREAD

**Issue by du2016** [kubernetes/client-go#64]
can the default conf.APIPath in k8s.io/client-go/1.5/dynamic/client.go change to  /apis,
i think the default APIPath is /apis and the default APIVersion path is /api.

**Comment by lavalamp** [comment]
This should already be set up correctly by default. Hopefully you got
whatever you were doing working :)

**Comment by du2016** [comment]
I have a wrong understanding of this,i hava got it,thank you very much.
