### ISSUE TITLE
Build failure using client-go version v12.0.0

### ISSUE THREAD

**Issue by chandankumar4** [kubernetes/client-go#640]
Build errors:
```
# github.com/mayadata-io/litmus-manager/vendor/k8s.io/client-go/rest/watch
vendor/k8s.io/client-go/rest/watch/decoder.go:57:103: undefined: watch.Bookmark
make: *** [Makefile:7: build] Error 2
```
Client-go version: "v12.0.0"
Go version: go1.12.6 linux/amd64

**Comment by nikhita** [comment]
> vendor/k8s.io/client-go/rest/watch/decoder.go:57:103: undefined: watch.Bookmark

It exists here https://github.com/kubernetes/apimachinery/blob/kubernetes-1.15.0/pkg/watch/watch.go#L47.

Are you using the corresponding version of apimachinery? https://github.com/kubernetes/client-go/blob/v12.0.0/go.mod#L30

You can also get this version by adding  `require k8s.io/apimachinery kubernetes-1.15.0` to your go.mod file.
