### ISSUE TITLE
Make ClientSet to rotate Bearer Token 

### ISSUE THREAD

**Issue by ganeshbms** [kubernetes/client-go#647]
Hi,

I'm using client-go's informer framework to watch some set of Pods in GKE. I have got a Google Service Account to authenticate my client with GKE master. I'm creating clientset by setting bearer token (which after after an hour) obtained from GCP and starting an informer.
This informer works fine as long as bearer token is valid and I don't see any way in clientset to pass the refreshed bearer token. I see re-creating entire informer is the only way and this seems too expensive.

Is there any plan to make informer framework / clientset to get refreshed tokens and re-create listwatcher transparently to application. 

I found many issues related to this and most of them got closed as staled issues. 

Thanks,
Ganesh

**Comment by liggitt** [comment]
If you point the client config at a bearer token file (rather than an inlined bearer token), it will construct a client that fill reload that token file

**Comment by ganeshbms** [comment]
Ok .. I will try that .. Thank you.

**Comment by taitelman** [comment]
k. trying too:
```
func try...

config, err := kubeclient.NewConfig(
		kubeclient.Instrument(lbl),
		tlsClientConfig(caData),
		host(containerHost),
		bearerToken(string(token)),
		kubeclient.QPS(100.0),
		kubeclient.Burst(100),
	)
	if err != nil {
		logger2.Error("failed to create Kube client , logger2.Err(err))
		return nil, err
	}

	err = os.WriteFile(idTokenFileName, token, idTokenFileUnixPerm)
	if err != nil {
		logger2.Error("failed to write token to file:"+idTokenFileName, logger2.Err(err))
		return nil, err
	}
	config.BearerTokenFile = idTokenFileName
	config.BearerToken = "" // empty bearer token . force clientset to use the bearerToken file.

```
