### ISSUE TITLE
Create secret issue

### ISSUE THREAD

**Issue by sunnyanand17** [kubernetes/client-go#651]
Hi, I am trying to create a secret as below:
newSecret := &v1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: namespace,
		},
		Data: map[string][]byte{
			"sslTruststoreLocationMountFolder": []byte(jks.sslTruststoreLocationMountFolder),
			"sslTruststoreLocation":            []byte(jks.sslTruststoreLocation),
			"sslTruststorePassword":            []byte(jks.sslTruststorePassword),
                         "truststore.jks":                    []byte(jks.truststore),
		},

The issue is I do not want the go client to base64 encode the value in the field truststore.jks. How can I achieve this. I want the value in the field to remain as string. Pls help

**Comment by liggitt** [comment]
json-encoding of []byte is base64-encoded, and there is no way to avoid that. When mounted into a pod, the content is base64-decoded so that the original byte content is placed in a file inside the pod

/close
