### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by sunnyanand17** [kubernetes/client-go#652]
Hi, I am using the K8 client to build a tool for automation. Until yesterday the docker build was working fine but today the docker fails while trying to get the k8s.io/client-go/kubernetes. Here is my dockerfile. 
FROM golang

ADD /microservices/ConfigurationService/server/ /go/src/com/ibm/cedp/datahub/microservices/ConfigurationService/server/
COPY /microservices/ConfigurationService/configurationservicepb/ /go/src/com/ibm/cedp/datahub/microservices/ConfigurationService/configurationservicepb/
COPY /utils/dhubformatter/ /go/src/com/ibm/cedp/datahub/utils/dhubformatter/
COPY /utils/extractssl/ /go/src/com/ibm/cedp/datahub/utils/extractssl/

WORKDIR /go/src/com/ibm/cedp/datahub/microservices/ConfigurationService/server/

RUN go get -v ./...
RUN go install -v ./...
ENTRYPOINT /go/bin/server
EXPOSE 50051

I get the below error code The command '/bin/sh -c go get -v ./...' returned a non-zero code: 2

**Comment by liggitt** [comment]
Builds against existing branches of client-go should use the version of klog that corresponds to that version of client-go.

For example, for the latest release branch:
https://github.com/kubernetes/client-go/blob/release-13.0/go.mod#L31
