### ISSUE TITLE
cannot convert klog.V(9) (type klog.Verbose) to type bool

### ISSUE THREAD

**Issue by BambooAce** [kubernetes/client-go#654]
# k8s.io/client-go/transport
../client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
../client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
../client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
../client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool

**Comment by Itfly** [comment]
I guess your klog package version is not match with client-go, and i think you should use an old version (v0.2.0)

**Comment by liggitt** [comment]
Builds against existing branches of client-go should use the version of klog that corresponds to that version of client-go.

For example, for the latest release branch:
https://github.com/kubernetes/client-go/blob/release-13.0/go.mod#L31
