### ISSUE TITLE
concurrent map writes on plugin/pkg/client/auth/gcp/gcp.go:115 

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/client-go#66]
client-go version: v2.0.0.alpha.1

We are encountering panics like:
```
fatal error: concurrent map writes
...
vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp.go:115 +0x191 fp=0xc4206e5510 sp=0xc4206e5468
```

Seems to be fixed in https://github.com/kubernetes/kubernetes/pull/36680/

But the change isn't available in any client-go release, or release-2.0 branch which should track k8s 1.5 changes.

**Comment by lavalamp** [comment]
This should be fixed in v2.0.0.
