### ISSUE TITLE
How to go get k8s.io/api@kubernetes-1.14.0?

### ISSUE THREAD

**Issue by wolking** [kubernetes/client-go#663]
go version 1.12.5
```
> $env:GO111MODULE="on"
> $env:GOPROXY="https://goproxy.io/"
> go get -v k8s.io/api@kubernetes-1.14.0
go: finding k8s.io/api kubernetes-1.14.0
Fetching https://goproxy.io/k8s.io/api/@v/kubernetes-1.14.0.info
k8s.io/api
go build k8s.io/api: no non-test Go files in D:\gopath\pkg\mod\k8s.io\api@v0.0.0-20190313235455-40a48860b5ab
```
![image](https://user-images.githubusercontent.com/12195297/63417631-38b15500-c434-11e9-8c86-eedd9370b888.png)

**Comment by liggitt** [comment]
https://github.com/kubernetes/api/releases/tag/kubernetes-1.14.0 is the 40a48860b5ab SHA. The v0.0.0... format is what [go normalizes non-semver tags to](https://github.com/golang/go/wiki/Modules#can-a-module-consume-a-package-that-has-not-opted-in-to-modules).

/close

**Comment by wolking** [comment]
@liggitt I see. Thanks for your reply.
