### ISSUE TITLE
How can  I get  node  allocated（not Allocatable）resource information through client-go？

### ISSUE THREAD

**Issue by toyow** [kubernetes/client-go#667]
I can  get  such  information  through kubectl describe，but how does it work in client-go？
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource        Requests     Limits
  --------        --------     ------
  cpu             3462m (10%)  3322m (10%)
  memory          8422Mi (3%)  8462Mi (3%)
  nvidia.com/gpu  1            1

**Comment by xuesea** [comment]
same question?

**Comment by 7imo** [comment]
+1 - Can anyone provide an answer?

**Comment by xuesea** [comment]
After searching, i found there is no api gives allocated resources information directly, only calcul it by Allocatable = (All resources) - (All Pods already requested), and the result is only a  approximate value because scheduler is doing the resource allocate in the same time.

**Comment by liukelin** [comment]
kubectl discribe node 

Non-terminated Pods and Allocated resources
