### ISSUE TITLE
k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible

### ISSUE THREAD

**Issue by veda-circle** [kubernetes/client-go#673]
na1/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)

require {
k8s.io/api v0.0.0-20190813180838-e711354a0280
        k8s.io/apimachinery v0.0.0-20190813060636-0c17871ad6fd
k8s.io/client-go v11.0.0+incompatible
)
any idea on this issue, started happening from today

**Comment by Jpatel86** [comment]
I followed this - https://github.com/kubernetes/client-go/blob/master/INSTALL.md but I still see this issue. This was working earlier.

**Comment by liggitt** [comment]
That likely means you have other dependencies that are pulling in newer versions of some libraries causing a mismatch

I'd suggest updating your requires statements to matching levels, like the following:

``` 
require (
k8s.io/api kubernetes-1.15.3
k8s.io/apimachinery kubernetes-1.15.3
k8s.io/client-go kubernetes-1.15.3
)
```
