### ISSUE TITLE
client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/rest/request.go:598:31

### ISSUE THREAD

**Issue by lakstap** [kubernetes/client-go#674]
k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)

require (
        k8s.io/api v0.0.0-20190813180838-e711354a0280
        k8s.io/apimachinery v0.0.0-20190813060636-0c17871ad6fd
        k8s.io/client-go v10.0.0+incompatible
)

Any thoughts on this, start happening from today

**Comment by lakstap** [comment]
k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher

Please let me know how to fix this

**Comment by liggitt** [comment]
Make sure you are using kubernetes-1.14 levels of k8s.io/apimachinery and k8s.io/api

**Comment by liggitt** [comment]
See https://github.com/kubernetes/client-go#compatibility-matrix for the matching api and apimachinery library levels
