### ISSUE TITLE
How to use raw ServiceAccount bearer token to authenticate out-of-cluster ? 

### ISSUE THREAD

**Issue by mydockergit** [kubernetes/client-go#679]
There are two ways to authenticate:
1. [In-cluster](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration)
2. [out-of-cluster](https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration)  

But I want to be able to use a raw ServiceAccount token I have without using the "in-cluster" method to create a container.  
The out-of-cluster method require me to specify a kubeconfig file.

Like `kubectl` have the option of `--token` to specify a raw token.
Is it possible ?

**Comment by liggitt** [comment]
when constructing a client, you can build a rest.Config struct manually, specifying the bearer token there: https://github.com/kubernetes/client-go/blob/master/rest/config.go#L72

/close
