### ISSUE TITLE
Compatibility matrix documentation

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/client-go#68]
The documentation on the compatibility is rather puzzling ;-)

> Compatibility matrix
> 
> client-go/1.4 is compatible with Kubernetes 1.3 through 1.5; it includes all features provided by Kubernetes 1.4.
> client-go/1.5 is compatible with Kubernetes 1.3 through 1.5; it includes all features provided by Kubernetes 1.4.

So when should one use 1.4 and when 1.5?

**Comment by WilliamDenniss** [comment]
The README has been updated, it the compatibility more clear now?
