### ISSUE TITLE
Can't install client-go: "go: cannot use path@version syntax in GOPATH mode"

### ISSUE THREAD

**Issue by mydockergit** [kubernetes/client-go#681]
I used the installation instructions here:
https://github.com/kubernetes/client-go/blob/master/INSTALL.md#for-the-casual-user

I ran the command:
`go get k8s.io/client-go@master`  

I received an error:  

> go: cannot use path@version syntax in GOPATH mode

I read [here](https://stackoverflow.com/a/54416455) what can it be and it was written that I need to use this syntax: `github.com/<user>/<repo>@<version>`

This is what I tried:
```
go get github.com/kubernetes/client-go@master
go get github.com/k8s.io/client-go@master
```  

None of them help. 
I am still getting the errors.

What can it be ?

**Comment by mydockergit** [comment]
The solution is here:
https://github.com/kubernetes/client-go/blob/master/INSTALL.md#enabling-go-modules

**Comment by anuradhai4i** [comment]
I too was having the same problem and then tried as @mydockergit suggested and issue sorted.

**Comment by saurabmish** [comment]
I did the following and was able to resolve the issue:

- added `export GO111MODULE=on` in `.zshrc`

- refreshed environment variables with `source .zshrc`

- installed Gopls package with `go get golang.org/x/tools/gopls@latest`

More info can be found at:
[Golang GitHub](https://github.com/golang/go/wiki/SettingGOPATH)
