### ISSUE TITLE
question: major version bump

### ISSUE THREAD

**Issue by xiang90** [kubernetes/client-go#69]
I noticed that there is a client 2.0 release branch, which bumps the major version from 1 to 2.

I assume that it introduces some breaking changes. But I could not find a doc that explains what has been changed and why it is changed. Will the release 1 branch continue to be maintained and supported? Or everyone should migrate to 2.0 as soon as possible?

I am asking since we just tried to migrate our client from k8s internal client to client-go/1.5. I am wondering if we should migrate from 1.5 to 2.0.

/cc @hongchaodeng @caesarxuchao @lavalamp @philips

**Comment by lavalamp** [comment]
Seems like there should be an entry in https://github.com/kubernetes/client-go/blob/master/CHANGELOG.md--maybe Chao can fill that in when he is back.

**Comment by lavalamp** [comment]
Actually, we've only tagged alphas out of the 2.0 branch. So I think it's not an emergency that we haven't published this yet. We probably aren't finished breaking things yet. :)

**Comment by xiang90** [comment]
> We probably aren't finished breaking things yet. :)

We'd better to finish all planned breaking issues before creating a release. We should not dis-encourage people to try out alpha release. Or there is no point to do alpha release I guess.

**Comment by lavalamp** [comment]
Hopefully the documentation is clear enough now. When k8s 1.6 is cut, we most likely will cut 3.0.0, unless there are no interface changes (in that unlikely case, we'd probably cut a 2.1.0 instead).

**Comment by xiang90** [comment]
@lavalamp 

Can you point me to the doc that describes the breaking changes between 1.5 and 2.0? Also I would expect a doc talking about how users should migrate from 1.5 to 2.0

**Comment by lavalamp** [comment]
CHANGELOG.md is partially completed.
https://github.com/kubernetes/client-go/issues/111 is open so we will
finish this.

**Comment by xiang90** [comment]
@lavalamp Thanks!
