### ISSUE TITLE
Dynamic client swallow the error

### ISSUE THREAD

**Issue by mrshengzyzy** [kubernetes/client-go#690]
Sometimes we need to know the detail error information from *API Server*,
but dynamic-client swallow it and only the error message was back.

e.g. `dynamic.Get`
```
result := c.client.client.Get().AbsPath(append(c.makeURLSegments(name), subresources...)...).SpecificallyVersionedParams(&opts, dynamicParameterCodec, versionV1).Do()
	if err := result.Error(); err != nil {
                // Only error message was back
		return nil, err
	}
```
If the resource we `GET` not found, we only get the error message like `The resource not found`, but the error code *404* was lost although the *API Server* return it.

Suppose we want to proxy *API Server* for `kubectl`,  what we do if error occured?
First, we have to compare the error message rather than error code so that we can classify error.
Second, rebuild the result, which is the same as *API Server* returns so that `kubectl` can accept.
At last, return the result to `kubectl` 

`dynamic-client` get the error but not return completely, that's a little unreasonable.

**Comment by liggitt** [comment]
`result.Error()` [returns an error, not a string](https://github.com/kubernetes/kubernetes/blob/948870b5840add1ba4068e3d27d54ea353839992/staging/src/k8s.io/client-go/rest/request.go#L1156-L1160). That error can be checked using methods like [IsNotFound()](https://github.com/kubernetes/kubernetes/blob/948870b5840add1ba4068e3d27d54ea353839992/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L463-L465)

**Comment by mrshengzyzy** [comment]
@liggitt  
Thx, you are right.
But I still not found how to the get raw response from *Api Server*.
Does this mean I have to rebuild the result?

**Comment by mrshengzyzy** [comment]
I use `Rest Client` instead of `Dynamic Client`  and zchieve  goal by modifying the source code.
