### ISSUE TITLE
incompatible: not enough arguments in call to watch.NewStreamWatcher

### ISSUE THREAD

**Issue by Lhmily** [kubernetes/client-go#691]
../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)

**Comment by nikhita** [comment]
If you are using client-go v11.x, make sure you are using kubernetes-1.14 levels of k8s.io/apimachinery and k8s.io/api.

Something like:

```
require (
k8s.io/api kubernetes-1.14.7
k8s.io/apimachinery kubernetes-1.14.7
k8s.io/client-go kubernetes-1.14.7
)
```

More details here: https://github.com/kubernetes/client-go/blob/master/INSTALL.md

/close
