### ISSUE TITLE
fake clientset: most "delete" endpoints ignore DeleteOptions so cascading deletes not possible

### ISSUE THREAD

**Issue by cxuu** [kubernetes/client-go#693]
From the following link, you can see the function body complete ignores `options *v1.DeleteOptions`. 

https://github.com/kubernetes/client-go/blob/41406bf985e3fa3c5eccd0a7c1fb39e9212340e8/kubernetes/typed/core/v1/fake/fake_configmap.go#L104-L109

This DeleteOptions allows us to specify `PropagationPolicy` so dependent objects (whose `ownerReference` points to the configmap we just deleted) will also be deleted.

https://github.com/kubernetes/apimachinery/blob/668e03ad66eef58ebce2c8203be90a1dc6db07c8/pkg/apis/meta/v1/types.go#L474-L483
```go
type DeleteOptions struct {
...
	// Whether and how garbage collection will be performed.
	// Either this field or OrphanDependents may be set, but not both.
	// The default policy is decided by the existing finalizer set in the
	// metadata.finalizers and the resource-specific default policy.
	// Acceptable values are: 'Orphan' - orphan the dependents; 'Background' -
	// allow the garbage collector to delete the dependents in the background;
	// 'Foreground' - a cascading policy that deletes all dependents in the
	// foreground.
	// +optional
	PropagationPolicy *DeletionPropagation `json:"propagationPolicy,omitempty" protobuf:"varint,4,opt,name=propagationPolicy"`
...
}
```

Such ignorance, in this case, has made writing unit test for controllers difficult and quite common in the fake package for other objects besides the configmap.

**Comment by liggitt** [comment]
note that cross object serverside behavior like GC is not supported by the fake client

Do you have a controller that sometimes deletes with different propagation policies you are trying to unit test?

**Comment by cxuu** [comment]
Is there a plan to support cross object serverside behavior in the future?

I have a controller that does something similar to the Job controller, where for each Job a pod is launched to do work. I want to reclaim all jobs and pods older than a certain retention period (GC). The controller always deletes with the same propagation policies (foreground). Do you think the fake client is the right tool for unit testing? If not, do you have any recommendation for replacement?

**Comment by liggitt** [comment]
If you want to use unit testing to test end-to-end scenarios, and rely on behavior that is normally accomplished by other controllers (like the garbage collection controller), you will have to add increasing amounts of fake behavior into your unit tests (which you can sort of do by adding reactors to your fake client and taking other actions in response to requests).

What I would recommend, though, is using unit tests to test a single scenario/response ("when these conditions exist, the controller makes this API call (e.g. a particular update, or a particular delete, etc)", and use end-to-end tests against a real server for testing flows that rely on other controllers

/close
