### ISSUE TITLE
Add support for release 1.16

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/client-go#695]
Hi
May I ask, when will the support for release 1.16 be added?

The "Dashboard"-team is waiting for client-go in order to extend support for release 1.16.
https://github.com/kubernetes/dashboard/issues/4327

Thank you

**Comment by liggitt** [comment]
the `kubernetes-1.16.0` tag is already available

see https://github.com/kubernetes/client-go/tree/kubernetes-1.16.0
