### ISSUE TITLE
Error Message for NamespaceInterface Get Should Use Namespace Not Namespaces

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/client-go#696]
The error message from [Get](https://github.com/kubernetes/client-go/blob/acc621f88da0907c3eee966001ea99bd59b0f92c/kubernetes/typed/core/v1/namespace.go#L64) in `namespace.go` uses the plural `namespaces` even though the function only can return one namespace object.

When a namespace does not exist using `Get()`, the error message returned is what is shown below:

`Error: namespaces "doesnotexist" not found`

The error message should return `Error: namespace "n2" not found`.

**Comment by liggitt** [comment]
Thanks for the report, but the plural resource name is how the api server refers to resources internally, so that is the error message it includes in notfound error messages. This maps to the url path segment for the resource request as well. 

/close
