### ISSUE TITLE
Go get package install fails

### ISSUE THREAD

**Issue by Smokrow** [kubernetes/client-go#699]
Hey there,

when I follow the tutorial to install the library I am getting the following.
```
go get k8s.io/client-go@master     
# cd .; git clone https://github.com/kubernetes/client-go@master /home/momo/go/src/k8s.io/client-go@master
Cloning into '/home/momo/go/src/k8s.io/client-go@master'...
fatal: unable to access 'https://github.com/kubernetes/client-go@master/': The requested URL returned error: 400
```
Not sure what is happening there, but the URL: https://github.com/kubernetes/client-go@master/' cannot be accessed via browser.

Greets

**Comment by liggitt** [comment]
what version of go are you using?

**Comment by Smokrow** [comment]
Ah. I just found out that the apt-get version is terribly outdated. Sorry for the inconvenience. Everything runs fine with an up to date version. I am gonne close this

**Comment by luizcarlospedrosogomes** [comment]
![image](https://user-images.githubusercontent.com/9791364/208982515-752e556c-06a5-4136-91d5-ae04aa19e933.png)
