### ISSUE TITLE
incompatibility between branches of release-2.0 and master

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/client-go#70]
I was having some incompatibility issues between release-2.0 branch and master branch in client-go. Just submitting issues here and inquiring more info on releases. Here are some example issues:

- "k8s.io/client-go/pkg/labels" doesn't exist anymore. We use some methods like labels.Everything(), labels.SelectorFromSet().

- "k8s.io/client-go/pkg/api/unversioned" doesn't exist anymore. We decode unversioned.Status{} from watch stream, use unversioned.TypeMeta/ListMeta for object/listObject, use unversioned.LabelSelector for "extensions/v1beta1".ReplicaSet, etc.

- "k8s.io/client-go/pkg/types" and "k8s.io/client-go/pkg/api/meta/metatypes" doesn't exist anymore. Use types.UID and meattypes.OwnerReference .

- Importing unfound packages: "k8s.io/client-go/pkg/api/meta", "k8s.io/apimachinery/pkg/openapi" .

What's the plan for client-go on this? Is client-go gonna release 3.0 for k8s 1.6? 

And what's the plan for maintaining each releases? It seems like release-2.0 has issues as mentioned in https://github.com/kubernetes/client-go/issues/66 but there wasn't any answer or releases to import fixes from upstream for it.

**Comment by lavalamp** [comment]
Go back to the alpha tag: https://github.com/kubernetes/client-go/tree/v2.0.0-alpha.1/pkg/labels

I think client-go head is broken right now because we moved these packages into the apimachinery repo.

**Comment by lavalamp** [comment]
@deads2k

**Comment by xiang90** [comment]
> Go back to the alpha tag: https://github.com/kubernetes/client-go/tree/v2.0.0-alpha.1/pkg/labels

alpha is broken due to https://github.com/kubernetes/client-go/issues/66

> I think client-go head is broken right now because we moved these packages into the apimachinery repo.

What is the future plan?

**Comment by lavalamp** [comment]
Labels is moving into the apimachinery repo, unversioned is becoming meta (I think). These things do actually exist in client-go, under the vendor/ directory. I guess you can get them from there for the moment. I don't have a plan yet because these client-go problems caught me by surprise earlier today. I don't know yet if we will fix this in a 2.x.x branch or if we'll have to cut a 3.x.x to solve this.

**Comment by smarterclayton** [comment]
Were these not being pulled from the client-go vendor dir?

**Comment by xiang90** [comment]
@lavalamp 

> under the vendor/ directory.

Hrm... I think the convention is that library does not vendor its dependencies in go.

**Comment by lavalamp** [comment]
Yes, that is the convention. But if we remove it, you'll have no way of getting the revision of k8s.io/apimachinery that the client depends on--and we expect to change this relatively often initially.

**Comment by smarterclayton** [comment]
We could fake deresolve them into client-go, but I'm pretty sure david hit a case where we either have common apimachinery in kube between client-go and master, or we can't use client-go in kubernetes.

**Comment by xiang90** [comment]
@lavalamp 

>  you'll have no way of getting the revision of k8s.io/apimachinery 

If client go has any hard dependency versioning requirement, can we simply document them?

I am actually fine with copying that hash or versioning string into the version system my project uses. I think it would be OK for most others since it is pretty much a go convention.

**Comment by deads2k** [comment]
> We could fake deresolve them into client-go, but I'm pretty sure david hit a case where we either have common apimachinery in kube between client-go and master, or we can't use client-go in kubernetes.

If we make copies, then the code becomes incompatible again and it's impossible untangle dependencies.  `client-go` has a logical dependency upon the API machinery which makes it work and expressing that dependency makes sense.  The level of API machinery vendored into the `client-go` will always work with client-go and will be listed in the godeps.json file.

**Comment by xiang90** [comment]
@deads2k 

> then the code becomes incompatible again and it's impossible untangle dependencies. 

Can you explain more? I do not understand this.

> The level of API machinery vendored into the client-go will always work with client-go and will be listed in the godeps.json file.

How do you expect this to work for projects that depend on client-go? What is the vendoring process do you suggest?

**Comment by lavalamp** [comment]
I think it's not clear so let me just add that release-2.0 branch hasn't had a 2.0.0 tagged yet. We've only released alphas of 2.0. So you will probably have a better time if you stay on the 1.5.0 tag.

**Comment by xiang90** [comment]
@lavalamp 

> But if we remove it, you'll have no way of getting the revision of k8s.io/apimachinery that the client depends

OK... I looked at the k8s.io/apimachinery repo. It seems that apimachinery itself is not even versioned, is unstable. If we want the client go to be stable, we need its dependencies to be stable first. Releasing a stable release that depends on a very unstable but critical component seems risky to me.

**Comment by deads2k** [comment]
> OK... I looked at the k8s.io/apimachinery repo. It seems that apimachinery itself is not even versioned, is unstable. If we want the client go to be stable, we need its dependencies to be stable first. Releasing a stable release that depends on a very unstable but critical component seems risky to me.

Not entirely true.  In order for client-go to be stable it must vendor a guaranteed level of apimachinery and there have to be bug fixes in whatever branch/tag is used.  As long as the actual commit is retrievable by a vendoring tool and we continue to provide fixes, we only need to be compatible for the interface types here.  If there's a contract break, we could simply ripple down here to another version.

**Comment by deads2k** [comment]
To put this in perspective, when client-go straight up copied things like `k8s.io/kubernetes/pkg/runtime`, you were already vulnerable to any change to what was considered to be an internal library and if we had to make a significant change, it would simply ripple out here.  Exactly as this recent vendoring made more obvious.

**Comment by lavalamp** [comment]
When we were copying those things, they didn't escape the package boundaries and changes were completely invisible to users of client-go. Now that we're moving to multiple repos, those dependencies DO escape the client-go repo and users are impacted.

**Comment by xiang90** [comment]
>  As long as the actual commit is retrievable by a vendoring tool and we continue to provide fixes

From vendoring perspective is OK. But from the stability perspective, it is not. If apimachinery fixes a bug, then client-go that vendors the old commit hash is "unstable".

**Comment by deads2k** [comment]
> From vendoring perspective is OK. But from the stability perspective, it is not. If apimachinery fixes a bug, then client-go that vendors the old commit hash is "unstable".

That was already happening, you just didn't know it.  The copy and mutate mechanism for building this repo did exactly the same thing, it was just more silent.

**Comment by hongchaodeng** [comment]
@deads2k 
Just because it's been wrong all the time doesn't mean keep doing it is right.
For client-go user, he wouldn't expect vendoring unstable, non-guaranteed repo into production.

**Comment by deads2k** [comment]
> @deads2k
> Just because it's been wrong all the time doesn't mean keep doing it is right.
> For client-go user, he wouldn't expect vendoring unstable, non-guaranteed repo into production.

Well, I think there's confusion about the state we're starting from.  This hasn't introduced new entropy.  It *has* made it possible to see that the entropy that already existed is there.  If we all understand the starting state (regardless of what previous claims were), we can talk about what needs to happen to get to the desired state without thinking we can simply "go back" and everything will work.

**Comment by xiang90** [comment]
@deads2k 

> That was already happening, you just didn't know it. 

Now I know that. And I begins to feel the instability. If we agree it is unstable, we can start to find a way to stabilize it. If you feel it is stable, then I disagree, and I have to sort it out with you on it since you are working on apimachinery. I think it is VERY important to make apimachinery stable at the first place.

**Comment by deads2k** [comment]
> I think it is VERY important to make apimachinery stable at the first place.

This statement I agree with and I think that recognition of our problems is the first step.  I want API machinery stable and we are actively working it.  However, I'm not sure its a one release kind of problem.

Pinning a particular interface level towards the end of 1.6 would at least make it possible to track changes in a way that wasn't possible before.  It may also mean that these versions change more than we'd like for the short term.

**Comment by xiang90** [comment]
> Pinning a particular interface level towards the end of 1.6 would at least make it possible to track changes in a way that wasn't possible before. It may also mean that these versions change more than we'd like for the short term.

OK. Good to know. Basically this means the client-go should not release 2.0 until the end of 1.6 when apimachinery is somewhat stable. Or we will probably face api break, and need to bump major version.

**Comment by caesarxuchao** [comment]
client-go release-2.0 is tracking **k8s release-1.5** branch, where the apimachinery moves hadn't occurred yet, so its API is stable.

client-go master branch is tracking k8s master, we'll solve the dependency issues in the master branch. Then, we'll cut a client-go 3.0 when k8s release-1.6 occurs.

**Comment by lavalamp** [comment]
Has something actually changed about a public interface? We shouldn't bump
the major version number unless it's necessary.

**Comment by lavalamp** [comment]
Also does that mean we should tag something as 2.0.0, so there's something
stable for users to grab?

**Comment by caesarxuchao** [comment]
I'm waiting for https://github.com/kubernetes/test-infra/pull/1733 to be merged. That will let the client-go/release-2.0 branch pick up the bug fixes merged to kubernetes/release-1.5, so that https://github.com/kubernetes/client-go/issues/66 will be solved. I plan to tag 2.0.0 after that.

**Comment by errordeveloper** [comment]
I am also pretty confused with `k8s.io/apimachinery/pkg/runtime` vs `k8s.io/client-go/pkg/runtime`, are these two supposed to become one eventually or nobody should be using `k8s.io/apimachinery` yet?

**Comment by errordeveloper** [comment]
Ok, looks like `k8s.io/client-go/pkg/runtime` is not part of this repo any more, I should probably stick to master.

**Comment by lavalamp** [comment]
runtime package is going to eventually live in k8s.io/apimachinery.

**Comment by sttts** [comment]
Runtime is already partly living in k8s.io/apimachinery. We are working
through the k8s.io/kubernetes code base, detangling everything. Code which
has clean dependencies is moved of to the staging repos.

The consequence of this iterative approach is that we have to live with
half-finished transitions of packages for a while (pkg/api, pkg/runtime,
pkg/api/meta, pkg/util are promiment examples).

**Rule of thumb:**

- use the code in k8s.io/apimachinery and k8s.io/apiserver
- consider the k8s.io/kubernetes counterparts of half-finished packages as
legacy in their current location
- avoid client-go/pkg/* as these are copies only.

Moreover, those packages needed by client-go are copied from
k8s.io/kubernetes into client-go (that's how client-go has been set up for
a number of months). That's why for the time being we still have a
client-go copy of this legacy generic code there. We are working towards
getting rid of this, leading to a much easier to understand packaging
structure again. This should answer your question, Ilya.

Best regards,
   Stefan

**Comment by lavalamp** [comment]
Please take a look at the current README. Hopefully this is clearly documented at this point.
