### ISSUE TITLE
discuss whether workqueue.queue.go need an isDone method

### ISSUE THREAD

**Issue by mjaow** [kubernetes/client-go#700]
if workqueue.queue.go support isDone method, user can shutdown the queue ,and make sure the queue has been cleaned before exit

```
func (q *Type) IsDone() bool {
	q.cond.L.Lock()
	defer q.cond.L.Unlock()
        return q.shuttingDown&&len(q.dirty)==0&&len(q.processing)==0
}
```

**Comment by liggitt** [comment]
a method like this that requires polling is not ideal. the `Get()` method returns a boolean that indicates if the queue is empty and shutting down. Having your processing loop handle that return value being true by shutting down is the recommended approach.

/close

**Comment by mjaow** [comment]
@liggitt 
the key of IsDone is checking all items is processed, no processing ,no dirty

i cannot known whether all of items in queue is finished by using get() or len()
maybe IsDone is a better choice to check it ?

**Comment by liggitt** [comment]
> i cannot known whether all of items in queue is finished by using get() or len()

The [workqueue example](https://github.com/kubernetes/client-go/blob/master/examples/workqueue/main.go) demonstrates how to run [worker goroutines](https://github.com/kubernetes/client-go/blob/kubernetes-1.16.0/examples/workqueue/main.go#L139-L142) that pull from the workqueue [until it is shutdown and queued items are drained](https://github.com/kubernetes/client-go/blob/kubernetes-1.16.0/examples/workqueue/main.go#L51-L56). Once all worker goroutines complete, the queue is empty and no items remain to be processed.

**Comment by mjaow** [comment]
@liggitt if only one items in the workqueue.queue,

shutdown...

get() will make queue size =0 and processing size =1 

done() will delete the processing queue ,make processing=0

next round...

get() will return 0 and true (shutdown flag) 

the processing job is forced kicking out of queue ,but job(maybe sleep, io ops) are not actually done

**Comment by liggitt** [comment]
> the processing job is forced kicking out of queue ,but job(maybe blocking in syncToStdout) are not actually done

The worker should not call Done() while it is still processing the item. See the example for deferring the call to Done() until the sync handler is complete

**Comment by mjaow** [comment]
thx , i know it now

but if i want to catch a sigterm or sigint , and  make all of my job  processed,How can i do it

**Comment by liggitt** [comment]
> but if i want to catch a sigterm or sigint , and make all of my job processed before exit ,How can i do it

in your signal handler, you can call queue.ShutDown(), then use a wait group to track the workers that are still running so that they all complete before your Run method returns:

```go
wg := &sync.WaitGroup{}
for i := 0; i < workers; i++ {
  wg.Add(1)
  go func(){
    defer wg.Done()
    for c.processNextItem() {}
  }()
}
wg.Wait()
```

**Comment by mjaow** [comment]
> > but if i want to catch a sigterm or sigint , and make all of my job processed before exit ,How can i do it
> 
> in your signal handler, you can call queue.ShutDown(), then use a wait group to track the workers that are still running so that they all complete before your Run method returns:
> 
> ```go
> wg := &sync.WaitGroup{}
> for i := 0; i < workers; i++ {
>   wg.Add(1)
>   go func(){
>     defer wg.Done()
>     for c.processNextItem() {}
>   }()
> }
> wg.Wait()
> ```

thx fo reply
