### ISSUE TITLE
How to create pull secrets?

### ISSUE THREAD

**Issue by zhangzerui20** [kubernetes/client-go#709]
Hey there,

is it possible to create k8s pull secrets using this api equivalent to this command line?

kubectl create secret docker-registry --dry-run=true test --docker-server=null --docker-username=test --docker-password=lol -o yaml > docker-secret.yaml

Thanks for each contribution!

**Comment by liggitt** [comment]
yes, the YAML file output by that command is the manifest you would need to submit to the API server

/close
