### ISSUE TITLE
Do we have any feature to do as "kubectl rollout"?

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/client-go#710]
Do we have any api to do as 
kubelet rollout update xxx
kubectl rollout restart xxx
kubectl rollout pause xxx
?

**Comment by stefanos1019** [comment]
hey @zehuaiWANG did you closed the issue because you found something?
If so can you please help me here?

**Comment by kuzaxak** [comment]
Can't find anything related to rollout section

**Comment by fangfenghuang** [comment]
I write a sample for rollout use: 
https://github.com/fangfenghuang/go-demo/blob/main/pkg/k8sclient/rollout.go
