### ISSUE TITLE
How do I create kube config file from rest.Config object?

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/client-go#711]
I have `rest.Config` (https://godoc.org/k8s.io/client-go/rest#Config) object in my code. I want to write it to a kube config file to use it later. How would I go about writing it to a file?

**Comment by vadasambar** [comment]
I think I will need to convert my `rest.Config` to `api.Config` first.

**Comment by aayush-rangwala** [comment]
Following. Have similar use case, to convert rest config to kubeconfig file

**Comment by vadasambar** [comment]
Ultimately, it's about converting https://pkg.go.dev/k8s.io/client-go/rest?tab=doc#Config into https://pkg.go.dev/k8s.io/client-go/tools/clientcmd/api?tab=doc#Config

**Comment by daxmc99** [comment]
This works 
```go
c, err := clientcmd.NewDefaultClientConfigLoadingRules().Load()
if err != nil {
	os.Exit(1)
}
clientConfig := clientcmd.NewDefaultClientConfig(*c, nil)
config, err = clientConfig.ClientConfig()
```

**Comment by Jordan396** [comment]
In my case, I had a `rest.Config`  from the cluster administrator's kube config file, and I needed to generate a kube config file for a new user using `api.Config`. Following the [bash script approach to generating a kube config file](https://stackoverflow.com/a/42186135/7552964), I formatted the parameters of `api.Config` using fields extracted from the cluster api with the `rest.config`. 
```go
func (kc *KubeController) GenerateKubeConfiguration(namespace string) (string, error) {
	// Get secret list for namespace
	secretList, err := kc.clientset.CoreV1().Secrets(namespace).List(context.TODO(), metav1.ListOptions{})
	if err != nil {
		return "", err
	}

	// Get secret containing authentication data
	secret := secretList.Items[1]

	clusters := make(map[string]*clientcmdapi.Cluster)
	clusters["default-cluster"] = &clientcmdapi.Cluster{
		Server:                   kc.restconfig.Host,
		CertificateAuthorityData: secret.Data["ca.crt"],
	}

	contexts := make(map[string]*clientcmdapi.Context)
	contexts["default-context"] = &clientcmdapi.Context{
		Cluster:   "default-cluster",
		Namespace: namespace,
		AuthInfo:  namespace,
	}

	authinfos := make(map[string]*clientcmdapi.AuthInfo)
	authinfos[namespace] = &clientcmdapi.AuthInfo{
		Token: string(secret.Data["token"]),
	}

	clientConfig := clientcmdapi.Config{
		Kind:           "Config",
		APIVersion:     "v1",
		Clusters:       clusters,
		Contexts:       contexts,
		CurrentContext: "default-context",
		AuthInfos:      authinfos,
	}
	clientcmd.WriteToFile(clientConfig,  "/var/tmp/" + namespace + ".kubeconfig")
}
```

**Comment by OyutianO** [comment]
> In my case, I had a `rest.Config` from the cluster administrator's kube config file, and I needed to generate a kube config file for a new user using `api.Config`. Following the [bash script approach to generating a kube config file](https://stackoverflow.com/a/42186135/7552964), I formatted the parameters of `api.Config` using fields extracted from the cluster api with the `rest.config`.
> 
> ```go
> func (kc *KubeController) GenerateKubeConfiguration(namespace string) (string, error) {
> 	// Get secret list for namespace
> 	secretList, err := kc.clientset.CoreV1().Secrets(namespace).List(context.TODO(), metav1.ListOptions{})
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	// Get secret containing authentication data
> 	secret := secretList.Items[1]
> 
> 	clusters := make(map[string]*clientcmdapi.Cluster)
> 	clusters["default-cluster"] = &clientcmdapi.Cluster{
> 		Server:                   kc.restconfig.Host,
> 		CertificateAuthorityData: secret.Data["ca.crt"],
> 	}
> 
> 	contexts := make(map[string]*clientcmdapi.Context)
> 	contexts["default-context"] = &clientcmdapi.Context{
> 		Cluster:   "default-cluster",
> 		Namespace: namespace,
> 		AuthInfo:  namespace,
> 	}
> 
> 	authinfos := make(map[string]*clientcmdapi.AuthInfo)
> 	authinfos[namespace] = &clientcmdapi.AuthInfo{
> 		Token: string(secret.Data["token"]),
> 	}
> 
> 	clientConfig := clientcmdapi.Config{
> 		Kind:           "Config",
> 		APIVersion:     "v1",
> 		Clusters:       clusters,
> 		Contexts:       contexts,
> 		CurrentContext: "default-context",
> 		AuthInfos:      authinfos,
> 	}
> 	clientcmd.WriteToFile(clientConfig,  "/var/tmp/" + namespace + ".kubeconfig")
> }
> ```

very useful!!!

**Comment by rainbowBPF2** [comment]
> This works
> 
> ```go
> c, err := clientcmd.NewDefaultClientConfigLoadingRules().Load()
> if err != nil {
> 	os.Exit(1)
> }
> clientConfig := clientcmd.NewDefaultClientConfig(*c, nil)
> config, err = clientConfig.ClientConfig()
> ```

I found a new way. Test ok~
       var kubeconfig * string 
       // update kubeconfig content. 

	bytesArray := []byte(*kubeconfig)

	clientConfig ,err:= clientcmd.NewClientConfigFromBytes(bytesArray)
	if err!=nil {
		logs.Error(err.Error())
		return nil
	}

	restConfig, _ := clientConfig.ClientConfig()
	clientSet, err := kubernetes.NewForConfig(restConfig)

**Comment by shamhub** [comment]
> 

https://github.com/kubernetes/client-go/issues/1144

@Jordan396

**Comment by shamhub** [comment]
> 

https://github.com/kubernetes/client-go/issues/1144

@rainbowBPF2

**Comment by ekesken** [comment]
just an easier way to create a kubeconfig file from the rest.Config coming from `sigs.k8s.io/controller-runtime/pkg/envtest`which is used in test suites generated by kubebuilder:

```go
import (
	"os"

	"k8s.io/client-go/rest"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
)


func CreateKubeconfigFileForRestConfig(restConfig rest.Config) string {
	clusters := make(map[string]*clientcmdapi.Cluster)
	clusters["default-cluster"] = &clientcmdapi.Cluster{
		Server:                   restConfig.Host,
		CertificateAuthorityData: restConfig.CAData,
	}
	contexts := make(map[string]*clientcmdapi.Context)
	contexts["default-context"] = &clientcmdapi.Context{
		Cluster:  "default-cluster",
		AuthInfo: "default-user",
	}
	authinfos := make(map[string]*clientcmdapi.AuthInfo)
	authinfos["default-user"] = &clientcmdapi.AuthInfo{
		ClientCertificateData: restConfig.CertData,
		ClientKeyData:         restConfig.KeyData,
	}
	clientConfig := clientcmdapi.Config{
		Kind:           "Config",
		APIVersion:     "v1",
		Clusters:       clusters,
		Contexts:       contexts,
		CurrentContext: "default-context",
		AuthInfos:      authinfos,
	}
	kubeConfigFile, _ := os.CreateTemp("", "kubeconfig")
	_ = clientcmd.WriteToFile(clientConfig, kubeConfigFile.Name())
	return kubeConfigFile.Name()
}
```

**Comment by delthas** [comment]
> just an easier way to create a kubeconfig file from the rest.Config coming from `sigs.k8s.io/controller-runtime/pkg/envtest`which is used in test suites generated by kubebuilder:

This will only work on a rest.Config object having a cert and key data. The other way to do it by @Jordan396 above works on any rest.Config object (it just uses the API server host).
