### ISSUE TITLE
How to use `FieldSelector`? How to filter Services service-side?

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/client-go#713]
After scouring the documentation (unsuccessfully), I found the example in #326 and tried to filter Services by NodePort:

```Golang
opts := metav1.ListOptions{
	LabelSelector: "app=...",
	FieldSelector: fmt.Sprintf("spec.ports[0].nodePort=%s", port),
}
_, err := c.CoreV1().Services(namespace).List(opts)
```

But this appears to not work. I'm possibly writing the filter incorrectly but this errors saying that you can only use `metadata.namespace` or `metadata.name` as `FieldSelector`.

+ Am I using this incorrectly?
+ Is there a way to filter (e.g. Services) service-side like this?

I've resorted to filtering the returned Services client-side but would prefer to not do so.

**Comment by diafour** [comment]
> Am I using this incorrectly?

Your "key=value" strings for selectors are correct. Although, if you want more type-safety, you can use a method LabelSelectorAsSelector in a package `k8s.io/apimachinery/pkg/apis/meta/v1` for LabelSelector and methods in a package `k8s.io/apimachinery/pkg/fields` for FieldSelector.

> Is there a way to filter (e.g. Services) service-side like this?

The short answer is "no, sorry".
The long story is this: according to the discussion in [kubernetes/#53459](https://github.com/kubernetes/kubernetes/issues/53459) and similar issues, it is not possible to filter by random fields. The set of fields is highly restricted, you can dig it here https://github.com/kubernetes/kubernetes/blob/v1.16.1/pkg/registry in `strategy.go` files (i collect them all to the fancy table for another project: [table](https://github.com/flant/shell-operator/blob/8fa3c3b8cfeb1ddb37b070b7a871561fdffe788b/HOOKS.md#fieldselector)).

**Comment by pantelis-karamolegkos** [comment]
Is there any example(s) of how this line

```
LabelSelector: "app=...",
```

can be replaced by leveraging `LabelSelectorAsSelector`?
