### ISSUE TITLE
How to get the `api/v1/nodes/<NodeName>/proxy/stats/summary` programatically

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes/client-go#716]

**Comment by yashbhutwala** [comment]
Figured it out, in case, anyone's wondering, had to construct the request using `SubResource` and `Suffix` and then parse it into struct; [see code here](https://github.com/yashbhutwala/kubectl-df-pv/blob/v0.1.0/pkg/plugin/plugin.go#L116)

```go
request := clientset.CoreV1().RESTClient().Get().Resource("nodes").Name(node.Name).SubResource("proxy").Suffix("stats/summary")
responseRawArrayOfBytes, err := request.DoRaw()
if err != nil {
	return nil, errors.Wrap(err, "failed to get stats from node")
}
```

**Comment by invidian** [comment]
With newer versions of `client-go`, context is needed for `DoRaw()`, so it would actually be:
```go
request := clientset.CoreV1().RESTClient().Get().Resource("nodes").Name(node.Name).SubResource("proxy").Suffix("stats/summary")
responseRawArrayOfBytes, err := request.DoRaw(context.Background())
if err != nil {
	return nil, errors.Wrap(err, "failed to get stats from node")
}
```

**Comment by vlerenc** [comment]
@yashbhutwala @invidian Do you know, whether there is also a bulk call to get these metrics for all nodes in one go?
