### ISSUE TITLE
How to authenticate from outside of cluster using go client?

### ISSUE THREAD

**Issue by emailtovamos** [kubernetes/client-go#720]
I have been through several examples of connection (e.g. [this](https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go)) and all of them seem to include usage of the config file. 
If I am trying to connect to a Kubernetes cluster from OUTSIDE of the cluster, how to proceed? I was looking into having service accounts and roles (e.g. [here](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#without-using-a-proxy)). But is there any example where one can do it using the go client? 
Thanks.

**Comment by harpratap** [comment]
What's the issue you are having with config file method? Works fine for us. Just create a service account and attach a token in a config file with rest of the cluster data and put this config file in $HOME/.kube/config and everything works good.

**Comment by mstrYoda** [comment]
You need to have .kube/config file where you can try to run your application from OUTSIDE of cluster. For details about config file: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

And if you will do any operation like get/list/update/delete resources, your serviceaccount need to has that permissions.

Lets assume you are on the default namespace and using default service account. You can create a custom role and rolebinding for your sa with:

```
kubectl create role some-role --verb=get --verb=list --verb=watch --verb=update --resource=pods --resource=services

kubectl create rolebinding some-binding --role=some-role --serviceaccount=default:default
```

**Comment by feixiaohuijava** [comment]
![image](https://user-images.githubusercontent.com/21102129/95566483-31904080-0a54-11eb-9ce9-2378fd85a8e5.png)
i don't like use kube config  to get clientset. I just use BearerToken and MasterUrl  ： ）
