### ISSUE TITLE
remotecommand doesn't handle stream EOF with 0 bytes read as an error

### ISSUE THREAD

**Issue by gngeorgiev** [kubernetes/client-go#724]
*Issue*:

When running a remotecommand and the connection dies or is killed (e.g. by using `tcpkill`) the returned values [here](https://github.com/kubernetes/client-go/blob/20e59c6/tools/remotecommand/errorstream.go#L42) are `0` and `nil` since [Buffer.ReadFrom](https://github.com/golang/go/blob/0f897f9/src/bytes/buffer.go#L211) handles the `EOF` case and returns `nil`. These values do not meet any of the conditions so it ends up sending a `nil` error into the channel.

*Desired result*:

Maybe we should return an error. What happens now is that the stream dies but instead it appears that everything is OK.

**Comment by madnight** [comment]
For reference, why it matters: 
https://gitlab.com/gitlab-org/gitlab-runner/issues/4119
