### ISSUE TITLE
Failed to import client-go with go mod

### ISSUE THREAD

**Issue by zhou-chao** [kubernetes/client-go#726]
go mod fails when importing `"k8s.io/client-go/kubernetes"`.

### Minimal code (`test.go`) to reproduce the error:

```
package main

import (
	"fmt"
	"k8s.io/client-go/kubernetes"
)

func main() {
	var c kubernetes.Clientset
	fmt.Println(c)
}
```

### Content of `go.mod` (created by go mod init)

```
module github.com/zhou-chao/test

go 1.13
```

### Steps

1. go mod init
2. go run test.go

### Console output

```
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/net latest
go: finding golang.org/x/time latest
go: finding k8s.io/utils latest
go: downloading golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: downloading golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: finding golang.org/x/crypto latest
go: downloading golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: extracting golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: extracting golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: extracting golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
verifying golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e/go.mod: 
golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e/go.mod: 
cannot authenticate record data in server response
```

### Version

- go version: go1.13.4 darwin/amd64
- client-go version: k8s.io/client-go@kubernetes-1.16.3

**Comment by liggitt** [comment]
a few questions:
* what is the content of your go.mod file?
* what version of client-go are you using?
* what version of go are you using?

**Comment by zhou-chao** [comment]
> a few questions:
> 
> * what is the content of your go.mod file?
> * what version of client-go are you using?
> * what version of go are you using?



> a few questions:
> 
> * what is the content of your go.mod file?
> * what version of client-go are you using?
> * what version of go are you using?

Edited. Thanks.

**Comment by zhou-chao** [comment]
> a few questions:
> 
> * what is the content of your go.mod file?
> * what version of client-go are you using?
> * what version of go are you using?

@liggitt  edited. thanks.

**Comment by liggitt** [comment]
> client-go version: k8s.io/client-go@kubernetes-1.16.3

where is that indicated as the required version of client-go? If I explicitly require a version of client-go as described in https://github.com/kubernetes/client-go/blob/master/INSTALL.md#add-client-go-as-a-dependency, this works as expected:

```sh
$ go mod init github.com/zhou-chao/test
```

> ```sh
> go: creating new go.mod: module github.com/zhou-chao/test
> ```
> 

```sh
$ go get k8s.io/client-go@v0.16.4
```

> ```sh
> go: finding k8s.io v0.16.4
> ```
> 

```sh
$ more test.go 
```

> ```go
> package main
> 
> import (
>         "fmt"
>         "k8s.io/client-go/kubernetes"
> )
> 
> func main() {
>         var c kubernetes.Clientset
>         fmt.Printf("%T\n",c)
> }
> ```
> 

```sh
$ go run test.go 
```

> ```sh
> kubernetes.Clientset
> ```

**Comment by zhou-chao** [comment]
> > client-go version: k8s.io/client-go@kubernetes-1.16.3
> 
> where is that indicated as the required version of client-go?

I am using Kubernetes version 1.16.3. Neither the latest version or kubernetes-1.16.3 works.
```
go get k8s.io/client-go@kubernetes-1.16.3
```
> ```
> go: finding k8s.io kubernetes-1.16.3
>go: finding k8s.io/client-go kubernetes-1.16.3
>verifying golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e/go.mod: >golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e/go.mod: cannot authenticate record > data in server response
> ```

```
go get k8s.io/client-go@latest  
go run test.go 
```

>```
>go: finding golang.org/x/time latest
>go: finding golang.org/x/net latest
>go: finding golang.org/x/crypto latest
>go: finding k8s.io/utils latest
>go: finding golang.org/x/oauth2 latest
>verifying golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e/go.mod: >golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e/go.mod: cannot authenticate record >data in server response
>```

Finally problem solved by adding the below line in `go.mod`:
```
replace golang.org/x/tools => golang.org/x/tools v0.0.0-20191120001058-ad01d5993d97
```
