### ISSUE TITLE
go run main.go -kubeconfig=~/.kube/config -logtostderr=true -lease-lock-name=example -lease-lock-namespace=default -id=1

### ISSUE THREAD

**Issue by ftyuuu** [kubernetes/client-go#727]
error:
# k8s.io/client-go/rest
../../../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)

what should i do?

**Comment by nikhita** [comment]
@ftyuuu what does your go.mod file look like and what version of client-go do you want to use?

**Comment by ftyuuu** [comment]
@nikhita thanks! i find the solution in https://github.com/kubernetes/client-go/blob/master/INSTALL.md#go-modules
