### ISSUE TITLE
SECURITY_CONTACTS

### ISSUE THREAD

**Issue by geoffreysmith** [kubernetes/client-go#730]
Please delete this, it is a dumb list of names I'm not supposed to contact even if I knew how to. The Product Security Committee can keep their list of meaningless usernames in a Word document on their desktop like the rest of us. I'm only doing this so that I hope whomever is on this list no longer gets "SECURITY CONTACTS MONTHLY REVIEW MEETING (HOT TOPICS)" meeting requests that gets cancelled at the last minute anyway.

**Comment by nikhita** [comment]
The SECURITY_CONTACTS file is used as the contact point for the Product Security Committee to reach out to for triaging and handling of security concerns.

If you have a vulnerability to report, please see https://kubernetes.io/docs/reference/issues-security/security/.
