### ISSUE TITLE
How to get Pod?

### ISSUE THREAD

**Issue by lwx294821** [kubernetes/client-go#731]
How to query pods that are not associated with a replica controller ? who can help me?

**Comment by mstrYoda** [comment]
One way is to do that might be like that:

```
	pods, err := clientset.CoreV1().Pods("default").List(metav1.ListOptions{})

	for _, pod := range l.Items {
		isAssociatedWithRS := false
		for _, ref := range pod.ObjectMeta.OwnerReferences {
			isAssociatedWithRS = ref.Kind == "ReplicaSet"
		}

		if !isAssociatedWithRS {
			fmt.Println(pod.Name)
		}
	}
```

metav1.ListOptions{} Has fields like FieldSelector and LabelSelector, you can list pods for ex. by namespace like:
```
metav1.ListOptions{
  FieldSelector="metadata.namespace=default",
}
```
but I don't know how to do that for OwnerReferences.

**Comment by lwx294821** [comment]
closed
