### ISSUE TITLE
Go mod get client-go version v11.0.0 old version, How do I get the latest version?

### ISSUE THREAD

**Issue by sky-big** [kubernetes/client-go#733]
Go mod get client-go version v11.0.0 old version, How do I get the latest version?

```
k8s.io/api v0.17.0
k8s.io/apimachinery v0.17.0
k8s.io/client-go v11.0.0+incompatible
k8s.io/code-generator v0.17.0
k8s.io/gengo v0.0.0-20200106221221-d8ecbaa43afd
k8s.io/klog v1.0.0
```

Compile error:

```
# k8s.io/client-go/rest
../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

**Comment by nikhita** [comment]
For client-go corresponding to kubernetes v1.17.0, you can use `go get k8s.io/client-go@v0.17.0`.

Please see https://github.com/kubernetes/client-go/blob/master/INSTALL.md#add-client-go-as-a-dependency for more details on how to get a specific version.

**Comment by sky-big** [comment]
@nikhita ok, It's work, thanks
