### ISSUE TITLE
client-go/testing: Can't list deployments after scaling

### ISSUE THREAD

**Issue by lynx-coding** [kubernetes/client-go#734]
**What happened**:
I wanted to test my method to scale deployments. But after changing the replicas by using `updateScale` I was not able to list deployments anymore.

**What you expected to happen**:
- create fake api
- create mock deployment
- scale it
- list it

**How to reproduce it (as minimally and precisely as possible)**:
- create fake api
- create a mock deployment
- scale the deployment
- list the deployment

**Anything else we need to know?**:
```
package scaling

import (
    "testing"

    v1api "k8s.io/api/apps/v1"
    autoscalingv1 "k8s.io/api/autoscaling/v1"
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/client-go/kubernetes/fake"

    "github.com/stretchr/testify/require"
)

func TestScaling(t *testing.T) {
    initialReplicas := int32(3)
    cs := fake.NewSimpleClientset()
    _, err := cs.AppsV1().Deployments("test-namespace").Create(&v1api.Deployment{
        ObjectMeta: metav1.ObjectMeta{
            Name: "test-deployment",
            Labels: map[string]string{
                "app": "test-app",
            },
        },
        Spec: v1api.DeploymentSpec{
            Replicas: &initialReplicas,
        },
    })
    require.NoError(t, err)
    scale := &autoscalingv1.Scale{
        ObjectMeta: metav1.ObjectMeta{
            Name:      "test-deployment",
            Namespace: "test-namespace",
        },
        Spec: autoscalingv1.ScaleSpec{
            Replicas: 5,
        },
    }
    _, err = cs.AppsV1().Deployments("test-namespace").UpdateScale("test-deployment", scale)
    require.NoError(t, err)
    _, err = cs.AppsV1().Deployments("test-namespace").List(metav1.ListOptions{FieldSelector: "app=test-app"})
    require.NoError(t, err)
}
```
Run like this:
```
go test -run TestScaling ./scaling
```

This will lead to an error like the following:
```
item[0]: can't assign or convert v1.Scale into v1.Deployment
```

**Environment**:
- go version: `go1.13.5 linux/amd64`
- client-go version: `k8s.io/client-go@v0.16.4`
- related issue(s)/pr(s):
  - [80354](https://github.com/kubernetes/kubernetes/issues/80354) 
  - [410](https://github.com/kubernetes-sigs/controller-runtime/pull/410)
  - [579](https://github.com/kubernetes/client-go/issues/579)

**Comment by chrisseto** [comment]
I'm also encountering this issue with Statefulsets.

@lynx-coding have you had any luck with tracking down a fix or work around?

From digging around a bit, it looks like `Scale` is a psuedo resource rather than a true subresource which may be the cause for issues?
