### ISSUE TITLE
Can't override config values

### ISSUE THREAD

**Issue by crunchtime-ali** [kubernetes/client-go#735]
I am loading my local kubeconfig which contains multiple clusters and contexts. The default context is "prod" and one of the config values I want to override is the `CurrentContext` 

```
	clientConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: "/Users/me/.kube/config"},
		&clientcmd.ConfigOverrides{
			CurrentContext: "stage",
		})

	rawConfig, _ := clientConfig.RawConfig()
	log.Printf(rawConfig.CurrentContext) // outputs "prod" instead of "stage"
```
When I inspect `RawConfig()` the current context is still "prod" instead of "stage".
Why does the config override not work?

Also how does the override for AuthInfo etc. work? The override accepts only a single `AuthInfo` whereas the configuration contains a map of `AuthInfo` etc.

**Comment by vvelikodny** [comment]
> Why does the config override not work?

@crunchtime-ali  according to

https://github.com/kubernetes/client-go/blob/a432bd9ba7da427ae0a38a6889d72136bce4c4ea/tools/clientcmd/client_config.go#L57-L58

`RawConfig` should return config with overrides, but it really doesn't

https://github.com/kubernetes/client-go/blob/a432bd9ba7da427ae0a38a6889d72136bce4c4ea/tools/clientcmd/client_config.go#L122-L124

just return config without overrides. You could see a possible solution here in my patch

https://github.com/vvelikodny/client-go/commit/8c99132f9960bc61d3fceb0bd20ad3e5964f8203

> Also how does the override for AuthInfo etc. work? The override accepts only a single AuthInfo whereas the configuration contains a map of AuthInfo etc.

override only AuthInfo with the key of username which presented in context.AuthInfo (string). 

https://github.com/kubernetes/client-go/blob/a432bd9ba7da427ae0a38a6889d72136bce4c4ea/tools/clientcmd/client_config.go#L424-L437

https://github.com/kubernetes/client-go/blob/a432bd9ba7da427ae0a38a6889d72136bce4c4ea/tools/clientcmd/client_config.go#L388-L394

**Comment by bioball** [comment]
/reopen

This is still a problem that exists today, and affects clients that are using client-go.

**Comment by crunchtime-ali** [comment]
> /remove-lifecycle-rotten
> /reopen
> 
> This is still a problem that exists today, and affects clients that are using client-go.

Let me lend you a hand :)

/remove-lifecycle-rotten
/reopen

**Comment by bioball** [comment]
@crunchtime-ali wohooo thanks!

**Comment by crunchtime-ali** [comment]
Still an issue
/reopen
/remove-lifecycle rotten
