### ISSUE TITLE
dynamic client requested resource not found 

### ISSUE THREAD

**Issue by AdheipSingh** [kubernetes/client-go#737]
Trying to access istio crds using dynamic client, each time i access i get this error 
```
2020/01/21 19:44:10 the server could not find the requested resource
```
Here is the code snippet i am trying to run 
```
loggingRes := schema.GroupVersionResource{
		Group:    "networking.istio.io",
		Version:  "v1beta1",
		Resource: "virtualservices",
	}

	client := utils.GetKubeClientset()

	result, err := client.Resource(loggingRes).Namespace("default").Get("reviews", metav1.GetOptions{})
	if err != nil {
		log.Printf("%s", err.Error())
	}
```
When i switch GVR kind to deployments or native kubernetes GVR it works. Any help would be appreciated.
Here are the version i am running 
```
BNG-188814-C02YH02XJGH8:.kube $ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
BNG-188814-C02YH02XJGH8:.kube $ minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad

```

Here is my go.mod
```
require (
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
	github.com/gorilla/mux v1.7.3
	github.com/imdario/mergo v0.3.8 // indirect
	golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d // indirect
	golang.org/x/time v0.0.0-20191024005414-555d28b269f0 // indirect
	k8s.io/apimachinery v0.17.1
	k8s.io/client-go  v12.0.0+incompatible
	k8s.io/utils v0.0.0-20200117235808-5f6fbceb4c31 // indirect
)

```

**Comment by liggitt** [comment]
is that the correct virtualservice API version? the documentation I see is `v1alpha3` (e.g. https://istio.io/docs/reference/config/networking/virtual-service/)

What does `kubectl api-versions` output?

**Comment by liggitt** [comment]
Verify you are using the correct resource name (`kubectl api-resources` will show all available resources, and you must use the plural resource name when constructing the dynamic client)

> The CRD is cluster scoped

For cluster-scoped resources, omit the `.Namespace("...")` call

**Comment by AdheipSingh** [comment]
plural was the issue, i was not aware of that. Silly....

Thanks a ton @liggitt . Much Appreciated

**Comment by AlexLast** [comment]
> Verify you are using the correct resource name (`kubectl api-resources` will show all available resources, and you must use the plural resource name when constructing the dynamic client)
> 
> > The CRD is cluster scoped
> 
> For cluster-scoped resources, omit the `.Namespace("...")` call

Thanks @liggitt solved for me too 👍

**Comment by hermanbanken** [comment]
👍  Thanks a million!

For people Googling my issue:
> reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch apps/v1, Kind=StatefulSet: failed to list apps/v1, Kind=StatefulSet: the server could not find the requested resource
reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch apps/v1, Kind=DaemonSet: failed to list apps/v1, Kind=DaemonSet: the server could not find the requested resource
reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch apps/v1, Kind=Deployment: failed to list apps/v1, Kind=Deployment: the server could not find the requested resource

The error "the server could not find the requested resource" is from the call that is 
```go
clientset.Resource(gvr).Namespace(namespace).List(context.TODO(), options)
```
The remainder of the error "Failed to watch apps/v1, Kind=Deployment: failed to list apps/v1, Kind=Deployment" is from the `watchtools.UntilWithSync` which takes the GVK from the `objType` argument (which you can set differently, but does not fix the issue of the GVR on the dynamic client).

**Comment by sharathchnandikonda** [comment]
> Verify you are using the correct resource name (`kubectl api-resources` will show all available resources, and you must use the plural resource name when constructing the dynamic client)
> 
> > The CRD is cluster scoped
> 
> For cluster-scoped resources, omit the `.Namespace("...")` call

Thanks @liggitt , it helped me too.
