### ISSUE TITLE
Kubelet Client and API types

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/client-go#74]
Kubelet exposes the stats API (https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/api/v1alpha1/stats) as well as an associated client (https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/client).  Heapster uses these to talk to the the legacy stats API and the summary API (see https://github.com/kubernetes/heapster/tree/master/metrics/sources/kubelet and https://github.com/kubernetes/heapster/tree/master/metrics/sources/kubelet).

Having those API types and the client code here (or in a separate repo) would be useful, since it would work towards removing the circular dependency between Heapster and Kubernetes.

cc @deads2k @lavalamp

**Comment by DirectXMan12** [comment]
@dashpole's proposed "Core Metrics API" (kubernetes/community#252) will most likely have a similar issue.

In the longer term, the API definitions for the metrics APIs shouldn't live in Heapster, but not requiring Heapster to vendor k8s proper would be nice in and of itself (seeing as it's a client of Kubernetes, mainly, that happens to take advantage of some of the shared API server code that's being split out).

**Comment by deads2k** [comment]
This client project may just be for speaking to an API server, but this does highlight a need to do something similar for the kubelet or to break the kubelet out of k8s.io/kubernetes to avoid the cycle.

**Comment by lavalamp** [comment]
I think once we're developing the client in a separate repo we could
actually do this but it would make things even more convoluted to add it in
right now? I could be wrong. I'm not opposed to this.

**Comment by deads2k** [comment]
> I think once we're developing the client in a separate repo we could
> actually do this but it would make things even more convoluted to add it in
> right now? I could be wrong. I'm not opposed to this.

It might not be too bad in 1.6 (february).  We're actually getting pretty close to eliminating most of the code vendored from k8s.io/kubernetes.

**Comment by DirectXMan12** [comment]
this is no longer needed, really.  We've got our own copy in Heapster for the moment, and that's "ok" until something changes with those APIs, since this issue isn't going anywhere.

**Comment by yashbhutwala** [comment]
Discovered this issue while trying to #716.  Any updates on integrating the clients?
