### ISSUE TITLE
Lowercase openapiv2 imports

### ISSUE THREAD

**Issue by mganta** [kubernetes/client-go#741]
Build breaking changes due to https://github.com/googleapis/gnostic/pull/155

Need to update imports to github.com/googleapis/gnostic/openapiv2

Here is the error:
 go get k8s.io/client-go/kubernetes
 ---> Running in 2aec6896da7e
package github.com/googleapis/gnostic/OpenAPIv2: cannot find package "github.com/googleapis/gnostic/OpenAPIv2"

**Comment by liggitt** [comment]
Getting a specific version will make use of correct transitive versions. For example, `go get k8s.io/client-go@v0.17.2`

See the INSTALL.md in the repo root for details

**Comment by TUTUBIG** [comment]
> Getting a specific version will make use of correct transitive versions. For example, `go get k8s.io/client-go@v0.17.2`
> 
> See the INSTALL.md in the repo root for details

failed again  and correct solution is to use a special version of github.com/googleapis/gnostic,such as v0.3.1

**Comment by nyetwurk** [comment]
> Getting a specific version will make use of correct transitive versions. For example, `go get k8s.io/client-go@v0.17.2`

This does not work.

```
$ go get k8s.io/client-go@v0.17.2 ./...
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
../../go/pkg/mod/k8s.io/client-go@v0.17.2/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```

**Comment by liggitt** [comment]
try `go get k8s.io/client-go@v0.17.2` alone

to see what else in your build is requiring a newer version of `github.com/googleapis/gnostic`, run:
```
go mod graph | grep github.com/googleapis/gnostic
```

**Comment by nyetwurk** [comment]
The issue is that a go get -u will generally get a newer version of gnostic

When will this be fixed in client-go properly?

**Comment by kubilesti** [comment]
same issue here.

**Comment by nyetwurk** [comment]
Please update at least one of the semver client-go versions i can reference (not master), TIA :)

**Comment by liggitt** [comment]
Existing client-go versions will not be updated. Updating this dependency is being looked at in https://github.com/kubernetes/kubernetes/pull/89704 and https://github.com/kubernetes/kube-openapi/pull/189, targeting Kubernetes 1.19.

**Comment by vishutrilio** [comment]
> Had to do both at the same time
> 
> ```
> go get -u k8s.io/client-go@v0.17.2 github.com/googleapis/gnostic@v0.3.1 ./...
> ```
> 
> since another module depends on gnostic.
> 
> When will upstream be fixed?

Thank you so much

**Comment by InfluencerNGZK** [comment]
> Had to do both at the same time
> 
> ```
> go get -u k8s.io/client-go@v0.17.2 github.com/googleapis/gnostic@v0.3.1 ./...
> ```
> 
> since another module depends on gnostic.
> 
> When will upstream be fixed?

Same issue here but only happens on ubuntu. On windows `github.com/googleapis/gnostic@v0.5.1` is fine.

**Comment by pumsscco** [comment]
It seems not work on centos7 either，I use my vm to test my script ,and the issue remains


go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
build my-client-go-rd: cannot load github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.2), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
[root@c7 my-client-go-rd]#

**Comment by EronWright** [comment]
A recap for those seeing an issue with the casing of `github.com/googleapis/gnostic/openapiv2`:  Older versions of the `openapiv2` package had a mixed-case name, then was updated to be lower-case.  Pre-1.19 builds of K8s used the former, and now use the latter.  You might experience a problem if you're building on a case-sensitive filesystem, esp. if using go mod vendoring.  Possible fix is to git remove the vendored content and then re-sync.

**Comment by nyetwurk** [comment]
> You might experience a problem if you're building on a case-sensitive filesystem
This should be reworded as 
"You will experience problems unless you're building on a case-insensitive filesystem". One is the exception, not the rule.

**Comment by aslin3** [comment]
Always specify matching versions of all three k8s.io/... components in your go.mod file

require (
    ...
    k8s.io/api v0.19.0
    k8s.io/apimachinery v0.19.0
    k8s.io/client-go v0.19.0
    ...
)

from: https://stackoverflow.com/questions/63655419/kubernetes-client-go-couldnt-find-module
this solved my problem, which wasted my several hours.

**Comment by nyetwurk** [comment]
> Getting a specific version will make use of correct transitive versions. For example, `go get k8s.io/client-go@v0.17.2`
> 
> See the INSTALL.md in the repo root for details

This is the last comment before the bug was unceremoniously closed, and it is inaccurate.

**Comment by TwinProduction** [comment]
@liggitt Any chance we can get this re-opened? 

This bug is seriously annoying, and I'm not fond of just randomly pinning versions until it works.
Downgrading to pre-0.19 isn't really a good option either for those of us that want to keep their dependencies updated.

For everybody else who's still struggling with this issue, the easiest way to go about "fixing" this issue for now is to use a pre-0.19 version of client-go. At the time of this message, the latest one is `v0.18.14`, which means your `go.mod` should look like this:

```
require (
        // ...
	k8s.io/api v0.18.14
	k8s.io/apimachinery v0.18.14
	k8s.io/client-go v0.18.14
)

replace k8s.io/client-go => k8s.io/client-go v0.18.14
```

**Comment by nyetwurk** [comment]
Agreed, it's inexcusable at this point

**Comment by liggitt** [comment]
The v0.19.x and v0.20.x versions of client-go work with the latest lowercased openapi library, so no pinning is required with those versions.

**Comment by JPZ13** [comment]
@liggitt I think the issue for many is that a lot of projects and deployments depend on pre-v0.19.x versions of this package, and updating to post-v0.19.x requires lots of changes to function signatures. If I sat down over New Years and fixed the broken imports from version v0.16.x to v0.18.x and put out PRs, would you merge them?

**Comment by liggitt** [comment]
> @liggitt I think the issue for many is that a lot of projects and deployments depend on pre-v0.19.x versions of this package, and updating to post-v0.19.x requires lots of changes to function signatures.

client-go 0.16.x-0.18.x versions work as-is if you use the matching version of the openapi library and don't have other dependencies that require the lowercase openapi packages. if you need/want to use the latest openapi version after the package name break, upgrading to client-go 0.19.x+ is the way to do that. 

> If I sat down over New Years and fixed the broken imports from version v0.16.x to v0.18.x and put out PRs, would you merge them?

No, backporting an incompatible dependency change to a patch release would be just as likely to break existing client-go consumers who have some other dependency in their tree that uses the uppercase openapi packages. We limit that sort of change to Kubernetes minor versions.

**Comment by JPZ13** [comment]
Makes sense. Thanks, man

**Comment by najork** [comment]
For those of you developing on macOS (or any other case-insensitive filesystem), I had to do the following in order for git to properly detect the filename change:

1. Upgrade the client-go dependency to v0.19.x+
2. `rm -rf vendor/github.com/googleapis/gnostic` and create an intermediate commit
3. Rerun `go mod vendor` to retrieve the files and create a new commit

**Comment by dongwangdw** [comment]
I have to use replace to get a compatible version and it works.

**Comment by lboix** [comment]
Using Kubernetes 1.14, here is the workaround my team and I found to fix this.

In your **go.mod** file, use:
```
k8s.io/api kubernetes-1.14.0
k8s.io/apimachinery kubernetes-1.14.0
k8s.io/client-go kubernetes-1.14.0
```

Then run:
```
go mod tidy
go mod vendor
```

And version / commit your **/vendor** folder (build was unable to pass on our Gitlab runner without this).

We are planning to migrate to Kubernetes 1.19 soon. We will be able after that to use the up-to-date Go client version and remove the /vendor folder,  I will let you know.

Hope it helps, have a great day!

**Comment by ReOneK** [comment]
> Had to do both at the same time
> 
> ```
> go get -u k8s.io/client-go@v0.17.2 github.com/googleapis/gnostic@v0.3.1 ./...
> ```
> 
> since another module depends on gnostic.
> 
> When will upstream be fixed?

Good job!

**Comment by wdma** [comment]
This solution did not work for me (versions updated to reflect mine)
```
go get -u k8s.io/client-go@v0.21.2 github.com/googleapis/gnostic@v0.4.1 ./...
```

I also tried this suggestion and failed (again, versions are updated to reflect my system)
```
In your go.mod file, use:

k8s.io/api kubernetes-1.21.2
k8s.io/apimachinery kubernetes-1.21.2
k8s.io/client-go kubernetes-1.21.2
```

I think I am missing something.  I have basic Go skills, and this error has taken days of my time.  Please help!
