### ISSUE TITLE
question: How to return client errors with fake client?

### ISSUE THREAD

**Issue by bcatubig** [kubernetes/client-go#742]
Hello,

I'm trying to write some unit tests using the `fake` package. I want to be able to return an error for unit testing, but it's unclear how to do so.

In my example, I want to be able to call `fakeCLient.CoreV1.Secrets(<namespace>).Create(<secret>)` and have `Create` return an `error` instead of a `*v1.Secret`. Is there a simple way to do this?

Thank you for the help :)

**Comment by julienstroheker** [comment]
Hi @bcatubig what about doing something like this : 
```
	kubernetesClient = fake.NewSimpleClientset()
	kubernetesClient.CoreV1().(*fakecorev1.FakeCoreV1).PrependReactor("create", "secrets", func(action testing.Action) (handled bool, ret runtime.Object, err error) {
				return true, &v1.Secret{}, errors.New("Error creating secret")
			})
```
?

**Comment by bcatubig** [comment]
Thanks @julienstroheker that works perfect!

**Comment by nikhita** [comment]
Closing since https://github.com/kubernetes/client-go/issues/742#issuecomment-633676780 answers this. Please reopen if needed!

/close

**Comment by JY226** [comment]
> Hi @bcatubig what about doing something like this :
> 
> ```
> 	kubernetesClient = fake.NewSimpleClientset()
> 	kubernetesClient.CoreV1().(*fakecorev1.FakeCoreV1).PrependReactor("create", "secrets", func(action testing.Action) (handled bool, ret runtime.Object, err error) {
> 				return true, &v1.Secret{}, errors.New("Error creating secret")
> 			})
> ```
> 
> ?

what if I have two Create calls and I want the second one to throw an error in the testing, any idea how to implement this?

**Comment by AgustinRamiroDiaz** [comment]
> what if I have two Create calls and I want the second one to throw an error in the testing, any idea how to implement this?

I think you'll need to do the same and modify the `func` to return errors depending on `ret runtime.Object`

**Comment by cikupin** [comment]
Hi @AgustinRamiroDiaz @julienstroheker any idea where I can learn about this reactor function on this kubernetes library? I'm still confused about the concept of reactor here and how to use it.

**Comment by AgustinRamiroDiaz** [comment]
Hi @cikupin :D 

I think your best bet is to read https://github.com/kubernetes/client-go/blob/master/testing/fake.go

From what I understand, this are not things you'll get in the usual client. This are just helpers for your unit tests. The `prependReactor` is like a middleware that you can use to tune the request handling of your fake client to fit your needs. For example, to return a custom error to assert your tests.

**Comment by cikupin** [comment]
@AgustinRamiroDiaz Thanks for the info 👍
