### ISSUE TITLE
change import for github.com/googleapis/gnostic/OpenAPIv2

### ISSUE THREAD

**Issue by VineethReddy02** [kubernetes/client-go#743]
client-go is dependent on 
https://github.com/googleapis/gnostic

The recent PR merged into the master of googleapis/gnostic/. Is flaking client-go at 
k8s.io/client-go/discovery/discovery_client.go:30:2: cannot find package **"github.com/googleapis/gnostic/OpenAPIv2"** 
The above import is renamed to
**"github.com/googleapis/gnostic/openapiv2"**

**Comment by VineethReddy02** [comment]
Also, I can raise PR addressing the same.

**Comment by liggitt** [comment]
See resolution in https://github.com/kubernetes/client-go/issues/741#issuecomment-580957445

Using a specific version of client go will correctly fetch compatible versions of dependencies

**Comment by lowang-bh** [comment]
`git config core.ignorecase false --local` to set git don't igrnore alpha case and then run go mod to re-gen the vendor
