### ISSUE TITLE
updateUnfinishedWorkLoop uses a large amount of CPU at idle

### ISSUE THREAD

**Issue by dramich** [kubernetes/client-go#746]
When we scale Rancher to 1000's of clusters we end up spending a large percentage of
our time waking up and doing nothing across 10s of thousands of goroutines. This was seen as constantly consuming 2-3 cores while the system was in an 'idle' state with approx. 78k queues being active. 

I think two things could help this:
1. Make `defaultUnfinishedWorkUpdatePeriod` configurable either through an envvar or similar to `SetProvider`
2. If the metrics coming into `newQueue` is of type `noMetrics` then don't run the go routine. 

If there are other approaches I would like to hear them. 
Assuming these options sound good I am happy to open a pr with these fixes.

**Comment by alexlovelltroy** [comment]
Seems reasonable to me, but it would be nice to see some links to the code in question so we can better discuss it in context.

**Comment by dramich** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/94811
