### ISSUE TITLE
cannot convert klog.V(9) (type klog.Verbose) to type bool

### ISSUE THREAD

**Issue by sjagvi** [kubernetes/client-go#750]
ERROR: cannot convert klog.V(9) (type klog.Verbose) to type bool
![image](https://user-images.githubusercontent.com/46345205/74348326-cdc55300-4db2-11ea-9038-8ae3edc780c6.png)
I'm trying to run a go test in my machine and it ended up with this error today. It was fine until yesterday, and it also runs fine with the old test files, and not with the newly created one. 

Any suggestions or help will be much appreciated.

**Comment by max-l-weaver** [comment]
Also getting the same error.
Seems to be in the [debugWrappers](https://github.com/kubernetes/client-go/blob/master/transport/round_trippers.go#L68) function which tries to convert Verbose type to bool

**Comment by praveen9354** [comment]
➜  test go version
go version go1.14.1 darwin/amd64
➜  test go run main.go
# k8s.io/client-go/transport
../k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
../k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
../k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
../k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
➜  test
