### ISSUE TITLE
A bug occurred in the client-go upgrade

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/client-go#751]
**Original version**:
```
k8s.io/client-go v10.0.0+incompatible

k8s.io/client-go v10.0.0+incompatible h1:F1IqCqw7oMBzDkqlcBymRq1450wD0eNqLE9jzUrIi34=
k8s.io/client-go v10.0.0+incompatible/go.mod h1:7vJpHMYJwNQCWgzmNV+VYUl1zCObLyodBc8nIyt8L5s=
````
**Upgraded version**:
```
$ go get -u k8s.io/client-go@kubernetes-1.14.0
$ go build -o api
...
...
# k8s.io/client-go/rest
..\..\..\..\pkg\mod\k8s.io\client-go@v11.0.0+incompatible\rest\request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```
**env**:
```
go version go1.13.3 windows/amd64
```

**Comment by liggitt** [comment]
client-go versions will not work properly with `go get -u`, due to the presence of major versions that predate go modules.

The recommendation is to select a particular version of client-go following the instructions in https://github.com/kubernetes/client-go/blob/master/INSTALL.md

/close

**Comment by xichengliudui** [comment]
Sorry, I don't understand
Isn't `go get -u` just a command for upgrading? why not use it with `client-go`? did i give the wrong order?
Thanks for your reply！

**Comment by liggitt** [comment]
if you want to update to a specific version of client-go, you can do `go get k8s.io/client-go@...version...`

`go get -u` updates to the "newest" version of the dependency specified, which in the case of client-go, includes major version tags released prior to the existence of go modules

**Comment by xichengliudui** [comment]
Thank you very much！
