### ISSUE TITLE
500 error returned in accessing unexisting server - v0.18.0-alpha.2

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/client-go#753]
#### Version
v0.18.0-alpha.2
_all k8s modules used in k8s dashboard has been updated to above._

#### Condition
`http://127.0.0.1:8080` does not exist.

#### Expected result:
`Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/services/heapster/proxy/healthz: dial tcp 127.0.0.1:8080: connect: connection refused`

#### Observed result
`an error on the server ("") has prevented the request from succeeding`
https://travis-ci.org/kubernetes/dashboard/jobs/651408636#L715

**Comment by shu-mutou** [comment]
please help! v0.17.3 seems to work. what's difference in v0.18?

**Comment by liggitt** [comment]
this is caused by https://github.com/kubernetes/kubernetes/issues/87510. It is considered release blocking for 1.18 and can be tracked there

/close

**Comment by shu-mutou** [comment]
@liggitt Thanks!!
