### ISSUE TITLE
Out of cluster example fails to build

### ISSUE THREAD

**Issue by drpaneas** [kubernetes/client-go#757]
### Scenario

I am trying to build https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go

#### Actual Behaviour

Build fails

#### Expected Behaviour

To build without problem or any manual configuration at `go.mod`.

#### Workaround
If I replace the `go-client` entry at the `Requirements` with the `v0.17.3` and run `go tidy`  then it works.

### Reproducer

```zsh
$ mkdir testdir; cd testdir
$ wget https://raw.githubusercontent.com/kubernetes/client-go/master/examples/out-of-cluster-client-configuration/main.go
$ git init -q
$ go build -o app
# k8s.io/client-go/rest
../../gocode/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

### Debug

```mod
$ cat go.mod
module github.com/drpaneas/talk2k8s

go 1.14

require (
	github.com/imdario/mergo v0.3.8 // indirect
	golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d // indirect
	golang.org/x/time v0.0.0-20191024005414-555d28b269f0 // indirect
	k8s.io/api v0.17.3 // indirect
	k8s.io/apimachinery v0.17.3
	k8s.io/client-go v11.0.0+incompatible
	k8s.io/utils v0.0.0-20200228132438-f9c14454073b // indirect
)
```

```go
$ go get
# k8s.io/client-go/rest
../../gocode/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

```go
$ go list -m -versions k8s.io/client-go
k8s.io/client-go v0.15.7 v0.15.8-beta.0 v0.15.8-beta.1 v0.15.8 v0.15.9-beta.0 v0.15.9 v0.15.10-beta.0 v0.15.10 v0.15.11-beta.0 v0.16.4 v0.16.5-beta.0 v0.16.5-beta.1 v0.16.5 v0.16.6-beta.0 v0.16.6 v0.16.7-beta.0 v0.16.7 v0.16.8-beta.0 v0.17.0 v0.17.1-beta.0 v0.17.1 v0.17.2 v0.17.3-beta.0 v0.17.3 v0.17.4-beta.0 v0.18.0-alpha.1 v0.18.0-alpha.2 v0.18.0-alpha.4 v0.18.0-alpha.5 v0.18.0-beta.0 v0.18.0-beta.1 v0.19.0-alpha.0 v1.4.0 v1.5.0 v1.5.1 v2.0.0-alpha.1+incompatible v2.0.0+incompatible v3.0.0-beta.0+incompatible v3.0.0+incompatible v4.0.0-beta.0+incompatible v4.0.0+incompatible v5.0.0+incompatible v5.0.1+incompatible v6.0.0+incompatible v7.0.0+incompatible v8.0.0+incompatible v9.0.0-invalid+incompatible v9.0.0+incompatible v10.0.0+incompatible v11.0.0+incompatible
```

```go
$ go list -m k8s.io/client-go
k8s.io/client-go v11.0.0+incompatible
```

Is it something wrong with my system?

**Comment by liggitt** [comment]
Unfortunately, the current state of client-go versioning is that you need to `go get` a version of client-go that matches the version you got the example from. 

The latest semver tags on the repo resolve to old versions (e.g v11.0.0+incompatible) lacking go.mod info, which makes go fetch `master` of all transitive dependencies, which are not compatible with the old version of client go.

**Comment by liggitt** [comment]
https://github.com/kubernetes/client-go/blob/master/INSTALL.md has instructions for specifying a particular version of client-go to use

**Comment by drpaneas** [comment]
> https://github.com/kubernetes/client-go/blob/master/INSTALL.md has instructions for specifying a particular version of client-go to use

I know. My question is why I need to specify a version in the first place? Why it doesn't pick the latest stable version as it happens with the other dependencies?

**Comment by liggitt** [comment]
> My question is why I need to specify a version in the first place? Why it doesn't pick the latest stable version as it happens with the other dependencies?

Because go modules do not let us tag further major versions without renaming the module. We are investigating doing that, but that is a larger change that has not been settled on yet.

**Comment by drpaneas** [comment]
Thanks for the information.
