### ISSUE TITLE
Default to protobuf?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/client-go#76]
I was reviewing some code that sets `cfg.ContentType = "application/vnd.kubernetes.protobuf"` to opt-in to protobuf, but then I was wondering why that is needed (context 
https://github.com/kubernetes/ingress/pull/143#discussion_r97200977)

Can client-go just default to protobuf?  As a user of client-go, I don't feel like I'm in a better position to make that decision than client-go is :-)

**Comment by wojtek-t** [comment]
The reason that we didn't change the default initially was that protobufs were supported for the first time in 1.3 (and this is the time when we added those ``` cfg.ContentType = application/vnd.kubernete.protobuf ``` line) and we wanted to client to work also with older versions of apiserver.

However, now when we have already 3 stables releases of protobufs being supported and used by our components, I think we should just change the default.

@lavalamp @caesarxuchao - for thoughts

**Comment by deads2k** [comment]
@smarterclayton

**Comment by ericchiang** [comment]
Per a comment on a design doc, @smarterclayton noted that

> Protobuf is still quasi "internal only" - we haven't had quite enough soak time to be 100% sure we won't have to break the schema.

Is there some place tracking the concerns around committing to the current serialization format? Maybe this package can handle any breaking changes transparently down the line?

**Comment by smarterclayton** [comment]
I'd probably prefer to continue to treat protobuf as an internal format, with the less strict guarantees we give around perfect compatibility (like we do for JSON).  Use at your own risk, we reserve the right to change it in the event we severely messed up, and JSON should be good enough for anyone.

I don't want it to be the default today.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#serialization-format is still in place.  It was in the docs somewhere, but can't find it now.

**Comment by lavalamp** [comment]
Given that we use proto for our storage format, I don't think we can break it. Therefore I don't see an issue with setting it to be the default.

**Comment by sttts** [comment]
If we want to default to protobuf, we probably need a tag for the client-go generator to switch to protobuf for those types that support it and leave it at json for CRDs (and other groups without proto support). Also note that we had native API groups for some time without proto support (those in staging like apiextensions.k8s.io).

**Comment by linxiulei** [comment]
Any possibility we review this?

@wojtek-t
