### ISSUE TITLE
Help on how clientset can be created and used without kubeconfig ?

### ISSUE THREAD

**Issue by bkannadassan** [kubernetes/client-go#760]
Hi All,

  In all client-go examples we see kubeconfig path has to be given. I would like to know is this the only way to do or can we get the clientset without giving kubeconfig path ?

```
        kubeconfig := flag.String("kubeconfig", os.Getenv("HOME")+"/.kube/config", "path to the kubeconfig file to use")
        flag.Parse()
        config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
        if err != nil {
                return err
        }
        clientset, err := kubernetes.NewForConfig(config)
        if err != nil {
                return err
        }
        api := clientset.CoreV1()
        watcher, err := api.Pods("").Watch(context.TODO(), metav1.ListOptions{})
```
How to have this working if I don't have a kuneconfig path ?.

rgds
Balaji Kamal Kannadassan

**Comment by bseenu** [comment]
@bkannadassan You can create clientset without kubeconfig , but for that your code should be running in a pod in an existing cluster and which uses the rest interface, you can check the relevant example here - https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration

**Comment by LRocc** [comment]
@bseenu how would you create a clientset without the kubeconfig?

**Comment by bseenu** [comment]
https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L42-L47

**Comment by francardoso93** [comment]
No way to do that outside the cluster?

**Comment by francardoso93** [comment]
If you want to do this outside the cluster, that's how:

``` go
config := &rest.Config{
		Host:        "xxxxxx",
		BearerToken: "xxxxxxxx", 
		TLSClientConfig: rest.TLSClientConfig{			
			 CertData: []byte(xxxxxx),
			
	},
}

clientset, err := kubernetes.NewForConfig(config)
```
