### ISSUE TITLE
Force deleting a job won't force delete the pods

### ISSUE THREAD

**Issue by mlumibao-wish** [kubernetes/client-go#761]
Client Go Version: v0.17.3

**Expected Behaviour:**
Running 
```go
var deleteOptions *metav1.DeleteOptions
var zero int64 = 0
deleteOptions = &metav1.DeleteOptions{GracePeriodSeconds: &zero}

cl.CoreV1().Pods(namespace).Delete(name, deleteOptions)
```
Will delete the pods immediately. But when we run

```go
deleteOptions := &metav1.DeleteOptions{}
var zero int64 = 0
bg := metav1.DeletePropagationBackground
deleteOptions.GracePeriodSeconds = &zero
deleteOptions.PropagationPolicy = &bg

cl.BatchV1().Jobs(namespace).Delete(name, deleteOptions)
``` 
I expect it to also delete the pods forcefully. like running the command
`kubectl delete job <my job> --grace-period 0 --force` does.

**Actual behaviour**
The pods are stuck in terminating and are not forcefully deleted like what happens using kubectl.

**Comment by arianitu** [comment]
I'm also running into this. Is there any way to use `--force`. The pods still continue to run and don't terminate even after 30 seconds, they're stuck on "terminating".

**Comment by coreyperkins** [comment]
Bump, why is this closed?

**Comment by guoziyi-study** [comment]
难道client-go连--force都没法加吗？

**Comment by kong62** [comment]
好像找不到，但是 kubectl 确实有的
