### ISSUE TITLE
Fake client not support subresources

### ISSUE THREAD

**Issue by kebe7jun** [kubernetes/client-go#763]
If I use fake client update subresources, the tracker will override resource with subresources.

Code: https://github.com/kubernetes/client-go/blob/5194bac869679e2d68716e9eeddf23d3c13661e1/testing/fixture.go#L79-L124

The objects' key only contains GroupVersionResource, the subresources' info missed.

Is there any plan to support subresources for fake client?

**Comment by lzlaa** [comment]
I got the same problem, how to handle it?

**Comment by tssurya** [comment]
I am running into the same problem. I see this issue was closed? Was there a fix?
