### ISSUE TITLE
ContainerStatus.LastState throws error.

### ISSUE THREAD

**Issue by collbrain** [kubernetes/client-go#765]
I am trying to get last state of my container but getting following error. 

containerState.LastState undefined (type "k8s.io/api/core/v1".ContainerStatus has no field or method LastState)

But other fields such as State, RestartCount, Ready etc work.

**Comment by bseenu** [comment]
@collbrain The correct field name is "LastTerminationState" and not "LastState"

Ref : https://godoc.org/k8s.io/api/core/v1#ContainerStatus
