### ISSUE TITLE
workqueue.ParallelizeUntil: Do we need to add some timeout to doWorkPiece

### ISSUE THREAD

**Issue by FingerLiu** [kubernetes/client-go#768]
https://github.com/kubernetes/client-go/blob/master/util/workqueue/parallelizer.go#L30

Since ParallelizeUntil is a common util widely used to parallelizing N jobs to speed up the how things. If one of the workPieces spend very long time to finish, it will slow down the whole process（since we do wg.wait).
For better performance, do we need to support a way to let user set timeout for executing each piece of work?

**Comment by liggitt** [comment]
All the places parallelizeuntil is used currently, the worker function passed in is a closure that has access to the same context passed to ParallelizeUntil. That context's stop channel can already be used internally by the worker function to stop work when the deadline expires.
