### ISSUE TITLE
Clientset how to support both CRD and built-in resources

### ISSUE THREAD

**Issue by pytimer** [kubernetes/client-go#774]
Hi, i use `client-go` to get some resources in Kubernetes, these include CRD and built-in resources, such as: Pod, Namespace. 

I use `code-generator`  to create CRD client but `crdclientset.NewForConfig(kubeconfig)` only have my crd resource, no built-in resources.

If i want to get built-in resources, i need to use `kubernetes.NewForConfig`, How can i create client that can query both a CRD resource and the built-in resources.

**Comment by yyf1986** [comment]
你是如何定义crd的clientset的啊？

**Comment by thehackercat** [comment]
Have the same issue, any update on this?

**Comment by sttts** [comment]
Use two clients.
