### ISSUE TITLE
why not fix bug in rest/request.go of v11.0.0

### ISSUE THREAD

**Issue by KielChan** [kubernetes/client-go#775]
it's output may like this:
```
k8s.io/client-go/rest
# k8s.io/client-go/rest
../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

even though it has been fixed in v12.0.0

**Comment by liggitt** [comment]
`k8s.io/client-go` requires building against `k8s.io/apimachinery@kubernetes-1.14` and `k8s.io/api@kubernetes-1.14` tags, not master.

**Comment by KielChan** [comment]
emm, the error came from the command `go mod tidy` output in my own project which used client-go.
