### ISSUE TITLE
Check Whether API Group of a Specific Version Exists on a Server

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/client-go#778]
I am looking for a way using client-go to check whether an API group with a specific version exists on a cluster. It appears [`ServerGroups()`](https://github.com/kubernetes/client-go/blob/1ae532aad6ad8b3a4e4ee51cb6756e5af8b5cfd6/discovery/discovery_client.go#L156) can be used to pull back information about all API Groups present on the cluster, but there doesn't seem to be a clear way to request a specific API group/APIVersion combination. I am wondering if there is a recommended approach for this, or whether this could added to discovery client?

/kind feature

**Comment by liggitt** [comment]
ServerResourcesForGroupVersion will check a specific group/version or return a NotFound error
