### ISSUE TITLE
Can I use client-go on for k3s?

### ISSUE THREAD

**Issue by dmxj** [kubernetes/client-go#780]
I want use this sdk for k3s, is this ok?

**Comment by yyf1986** [comment]
可以，我在用

**Comment by nikhita** [comment]
@dmxj If you have further questions about using client-go with k3s, please open an issue directly in the k3s repo since they'd be able to help with this better. :)

Closing.

**Comment by Ruzung** [comment]
> 可以，我在用

我这边用链接k8s直接报“nodes is forbidden: User "system:serviceaccount:default:default" cannot list resource "nodes" in API group "" at the cluster scope”， 你那边是怎么初始化客户端的
