### ISSUE TITLE
Namespace for events whose involvedObject is cluster-scoped

### ISSUE THREAD

**Issue by xinlaini** [kubernetes/client-go#781]
Hello,
We have a CRD that's cluster-scoped, in its controller, we are trying to create relevant events related to this CR. Since Event itself is namespace-scoped, we have to set the namespace for the event when posting the create request. We have tried 3 options:
1. setting event' namespace to our CRD controller's namespace (app-specific): this seems to be the most reasonable option, however, its rejected by the server due to "[involved object's namespace does not match event.namespace](https://github.com/kubernetes/kubernetes/blob/a7f43a72032028b7e92acd70a3de1d6e6bc19cbe/pkg/apis/core/validation/events.go#L45)": 

2. setting event's namespace to "", this arguably makes sense since our CRD is cluster-scope, and one could argue posting its related events against "" namespace is reasonable. However, this was rejected by the [client-go request preflight validation](https://github.com/kubernetes/client-go/blob/386829fa6bc569efceb8edb8c562552c987c4304/rest/request.go#L799)

3. setting event's namespace to "default", this works, however we feel uncomfortable because this doesn't seem to be as clean as 1 or 2.
thoughts?
Thanks!

**Comment by luebken** [comment]
Can we re-open this? 

I'm happy to answer questions from a Crossplane perspective. My use-case is I would like to filter events of a  Crossplane ManagedResource which happens to be cluster-scoped.
