### ISSUE TITLE
version of k8s.io/apimachinery conflicts

### ISSUE THREAD

**Issue by beimx** [kubernetes/client-go#789]
1. Imports client-go in to my project by Go Module
2. go build my project
3. Actcual results:
    3.1 default the version is v11.0.0+incompatible
    3.2 default the version is v0.18.2
    3.3 compition failed:
   ../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/clientcmd/api/v1/conversion.go:29:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
   ../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher

4. My personal guess:
   Because of the lack of file 'go-mod' in the package 'client-go', go module always download the latest version of package 'k8s.io/apimachinery'

**Comment by myonlyzzy** [comment]
cd {yourgopath}/pkg/mod/k8s.io/
`sudo rm -rf ./apimachinery@* `
`sudo rm -rf ./api@*`
go mod tidy

**Comment by RexG** [comment]
`go get k8s.io/client-go@kubernetes-1.16.3 (replace kubernetes-1.16.3 with the desired version)`
after that you may also need to try what myonlyzzy mentioned above, because package management in golang sucks

**Comment by hoang-tranviet** [comment]
I have try both your solutions (@RexG and @myonlyzzy) together, but the problem still persists.
FYI, I anchor the client-go version to `k8s.io/client-go@kubernetes-1.15.11`.

**Comment by lolin9** [comment]
@RexG package management isn't the only thing that sucks in this language. It's hard to find anything in it that doesn't suck for any serious project.

**Comment by StevenPG** [comment]
I'm struggling to disagree with you @lolin9. I've been trying to resolve a dependency issue for the last 4 hours... This is insane, I'm surprised there hasn't been a better solution. I feel like you have to have a different GOPATH for every project.

**Comment by liggitt** [comment]
The recommendation for all supported versions of go is to define a go.mod for your project that requires matching versions of k8s.io/{api,apimachinery,client-go}, for example, to use library versions corresponding to Kubernetes v1.18.2:

```
module example.com/mymodule

require (
  k8s.io/api v0.18.2
  k8s.io/apimachinery v0.18.2
  k8s.io/client-go v0.18.2
)
```

More details can be found at https://github.com/kubernetes/client-go/blob/master/INSTALL.md
