### ISSUE TITLE
Update the Godeps version for cloud.google.com/go and github.com/davecgh/go-spew

### ISSUE THREAD

**Issue by ruiyang2015** [kubernetes/client-go#79]
We have a Go project using glide to manage the dependency package, k8s.io/client-go reference some quite old version of cloud.google.com/go and github.com/davecgh/go-spew, and we have another lib package reference the latest one, doing a glide up cause a lot of un-related error and we have to pin a very specify sha of k8s.io/client-go to work around this issue, ideally, we want to use the latest release version, and hope this can be resolved. 
Even better if you could use glide to replace godeps for manage the package, so you can specify a range of supported dependent lib.

**Comment by lavalamp** [comment]
I hope to get the client to start using https://github.com/golang/dep for
dep management in the coming few weeks. Please take a look at that and see
if you think it will be better or worse that the current state?

**Comment by ruiyang2015** [comment]
dep is still in Pre-alpha mode, it is harder for us to switch to this system while glide works most of the time for us. and glide is already doing the flatting of the dependency for us.

**Comment by ericchiang** [comment]
@ruiyang2015 you can also open a PR to the main kubernetes repo to update the version. If the APIs haven't changed then that might be an easy solution in the short term.

**Comment by ericchiang** [comment]
@ruiyang2015 https://github.com/kubernetes/kubernetes/pull/41532 removes the cloud.google.com/go dependency. 

This was the one use of spew I found in client-go currently. Maybe we can replace it with some stdlib code? https://github.com/kubernetes/client-go/blob/8b466d64c5da37e0d3985b907d812e1f58cb41cb/pkg/api/helpers.go#L46

**Comment by caesarxuchao** [comment]
@ruiyang2015 @ericchiang will this work: we keep a glide.yaml along with the Godeps.json in client-go, and specify a range of versions for those two dependencies in question (and others).

**Comment by ericchiang** [comment]
@caesarxuchao I think if you create a glide.yaml with an explicit version of a package it will override whatever Kubernetes wants.

```yaml
package: ( your package's import path )
import:
- package: k8s.io/client-go
  version: v2.0.0
# Use a newer version of go-spew even though client-go wants an old one.
- package: github.com/davecgh/go-spew
  version: v1.1.0
```

You'll even get the following warning explaining what's going on:

```
[WARN]	Conflict: github.com/davecgh/go-spew rev is currently v1.1.0, but k8s.io/client-go wants 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d
```

Maybe that's a lower overhead fix? The real question is if client-go supports newer versions of go-spew.

**Comment by ericchiang** [comment]
@caesarxuchao and I mean "If a client-go user creates a glide.yaml file..."

**Comment by ffledgling** [comment]
Hello, bumping this thread, ran into the same problem with spew being overridden by the older version that kubernetes client uses. Any idea of what's required to bump the version of spew in the client-go code base? Seems like the one usage pointed out is pretty simple, and as @ericchiang pointed out can either be replaced by some stdlib code, or can be kept the same, since it will work even under newer versions of spew.

**Comment by ash2k** [comment]
I sent a PR to update spew and testify dependencies just yesterday. I hope it'll get some attention and not drown like other PRs https://github.com/kubernetes/kubernetes/pull/48384

**Comment by ffledgling** [comment]
It'd still be really nice to have this, but looks like it got drowned in the noise. :/

**Comment by sttts** [comment]
kubernetes/kubernetes#48384 is merged.

For what do we need cloud.google.com/go ?
