### ISSUE TITLE
Fake client doesn't limit results

### ISSUE THREAD

**Issue by sagikazarmark** [kubernetes/client-go#793]
As the title says, the fake client ignores the `Limit` parameter in a list operation:

```go
package fake_test

import (
	"context"
	"testing"

	"k8s.io/api/core/v1"
	metaV1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func TestPodLimit(t *testing.T) {
	client := fake.NewSimpleClientset(
		&v1.Pod{
			TypeMeta: metaV1.TypeMeta{Kind: "Pod", APIVersion: "v1"},
			ObjectMeta: metaV1.ObjectMeta{
				Name:      "my-pod-1",
				Namespace: "default",
			},
		},
		&v1.Pod{
			TypeMeta: metaV1.TypeMeta{Kind: "Pod", APIVersion: "v1"},
			ObjectMeta: metaV1.ObjectMeta{
				Name:      "my-pod-2",
				Namespace: "default",
			},
		},
	)

	podList, _ := client.CoreV1().Pods("default").List(context.Background(), metaV1.ListOptions{Limit: 1})
	if len(podList.Items) > 1 {
		t.Errorf("expected one items in podList, got %d", len(podList.Items))
	}
}
```

Feels like it would be a trivial thing to implement, since slices are ordered in Go it would probably even be consistent enough so that tests could safely rely on the behavior.

**Comment by liggitt** [comment]
I'd tend to put this on this list of server-side behaviors that are not replicated by the client fake

**Comment by sagikazarmark** [comment]
Why? sounds like a trivial thing to me.

**Comment by liggitt** [comment]
generating `continue` tokens and serving coherent sublists for a given `resourceVersion` is a fundamental part of returning paged lists. Simply returning a partial list without doing those other things (which the resource tracker doesn't have the info to do) is worse than returning a full list (which is permitted by the API definition and which clients must be prepared to handle)

**Comment by sagikazarmark** [comment]
Thanks for the explanation, makes sense.

**Comment by mbobrovskyi** [comment]
What if we add `Limit` and `Continue` to `ListRestrictions` [here](https://github.com/kubernetes/client-go/blob/master/testing/actions.go#L354)? It will allow us to manually filtering list using `Reactor`.
