### ISSUE TITLE
How to get nodes based on label fields.

### ISSUE THREAD

**Issue by collbrain** [kubernetes/client-go#795]
Hello...

I have configured few nodes with label key=test. Would like to use go client to list only nodes having those label. Tried following, does not seem to work

nodes, _ := cs.CoreV1().Nodes().List(metav1.ListOptions{
                    LabelSelector: "key=test",
                    })

**Comment by liggitt** [comment]
that's the proper syntax... your code is ignoring the returned error... try checking that to see if you have a connection or permission issue

**Comment by collbrain** [comment]
Thanks it worked. Yes it was connection issue
