### ISSUE TITLE
DirectClientConfig.ConfirmUsable does not check config.overrides for context

### ISSUE THREAD

**Issue by wfernandes** [kubernetes/client-go#797]
This is my use case
```golang
configOverrides := &clientcmd.ConfigOverrides{
  CurrentContext: "some-context-that-exists",
}
// config.contextName = "does-not-exist" 
// config.CurrentContext = "does-not-exist"
restConfig, err := clientcmd.NewDefaultClientConfig(*config, configOverrides).ClientConfig()
// I get an error from ConfirmUsable()
```
I noticed that `ClientConfig` calls `config.ConfirmUsable`
https://github.com/kubernetes/client-go/blob/06f6a9f8889fe4d18c469bf9f59a5a20e8d03ad1/tools/clientcmd/client_config.go#L147-L149

And inside `ConfirmUsable` it does a series of checks. However, for the contexts, instead of calling `getContext` or `getContextName` it does its own context check but fails to include `config.overrides.CurrentContext`.

https://github.com/kubernetes/client-go/blob/06f6a9f8889fe4d18c469bf9f59a5a20e8d03ad1/tools/clientcmd/client_config.go#L342-L357

My suggestion is at the very least call `config.getContextName` to get the context name and then check if it is in `config.config.Contexts`.

https://github.com/kubernetes/client-go/blob/06f6a9f8889fe4d18c469bf9f59a5a20e8d03ad1/tools/clientcmd/client_config.go#L375-L384

If y'all think this is a bug,  I'm happy to create a PR.

**Comment by wfernandes** [comment]
The main point that I'm testing is that,
I have a kubeconfig file with a contexts (contextA, contextB...). **However** the `currentContext` in that file is pointing to something that doesn't exist.
Now if I specify and override for `CurrentContext=contextA`, I'd expect to get the client config for `contextA`.

**Comment by JCzz** [comment]
I have an issue in line 404:

`_, exists := config.config.Contexts[contextName]`

exists is false, when running in test - but works in go run?
