### ISSUE TITLE
Compile time?

### ISSUE THREAD

**Issue by Tigraine** [kubernetes/client-go#80]
Hi guys, thanks for `client-go` library - i am just wondering if there is something to do to get the compile time down?

If I run the standard [out-of-cluster example](https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster/main.go) I get stats like these on a not too old Macbook Pro (late 2012 MBP Retina). (Go 1.7.5)

```
go build  88,71s user 8,39s system 223% cpu 43,515 total
```

Is this common? I am pretty new to go and wanted to write a few utilities to monitor our K8s cluster and this is just not working out with having to wait 40+ seconds for a compile error :(

**Comment by Tigraine** [comment]
Silly me - doing a `go install` reduced the compilation time by 10x down to:
```
go build  3,62s user 0,79s system 94% cpu 4,654 total
```

**Comment by hongchaodeng** [comment]
Do you know why it's faster?
