### ISSUE TITLE
How to get node‘s Role with client-go?

### ISSUE THREAD

**Issue by kqzh** [kubernetes/client-go#800]

**Comment by gkarthiks** [comment]
/assign

Node's role are determined by the labels attached to it with the boolean values. For example if the label k:v pair `node-role.kubernetes.io/compute: true` is attached to node, then it is a worker node. For master `node-role.kubernetes.io/master: true`. 

So you can get the node's labelMap by getting the node and then iterate over the map to get the role label to determine the role of the node.

```go
clientset.CoreV1().Nodes().Get(context.Background(), "devckua005.dev.blackrock.com", metav1.GetOptions{})
```

Note: the role label differs with different distro of kubernetes.

**Comment by kqzh** [comment]
> /assign
> 
> Node's role are determined by the labels attached to it with the boolean values. For example if the label k:v pair `node-role.kubernetes.io/compute: true` is attached to node, then it is a worker node. For master `node-role.kubernetes.io/master: true`.
> 
> So you can get the node's labelMap by getting the node and then iterate over the map to get the role label to determine the role of the node.
> 
> ```go
> clientset.CoreV1().Nodes().Get(context.Background(), "devckua005.dev.blackrock.com", metav1.GetOptions{})
> ```
> 
> Note: the role label differs with different distro of kubernetes.

Thank you for your advice！ It's the same as my solution.

**Comment by caihy05** [comment]
get获取信息labels似乎未nil
