### ISSUE TITLE
RFE: pass GVK to tweakListOptions in Informers

### ISSUE THREAD

**Issue by squeed** [kubernetes/client-go#801]
## The problem:
Providing a TweakListOptions function to a SharedInformerFactory is awkward, because the options are applied to *all resources*. Constructing a single S-I-F with per-resource filters is not currently possible.

### Background:
Sometimes it makes sense for the shared ("global") informer to be filtered. For example, the kubelet only watches pods assigned to its node. Kube-proxy only watches for Services and Endpoints that don't have a magic "headless" label. 

However, this is awkward to express with the current SharedInformerFactory. It takes a single TweakListOptions, a function manipulating ListOptions at List time, which receives no information about the listed type. Thus, the tweak function must, by nature, apply to all resources. This makes adding FieldSelectors particularly awkward. The kube-proxy filtering relies on some label-selectors that, by luck, is a no-op for unrelated resources . This is... fragile.

It would be useful to be able to construct a SharedInformerFactory that allows for per-resource tweaking.

### Proposal
Add a new `SharedInformerOption`, `WithTypedTweakListOptions`, that allows the end-user to specify a new, per-resource TweakListOptions function.

/cc @sttts

**Comment by squeed** [comment]
This is definitely still relevant; we could really use this for several projects of mine. Should I try and write an implementation? It will require a bump to informer-gen...

**Comment by mjsmith1028** [comment]
👋  Hi, I find this feature useful as well. Are there any plans to add this in the future? I am mostly concerned with reducing the memory footprint when I am in heavily used clusters. Thanks!

**Comment by mjsmith1028** [comment]
nevermind, think I found it https://github.com/kubernetes/client-go/blob/master/informers/factory.go#L58 👍
