### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by shanchenggang** [kubernetes/client-go#802]
import cycle not allowed
package main
	imports k8s.io/client-go/kubernetes
	imports k8s.io/client-go/discovery
	imports k8s.io/client-go/rest
	imports k8s.io/client-go/plugin/pkg/client/auth/exec
	imports k8s.io/client-go/transport
	imports golang.org/x/oauth2
	imports golang.org/x/oauth2
When I was debugging my project, there were some errors like the one above.

**Comment by sttts** [comment]
The cycle is in oauth2, not here, isn't it?

**Comment by shanchenggang** [comment]
The problem has been solved. I got the wrong version. Thank you

**Comment by shanchenggang** [comment]
yes,it is.thank you. Client-go version problem,  I have solved this problem.
















At 2020-05-20 19:31:20, "Dr. Stefan Schimanski" <notifications@github.com> wrote:

The cycle is in oauth2, not here, isn't it?
