### ISSUE TITLE
ExecProvider warning in long running programs

### ISSUE THREAD

**Issue by bonifaido** [kubernetes/client-go#803]
We have a long-running application which constructs many Kubernetes clients for the same cluster based on events and API calls. For EKS clusters (for which the client uses the aws-iam-authenticator) we started to see the following warning message in the logs quite often (and soon for the same cluster):

```
W0521 15:54:02.768947   53957 exec.go:203] constructing many client instances from the
same exec auth config can cause performance problems during cert rotation and can exhaust
available network connections; 1230 clients constructed calling "aws-iam-authenticator"
```

I have checked the code and found that the Authenticator object is cached per cluster configuration for later usage, so if we construct a client again for the same cluster (with `NewForConfig`) the `Authenticator.UpdateTransportConfig` is getting called again which puts 40 elements on the `onRotateList` of the cached authenticator object because `UpdateTransportConfig` is called for each K8S API sub-client. This list has a threshold for warnings: `const onRotateListWarningLength = 1000`, which gets hit quite soon because constructing 25 clients for the same cluster (takes a few hours for us) and the warning appears and never goes away.

I wonder if this cache could be turned-off for long-running applications, or some call could be added to close a client after work is done with it and remove the underlying dialer closers of those clients from the aforementioned list.

Anyhow, I think this check is not quite correct, because it should check all authenticator objects globally in memory not just the actual one running.

**Comment by liggitt** [comment]
Without the cache, repeatedly constructing clients produces multiple identically configured http.Transport objects, each of which each keep their own pool of kept-alive network connections to target servers. The cache is needed to prevent network connection exhaustion.

**Comment by bonifaido** [comment]
I'm totally happy with the cache, except that in long-running applications it might cause a memory leak since there is no way to get off it, and for unused cluster configurations the authenticator object remains in memory forever (but no big deal, these are fairly small objects).

My misunderstanding may come from that I'm not sure how to use the Client in long-running applications. Since there is no Close method on the Client we should probably cache and reuse them?

According to my tests, clients are building up a single network connection/cluster with a default 30 seconds of keep-alive. If the client is thrown away, the network connection will be idle and closed automatically. In this case, I think the dialer callback should be removed from the `onRotateList`.
