### ISSUE TITLE
Boolean in config-map data string are getting removed

### ISSUE THREAD

**Issue by bappr** [kubernetes/client-go#805]
Hey guys,

weird weird weird issue.

Works with `kubectl`, does not work with the `go-client`.
I am using `0.18.0`.

Basically, consider something like (with `block` value being actually bigger)

```
apiVersion: v1
data:
  block: '{"isPublicURL":true}'
kind: ConfigMap
metadata:
...
```

Using the `go-client`, the `ConfigMap().Create()` is gonna remove the `isPublicURL`.

Even weirder, I tried to track down the issue with the debugger. Everything looked fine.
And actually the end result was fine too.

So worked with the debugger, does not work with a normal run...

I can provide more information if needed but maybe a video of that would me more meaningful. LMK.

**Comment by liggitt** [comment]
do you have the full code snippet? the data value is a string, so client-go isn't expected to interact with that content at all

**Comment by bappr** [comment]
Hey @liggitt 
I tried my best to repro with a small snippet of code but without success.
I am closing this issue for now and will open a new one when I finally manage to get something testable. It just feels weird.
