### ISSUE TITLE
Get Logs implementation in fake_pod_expansion.go returns empty request

### ISSUE THREAD

**Issue by harjas27** [kubernetes/client-go#806]
I am trying to use the fake client to test some code where I get logs for a container. My code is :

`req := k8sClient.CoreV1().Pods(podNamespace).GetLogs(podName, &opts)`

`containerLogs, err := req.Stream()`

But when I stream the request, the program panics because of a nil `backoffMgr` in the request returned.

**Comment by FrelDX** [comment]
![image](https://user-images.githubusercontent.com/32826879/83704079-b3ee9b00-a643-11ea-8ba1-cdb967966e9a.png)

**Comment by FrelDX** [comment]
Connect pod through SSH protocol  https://github.com/FrelDX/kube-console-on-ssh

**Comment by knight42** [comment]
this issue should be addressed by https://github.com/kubernetes/kubernetes/pull/91485, feel free to reopen it if you have any other problems.

/close
