### ISSUE TITLE
github.com/googleapis/gnostic/OpenAPIv2 import error

### ISSUE THREAD

**Issue by tivonheng** [kubernetes/client-go#808]
../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2

**Comment by liggitt** [comment]
Thanks for the report. This is a duplicate of https://github.com/kubernetes/client-go/issues/741#issuecomment-606883355
