### ISSUE TITLE
command terminated with exit code 127

### ISSUE THREAD

**Issue by FrelDX** [kubernetes/client-go#810]
I use the client to implement a pty shell through API and k8s interaction, but if I use / bin / sh to enter the container, and then use exit to exit the shell, I will report an error command terminated with exit code 127 and then exit. Even if I handle it, the exit information is the same. I don't want my program to exit. I just want to exit the container and use / bin / bash to enter the container. Everything is OK

**Comment by FrelDX** [comment]
![image](https://user-images.githubusercontent.com/32826879/83610599-49414f00-a5b2-11ea-82a0-2a582384a9c7.png)

**Comment by FrelDX** [comment]
func Remotepty(client kubernetes.Interface, config *restclient.Config, namespace string,podName string,
	command string,container string, stdin io.Reader, stdout io.Writer, stderr io.Writer) error {
	cmd := []string{
		command,
	}
	req := client.CoreV1().RESTClient().Post().Resource("pods").Name(podName).
		Namespace(namespace).SubResource("exec").Param("container",container)
	option := &v1.PodExecOptions{
		Container: container,
		Command: cmd,
		Stdin:   true,
		Stdout:  true,
		Stderr:  true,
		TTY:     true,
	}
	if stdin == nil {
		option.Stdin = false
	}
	req.VersionedParams(
		option,
		scheme.ParameterCodec,
	)
	exec, err := remotecommand.NewSPDYExecutor(config, "POST", req.URL())
	if err != nil {
		return err
	}
	err = exec.Stream(remotecommand.StreamOptions{
		Stdin:  stdin,
		Stdout: stdout,
		Stderr: stderr,
	})
	if err != nil {
		return err
	}
	return nil
}

**Comment by 871690991** [comment]
Me too. Take a look at my code
https://github.com/kubernetes/client-go/issues/809

**Comment by 871690991** [comment]
Are you Chinese? Can you share your code

**Comment by 871690991** [comment]
大佬求分享下你的代码我也在搞这个通过k8s api 实现tty

**Comment by FrelDX** [comment]
是的可以的

**Comment by FrelDX** [comment]
@871690991 你可以看下我仓库里面的一个项目，https://github.com/FrelDX/kube-console-on-ssh，一个通过ssh协议登录到容器中的tty，如果你是想通过websocket的话，下一个版本支持，觉得好用的话，给点个星哈哈哈哈哈哈

**Comment by FrelDX** [comment]
![image](https://user-images.githubusercontent.com/32826879/83703805-0da29580-a643-11ea-8635-d12bb4ec3127.png)

**Comment by 871690991** [comment]
大佬你这个是需要再K8S pod中安装ssh服务？

**Comment by FrelDX** [comment]
不需要的

**Comment by FrelDX** [comment]
我的程序实现了一个ssh的服务端，通过调用 k8s的api实现了tty

**Comment by 871690991** [comment]
多谢 大佬我试试看

**Comment by 871690991** [comment]
> 我的程序实现了一个ssh的服务端，通过调用 k8s的api实现了tty

发现你这个有bug 使用less窗口大小有问题 用pgup和pgdown按键就有问题了
