### ISSUE TITLE
Question: Will fake client ever honor DryRun option? 

### ISSUE THREAD

**Issue by zbindenren** [kubernetes/client-go#811]
Currently fake client does not honor `DryRun` option. If I run:

```go
_, err := cli.CoreV1().Namespaces().Create(context.Background(), ns, metav1.CreateOptions{
    DryRun: []string{metav1.DryRunAll},
})
```

the namespace gets created. Will this option ever respected in future?

**Comment by dr-shim** [comment]
I'm suffering the same issue. Any update on this?
