### ISSUE TITLE
How to use client-go to create a pod with GPU support

### ISSUE THREAD

**Issue by InfluencerNGZK** [kubernetes/client-go#812]
In kubernetes 1.10, I can use ResourceName"alpha.kubernetes.io/nvidia-gpu" to enable GPU support when creating a pod using client-go.
But in recent versions, as the picture shown below, the source code k8s.io\api@kubernetes-1.14.0\core\v1\types.go does not have resourceNVIDIAGPU.
![image](https://user-images.githubusercontent.com/54970620/84216876-49cf6d80-aafd-11ea-85a0-a92df091db3b.png)
I found a changelog in the repo as shown below, but seems that the ResourceName shown above does not contain "nvidia.com/gpu", so how can I enable GPU support in a pod created by client-go instead of using yaml files.
![image](https://user-images.githubusercontent.com/54970620/84217262-425c9400-aafe-11ea-84d7-d90978946e61.png)

**Comment by marload** [comment]
@InfluencerNGZK 
How do you resolve this issue?
also I want to this feature.

**Comment by InfluencerNGZK** [comment]
You can specify `gpuNum` yourself
```sh
import (
	apiv1 "k8s.io/api/core/v1"
)

Resources: apiv1.ResourceRequirements{
	Limits: apiv1.ResourceList{
		"nvidia.com/gpu": resource.MustParse(gpuNum),
	},
},
```

**Comment by marload** [comment]
You save me.
Thanks :smile:

**Comment by InfluencerNGZK** [comment]
Glad to hear : )
