### ISSUE TITLE
Azure AD plugin for client auth adding spn: prefix to apiserver-id indefinelty when unauthorized

### ISSUE THREAD

**Issue by softlion** [kubernetes/client-go#814]
I'm using kubectl Windows version v1.18.0 with the Azure AD plugin for client authentication.
The first time it works fine.

After 1 or 2 hours or inactivity, it fails. Remark the spn:spn:spn:spn string.
```
E0611 15:21:07.898016   28816 azure.go:154] Failed to acquire a token: refreshing the expired token: refreshing token: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named spn:spn:spn:spn:spn:spn:spn:35XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX was not found in the tenant named XXXX. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\n .... "error_uri":"https://login.microsoftonline.com/error?code=500011"}
```

Following google recommendations, i deleted access-token and refresh-token in the kube's config file. I also removed all the spn: prefixes that were present on the apiserver-id line.
```
apiserver-id: spn:spn:spn:spn:spn:spn:spn:35XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
```
to
```
apiserver-id: 35XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
```

After succesfully relogin to azure, the connection to the cluster still fails. But this is not the problem here. Each time the following command is issued and fails, the kube's config file is modified:
```
PS C:\> kubectl get pods
error: You must be logged in to the server (Unauthorized)
```
modified kube's config file:
```
apiserver-id: spn:35XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
```
After a second fail:
```
apiserver-id: spn:spn:35XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
```
etc...

So i suppose this is the issue everyone is reporting since 2 years. Each time the command fails, it adds the spn: prefix to the apiserver-id.
Note that config-mode is set to 0. Setting it to 1 (or removing the line) triggers the issue.

Client version info:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
```

**Comment by liggitt** [comment]
This was fixed in 1.18.1 in https://github.com/kubernetes/kubernetes/pull/89783
