### ISSUE TITLE
CoreV1().Pods.List and pod.Status.Phase == apiv1.PodRunning is not a good way to test if pods are Running

### ISSUE THREAD

**Issue by BrunoMCBraga** [kubernetes/client-go#815]
Hello guys

What is my k8s client-go version? Latest but this is my go.sum:

k8s.io/client-go v0.0.0-20200307122516-5194bac86967 
k8s.io/client-go v0.0.0-20200307122516-5194bac86967/go.mod 
k8s.io/client-go v0.17.0 
k8s.io/client-go v0.17.0/go.mod 
k8s.io/client-go v11.0.0+incompatible 
k8s.io/client-go v11.0.0+incompatible/go.mod

I am using this library to deploy Docker containers on Amazon and after the deployment is done, i check the status of the pods with: pod.Status.Phase == apiv1.PodRunning.

However, looking at all the possible states (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/), it seems none is good enough to test the pod is healthy and running. Running only means the Container has been started or is starting but i noticed that sometimes the check succeeds but then the pod is stuck on CrashLoopBackOff.

Any ideas on how to wait for all the containers to be in a Running state? Succeeded does not work for me because i expect the container to keep running.

Best regards and thank you

PS: Let me know if you need more information regarding versions. I assume the problem is generic enough.

**Comment by BrunoMCBraga** [comment]
BUMP

**Comment by avtarOPS** [comment]
Yeah had to see the Status from Condition in PodStatus struct. IsPodReady function is also there which can be used https://godoc.org/k8s.io/kubernetes/pkg/api/v1/pod didn't use it though.
