### ISSUE TITLE
Additional examples

### ISSUE THREAD

**Issue by manuel-lang** [kubernetes/client-go#817]
I spent quite some time creating different resources from a huge yaml configuration. Some more examples would definitely have been useful and might have saved a lot of time. Thus, I was curious if you were looking for contributions in the examples section or are intending to extend them in general.

**Comment by nikhita** [comment]
@manuel-lang Yes please, contributions for expanding examples are welcome! :smile: 

To ensure that your change gets accepted, I'd suggest asking for initial feedback on the example you intend on adding in the #sig-api-machinery channel on slack first.

**Comment by manuel-lang** [comment]
Awesome, thank you @nikhita, will do that!

**Comment by nikhita** [comment]
@manuel-lang :tada: 

Do you think this issue can be closed? We can open new issues for specific examples later. :+1:
