### ISSUE TITLE
PodLogs Streaming Updates

### ISSUE THREAD

**Issue by kipply** [kubernetes/client-go#820]
With the following, I can get a working Stream object; 
```
		req := o.Cluster.KubeClient.PodClient.GetLogs(pod.Name, &core.PodLogOptions{})
		podLogs, err := req.Stream()
```
and to output I use (below), which works only for the logs that were captured at the first line above. Newer logs are not captured in the stream. 
```
		for {
			buf := make([]byte, 100)

			numBytes, err := podLogs.Read(buf)
			if numBytes == 0 {
				continue
			}
			if err == io.EOF {
				break
			}
			if err != nil {
				return errors.Wrap(err, "error in copy information from podLogs to buf")
			}

			logStr := string(buf[:numBytes])
		}
```

This seems like it might be expected behaviour, though I'm trying to find a way to stream logs through the API and `GetLogs` doesn't seem to provide me a way of doing that.

**Comment by liggitt** [comment]
Set `PodLogOptions{Follow: true}`

**Comment by kipply** [comment]
woops, thanks~

**Comment by Ruudieboy** [comment]
I followed your example and it works great for the first 10 seconds. After 10 seconds no new data is received. `podlogs.reqDidTimeout()` returns true at that point. If tried modifying the timeout but that doesn't seem to change anything. Am I missing something?

**Comment by adamwoolhether** [comment]
> With the following, I can get a working Stream object;
> 
> ```
> 		req := o.Cluster.KubeClient.PodClient.GetLogs(pod.Name, &core.PodLogOptions{})
> 		podLogs, err := req.Stream()
> ```
> 
> and to output I use (below), which works only for the logs that were captured at the first line above. Newer logs are not captured in the stream.
> 
> ```
> 		for {
> 			buf := make([]byte, 100)
> 
> 			numBytes, err := podLogs.Read(buf)
> 			if numBytes == 0 {
> 				continue
> 			}
> 			if err == io.EOF {
> 				break
> 			}
> 			if err != nil {
> 				return errors.Wrap(err, "error in copy information from podLogs to buf")
> 			}
> 
> 			logStr := string(buf[:numBytes])
> 		}
> ```
> 
> This seems like it might be expected behaviour, though I'm trying to find a way to stream logs through the API and `GetLogs` doesn't seem to provide me a way of doing that.

Sorry to bring up an old issue, just curious why you'd want to continue if `numBytes == 0`? Shouldn't this case also be `break`? If not, how would you gracefully end the for loop? The logs don't output an EOF to the stream if the pod finished running.
