### ISSUE TITLE
Unable to find docs.

### ISSUE THREAD

**Issue by deepak1725** [kubernetes/client-go#823]
Can you please Point me to API docs.

**Comment by jeevanshu** [comment]
You might find this to be helpful
https://pkg.go.dev/k8s.io/client-go/kubernetes?tab=doc

**Comment by deepak1725** [comment]
@jeevanshu  Thanks for Reply.
1 Question: Deployment is of type` *appsv1.Deployment` and Volumes are of type `*corev1.PersistentVolume`

How is New User able to figure this out..?

Sorry, if I am missing out something.

**Comment by jeevanshu** [comment]
@deepak1725 All the API endpoints used in Kubernetes are documented here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/. 
So you can find out the group and version for each of the objects
