### ISSUE TITLE
logr.InfoLogger does not implement logr.Logger (missing Error method)

### ISSUE THREAD

**Issue by yzhao66** [kubernetes/client-go#824]
![image](https://user-images.githubusercontent.com/44268973/85943442-bef6cb80-b962-11ea-9158-03d8eaf74dbf.png)

![image](https://user-images.githubusercontent.com/44268973/85943470-dcc43080-b962-11ea-96b6-7a27a4c15c74.png)

when  i use  kubernetes NewForConfig method to create clientset ,the console report is as below.

**Comment by vasartori** [comment]
I caught this error too
Found an entry on go.mod, in `replace` section:
```
	github.com/go-logr/logr => github.com/go-logr/logr v0.1.0	
```

Just remove...
