### ISSUE TITLE
Create resources from raw yaml files.

### ISSUE THREAD

**Issue by eugenetaranov** [kubernetes/client-go#825]
Hello,

I am working on a tool that creates k8s resources and I would like to avoid hard coding resource definitions into the source like here https://github.com/kubernetes/client-go/blob/master/examples/create-update-delete-deployment/main.go#L66

Please advise if it is possible to create resources from plain yaml instead of constructing objects?

Thanks!

**Comment by LoveXiaoLiu** [comment]
I need this feature, too. Is there a way now？

**Comment by loveyacper** [comment]
> Hello,
> 
> I am working on a tool that creates k8s resources and I would like to avoid hard coding resource definitions into the source like here https://github.com/kubernetes/client-go/blob/master/examples/create-update-delete-deployment/main.go#L66
> 
> Please advise if it is possible to create resources from plain yaml instead of constructing objects?
> 
> Thanks!

Build the k8s resources objects from yaml file, use gopkg.in/yaml.v2 package.

**Comment by jspruance** [comment]
> Hello,
> 
> I am working on a tool that creates k8s resources and I would like to avoid hard coding resource definitions into the source like here https://github.com/kubernetes/client-go/blob/master/examples/create-update-delete-deployment/main.go#L66
> 
> Please advise if it is possible to create resources from plain yaml instead of constructing objects?
> 
> Thanks!

I need to do this as well. Is there any standard approach to doing a client-go deployment from a yaml file?

**Comment by melnikalex** [comment]
Same
