### ISSUE TITLE
Namespace passed in place of subresource (and vice versa) to method call NewUpdateSubresourceAction in fakeNamespacedScaleClient.Update 

### ISSUE THREAD

**Issue by diwanc** [kubernetes/client-go#830]
Came across this bug in scale/fake/client.go. `f.namespace` and `"scale"` i.e 2nd and 3rd arg values to the method call `testing.NewUpdateSubresourceAction` are in inverted order.  `"scale"` should have been 2nd arg and `f.namespace` should have been 3rd.

https://github.com/kubernetes/client-go/blob/1e6150831a960cf38075bb8561e01f48837f8d74/scale/fake/client.go#L63

**Comment by DirectXMan12** [comment]
This is why structs or something type-safe is good when you have a bunch of arguments like this ;-).  Good catch.

**Comment by diwanc** [comment]
I see this is fixed in this commit https://github.com/kubernetes/kubernetes/commit/34a446d812c423da7a306963f250f4002dac9be8#diff-1b24eea06678864c03f75811317ad446
