### ISSUE TITLE
Discovery for subresource

### ISSUE THREAD

**Issue by yunhjiang** [kubernetes/client-go#840]
The subresource information is needed on the RBAC and audit setup. However, when I use the kubectl api-resources to fetch the resoruces, it will not return the subresource. 

I checked the code. The kubectl is using the discovery API, which does not return the subresource. https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L317 will ignore the subresource. 

Want to know if we can extend the discovery client API to support return sub resource also, either through a new interface or extending the existing one.

**Comment by liggitt** [comment]
if you want the list of all resources and subresources, use `DiscoveryInterface#ServerGroupsAndResources()`

**Comment by yunhjiang** [comment]
Thanks for the info.
