### ISSUE TITLE
resource-level isolation in controller

### ISSUE THREAD

**Issue by charles-tan** [kubernetes/client-go#841]
Hello

I noticed in the controller code only one Reflector object is created per controller instance: https://github.com/kubernetes/client-go/blob/36233866f1c7c0ad3bdac1fc466cb5de3746cfa2/tools/cache/controller.go#L130

We have a controller that watches over a list of resources, so if any of the resources in the list change, the reflector detects the change and updates the state store. However, if one of these resources has an issue and can't be read, the reflector will fail and won't watch any of the other resources in the list. Is it possible to change the design of the controller and reflector to provide resource isolation? So if the reflector object fails to watch one resource, it doesn't impact watching the other resources.

**Comment by liggitt** [comment]
all in-tree use of the cache controller is for a single resource... can you construct a controller per resource?

**Comment by charles-tan** [comment]
Ok thanks for the response. Changing our design will be substantial work to refactor, but since the controller/reflector is designed for a single resource I'll close this issue.
