### ISSUE TITLE
How to get all pods that use the same PVC?

### ISSUE THREAD

**Issue by acim** [kubernetes/client-go#847]
I have a ReadWriteMany PVC used in multiple pods and when I do "kubectl describe pvc xyz" under "Mounted by" I get all pods using it. I want to do  the same in Go.

I tried to get pods with field selector spec.volumes.persistentVolumeClaim.claimName:

```
	pods, err := c.CoreV1().Pods("").List(ctx, metav1.ListOptions{
		FieldSelector: fields.Set{"spec.volumes.persistentVolumeClaim.claimName": "xyz"}.AsSelector().String(),
	})
```

 but this reports the following error:

```
field label not supported: spec.volumes.persistentVolumeClaim.claimName
```

Is there any other way to achieve this except to loop over all pods and filter the "right" ones?

**Comment by liggitt** [comment]
No, looping and filtering is the only way to locate pods using a specific PVC
