### ISSUE TITLE
Specify ServiceAccount when using InClusterConfig

### ISSUE THREAD

**Issue by oze4** [kubernetes/client-go#848]
I am trying to use `InClusterConfig` to read namespaces like:

```golang
clientset.CoreV1().Namespaces().List(metav1.ListOptions{})
```

but I get this error (within the container):

```
panic: namespaces is forbidden: User "system:serviceaccount:default:default" cannot list resource "namespaces" in API group "" at the cluster scope
```

Is there any way to specify the service account?

Any help would be greatly appreciated!

**Comment by liggitt** [comment]
In-cluster config means the pod's service account credentials are used.

Options:
* you can change the service account by setting the `spec.serviceAccountName` field in the pod template
* you can grant permissions to the default service account

**Comment by oze4** [comment]
Thank you for the clarification! In hindsite, what a dumb question haha

I have limited kube experience (if you couldn't tell) - been about 10 months since I even logged into a cluster. What I'm trying to say is: your patience is appreciated. Thank you.
