### ISSUE TITLE
get containger image size ?

### ISSUE THREAD

**Issue by medyagh** [kubernetes/client-go#85]
Ithe kuberentes api has this 
`v1.ContainerImage, sizeBytes`
https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_pod

is there any way to get the container image size through this go library ?

**Comment by lavalamp** [comment]
Nodes report the size of *some* containers loaded on them. https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_nodestatus

You can't get the size of an arbitrary image, nor can you get the size of an image by looking at a pod that uses it.

I'm guessing you'll probably want to talk to the relevant container registry directly for metadata like this.

Hope that helps.

(This is a Kubernetes API question, not a go client question, btw)
