### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubernetes/client-go#853]
fatal error: concurrent map read and map write

goroutine 85 [running]:
runtime.throw(0x1c2e8cc, 0x21)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000516160 sp=0xc000516130 pc=0x436792
runtime.mapaccess1_faststr(0x197eb60, 0xc000265230, 0x180e582, 0x12, 0x0)
        /usr/local/go/src/runtime/map_faststr.go:21 +0x43c fp=0xc0005161d0 sp=0xc000516160 pc=0x414b1c
github.com/json-iterator/go._getTypeDecoderFromExtension(0xc000415500, 0x20025e0, 0xc0003666c0, 0x18e5a00, 0x20025e0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:274 +0x1c0 fp=0xc000516248 sp=0xc0005161d0 pc=0x10d4060
github.com/json-iterator/go.getTypeDecoderFromExtension(0xc000415500, 0x20025e0, 0xc0003666c0, 0xc000516308, 0xc000516308)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:244 +0x43 fp=0xc0005162b0 sp=0xc000516248 pc=0x10d3d03
github.com/json-iterator/go.decoderOfType(0xc000415500, 0x20025e0, 0xc0003666c0, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:115 +0x43 fp=0xc000516318 sp=0xc0005162b0 pc=0x10d0a73
github.com/json-iterator/go.describeStruct(0xc0005167b8, 0x20025e0, 0xc000366cc0, 0x1a35720)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc000516528 sp=0xc000516318 pc=0x10d5715
github.com/json-iterator/go.encoderOfStruct(0xc0005167b8, 0x20025e0, 0xc000366cc0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_encoder.go:18 +0x5a fp=0xc000516620 sp=0xc000516528 pc=0x10e888a
github.com/json-iterator/go._createEncoderOfType(0xc0005167b8, 0x20025e0, 0xc000366cc0, 0xc0001de038, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:270 +0x441 fp=0xc0005166a8 sp=0xc000516620 pc=0x10d20e1
github.com/json-iterator/go.createEncoderOfType(0xc0005167b8, 0x20025e0, 0xc000366cc0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:240 +0x10b fp=0xc0005166f8 sp=0xc0005166a8 pc=0x10d1c2b
github.com/json-iterator/go.encoderOfType(0xc0005167b8, 0x20025e0, 0xc000366cc0, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:222 +0x78 fp=0xc000516760 sp=0xc0005166f8 pc=0x10d1978
github.com/json-iterator/go.encoderOfSlice(0xc000415470, 0x2002540, 0xc00031adc0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_slice.go:18 +0x105 fp=0xc0005167f0 sp=0xc000516760 pc=0x10e0865
github.com/json-iterator/go._createEncoderOfType(0xc000415470, 0x2002540, 0xc00031adc0, 0xc0001dd238, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:274 +0x490 fp=0xc000516878 sp=0xc0005167f0 pc=0x10d2130
github.com/json-iterator/go.createEncoderOfType(0xc000415470, 0x2002540, 0xc00031adc0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:240 +0x10b fp=0xc0005168c8 sp=0xc000516878 pc=0x10d1c2b
github.com/json-iterator/go.encoderOfType(0xc000415470, 0x2002540, 0xc00031adc0, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:222 +0x78 fp=0xc000516930 sp=0xc0005168c8 pc=0x10d1978
github.com/json-iterator/go.describeStruct(0xc000414c60, 0x20025e0, 0xc000366540, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:384 +0xdc0 fp=0xc000516b40 sp=0xc000516930 pc=0x10d55a0
github.com/json-iterator/go.decoderOfStruct(0xc000414c60, 0x20025e0, 0xc000366540, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc000516d58 sp=0xc000516b40 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc000414c60, 0x20025e0, 0xc000366540, 0xc0001da6f8, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc000516de8 sp=0xc000516d58 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc000414c60, 0x20025e0, 0xc000366540, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000516e38 sp=0xc000516de8 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc000414c60, 0x20025e0, 0xc000366540, 0xc000516ee8, 0x109db07)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000516ea0 sp=0xc000516e38 pc=0x10d0aa8
github.com/json-iterator/go.decoderOfOptional(0xc000414c60, 0x20024a0, 0xc0003664e0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_optional.go:12 +0x68 fp=0xc000516ef8 sp=0xc000516ea0 pc=0x10dfbe8
github.com/json-iterator/go._createDecoderOfType(0xc000414c60, 0x20024a0, 0xc0003664e0, 0xc0001db5a8, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:179 +0x554 fp=0xc000516f88 sp=0xc000516ef8 pc=0x10d1324
github.com/json-iterator/go.createDecoderOfType(0xc000414c60, 0x20024a0, 0xc0003664e0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000516fd8 sp=0xc000516f88 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc000414c60, 0x20024a0, 0xc0003664e0, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000517040 sp=0xc000516fd8 pc=0x10d0aa8
github.com/json-iterator/go.describeStruct(0xc0007ab020, 0x20025e0, 0xc000358c60, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc000517250 sp=0xc000517040 pc=0x10d5715
github.com/json-iterator/go.decoderOfStruct(0xc0007ab020, 0x20025e0, 0xc000358c60, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc000517468 sp=0xc000517250 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc0007ab020, 0x20025e0, 0xc000358c60, 0xc0001db178, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc0005174f8 sp=0xc000517468 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc0007ab020, 0x20025e0, 0xc000358c60, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000517548 sp=0xc0005174f8 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc0007ab020, 0x20025e0, 0xc000358c60, 0xc0005175f8, 0x109db07)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc0005175b0 sp=0xc000517548 pc=0x10d0aa8
github.com/json-iterator/go.decoderOfOptional(0xc0007ab020, 0x20024a0, 0xc000358c00, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_optional.go:12 +0x68 fp=0xc000517608 sp=0xc0005175b0 pc=0x10dfbe8
github.com/json-iterator/go._createDecoderOfType(0xc0007ab020, 0x20024a0, 0xc000358c00, 0xc0001db7c8, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:179 +0x554 fp=0xc000517698 sp=0xc000517608 pc=0x10d1324
github.com/json-iterator/go.createDecoderOfType(0xc0007ab020, 0x20024a0, 0xc000358c00, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc0005176e8 sp=0xc000517698 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc0007ab020, 0x20024a0, 0xc000358c00, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000517750 sp=0xc0005176e8 pc=0x10d0aa8
github.com/json-iterator/go.describeStruct(0xc0003fe2a0, 0x20025e0, 0xc000440030, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc000517960 sp=0xc000517750 pc=0x10d5715
github.com/json-iterator/go.decoderOfStruct(0xc0003fe2a0, 0x20025e0, 0xc000440030, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc000517b78 sp=0xc000517960 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc0003fe2a0, 0x20025e0, 0xc000440030, 0xc0005ccce8, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc000517c08 sp=0xc000517b78 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc0003fe2a0, 0x20025e0, 0xc000440030, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000517c58 sp=0xc000517c08 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc0003fe2a0, 0x20025e0, 0xc000440030, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000517cc0 sp=0xc000517c58 pc=0x10d0aa8
github.com/json-iterator/go.describeStruct(0xc0003fe210, 0x20025e0, 0xc000543ec0, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc000517ed0 sp=0xc000517cc0 pc=0x10d5715
github.com/json-iterator/go.decoderOfStruct(0xc0003fe210, 0x20025e0, 0xc000543ec0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc0005180e8 sp=0xc000517ed0 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc0003fe210, 0x20025e0, 0xc000543ec0, 0xc0005cce28, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc000518178 sp=0xc0005180e8 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc0003fe210, 0x20025e0, 0xc000543ec0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc0005181c8 sp=0xc000518178 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc0003fe210, 0x20025e0, 0xc000543ec0, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000518230 sp=0xc0005181c8 pc=0x10d0aa8
github.com/json-iterator/go.describeStruct(0xc00037f860, 0x20025e0, 0xc00037f8c0, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc000518440 sp=0xc000518230 pc=0x10d5715
github.com/json-iterator/go.decoderOfStruct(0xc00037f860, 0x20025e0, 0xc00037f8c0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc000518658 sp=0xc000518440 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc00037f860, 0x20025e0, 0xc00037f8c0, 0xc0005cce08, 0xc000264c90)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc0005186e8 sp=0xc000518658 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc00037f860, 0x20025e0, 0xc00037f8c0, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000518738 sp=0xc0005186e8 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc00037f860, 0x20025e0, 0xc00037f8c0, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc0005187a0 sp=0xc000518738 pc=0x10d0aa8
github.com/json-iterator/go.describeStruct(0xc000518d68, 0x20025e0, 0xc0001c5200, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc0005189b0 sp=0xc0005187a0 pc=0x10d5715
github.com/json-iterator/go.decoderOfStruct(0xc000518d68, 0x20025e0, 0xc0001c5200, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc000518bc8 sp=0xc0005189b0 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc000332d68, 0x20025e0, 0xc0001c5200, 0xc000412428, 0x1acd580)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc000518c58 sp=0xc000518bc8 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc000332d68, 0x20025e0, 0xc0001c5200, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000518ca8 sp=0xc000518c58 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc000518d68, 0x20025e0, 0xc0001c5200, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000518d10 sp=0xc000518ca8 pc=0x10d0aa8
github.com/json-iterator/go.decoderOfSlice(0xc0001c5110, 0x2002540, 0xc0004c2540, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_slice.go:12 +0x105 fp=0xc000518da0 sp=0xc000518d10 pc=0x10e0685
github.com/json-iterator/go._createDecoderOfType(0xc0001c5110, 0x2002540, 0xc0004c2540, 0xc000412418, 0xc000264c90)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:175 +0x4ff fp=0xc000518e30 sp=0xc000518da0 pc=0x10d12cf
github.com/json-iterator/go.createDecoderOfType(0xc0001c5110, 0x2002540, 0xc0004c2540, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc000518e80 sp=0xc000518e30 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc0001c5110, 0x2002540, 0xc0004c2540, 0x1bf6aa8, 0x1)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000518ee8 sp=0xc000518e80 pc=0x10d0aa8
github.com/json-iterator/go.describeStruct(0xc0005194a8, 0x20025e0, 0xc0001c4a80, 0xc00000f7f0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_extension.go:380 +0xf35 fp=0xc0005190f8 sp=0xc000518ee8 pc=0x10d5715
github.com/json-iterator/go.decoderOfStruct(0xc0005194a8, 0x20025e0, 0xc0001c4a80, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect_struct_decoder.go:14 +0xb6 fp=0xc000519310 sp=0xc0005190f8 pc=0x10e13e6
github.com/json-iterator/go._createDecoderOfType(0xc0003334a8, 0x20025e0, 0xc0001c4a80, 0xc0004123e8, 0xc000264c90)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:171 +0x4aa fp=0xc0005193a0 sp=0xc000519310 pc=0x10d127a
github.com/json-iterator/go.createDecoderOfType(0xc0003334a8, 0x20025e0, 0xc0001c4a80, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:137 +0x10b fp=0xc0005193f0 sp=0xc0005193a0 pc=0x10d0d5b
github.com/json-iterator/go.decoderOfType(0xc0005194a8, 0x20025e0, 0xc0001c4a80, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:119 +0x78 fp=0xc000519458 sp=0xc0005193f0 pc=0x10d0aa8
github.com/json-iterator/go.(*frozenConfig).DecoderOf(0xc00021c6e0, 0x20024a0, 0xc0001c49c0, 0x20024a0, 0xc0001c49c0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:109 +0x111 fp=0xc0005194e0 sp=0xc000519458 pc=0x10d0921
github.com/json-iterator/go.(*Iterator).ReadVal(0xc00053eb00, 0x1b520a0, 0xc0001a6000)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/reflect.go:71 +0x169 fp=0xc000519548 sp=0xc0005194e0 pc=0x10d05a9
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc00021c6e0, 0xc000720000, 0x270af, 0x3fe00, 0x1b520a0, 0xc0001a6000, 0x0, 0x0)
        /app/go/pkg/mod/github.com/json-iterator/go@v1.1.7/config.go:348 +0xb7 fp=0xc0005195a8 sp=0xc000519548 pc=0x10c6e27
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc000202b00, 0xc000720000, 0x270af, 0x3fe00, 0x0, 0x1fae5c0, 0xc0001a6000, 0x0, 0x0, 0x0, ...)
        /app/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004074956-01f8b7d1121a/pkg/runtime/serializer/json/json.go:236 +0x7d2 fp=0xc000519898 sp=0xc0005195a8 pc=0x10fcdb2
k8s.io/apimachinery/pkg/runtime/serializer/versioning.DirectDecoder.Decode(0x1f9ad00, 0xc000202b00, 0xc000720000, 0x270af, 0x3fe00, 0x0, 0x1fae5c0, 0xc0001a6000, 0x2, 0xc0000a7020, ...)
        /app/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004074956-01f8b7d1121a/pkg/runtime/serializer/versioning/versioning.go:275 +0x97 fp=0xc000519930 sp=0xc000519898 pc=0x11099d7
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*DirectDecoder).Decode(0xc00053c0b0, 0xc000720000, 0x270af, 0x3fe00, 0x0, 0x1fae5c0, 0xc0001a6000, 0xc0003339e8, 0xc000720000, 0x270af, ...)
        <autogenerated>:1 +0x9f fp=0xc0005199a8 sp=0xc000519930 pc=0x1109b5f
k8s.io/client-go/rest.Result.Into(0xc000720000, 0x270af, 0x3fe00, 0xc00012db60, 0x10, 0x0, 0x0, 0xc8, 0x1f9c8e0, 0xc00053c0b0, ...)
        /app/go/pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/rest/request.go:1106 +0xba fp=0xc000519a48 sp=0xc0005199a8 pc=0x1133e1a
k8s.io/client-go/kubernetes/typed/apps/v1.(*deployments).List(0xc000110060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/go/pkg/mod/k8s.io/client-go@v0.0.0-20191004102537-eb5b9a8cfde7/kubernetes/typed/apps/v1/deployment.go:96 +0x1fa fp=0xc000519b30 sp=0xc000519a48 pc=0x114f17a

![image](https://user-images.githubusercontent.com/9782796/91252706-abb08280-e790-11ea-8658-d1bd92a2812b.png)

**Comment by sttts** [comment]
Is this in json-iterator or in Kube code?
