### ISSUE TITLE
The client-go doesn't compile into web assembly platform

### ISSUE THREAD

**Issue by martinkunc** [kubernetes/client-go#854]
The client-go is using x/crypto, which has some platform specific code to support terminals. Because there is no support for wasm platform in x/crypto, the client-go doesn't compile in wasm.

I believe it could help to make terminal specific code platform specific using conditional compilation until this is fixed in x/crypto.

**Comment by mortezaalizadeh** [comment]
@martinkunc we ran into exact same issue, I was trying to build it into web assembly and use it straight in my React code, but got below error during compilation. That would be great if we can make the dependency conditional in the SDK.

╰─➤  make build                                                                                                                                                                                                                           2 ↵
k8s.io/client-go/plugin/pkg/client/auth/exec
# k8s.io/client-go/plugin/pkg/client/auth/exec
../../../../pkg/mod/k8s.io/client-go@v0.20.5/plugin/pkg/client/auth/exec/exec.go:196:16: undefined: terminal.IsTerminal
make: *** [Makefile:25: build] Error 2

**Comment by mstrYoda** [comment]
Hi, what is the current status of this issue?
