### ISSUE TITLE
How to connect K8s cluster with ca.pem

### ISSUE THREAD

**Issue by kengan** [kubernetes/client-go#863]
I hava 3 cerficates file about my k8s cluster. For python client I can use these cerficates to connect my k8s cluster as following:

  ca = os.path.join(ca_path, "ca.pem")
  cert = os.path.join(ca_path, "apiserver.pem")
  key = os.path.join(ca_path, "apiserver-key.pem")

    config_inst = client.Configuration()
    config_inst.host = cluster_ip.ip
    config_inst.ssl_ca_cert = ca
    config_inst.key_file = key
     config_inst.cert_file = cert
     client.CoreV1Api(), client.ExtensionsV1beta1Api()

I want to know how to use go-client to connect my k8s cluster with these cerficates . Thank you

**Comment by kanzhuchengbi** [comment]
import (
	apiv1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/kubernetes"
)
    
    func main() {
    restClientConfig := &restclient.Config{}
	restClientConfig.Host = "host"
	restClientConfig.ContentType = runtime.ContentTypeJSON
	restClientConfig.TLSClientConfig = restclient.TLSClientConfig{}
	restClientConfig.TLSClientConfig.CAFile = "capath"
	restClientConfig.TLSClientConfig.CertFile = "CertFilePath"
	restClientConfig.TLSClientConfig.KeyFile = "KeyFilePath"
	clientset,err := kubernetes.NewForConfig(restClientConfig)
    podsclient := clientset.CoreV1().Pods(apiv1.NamespaceAll)
    ......
}

**Comment by jiayouxujin** [comment]
Did you resolve it? when I use your code, it occurs "user system:kube-proxy".the code doesn't work.

**Comment by kanzhuchengbi** [comment]
> 
> 
> Did you resolve it? when I use your code, it occurs "user system:kube-proxy".the code doesn't work.

Is your CA is right? 

restClientConfig.TLSClientConfig.CAFile = "capath"  // use your capath
restClientConfig.TLSClientConfig.CertFile = "CertFilePath" // use your CertFilePath
restClientConfig.TLSClientConfig.KeyFile = "KeyFilePath" // use your KeyFilePath
