### ISSUE TITLE
Can you provide an example of base64 encoding a value for a Secret?

### ISSUE THREAD

**Issue by bukowa** [kubernetes/client-go#864]
While using this function, my container says the data is invalid (using the data from a volume). While i decode the string, it looks correct to me.

````golang
func setData(key string, raw []byte, secret *v1core.Secret) error {
	var buff bytes.Buffer
	var b64 []byte
	_, err := base64.NewEncoder(base64.StdEncoding, &buff).Write(raw)
	if err != nil {
		return err
	}
	// Read buffer
	if b64, err = ioutil.ReadAll(&buff); err != nil {
		return err
	}
	// Set data
	if secret.Data == nil {
		secret.Data = make(map[string][]byte)
	}
	secret.Data[key] = b64
	return nil
}

**Comment by bukowa** [comment]
Hmm i think i just realized it's mounted as a base64 string :) I thought kubernetes will decode it before mounting.

**Comment by liggitt** [comment]
When working with the go API, set the bytes you want directly. Go will encode those to base64 when speaking to the API.
