### ISSUE TITLE
Event watcher returns "*v1.Status" instead of "*v1.Event*" sometimes 

### ISSUE THREAD

**Issue by qinqon** [kubernetes/client-go#869]
At [kubevirt](https://github.com/kubevirt/kubevirt) we are facing some issues at client-go after upgrading to k8s-1.19 https://github.com/kubevirt/kubevirt/issues/4239

At that code we ar doing some casting from from `k8s.io/apimachinery/pkg/watch/event.Object` to `*v1.Event` but look like
sometimes we receive `*v1.Status` instead 

We are using k8s.io/client-go => k8s.io/client-go v0.16.4 and the cluster is k8s-1.19

Could this be related to client-go version ?

**Comment by liggitt** [comment]
watches can receive status objects when event.Type == ERROR

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L459-L465

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L98-L119

> Could this be related to client-go version ?

No, watches have always returned status objects in error conditions.
