### ISSUE TITLE
high memory usage in Reflector.ListAndWatch

### ISSUE THREAD

**Issue by murali-reddy** [kubernetes/client-go#871]
I am investigating high memory usage in one of the Kubernetes controller that use client-go. In a cluster with 15000 pods it is observed that 200-300 MB memory is used by client-go constructs. I stripped down my code interaction with client-go to include just below lines with no listing of pods and no resource event handler registered.

``` go
informerFactory := informers.NewSharedInformerFactory(kr.Client, 0)
podInformer := informerFactory.Core().V1().Pods().Informer()
```
I still see heavy memory usage. Attached is the pprof heap profile.

[pod.informer.pb.gz](https://github.com/kubernetes/client-go/files/5276832/pod.informer.pb.gz)

api, apimachinery, client-go all at v0.19.2

**Comment by murali-reddy** [comment]
Also there seems to be unbounded memory growth resulting due to listing of the cached objects particularly pods over long period of time. Attached is heap profile.
 
[pod.informer.longrunning.pb.gz](https://github.com/kubernetes/client-go/files/5336092/pod.informer.longrunning.pb.gz)

Appriciate any insight into how to debug this.

**Comment by zoux86** [comment]
@murali-reddy do you fix it?  I am faced with the same problem too.

**Comment by evanlixin** [comment]
follow

**Comment by evanlixin** [comment]
@murali-reddy  do you fix it  completely ? I am faced with the same problem now.

**Comment by codwu** [comment]
same problem +1
/remove-lifecycle rotten

**Comment by xgp01** [comment]
mark, same problem +1

**Comment by gizas** [comment]
Same problem, +1

**Comment by shikingram** [comment]
Same problem, +1

**Comment by YongBig** [comment]
@zoux86 @murali-reddy @evanlixin  Hi , Everyone ！do you fix it completely ?

**Comment by kusolank** [comment]
@murali-reddy  Are you able to fix it?

**Comment by zk-123** [comment]
same problem + 1

**Comment by orangle** [comment]
same problem + 1

**Comment by Baytwt** [comment]
same problem + 1

**Comment by vietanhduong** [comment]
Same problem +1

**Comment by beautyofmath** [comment]
same problem +1
