### ISSUE TITLE
Fake impl crashes if clientset.CoreV1().Pods(..).GetLogs(..) is called

### ISSUE THREAD

**Issue by codezork** [kubernetes/client-go#873]
Hi,
Calling GetLogs will call ObjectReaction later in fixture.go with a GenericActionImpl action type. Thus being handled by the default case in line 192 that tries to create a fmt.Errorf with action as a string attribute. This crashes.
I suggest to change line 192 to:
`return false, nil, fmt.Errorf("no reaction implemented for verb:%s subresource:%s", action.GetVerb(), action.GetSubresource())`
I could create a pull request if you wish to.
Cheers
Joerg

**Comment by zzxwill** [comment]
@codezork, This fix is indeed needed.
