### ISSUE TITLE
client-go v0.19.2 is not working because of "but does not contain package k8s.io/api/auditregistration/v1alpha1"

### ISSUE THREAD

**Issue by Thoro** [kubernetes/client-go#874]
I have read the 3 other tickets about this, and I add into my go.mod file: 

```
        k8s.io/api v0.19.2
	k8s.io/apimachinery v0.19.2
	k8s.io/client-go v0.19.2
	k8s.io/code-generator v0.19.2
	k8s.io/kubelet v0.19.2
```

But go mod vendor, or go run or go build all change the dependencies to

```
        k8s.io/api v0.19.2
	k8s.io/apimachinery v0.19.2
	k8s.io/client-go v11.0.0+incompatible
	k8s.io/code-generator v0.19.2
	k8s.io/kubelet v0.19.2
```

How are we supposed to use it, if it auto changes back and then the compile error appears?

```
../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:26:2: module k8s.io/api@latest found (v0.19.2), but does not contain package k8s.io/api/auditregistration/v1alpha1
```
Edit: I'm using go 1.15.2 on osx

**Comment by Thoro** [comment]
Oh God, so, issue is that some submodule was using v11.0.0 which is then preferred to the module that I put there ... I think go mod needs still some work.

**Comment by waterfeeds** [comment]
> Oh God, so, issue is that some submodule was using v11.0.0 which is then preferred to the module that I put there ... I think go mod needs still some work.
> 
> You can use go mod replace, so put into the go.mod file:
> 
> ```
> replace k8s.io/client-go => k8s.io/client-go v0.19.2
> ```

it does works for this method, thanks!

**Comment by taigrr** [comment]
`replace k8s.io/api => k8s.io/api v0.19.2` is also required now

**Comment by nrnrk** [comment]
This works for me. Thank you.

I guess this would be a little better :+1:

```go.mod
require(
    ...
    //  k8s.io/client-go v0.20.0 is also fine
    k8s.io/client-go v0.19.2
    ...
)
```

Or you can execute the following command

```sh
go get k8s.io/client-go@v0.19.2
```

**Comment by nikhiljsk** [comment]
Thanks! @nrnrk `k8s.io/client-go v0.20.0` worked for me, v0.19.2 didn't work.

**Comment by hzliangbin** [comment]
@nikhiljsk worked for me.thx.
