### ISSUE TITLE
Go files inside ./metadata folder are failing to build, with gollvm, cause of decency on reflect2

### ISSUE THREAD

**Issue by advancedwebdeveloper** [kubernetes/client-go#877]
Looks like [metadata](https://github.com/kubernetes/client-go/tree/master/metadata) is relying on [reflect2](https://github.com/modern-go/reflect2) package.

Last time I saw this bug during the build of k8s's dependency, [json-iterator](https://github.com/json-iterator/go) . I hoped that (at least) the client library would not depend on reflect2.
What is odd is that gollvm allows to compile all examples - but not the files in this folder.

> $ go test ./...
> # k8s.io/client-go/metadata.test
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> # k8s.io/client-go/metadata
> vet: ./metadata_test.go:28:9: could not import k8s.io/api/core/v1 (EOF)
> FAIL	k8s.io/client-go/metadata [build failed]
> # k8s.io/client-go/metadata/fake.test
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> FAIL	k8s.io/client-go/metadata/fake [build failed]
> # k8s.io/client-go/metadata/metadatainformer.test
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> # k8s.io/api/apps/v1
> vet: ../vendor/k8s.io/api/apps/v1/generated.pb.go:28:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/apps/v1beta1
> vet: ../vendor/k8s.io/api/apps/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/apps/v1beta2
> vet: ../vendor/k8s.io/api/apps/v1beta2/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/autoscaling/v1
> vet: ../vendor/k8s.io/api/autoscaling/v1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/autoscaling/v2beta1
> vet: ../vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/autoscaling/v2beta2
> vet: ../vendor/k8s.io/api/autoscaling/v2beta2/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/batch/v1
> vet: ../vendor/k8s.io/api/batch/v1/generated.pb.go:28:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/certificates/v1
> vet: ../vendor/k8s.io/api/certificates/v1/generated.pb.go:30:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/batch/v1beta1
> vet: ../vendor/k8s.io/api/batch/v1beta1/generated.pb.go:28:6: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/batch/v2alpha1
> vet: ../vendor/k8s.io/api/batch/v2alpha1/generated.pb.go:28:6: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/certificates/v1beta1
> vet: ../vendor/k8s.io/api/certificates/v1beta1/generated.pb.go:30:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/discovery/v1alpha1
> vet: ../vendor/k8s.io/api/discovery/v1alpha1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/discovery/v1beta1
> vet: ../vendor/k8s.io/api/discovery/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/events/v1
> vet: ../vendor/k8s.io/api/events/v1/generated.pb.go:28:6: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/events/v1beta1
> vet: ../vendor/k8s.io/api/events/v1beta1/generated.pb.go:28:6: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/extensions/v1beta1
> vet: ../vendor/k8s.io/api/extensions/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/networking/v1
> vet: ../vendor/k8s.io/api/networking/v1/generated.pb.go:28:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/networking/v1beta1
> vet: ../vendor/k8s.io/api/networking/v1beta1/generated.pb.go:28:6: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/node/v1alpha1
> vet: ../vendor/k8s.io/api/node/v1alpha1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/node/v1beta1
> vet: ../vendor/k8s.io/api/node/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/policy/v1beta1
> vet: ../vendor/k8s.io/api/policy/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/scheduling/v1
> vet: ../vendor/k8s.io/api/scheduling/v1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/scheduling/v1alpha1
> vet: ../vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/scheduling/v1beta1
> vet: ../vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/storage/v1
> vet: ../vendor/k8s.io/api/storage/v1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/storage/v1alpha1
> vet: ../vendor/k8s.io/api/storage/v1alpha1/generated.pb.go:29:6: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/api/storage/v1beta1
> vet: ../vendor/k8s.io/api/storage/v1beta1/generated.pb.go:29:21: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/tools/reference
> vet: ../tools/reference/ref.go:23:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/kubernetes/scheme
> vet: ../kubernetes/scheme/register.go:42:9: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/apps/v1
> vet: ../listers/apps/v1/daemonset_expansion.go:23:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/kubernetes/typed/core/v1
> vet: ../kubernetes/typed/core/v1/componentstatus.go:25:5: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/apps/v1beta1
> vet: ../listers/apps/v1beta1/statefulset_expansion.go:23:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/apps/v1beta2
> vet: ../listers/apps/v1beta2/daemonset_expansion.go:23:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/batch/v1
> vet: ../listers/batch/v1/job_expansion.go:23:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/core/v1
> vet: ../listers/core/v1/componentstatus.go:22:5: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/informers/core/v1
> vet: ../informers/core/v1/componentstatus.go:25:9: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/extensions/v1beta1
> vet: ../listers/extensions/v1beta1/daemonset_expansion.go:23:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/listers/policy/v1beta1
> vet: ../listers/policy/v1beta1/poddisruptionbudget_expansion.go:22:2: could not import k8s.io/api/core/v1 (EOF)
> # k8s.io/client-go/metadata/metadatalister.test
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:74: error: undefined reference to 'reflect.typelinks'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:78: error: undefined reference to 'reflect.resolveTypeOff'
> /home/oceanfish81/go_projects/client-go/vendor/github.com/modern-go/reflect2/type_map.go:42: error: undefined reference to 'reflect.typelinks'
> # k8s.io/client-go/informers
> vet: ../informers/generic.go:40:9: could not import k8s.io/api/core/v1 (EOF)
> FAIL	k8s.io/client-go/metadata/metadatainformer [build failed]
> FAIL	k8s.io/client-go/metadata/metadatalister [build failed]
> FAIL
>

**Comment by advancedwebdeveloper** [comment]
Here is my Golang 1.15.2 environment:
> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build121108682=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by advancedwebdeveloper** [comment]
CC @wojtek-t @mikedanese @liggitt

**Comment by liggitt** [comment]
> What is odd is that gollvm allows to compile all examples - but not the files in this folder.

This seems like a bug that should be reported to gollvm, since this works properly with the standard go compiler.
