### ISSUE TITLE
metadata Watch and metadata Informer do not work on Kubernetes <= 1.14

### ISSUE THREAD

**Issue by nicks** [kubernetes/client-go#882]
According to the GoDoc, 
https://pkg.go.dev/k8s.io/client-go/metadata#Client

> The client uses the meta.k8s.io/v1 PartialObjectMetadata resource to more efficiently retrieve just the necessary metadata, but on older servers (Kubernetes 1.14 and before) will retrieve the object and then convert the metadata.

But when I try to use metadatainformer or Watch() on Kuberentes 1.14, I get errors like this:

> W1020 18:23:54.425957 177752 reflector.go:424] tilt/internal/k8s/watch.go:336: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind "ReplicaSet" is registered for version "apps/v1" in scheme "k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go:27"") has prevented the request from succeeding

When I poke around in the client-go code to see how this works, it looks like the List() methods have fallback for the case when the server doesn't return PartialObjectMetadata

```
if runtime.IsNotRegisteredError(err) {
 // deserialize manually
```

https://github.com/kubernetes/client-go/blob/v0.19.2/metadata/metadata.go#L205

But as far as I can tell, the Watch() methods don't have any deserialization for this, and just fall over.

Am I missing something?

**Comment by liggitt** [comment]
/assign @smarterclayton 

https://github.com/kubernetes/kubernetes/pull/77819#discussion_r299661761 indicated handling this case was desired... was it intentional not to do it for watch?
