### ISSUE TITLE
ClientConfigLoadingRules is not working correctly

### ISSUE THREAD

**Issue by kotyara85** [kubernetes/client-go#901]
Hey there,
Looks like ClientConfigLoadingRules is not working correctly
I do merge two configs (old one & updated one) using this code -
```
// kubeConfigPath = ~/.kube/config
// newConfig = path to new config

	loadingRules := clientcmd.ClientConfigLoadingRules{
		Precedence: []string{newConfig, kubeConfigPath},
	}

	// merge the configs
	mergedConfig, err := loadingRules.Load()
	if err != nil {
		return err
	}

	spew.Dump(mergedConfig)
```

The weird story is that using code above current context is being updated, but not cluster & user info fields

If I change 
```
Precedence: []string{kubeConfigPath, newConfig},
```
Then everything is being updated besides current context

Im on the latest version of client-go

Thanks

**Comment by DavidSpek** [comment]
/reopen
I am also experiencing this issue.
