### ISSUE TITLE
event recorder fails to record repeating events

### ISSUE THREAD

**Issue by RamLavi** [kubernetes/client-go#908]
**What happened**:
I created a pod and then wrote a simple go routine to emit an `Available` event each second.
I then watch the events, and see that the `LAST SEEN` column after a while start to grow, meaning the events stop being received/sent.
attached a bash script for easy recreation.

**What you expected to happen**:
since we're sending an event every second, the `LAST SEEN` column should show the event with a value of 0/1s. 

In actuality after about 0.5min, the events `LAST SEEN` starts growing (see last line):
```
Every 2.0s: kubectl get events                               hades01.lab.eng.tlv2.redhat.com: Thu Dec 17 14:41:11 2020

LAST SEEN   TYPE      REASON             OBJECT     MESSAGE
2m42s       Warning   DNSConfigForming   pod/test   Search Line limits were exceeded, some search paths have been omit
ted, the applied search line is: default.svc.cluster.local svc.cluster.local cluster.local lab.eng.tlv2.redhat.com mgm
t.lab.eng.tlv2.redhat.com eng.lab.tlv.redhat.com
105s        Normal    Scheduled          pod/test   Successfully assigned default/test to kind-control-plane
25s         Warning   DNSConfigForming   pod/test   Search Line limits were exceeded, some search paths have been omit
ted, the applied search line is: default.svc.cluster.local svc.cluster.local cluster.local lab.eng.tlv2.redhat.com mgm
t.lab.eng.tlv2.redhat.com eng.lab.tlv.redhat.com
104s        Normal    Pulling            pod/test   Pulling image "busybox"
101s        Normal    Pulled             pod/test   Successfully pulled image "busybox" in 2.771330479s
101s        Normal    Created            pod/test   Created container test
101s        Normal    Started            pod/test   Started container test
63s         Normal    Available          pod/test   All applied components are available
```

**How to reproduce it (as minimally and precisely as possible)**:
1. create a kind cluster (quick kind [install](https://kind.sigs.k8s.io/docs/user/quick-start/))
```
kind create cluster
```

2. download, unzip and run the reproducing script. It'll do the following:
- copy the go routine to the local directory
- create a simple pod "test" on default namespace
- run the go-routine that will record an "Available" event every 1 second
```
unzip test_script.zip
chmod +x test.sh
./test.sh
```

3. open another terminal, and watch the events
```
watch kubectl get events
```

**Anything else we need to know?**:
I chose showing this with the `kubectl get events` tool for simplicity, but it also doesn't work when I tried watching the pod object via k8s api like `watcher, err := k8sClient.CoreV1().Pods(namespace).Watch(ctx, metav1.ListOptions{})`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux hades01.lab.eng.tlv2.redhat.com 5.8.15-101.fc31.x86_64 #1 SMP Thu Oct 15 16:57:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

[test_script.zip](https://github.com/kubernetes/client-go/files/5709539/test_script.zip)

**Comment by hamburgerbun** [comment]
i'm not a client-go dev or anything so take this with a grain of salt, but when i noticed events were getting swallowed or aggregated funny, there were two main things afoot that i think is most easily explained using the constants involved
https://github.com/kubernetes/client-go/blob/master/tools/record/events_cache.go
```
const (
	maxLruCacheEntries = 4096

	// if we see the same event that varies only by message
	// more than 10 times in a 10 minute period, aggregate the event
	defaultAggregateMaxEvents         = 10
	defaultAggregateIntervalInSeconds = 600

	// by default, allow a source to send 25 events about an object
	// but control the refill rate to 1 new event every 5 minutes
	// this helps control the long-tail of events for things that are always
	// unhealthy
	defaultSpamBurst = 25
	defaultSpamQPS   = 1. / 300.
```
1. when all fields but the message are matched and it exceeds a certain count, it'll start just aggregating them together. If you have a completely identical event though i don't even think it shows you the 10 events mentioned in the defaults here. 
2. point 1 aside, spam burst prevents you from having too many unique events at all once, and then it only allocates "slots" for new events to show up at QPS speed, so by default you get like, 25 events, and then 1 slot is allocated for a new event every 5 minutes

To dodge these things, I had to
1. make the reason field unique as needed so it'd aggregate based on that instead of smashing all of my events together blindly (added an id or hash related to what was happening)
2. start an EventBroadcaster with specific correlator options, and then use the event recorder from this broadcaster
```
bc := record.NewBroadcasterWithCorrelatorOptions(record.CorrelatorOptions{
		BurstSize:            25, // default is 25
		QPS:                  4,  // default is 1 per 300 seconds
		MaxEvents:            25,
		MaxIntervalInSeconds: 1,
	})
	rec := bc.NewRecorder(scheme, corev1.EventSource{
		Component: "toplevelcontroller",
	})
```

**Comment by RamLavi** [comment]
@hamburgerbun thanks for the reply! I will take a look
