### ISSUE TITLE
Fake client update bind sub resource result in panic

### ISSUE THREAD

**Issue by hrishin** [kubernetes/client-go#911]
For a given `Pod` resource, when the fake client creates the `bind` resource, sub-sequent get() call results in the panic. Is it expected?

```
panic: interface conversion: runtime.Object is *v1.Binding, not *v1.Pod [recovered]
	panic: interface conversion: runtime.Object is *v1.Binding, not *v1.Pod

goroutine 57 [running]:
testing.tRunner.func1.1(0x20fedc0, 0xc0007101e0)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0004d1500)
	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1075 +0x41a
panic(0x20fedc0, 0xc0007101e0)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
k8s.io/client-go/kubernetes/typed/core/v1/fake.(*FakePods).Get(0xc00000fb60, 0x2480960, 0xc0000c6010, 0x22a10d4, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/someuser/go/pkg/mod/k8s.io/client-go@v0.18.6/kubernetes/typed/core/v1/fake/fake_pod.go:51 +0x251
```

**Client-go version:** 0.18.6
**k8s.io/api:** v0.18.6
**k8s.io/apimachinery:** v0.18.6

**Comment by mental2008** [comment]
> For a given `Pod` resource, when the fake client creates the `bind` resource, sub-sequent get() call results in the panic. Is it expected?
> 
> ```
> panic: interface conversion: runtime.Object is *v1.Binding, not *v1.Pod [recovered]
> 	panic: interface conversion: runtime.Object is *v1.Binding, not *v1.Pod
> 
> goroutine 57 [running]:
> testing.tRunner.func1.1(0x20fedc0, 0xc0007101e0)
> 	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1072 +0x30d
> testing.tRunner.func1(0xc0004d1500)
> 	/usr/local/Cellar/go/1.15.5/libexec/src/testing/testing.go:1075 +0x41a
> panic(0x20fedc0, 0xc0007101e0)
> 	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
> k8s.io/client-go/kubernetes/typed/core/v1/fake.(*FakePods).Get(0xc00000fb60, 0x2480960, 0xc0000c6010, 0x22a10d4, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/Users/someuser/go/pkg/mod/k8s.io/client-go@v0.18.6/kubernetes/typed/core/v1/fake/fake_pod.go:51 +0x251
> ```
> 
> **Client-go version:** 0.18.6 **k8s.io/api:** v0.18.6 **k8s.io/apimachinery:** v0.18.6

Same question here. Do you have any subsequent solution about it?
