### ISSUE TITLE
exec with client-go

### ISSUE THREAD

**Issue by divinerapier** [kubernetes/client-go#912]
Hi,
I am writing a gRPC service as a web terminal to `exec` into a pod. Here is my code:

``` go
func (e *ProxyExecutor) Run() error {
	pod, _ := e.podclient.Pods(e.namespace).Get(e.podname, metav1.GetOptions{})

	containerName := pod.Spec.Containers[0].Name
	if len(pod.Spec.Containers) > 1 {
	}

	req := e.restclient.Post().
		Resource("pods").
		Name(pod.Name).
		Namespace(pod.Namespace).
		SubResource("exec")

	req.VersionedParams(&v1.PodExecOptions{
		Container: containerName,
		Command:   e.command,
		Stdin:     true,
		Stdout:    true,
		Stderr:    true,
		TTY:       true,
	}, scheme.ParameterCodec)

	exec, _ := remotecommand.NewSPDYExecutor(e.config, "POST", req.URL())

	return exec.Stream(remotecommand.StreamOptions{
		Stdin:             e.stdin,
		Stdout:            e.stdout,
		Stderr:            e.stderr,
		Tty:               true,
		TerminalSizeQueue: e.sizequeue,
	})
}
```
I find the data from `stdin` will be printed on `stdout`.  Like the `ls` command:
<img width="763" alt="捕获" src="https://user-images.githubusercontent.com/21213088/103120052-04e1e180-46b1-11eb-95f0-c2c1072e1052.PNG">

Thanks.

**Comment by divinerapier** [comment]
Then I want to use `tab`, `ctrl-d` on my client and send these commands to pod via my `gRPC` service.

**Comment by sxllwx** [comment]
os.Stdin needs to be set to Raw mode. The code snippet is as follows:

```bash
	in := streams.NewIn(os.Stdin)
	if err := in.SetRawTerminal(); err != nil{
                 // handle err
	}
	err = exec.Stream(remotecommand.StreamOptions{
		Stdin:             in,
		Stdout:           stdout,
		Stderr:            stderr,
        }
```

> 	The full package name of **stream** "github.com/docker/cli/cli/streams"

**Comment by divinerapier** [comment]
@sxllwx Thank you very much. I will try it.

**Comment by sxllwx** [comment]
> @sxllwx Thank you very much. I will try it.

😊, if the plan is feasible, please make a reply and close the issue。

**Comment by divinerapier** [comment]
@sxllwx Yes, I set the instream both of the client and the gRPC service to be RawTerminal, this problem was solved. 
But, I met other problems. For example, first I type `perfz`, and then I type `tab` button. The output is wrapped.

<img width="598" alt="wrap" src="https://user-images.githubusercontent.com/21213088/104675091-bfe52400-571f-11eb-9a15-152f5429c1fd.PNG">

Could you provide me a sample code?

**Comment by sxllwx** [comment]
> @sxllwx Yes, I set the instream both of the client and the gRPC service to be RawTerminal, this problem was solved.
> But, I met other problems. For example, first I type `perfz`, and then I type `tab` button. The output is wrapped.
> 
> <img alt="wrap" width="598" src="https://user-images.githubusercontent.com/21213088/104675091-bfe52400-571f-11eb-9a15-152f5429c1fd.PNG">
> 
> Could you provide me a sample code?
```bash
        in := streams.NewIn(os.Stdin)
	if err := in.SetRawTerminal(); err != nil{
		// xxxx
	}
	defer in.RestoreTerminal()

	err = exec.Stream(remotecommand.StreamOptions{
		Stdin:             in,
		Stdout:            os.Stdout,
		Stderr:            os.Stderr,
		//Tty:               true,
		//TerminalSizeQueue: &TS{},
	})
	if err != nil {
		// xxx
	}
```
I think it is caused by incorrect setting of the `TerminalSizeQueue` parameter.

**Comment by divinerapier** [comment]
@sxllwx Ummm, I have set the `TerminalSizeQueue` parameter. I think I should check it.  Thank you. :)

**Comment by divinerapier** [comment]
@sxllwx You are absolutely right. The initial size is missed. T.T

**Comment by zhamdoctor** [comment]
> 

how can you resolve this when you exit terminal,bash or sh process will left in container without killed.

**Comment by zhamdoctor** [comment]
> github.com/docker/cli/cli/streams"



> > @sxllwx Thank you very much. I will try it.
> 
> 😊, if the plan is feasible, please make a reply and close the issue。

how to close sh process when i close websocket,sh process will left in container!

**Comment by sxllwx** [comment]
> > github.com/docker/cli/cli/streams"
> 
> > > @sxllwx Thank you very much. I will try it.
> > 
> > 
> > 😊, if the plan is feasible, please make a reply and close the issue。
> 
> how to close sh process when i close websocket,sh process will left in container!

FYI: 

We can bind the life cycle of websocket's conn with the ExecStream life cycle through `context`.

https://github.com/kubernetes/kubernetes/blob/v1.26.0-rc.0/staging/src/k8s.io/client-go/tools/remotecommand/remotecommand.go#L56

**Comment by CirillaQL** [comment]
> > > github.com/docker/cli/cli/streams"
> > 
> > 
> > > > @sxllwx Thank you very much. I will try it.
> > > 
> > > 
> > > 😊, if the plan is feasible, please make a reply and close the issue。
> > 
> > 
> > how to close sh process when i close websocket,sh process will left in container!
> 
> FYI:
> 
> We can bind the life cycle of websocket's conn with the ExecStream life cycle through `context`.
> 
> https://github.com/kubernetes/kubernetes/blob/v1.26.0-rc.0/staging/src/k8s.io/client-go/tools/remotecommand/remotecommand.go#L56

Sorry to bother you, I tried using StreamWithContext(ctx, ...) with context.WithTimeout(context.Background(), 10*time.Second). After 10 seconds, it was closed. However, when I use kubectl exec <pod> -it /bin/sh to enter the container and run lsof, I still find that there are two processes open dev/pts/<number> and dev/tty (the new one is opened by kubectl). Could you give me some advice on how to handle this problem? Currently, I can only send exit at the end.

**Comment by zhamdoctor** [comment]
> > github.com/docker/cli/cli/streams"
> 
> > > @sxllwx Thank you very much. I will try it.
> > 
> > 
> > 😊, if the plan is feasible, please make a reply and close the issue。
> 
> how to close sh process when i close websocket,sh process will left in container!

my leader suggested to me that i can store pid and pid name in mysql,when network closed unexpectly and have no chance to send exit from frontend(send exit from frontend when users close web himself ),and if network closed until sending,you can send `ps -ef|grep "sh|bash"|grep xxx&&kill-9 xxx` command  next time the user log in.

**Comment by zhamdoctor** [comment]
> I can only send exit at the end.

`exit` from frontend cant resolve with vpn disconnection problem.and pid will remain when vpn environment was very rigid and full of fluctration.here is my leader`s suggestion https://github.com/kubernetes/client-go/issues/912#issuecomment-1454657070

**Comment by CirillaQL** [comment]
> > I can only send exit at the end.
> 
> `exit` from frontend cant resolve with vpn disconnection problem.and pid will remain when vpn environment was very rigid and full of fluctration.here is my leader`s suggestion [#912 (comment)](https://github.com/kubernetes/client-go/issues/912#issuecomment-1454657070)

Thanks, and I think that it is better to use pkill instead of kill -9.
