### ISSUE TITLE
Cannot build v0.20.0 (amongst others) in go module mode with go v1.14.12.

### ISSUE THREAD

**Issue by bjorndm** [kubernetes/client-go#916]
Running the following minimal test:
```
mkdir tryk8s
cd tryk8s/
go mod init tryk8s
printf "package tryk8s\nimport (\n  _ \"k8s.io/client-go\"\n  _ \"k8s.io/api\" \n  _ \"k8s.io/apimachinery/v1\"\n)\n\n " > tryk8s.go
go get k8s.io/client-go@v0.20.0
go get k8s.io/api@v0.20.0
go get k8s.io/apimachinery@v0.20.0
go build
```
Gives the following error on the last command:
```
go: finding module for package k8s.io/apimachinery
go: finding module for package k8s.io/client-go
tryk8s.go:5:3: module k8s.io/apimachinery@latest found (v0.20.2), but does not contain package k8s.io/apimachinery
tryk8s.go:3:3: module k8s.io/client-go@latest found (v11.0.0+incompatible), but does not contain package k8s.io/client-go
```
I am using go  go v1.14.12. I also tried other versions but they all gave this error or similar errors.

I don't how else I should be using the k8s modules. It seems the Go module support of the k8i go client isn't working very well "out of the box". How to resolve this?

**Comment by liggitt** [comment]
what does your go.mod file look like? what does `go mod graph` output? the `@latest` output is unexpected

**Comment by liggitt** [comment]
oh, you are not importing actual go packages in your go file.

this should work better:
```
mkdir tryk8s
cd tryk8s/
go mod init tryk8s
printf "package tryk8s\nimport (\n  _ \"k8s.io/client-go/kubernetes\"\n)\n\n " > tryk8s.go
go get k8s.io/client-go@v0.20.0
go build
```

**Comment by bjorndm** [comment]
Thanks for the hint! I see now, none of the modules has any usable content under the root, so that's why the imports aren't working correctly. That was the problem we were having. We were upgrading from a very old version of client-go and some packages had been moved around. Thanks a lot, I will close this issue now.
