### ISSUE TITLE
Not sure how to add k8s.io/go-client to dockerfile

### ISSUE THREAD

**Issue by zohiba** [kubernetes/client-go#917]
I have these imported in my main.go file
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"

I am trying to containerize the application using a dockerfile. This is what my dockerfile looks like:

FROM golang:1.12.0-alpine3.9
RUN mkdir /app
RUN apk update && apk add git

RUN go get k8s.io/client-go/kubernetes 
RUN go get k8s.io/client-go/rest
RUN go get k8s.io/apimachinery/pkg/apis/meta/v1
ADD . /app
WORKDIR /app
RUN go build -o main .
CMD ["/app/main"]

After running docker build I get this error:
Sending build context to Docker daemon  35.93MB
Step 1/10 : FROM golang:1.12.0-alpine3.9
 ---> 2205a315f9c7
Step 2/10 : RUN mkdir /app
 ---> Using cache
 ---> 317f38656792
Step 3/10 : RUN apk add git
 ---> Using cache
 ---> 3986c25cf588
Step 4/10 : RUN go get k8s.io/client-go/kubernetes
 ---> Running in 3a9326155086
# k8s.io/apimachinery/pkg/util/errors
src/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
# k8s.io/apimachinery/pkg/api/resource
src/k8s.io/apimachinery/pkg/api/resource/quantity.go:470:34: invalid operation: int64(1) << (exponent * 10) (shift count type int, must be unsigned integer)
# k8s.io/apimachinery/pkg/util/net
src/k8s.io/apimachinery/pkg/util/net/http.go:67:5: undefined: errors.As
src/k8s.io/apimachinery/pkg/util/net/http.go:84:5: undefined: errors.As
src/k8s.io/apimachinery/pkg/util/net/util.go:43:5: undefined: errors.As
src/k8s.io/apimachinery/pkg/util/net/util.go:52:5: undefined: errors.As

New to using GO and now sure how to add those packages.

**Comment by fourhundredfour** [comment]
Hey, glad to see you giving Golang a try <3

Did you created a `go.mod` file or executed the initialization command for a Go module to facilitate the built-in dependency management? (`$ go mod init <module path>`)

You dont have to install the dependencies explicitly, they are installed implicitly and automatically by the `$ go build` command in your Dockerfile.
