### ISSUE TITLE
client losses service account secret files. 

### ISSUE THREAD

**Issue by pkutishch** [kubernetes/client-go#92]
Time to time getting following error:

"the server has asked for the client to provide credentials (get pods)"

Mostly during client startup, but after a couple of restarts it starting work well.
Using inside privileged pod which is inside cluster which i trying to access. 
Would you please advice.

**Comment by lavalamp** [comment]
What Kubernetes version? Is your cluster an HA configuration?

Sounds like a race somewhere in the system (doesn't sound like a client
bug). @deads2k or @ligget maybe have a better guess.

**Comment by deads2k** [comment]
Can you provide the detailed logs?  Glog level 8 ought to do.

**Comment by pkutishch** [comment]
Yes, im using HA k8s cluster, i have a daemon set which runs k8s go client. 
and time - to - time i getting error accessing kube api as i said above. 

@deads2k would you please clarify which log are you wan't to see? 

i running hyperkube. so there are a few containers like kubelet, sched, proxy, api ...etc

**Comment by deads2k** [comment]
> @deads2k would you please clarify which log are you want to see?

The client log.  It would be useful to know exactly which headers are sent and which responses are coming back to narrow down where the problem lies.

Given an HA cluster, its possible that you're having trouble due
 1. Missing certificate on one of your masters
 2. Slow k8s GET cache (pretty sure that merged already) if you're checking for token revocation (you should be)
 3. Slow etcd (if you're not forcing all traffic to one node)

Those would all manifest differently than "SA token is missing entirely".

**Comment by pkutishch** [comment]
Check all tree pods of my daemon set all data is equals and files are present, ca.crt, namespace, token
but still the same issue

the server has asked for the client to provide credentials (get pods)

at this time i can access API from others, it means that API works only from 2 of 3 pods.

**Comment by lavalamp** [comment]
I suspect one of your apiservers is configured differently. Check
credentials against each, perhaps?

**Comment by pkutishch** [comment]
@deads2k Log what i have from client:

node108 ~ # kubectl logs qa-data-t6tvk
2017/02/07 19:14:29 whoIAM error:  the server has asked for the client to provide credentials (get pods)

code:

func whoIAM() (string, error) {
	var nodename string
	hostname := os.Getenv("HOSTNAME")
	config, err := rest.InClusterConfig()
	if err != nil {
		panic(err.Error())
	}

	cli, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}
	pods, err := cli.CoreV1().Pods(NAMESPACE).List(v1.ListOptions{})
	if err != nil {
		return "", err
	}
	for _, p := range pods.Items {
		if p.Name == hostname {
			nodename = p.Spec.NodeName
		}
	}
	return nodename, nil
}

**Comment by pkutishch** [comment]
Issue closed by adding static token to k8s cluster, and to config in code

`config.BearerToken = "Token string"`
