### ISSUE TITLE
Getting invalid: status.conditions: Forbidden: updates may not add a condition of type "Approved"

### ISSUE THREAD

**Issue by duhruh** [kubernetes/client-go#921]
When attempting to create a CertificateSigningRequests then approving that request via this api i keep getting 

```
CertificateSigningRequest.certificates.k8s.io "foobar.com" is invalid: status.conditions: Forbidden: updates may not add a condition of type "Approved"
```

wondering if this is possible or i'm just missing something.

**Comment by duhruh** [comment]
found the issue by just following what kubectl does and using  `UpdateApproval`

**Comment by m-aamir-ashfaq** [comment]
@duhruh can you elaborate 'what kubectl does and using UpdateApproval', having same issue, and not able to figure out whats causing it
