### ISSUE TITLE
`v0.20.2` is not found in `https://pkg.go.dev`

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/client-go#923]
The most recent version `v0.20.2` is not found in following site.
https://pkg.go.dev/k8s.io/client-go?tab=versions

I don't know how is the site updated, can we do it?

**Comment by dims** [comment]
the tag seems be ok on the github repo - https://github.com/kubernetes/client-go/tree/v0.20.2

**Comment by nikhita** [comment]
The git tag looks fine. Created https://github.com/golang/go/issues/43775

**Comment by nikhita** [comment]
It's available now - https://github.com/golang/go/issues/43775#issuecomment-762978708 :)

https://pkg.go.dev/k8s.io/client-go@v0.20.2
