### ISSUE TITLE
Context is stupid

### ISSUE THREAD

**Issue by haalcala** [kubernetes/client-go#926]
I understand the purpose of Context in golang.  But passing it on all api calls is stupid, I think.  It violates the DRY principle.  Why can't just put an object that manages this? If you just want to have the ability to cancel remote calls, why not just the function call return the Context?

**Comment by liggitt** [comment]
The functions block until the call is complete, so a return value is not an option. Context is intended to be 1:1 with a remote call, so a manager object that would reuse it would not work.
