### ISSUE TITLE
Implementation of simpleclientset overrides the concept of Reactors in the current test environment.

### ISSUE THREAD

**Issue by Bjohnson131** [kubernetes/client-go#948]
## Problem: 

Currently, the [kubernetes simple fake clientset](https://github.com/kubernetes/client-go/blob/master/kubernetes/fake/clientset_generated.go#L130) adds a reactor that handles all objects for all verbs. This means that in the current implementation, it is impossible to add a reactor to the simple client set without first deleting the entire set of reactors. Why? As one can see in [testing/fake](https://github.com/kubernetes/client-go/blob/a7d2e0118033720853dcd4aaa50b3b971387262d/testing/fake.go#L164), once the client finds an appropriate reactor, the entire function returns without regard for the rest of the reactors. This means that any reactors added post-hoc are moot.

## Solutions:

- When [adding reactors to the list](https://github.com/kubernetes/client-go/blob/master/testing/fake.go#L99), instead of appending the reactors to the end of the list, add them to the beginning, giving the engineer priority in the handling of the client.
- Give priority to non '*' handlers. If a handler exists for an object or action which is encompassed in a reactor with a '*' in its object type or verb, and another reactor encompasses the same thing, except that this reactor doesn't have a '*' where the other reactor does, give priority to the reactor with doesn't contain a '*'. This is my preferred solution.
- Add a nil-check such that if a reactor returns nil or error, the watcher keeps executing through the list.

**Comment by ytimocin** [comment]
I think this function https://github.com/kubernetes/client-go/blob/master/testing/fake.go#L103 corresponds to your first solution. @Bjohnson131
