### ISSUE TITLE
gcp auth package is loaded by default, but should be an optional dependency

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/client-go#95]
I think the offending bit is here: https://github.com/kubernetes/client-go/blob/fb6075f2e0b094320f3d2c3e99add90a4661fcff/discovery/helper.go#L27

We should:
- [x] Fix that reference, any other references, and any invocations that accidentally work because the discovery client does this import. kubernetes/kubernetes#41532
- Write a test
  - [x] that checks that plugins are not imported by default: https://github.com/kubernetes/kubernetes/pull/42466
  - [ ] that lets us see exactly what dependencies are required by default (no plugins loaded) and fails if the list changes. 
- [ ] Add an example that demonstrates using the GCP auth or the OIDC auth plugin. (since there seem to be two choices at the moment.)

**Comment by caesarxuchao** [comment]
> Write a test that lets us see exactly what dependencies are required by default (no plugins loaded) and fails if the list changes.

Do you mean writing the test for the discovery client?

**Comment by lavalamp** [comment]
No, I mean for the client overall.

**Comment by ericchiang** [comment]
Resolved by https://github.com/kubernetes/kubernetes/pull/41532

**Comment by lavalamp** [comment]
@sttts

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/42466
