### ISSUE TITLE
PodList not declared by package v1

### ISSUE THREAD

**Issue by dbgoytia** [kubernetes/client-go#952]
Hey all,

I'm kind of new to the client-go for Kubernetes. In this particular example I'm trying to get a list of all available pods in the kube-system namespace. When I try to return the following code, it gives the error:

`PodList not declared by package v1`

I'm guessing it's an issue in my imports, but I don't know how to fix this:

```
import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"path/filepath"
	"reflect"

	v1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/homedir"
)

```

```
func getAvailableResources(clientset *kubernetes.Clientset) *v1.PodList {
	list, err := clientset.CoreV1().Pods("kube-system").List(context.TODO(), metav1.ListOptions{})
	if err != nil {
		panic(err)
	}
	fmt.Println(reflect.TypeOf(list))
}
```

Any help is highly appreciated!

Thanks in advance!

**Comment by thaney071** [comment]
@dbgoytia, the PodList  Structure is in the [core/v1 package](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3740) 

You need to import `"k8s.io/api/core/v1"` to use the PodList structure

**Comment by dbgoytia** [comment]
thanks a lot @thaney071 !!! Eventhough I figured this one out a while ago, I think it could help someone else understand it in case they get lost. 

Really appreciate it!
