### ISSUE TITLE
Support loadbalancing endpoints

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/client-go#955]
Looks like in https://github.com/kubernetes/kubernetes/issues/18174 theres alot of churn around the fact that we cant loadbalance APIServers for client-go.

Can we support this ? i.e. 

change 
```
type Config struct {
	Host string
```
to something like this? 
```
type Config struct {
        // for backward compatibility
        Host string 
	// Hosts must be  an array of  host strings, a host:port pair, or a URL to the base of the apiserver.
	Hosts []string
```

**Comment by MadhavJivrajani** [comment]
Hi!

I'd like to work on this :smile:

/assign

**Comment by jayunit100** [comment]
@MadhavJivrajani i guess the first step might be to see if you can hack it together, and then figure out who owns client-go and what SIG you need to go to to talk about this , and wether a KEP is needed to follow up

thanks

**Comment by enj** [comment]
https://github.com/kubernetes/kubernetes/issues/18174#issuecomment-821991466
/remove-good-first-issue
/sig api-machinery

**Comment by enj** [comment]
https://github.com/kubernetes/kubernetes/issues/18174#issuecomment-1218046238

There are no plans to address this.

/close
