### ISSUE TITLE
client-go github page shows incorrect latest release

### ISSUE THREAD

**Issue by Himani-relan** [kubernetes/client-go#961]
https://github.com/kubernetes/client-go shows the latest release as "v12.0.0" . (which is wrong)
It was created on Jul3,2019.

Latest release information should be updated correctly.

**Comment by liggitt** [comment]
that is controlled by github, unfortunately, not by us. https://github.com/kubernetes/client-go/releases shows the most recent releases

**Comment by Himani-relan** [comment]
I have renovate-bot configured to fetch the latest release. It gets the wrong information because latest-release tag is labelled wrong. We could edit the tag and correct this.

**Comment by Himani-relan** [comment]
> that is controlled by github, unfortunately, not by us. https://github.com/kubernetes/client-go/releases shows the most recent releases

I have renovate-bot configured to fetch the latest release. It gets the wrong information because latest-release tag is labelled wrong. We could edit the tag and correct this.
I think it's in the hands of repository owners who creates tag/releases.

**Comment by liggitt** [comment]
deleting the tag is not an option. deleting the github release may be?

**Comment by Himani-relan** [comment]
> deleting the tag is not an option. deleting the github release may be?

yeah it could fix the issue.

**Comment by Himani-relan** [comment]
@liggitt : Is there any update on this issue ?

**Comment by nikhita** [comment]
> deleting the tag is not an option. deleting the github release may be?

I tried deleting a "GitHub release" on a dummy repo. Some findings:

- [Deleting a "GitHub release"](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#deleting-a-release)  does not delete the tag, so it should be safe to delete the GitHub release.
- If the latest GitHub release is deleted but an older GitHub release exists, the older release will be displayed as the "latest release". E.g. if we delete the `v12.0.0` release for client-go, GitHub will show `v11.0.0` as the latest release. So we will need to delete all GitHub releases for client-go.
- If we delete all GitHub releases, GitHub will **not** automatically display the latest tag (by date) as the latest release. In fact, it will not display _any_ latest release, similar to https://github.com/kubernetes/api.
This means that https://github.com/kubernetes/client-go/releases/latest will just redirect to https://github.com/kubernetes/client-go/releases instead of https://github.com/kubernetes/client-go/releases/tag/v12.0.0. This is okay, and will at least help in communicating that v12.0.0 is not the latest release.

I used the [gh cli](https://github.com/cli/cli) to get a list of "GitHub releases" for client-go. We'll need to delete all of these releases:

```console
$ gh release list --repo=kubernetes/client-go
v1.5.2          Pre-release  (v1.5.2)          about 3 months ago
v12.0.0         Latest       (v12.0.0)         about 1 year ago
v11.0.0                      (v11.0.0)         about 2 years ago
v10.0.0                      (v10.0.0)         about 2 years ago
v9.0.0                       (v9.0.0)          about 2 years ago
v8.0.0                       (v8.0.0)          about 2 years ago
v7.0.0                       (v7.0.0)          about 3 years ago
v6.0.0                       (v6.0.0)          about 3 years ago
v5.0.1                       (v5.0.1)          about 3 years ago
v5.0.0                       (v5.0.0)          about 3 years ago
v4.0.0                       (v4.0.0)          about 3 years ago
v4.0.0-beta.0   Pre-release  (v4.0.0-beta.0)   about 3 years ago
v3.0.0                       (v3.0.0)          about 3 years ago
v3.0.0-beta.0   Pre-release  (v3.0.0-beta.0)   about 4 years ago
v2.0.0                       (v2.0.0)          about 4 years ago
v1.5.1                       (v1.5.1)          about 4 years ago
v2.0.0-alpha.1  Pre-release  (v2.0.0-alpha.1)  about 4 years ago
v1.5.0                       (v1.5.0)          about 4 years ago
v1.4.0                       (v1.4.0)          about 4 years ago
```

**Comment by dims** [comment]
+1 from me. cc @liggitt

**Comment by liggitt** [comment]
sgtm

**Comment by nikhita** [comment]
Deleted all GitHub releases by running:

```console
➜  client-go git:(master) gh release list --repo=kubernetes/client-go | sed 's/|/ /' | awk '{print $1, $8}' | while read -r line; do gh release delete "$line"; done
✓ Deleted release v1.5.2
! Note that the v1.5.2 git tag still remains in the repository
✓ Deleted release v12.0.0
! Note that the v12.0.0 git tag still remains in the repository
✓ Deleted release v11.0.0
! Note that the v11.0.0 git tag still remains in the repository
✓ Deleted release v10.0.0
! Note that the v10.0.0 git tag still remains in the repository
✓ Deleted release v9.0.0
! Note that the v9.0.0 git tag still remains in the repository
✓ Deleted release v8.0.0
! Note that the v8.0.0 git tag still remains in the repository
✓ Deleted release v7.0.0
! Note that the v7.0.0 git tag still remains in the repository
✓ Deleted release v6.0.0
! Note that the v6.0.0 git tag still remains in the repository
✓ Deleted release v5.0.1
! Note that the v5.0.1 git tag still remains in the repository
✓ Deleted release v5.0.0
! Note that the v5.0.0 git tag still remains in the repository
✓ Deleted release v4.0.0
! Note that the v4.0.0 git tag still remains in the repository
✓ Deleted release v4.0.0-beta.0
! Note that the v4.0.0-beta.0 git tag still remains in the repository
✓ Deleted release v3.0.0
! Note that the v3.0.0 git tag still remains in the repository
✓ Deleted release v3.0.0-beta.0
! Note that the v3.0.0-beta.0 git tag still remains in the repository
✓ Deleted release v2.0.0
! Note that the v2.0.0 git tag still remains in the repository
✓ Deleted release v1.5.1
! Note that the v1.5.1 git tag still remains in the repository
✓ Deleted release v2.0.0-alpha.1
! Note that the v2.0.0-alpha.1 git tag still remains in the repository
✓ Deleted release v1.5.0
! Note that the v1.5.0 git tag still remains in the repository
✓ Deleted release v1.4.0
! Note that the v1.4.0 git tag still remains in the repository
```

---

Confirmed that:

1. Tags for deleted releases exist - https://github.com/kubernetes/client-go/releases/tag/v12.0.0

2. Number of tags before deleting releases = number of tags after deleting releases = 724

3. The link https://github.com/kubernetes/client-go does not show `v12.0.0` as the latest release anymore. https://github.com/kubernetes/client-go/releases/latest also redirects to https://github.com/kubernetes/client-go/releases.

Closing as this is now done!

**Comment by alinalex1392** [comment]
We have one renovate bot, under a go repo, and in the past two weeks we got this:
[k8s.io/client-go](https://github.com/kubernetes/client-go)
require
major
v0.26.1 -> v12.0.0

Does this relate to this old issue?

**Comment by liggitt** [comment]
no, this issue was purely about what github displays

it sounds like the bot proposing updates is not go-module-version aware

https://github.com/kubernetes/client-go/blob/v1.5.2/go.mod is the latest tag for the k8s.io/client-go module, and retracts the v12.0.0 series

**Comment by alinalex1392** [comment]
Ok , thank you for the prompt response!
