### ISSUE TITLE
Error: "Failed to release lock: resource name may not be empty" might occur if `ReleaseOnCancel` is `true` in leaderelection package

### ISSUE THREAD

**Issue by tokers** [kubernetes/client-go#966]
Recently I found there is an exception in leaderelection package.

If the `LeaderElector` was created with `ReleaseOnCancel: true`, and we cancel the context passed to `LeaderElector.Run` by ourselves, error `Failed to release lock: resource name may not be empty` might occur.

This is because we canceled the context and make the following operations returning a zero value:

* ConfigMap.Get / ConfigMap.Create

```go
cml.cm, err = cml.Client.ConfigMaps(cml.ConfigMapMeta.Namespace).Get(ctx, cml.ConfigMapMeta.Name, metav1.GetOptions{})
if err != nil {
	return nil, nil, err
}

cml.cm, err = cml.Client.ConfigMaps(cml.ConfigMapMeta.Namespace).Create(ctx, &v1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      cml.ConfigMapMeta.Name,
			Namespace: cml.ConfigMapMeta.Namespace,
			Annotations: map[string]string{
				LeaderElectionRecordAnnotationKey: string(recordBytes),
			},
		},
	}, metav1.CreateOptions{})
```

* Lease.Get / Lease.Create

```go
ll.lease, err = ll.Client.Leases(ll.LeaseMeta.Namespace).Get(ctx, ll.LeaseMeta.Name, metav1.GetOptions{})
if err != nil {
	return nil, nil, err
}

ll.lease, err = ll.Client.Leases(ll.LeaseMeta.Namespace).Create(ctx, &coordinationv1.Lease{
	ObjectMeta: metav1.ObjectMeta{
		Name:      ll.LeaseMeta.Name,
		Namespace: ll.LeaseMeta.Namespace,
	},
	Spec: LeaderElectionRecordToLeaseSpec(&ler),
}, metav1.CreateOptions{})
```

* Endpoints.Get / Endpoints.Create

```go
el.e, err = el.Client.Endpoints(el.EndpointsMeta.Namespace).Get(ctx, el.EndpointsMeta.Name, metav1.GetOptions{})
if err != nil {
	return nil, nil, err
}

el.e, err = el.Client.Endpoints(el.EndpointsMeta.Namespace).Create(ctx, &v1.Endpoints{
	ObjectMeta: metav1.ObjectMeta{
		Name:      el.EndpointsMeta.Name,
		Namespace: el.EndpointsMeta.Namespace,
		Annotations: map[string]string{
			LeaderElectionRecordAnnotationKey: string(recordBytes),
		},
	},
}, metav1.CreateOptions{})
```

Once they returned, the corresponding object in `ConfigMapLock`, `LeaseLock` or `EndpointsLock` will be a zero value, which `metav1.ObjectMeta` is also zeroed. So when the `release` was triggered, the underlying client object returns "resource name may not be empty".

```go
if err := le.config.Lock.Update(context.TODO(), leaderElectionRecord); err != nil {
	klog.Errorf("Failed to release lock: %v", err)
	return false
}
```

I will wait for your replies, and I'd like to submit a PR to fix it.

**Comment by michaelbor** [comment]
> ```go
> ll.lease, err = ll.Client.Leases(ll.LeaseMeta.Namespace).Get(ctx, ll.LeaseMeta.Name, metav1.GetOptions{})
> ```

Hi @tokers , I'm currently facing the same issue with failure to gracefully release leadership. Do you know if there is a plan to fix this issue or maybe you found a workaround for it?

**Comment by michaelbor** [comment]
> > ```go
> > ll.lease, err = ll.Client.Leases(ll.LeaseMeta.Namespace).Get(ctx, ll.LeaseMeta.Name, metav1.GetOptions{})
> > ```
> 
> Hi @tokers , I'm currently facing the same issue with failure to gracefully release leadership. Do you know if there is a plan to fix this issue or maybe you found a workaround for it?

Just found that the fix has been already implemented! https://github.com/kubernetes/client-go/commit/d04c2ced1cc5a27f7c980eff65b5dfd20e73ce24
