### ISSUE TITLE
Got error "expected type *v1.Pod, but watch event object had type *unstructured.Unstructured"

### ISSUE THREAD

**Issue by 27149chen** [kubernetes/client-go#967]
I'm using controller-runtime (v0.8.2) to cache k8s objects. but I encontered the following issue many times, which will cause the cached objects never been updated again.
It happened on various objects (Pod, Node, ...)，and I also tried client-go 0.19 and 0.20.
It is not 100% reproducible, so I don't know how to debug it, is there any suggetions?
```
E0513 20:55:34.007436       1 reflector.go:465] pkg/mod/k8s.io/client-go@v0.19.10/tools/cache/reflector.go:156: expected type *v1.Pod, but watch event object had type *unstructured.Unstructured
```

**Comment by weilaaa** [comment]
@27149chen May I ask if this problem was finally solved, because I also faced the same problem.

**Comment by 27149chen** [comment]
the problem is still there
