### ISSUE TITLE
PatchType is not supported for ApplyPatchType in fake

### ISSUE THREAD

**Issue by grishy** [kubernetes/client-go#970]
Hi,
When I write a tests:
```go
fakeReadyDeployment := fake.NewSimpleClientset(&appV1.Deployment{
TypeMeta: metav1.TypeMeta{
	Kind:       "Deployment",
	APIVersion: "apps/v1",
},
ObjectMeta: metav1.ObjectMeta{
	Name:            deploymentName,
	Namespace:       "default",
},
}).AppsV1().Deployments("default")
```

After try to apply:
```go
	_, err := fakeReadyDeployment.Apply(context.TODO(), deployment, metav1.ApplyOptions{
		FieldManager: appUID,
	})
```

I get: **PatchType is not supported**

Because we have 4 of const:
**k8s.io/apimachinery@v0.21.0/pkg/types/patch.go:25**
```go
const (
	JSONPatchType           PatchType = "application/json-patch+json"
	MergePatchType          PatchType = "application/merge-patch+json"
	StrategicMergePatchType PatchType = "application/strategic-merge-patch+json"
	ApplyPatchType          PatchType = "application/apply-patch+yaml"
)
```

But in switch only 3 case:
https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L150

**Comment by benjaminjb** [comment]
Yeah, this caught me too

**Comment by grishy** [comment]
@benjaminjb any progress? 😄

**Comment by computerphilosopher** [comment]
I ran a debugger on my test code. When run [ObjectReaction function](), my 'action.PatchType' is '[ApplyPatchType](https://github.com/kubernetes/apimachinery/blob/57f2a0733447cfd41294477d833cce6580faaca3/pkg/types/patch.go#L24-L29)(application/apply-patch+yaml)'

![image](https://user-images.githubusercontent.com/26251856/190989554-e7ad273a-7a15-4074-bc5e-7ef8e6aed519.png)


[But this type is not handled in a switch case statement.](https://github.com/kubernetes/client-go/blob/037b5fd01db4432f8f6bb6139ff2b6dd00008b99/testing/fixture.go#L161-L204)

**Comment by Skarlso** [comment]
Is there any kind of workaround for this?

**Comment by therealmitchconnors** [comment]
See https://github.com/kubernetes/client-go/issues/1184 for a workaround.

**Comment by Skarlso** [comment]
Yippy thank you!

**Comment by hairyhenderson** [comment]
/remove-lifecycle rotten

Still relevant...
