### ISSUE TITLE
travis-ci.org is going to be shutdown the end of this month

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/client-go#972]
👋 just saw the project is still using travis-ci.org for CI, and I have to call out that Travis is going to [shut it down on this May 31](https://blog.travis-ci.com/2021-05-07-orgshutdown).

**Comment by dims** [comment]
thanks @chenrui333 cleaning up in https://github.com/kubernetes/client-go/pull/974

**Comment by chenrui333** [comment]
Thanks @dims, that is quick. :)

**Comment by dims** [comment]
Anything for you @chenrui333 !!!!
