### ISSUE TITLE
Create a better user documentation of client-go

### ISSUE THREAD

**Issue by shenmou98** [kubernetes/client-go#976]
I can't find the user documentation. Could you please point it to me?

**Comment by lukos** [comment]
@shenmou98 if you start with the examples directory and then use the go package docs, you should be able to work things out. It hasn't taken me long using Go in VSCode so I get the intellisense to find out what values to pass to the various functions.

[https://pkg.go.dev/k8s.io/api/core/v1#pkg-overview](https://pkg.go.dev/k8s.io/api/core/v1#pkg-overview)

**Comment by caleb15** [comment]
Documentation would be really nice, as a newcomer to this library, especially as a newcomer to Go. 

> https://pkg.go.dev/k8s.io/api/core/v1#pkg-overview

That's the API reference for the Kubernetes API. I could be mistaken, but I believe the API reference for this repo (client-go) is here: https://pkg.go.dev/k8s.io/client-go

**Comment by SaberStrat** [comment]
Kind of crazy that a project connected to the same company that made the language has no canonical package documentation.

I see how it's technically not a requirement to work with the package, but still weird.
