### ISSUE TITLE
k8s client-go/dynamic client does not pass along Content-Type header

### ISSUE THREAD

**Issue by arunmahadevan** [kubernetes/client-go#980]
Observe that while creating resources using `dynamic client` (k8s.io/client-go version v0.17.3), the `Content-Type` header is not passed along.

This is causing issues when the request is routed via a proxy. The proxy fills in a default `Content-Type` header (`application/octet-stream`) and the request is rejected by the K8s API server. 

Is there a way to force the dynamic client to pass `Content-Type: application/json` header while making the HTTP request?

Heres a sample snippet:

```go

import(
"k8s.io/client-go/dynamic"
"k8s.io/client-go/tools/clientcmd"
)

//....
config, err := clientcmd.RESTConfigFromKubeConfig([]byte(kubeConfig))
config.ContentType = "application/json"
client, err := dynamic.NewForConfig(config)
resource := schema.GroupVersionResource{/*....*/}
obj := &unstructured.Unstructured{/*....*/}
client.Resource(resource).Namespace("foo").Create(obj, v1.CreateOptions{})
```

It appears that from below, only the "Accept" header is set, the "Content-type" is not.

https://github.com/kubernetes/client-go/blob/master/rest/request.go#L149-L154

**Comment by sxllwx** [comment]
After reading through the code, I found that k8s uses the Codec negotiation module that is strongly related to the transmission object to determine how to set the content-type.

**Comment by sxllwx** [comment]
Read through request.go. I think it is a bug in client-go. When using a non-runtime.Object object as the http body, the Content-Type in http.Header is not set correctly. The unstructured.Unstructured used in the code snippet you provided cannot set http.Header.Content-Type correctly after serialization, The key code is as follows https://github.com/kubernetes/client-go/blob/master/dynamic/simple.go#L94-L113
