### ISSUE TITLE
`v0.21.2` is not found in `https://pkg.go.dev`

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/client-go#989]
The tag `v0.21.2` for `k8s.io/client-go` is missing in https://pkg.go.dev/k8s.io/client-go?tab=versions
But exists at:
* https://github.com/kubernetes/client-go/tree/v0.21.2
* https://github.com/kubernetes/client-go/releases/tag/v0.21.2
* https://proxy.golang.org/k8s.io/client-go/@v/v0.21.2.info

This issue is for tracking https://github.com/golang/go/issues/46844

**Comment by liggitt** [comment]
looks like https://github.com/golang/go/issues/46844 was closed as fixed

/close
