### ISSUE TITLE
How to describe a service 

### ISSUE THREAD

**Issue by anthhub** [kubernetes/client-go#999]
How to describe a service using the client-go ?

**Comment by anthhub** [comment]
For instance: kubectl describe svc my-nginx

**Comment by yuswift** [comment]
`kubectl describe svc kubernetes` works.

**Comment by anthhub** [comment]
> `kubectl describe svc kubernetes` works.

I say use client-go API, instead of command

**Comment by yuswift** [comment]
> > `kubectl describe svc kubernetes` works.
> 
> I say use client-go API, instead of command

add --v=5 flag
you can see the api call

**Comment by anthhub** [comment]
... I say client-go code API

**Comment by anthhub** [comment]
> `kubectl describe svc kubernetes` works.

who don't know?
